// ---------------------------------------------------------------------------
// SIMULATED SAAT (TAHSILI) QUESTION BANK — part A.
//
// SOURCE. An English rendering of the 2021 SAAT mathematics set, reduced to the
// skills that are unique to SAAT (the quantitative-reasoning items in the same
// document belong to the GAT bank and are not touched here). That set carries
// 38 numbered questions but 37 distinct SKILLS: the singular-matrix item appears
// twice, once with the parameter in the top-left corner and once in the bottom
// right.
//
// WHAT IS TAKEN AND WHAT IS NOT. The skill and the trick are taken. The stem,
// the numbers, the option values and the figures are not: every item below was
// written from scratch and every answer re-derived in verify_saat.py. Nothing a
// student memorised from a circulated recall sheet is reproduced here — which
// is the whole point, since ETEC repeats ideas and never repeats questions.
//
// TWO ITEMS PER SKILL. The first states the skill plainly; the second turns the
// trick on it — the term index that is one less than the term number, the
// endpoint that beats the critical point, the negative r that moves the point
// to the opposite side. 37 skills, 74 items.
//
// STRANDS.  SAAT-M-ALG algebra · SAAT-M-GEO geometry · SAAT-M-TRI trigonometry
//           SAAT-M-CAL calculus · SAAT-M-STA statistics and probability
// ---------------------------------------------------------------------------
module.exports = [

// ================================================================== ALGEBRA
{ sig: "binomial-coefficient-of-a-term", code: "SAAT-M-ALG.1", lvl: 2,
  stem: "What is the coefficient of the term in x² in the expansion below?",
  stemEq: "a_bin1",
  opts: ["540", "1080", "108", "270"], ans: 1,
  trick: "the whole of 2x is raised to the power, so the 2 is squared as well — dropping it is the standard loss",
  why: "The term in x² comes from C(5, 3)(2x)²(3)³ = 10 × 4x² × 27 = 1080x².",
  traps: ["A: the 2 dropped altogether, 10 × 27.",
          "C: the binomial coefficient 10 left out, 4 × 27.",
          "D: the 2 in 2x squared as 2 rather than 4, 10 × 2 × 27."] },

{ sig: "binomial-nth-term-index", code: "SAAT-M-ALG.1", lvl: 3,
  stem: "What is the fourth term of the expansion below, written in descending powers of x?",
  stemEq: "a_bin2",
  opts: [{ eq: "a_bin2o1" }, { eq: "a_bin2o2" }, { eq: "a_bin2o3" }, { eq: "a_bin2o4" }], ans: 0,
  trick: "the fourth TERM carries index 3, not 4 — the count starts at zero, and the odd power of −3 makes the term negative",
  why: "The fourth term is C(5, 3)x²(−3)³ = 10 × x² × (−27) = −270x².",
  traps: ["B: the sign of (−3)³ taken as positive.",
          "C: the fourth term read as index 4, giving C(5, 4)x(−3)⁴ = 405x.",
          "D: the binomial coefficient 10 left out."] },

{ sig: "matrix-inverse-2x2", code: "SAAT-M-ALG.2", lvl: 2,
  stem: "Find the inverse of the matrix below.",
  stemEq: "a_mati",
  opts: [{ eq: "a_matio1" }, { eq: "a_matio2" }, { eq: "a_matio3" }, { eq: "a_matio4" }], ans: 1,
  trick: "the determinant here is −1, so every entry of the adjugate changes sign — a determinant of 1 is what people assume and never check",
  why: "The determinant is 4 × 2 − 3 × 3 = −1. Swap 4 and 2, negate the two 3s, then divide by −1.",
  traps: ["A: the adjugate written down but never divided by the determinant.",
          "C: the 3s negated and divided, but 4 and 2 not swapped.",
          "D: the original matrix returned with the off-diagonal signs changed."] },

{ sig: "solve-2x2-system-by-inverse", code: "SAAT-M-ALG.2", lvl: 3,
  stem: "Solve the system below using the inverse of its coefficient matrix. What is x + y?",
  stemEq: "a_matsys",
  opts: ["2", "3", "4", "1"], ans: 2,
  trick: "the determinant is 5, not 1 — the division at the end is the step that gets skipped, and the question asks for a SUM, not for x",
  why: "The determinant is 2 × 4 − 1 × 3 = 5, giving x = (7 × 4 − 1 × 13) ÷ 5 = 3 and y = (2 × 13 − 3 × 7) ÷ 5 = 1, so x + y = 4.",
  traps: ["A: x − y computed instead of x + y.", "B: x alone reported.", "D: y alone reported."] },

{ sig: "log-evaluate-perfect-power", code: "SAAT-M-ALG.3", lvl: 1,
  stem: "Which of the logarithms below is NOT equal to the other three?",
  opts: [{ eq: "a_lg3" }, { eq: "a_lg4" }, { eq: "a_lg1" }, { eq: "a_lg2" }], ans: 3,
  trick: "read every logarithm as a question — what power of the base gives that number? — and three of the four come out at 4",
  why: "log₄256 = 4, log₃81 = 4 and log₂16 = 4, but log₅125 = 3 because 5³ = 125.",
  traps: ["A: 3⁴ = 81, so this equals 4.",
          "B: 2⁴ = 16, so this equals 4.",
          "C: 4⁴ = 256, so this equals 4 like two of the others."] },

{ sig: "log-solve-for-unknown-base", code: "SAAT-M-ALG.3", lvl: 2,
  stem: "If log of 27 to the base x equals 3/2, what is x?",
  opts: ["9", "18", "54", "3"], ans: 0,
  trick: "turn the logarithm into a power first — x raised to 3/2 is 27, so x is 27 raised to the RECIPROCAL power 2/3",
  why: "x^(3/2) = 27, so x = 27^(2/3) = 3² = 9.",
  traps: ["B: 27 multiplied by 2/3.",
          "C: 27 multiplied by 2.",
          "D: the cube root of 27 taken and the power 2 forgotten."] },

{ sig: "parent-absolute-value-function", code: "SAAT-M-ALG.4", lvl: 1,
  stem: "The graph below is the graph of y = |x − 3| + 1. Which is its parent function?",
  fig: "saat_absgraph", figW: 1.85,
  opts: [{ eq: "a_par4" }, { eq: "a_par1" }, { eq: "a_par2" }, { eq: "a_par3" }], ans: 1,
  trick: "the parent function carries NO shift at all — every number in the rule is a transformation, so strip all of them",
  why: "Both the 3 inside the bars and the +1 outside them are shifts, so the parent function is y = |x|.",
  traps: ["A: the 3 moved outside the bars and kept.",
          "C: the vertical shift kept.",
          "D: the horizontal shift kept."] },

{ sig: "absolute-value-transformation-rule", code: "SAAT-M-ALG.4", lvl: 2,
  stem: "The graph of y = |x| is moved 4 units to the left and 2 units down. What is the rule of the image?",
  opts: [{ eq: "a_sh1" }, { eq: "a_sh2" }, { eq: "a_sh3" }, { eq: "a_sh4" }], ans: 2,
  trick: "a move to the LEFT adds inside the bars — the sign inside is always the opposite of the direction, while the sign outside is not",
  why: "Left by 4 gives |x + 4|, and down by 2 subtracts outside the bars: y = |x + 4| − 2.",
  traps: ["A: left read as −4 inside the bars.",
          "B: down read as +2 outside them.",
          "D: the 4 and the 2 exchanged."] },

{ sig: "combine-logs-into-one", code: "SAAT-M-ALG.5", lvl: 2,
  stem: "Write the expression below as a single logarithm.",
  stemEq: "a_cmb",
  opts: [{ eq: "a_cmb3" }, { eq: "a_cmb4" }, { eq: "a_cmb1" }, { eq: "a_cmb2" }], ans: 3,
  trick: "a coefficient in front of a logarithm becomes a POWER, never a multiplier, and subtraction becomes division in that order",
  why: "3log₂x = log₂x³, and subtracting log₂(x + 1) divides, giving log₂[x³ ÷ (x + 1)].",
  traps: ["A: the division taken the wrong way round.",
          "B: subtraction of logarithms read as subtraction of arguments.",
          "C: the coefficient 3 multiplied into the argument."] },

{ sig: "expand-single-log", code: "SAAT-M-ALG.5", lvl: 2,
  stem: "Which expression is equal to the logarithm below?",
  stemEq: "a_exp",
  opts: [{ eq: "a_exp1" }, { eq: "a_exp2" }, { eq: "a_exp3" }, { eq: "a_exp4" }], ans: 0,
  trick: "log₅25 is a NUMBER, 2 — leaving 25 sitting in the answer is the trap the option list is built around",
  why: "log₅25 = 2, the power 4 comes down as a coefficient, and the square root in the denominator subtracts half of log₅y.",
  traps: ["B: the quotient turned into a sum.",
          "C: log₅25 written as 25 instead of 2.",
          "D: the square root read as a power of 2 rather than one half."] },

{ sig: "matrix-product-order", code: "SAAT-M-ALG.6", lvl: 1,
  stem: "A matrix of order 3 × 5 is multiplied by a matrix of order 5 × 2. What is the order of the product?",
  opts: ["2 × 3", "3 × 2", "3 × 5", "5 × 5"], ans: 1,
  trick: "the inner pair must match and then disappears; the OUTER pair, in that order, is the order of the product",
  why: "The inner 5s match, leaving 3 rows and 2 columns.",
  traps: ["A: the outer pair written in the wrong order.",
          "C: the order of the first matrix copied out.",
          "D: the inner pair kept instead of the outer one."] },

{ sig: "matrix-product-defined", code: "SAAT-M-ALG.6", lvl: 2,
  stem: "For which pair of matrices below is the product AB defined?",
  opts: ["A is 2 × 3 and B is 2 × 3",
         "A is 1 × 4 and B is 1 × 4",
         "A is 2 × 4 and B is 4 × 3",
         "A is 3 × 2 and B is 3 × 2"], ans: 2,
  trick: "equal orders are exactly what does NOT work — the columns of A must match the rows of B, which is a different condition",
  why: "A has 4 columns and B has 4 rows, so AB is defined and has order 2 × 3.",
  traps: ["A: equal orders assumed to be enough.",
          "B: two row vectors assumed to multiply.",
          "D: equal orders again, with a transpose taken silently."] },

{ sig: "complex-square", code: "SAAT-M-ALG.7", lvl: 2,
  stem: "Compute the value below and write it in the form a + bi.",
  stemEq: "a_cx1",
  opts: [{ eq: "a_cx1o3" }, { eq: "a_cx1o4" }, { eq: "a_cx1o1" }, { eq: "a_cx1o2" }], ans: 3,
  trick: "i² = −1, so the last term SUBTRACTS 4 — treating i² as +1 is the whole item",
  why: "(3 − 2i)² = 9 − 12i + 4i² = 9 − 12i − 4 = 5 − 12i.",
  traps: ["A: the middle term dropped and the two squares added.",
          "B: the sign of the middle term lost.",
          "C: i² taken as +1, giving 13 − 12i."] },

{ sig: "complex-quotient-conjugate", code: "SAAT-M-ALG.7", lvl: 3,
  stem: "Write the quotient below in the form a + bi.",
  stemEq: "a_cx2",
  opts: [{ eq: "a_cx2o3" }, { eq: "a_cx2o4" }, { eq: "a_cx2o1" }, { eq: "a_cx2o2" }], ans: 0,
  trick: "multiply top and bottom by the CONJUGATE of the denominator — and (2 − i)(2 + i) is 4 + 1, not 4 − 1",
  why: "5(2 + i) ÷ [(2 − i)(2 + i)] = (10 + 5i) ÷ 5 = 2 + i.",
  traps: ["B: (2 − i)(2 + i) computed as 4 − 1 = 3.",
          "C: the sign changed in the answer instead of in the denominator.",
          "D: the denominator never cleared."] },

{ sig: "singular-matrix-parameter", code: "SAAT-M-ALG.8", lvl: 2,
  stem: "For which value of k does the matrix below have no multiplicative inverse?",
  stemEq: "a_sing",
  opts: ["−12", "−4", "4", "12"], ans: 1,
  trick: "no inverse means determinant zero, and subtracting the product of two negatives ADDS — the sign of the 12 is where this is lost",
  why: "The determinant is 3k − (−2)(6) = 3k + 12, and 3k + 12 = 0 gives k = −4.",
  traps: ["A: the leading 3 left out, k + 12 = 0.",
          "C: the two minus signs cancelled, 3k − 12 = 0.",
          "D: both errors together, k − 12 = 0."] },

{ sig: "zero-determinant-meaning", code: "SAAT-M-ALG.8", lvl: 1,
  stem: "A square matrix has determinant 0. Which statement about it must be true?",
  opts: ["Its inverse is the zero matrix.",
         "It is the identity matrix.",
         "It has no multiplicative inverse.",
         "Its inverse is equal to itself."], ans: 2,
  trick: "dividing by the determinant is the LAST step of forming an inverse — a determinant of zero means there is nothing to divide by, so no inverse exists at all",
  why: "The inverse is the adjugate divided by the determinant, so a determinant of 0 leaves the inverse undefined.",
  traps: ["A: \"no inverse\" softened into an inverse made of zeros.",
          "B: determinant 0 confused with determinant 1.",
          "D: true of a few special matrices, never a consequence of a zero determinant."] },

{ sig: "scientific-notation-to-decimal", code: "SAAT-M-ALG.9", lvl: 1,
  stem: "Which is the ordinary decimal form of the number below?",
  stemEq: "a_sci1",
  opts: ["0.006", "60 000", "0.00006", "0.0006"], ans: 3,
  trick: "a power of −4 moves the point four places, and the 6 itself occupies the fourth place — counting zeros instead of places gives one too many",
  why: "6 × 10⁻⁴ = 0.0006.",
  traps: ["A: three decimal places written.",
          "B: the negative sign in the exponent ignored.",
          "C: five decimal places written instead of four."] },

{ sig: "scientific-notation-product", code: "SAAT-M-ALG.9", lvl: 2,
  stem: "Write the product below in scientific notation.",
  stemEq: "a_sci2",
  opts: [{ eq: "a_sci2o3" }, { eq: "a_sci2o4" }, { eq: "a_sci2o1" }, { eq: "a_sci2o2" }], ans: 0,
  trick: "4 × 2.5 = 10, which is NOT between 1 and 10 — one more power of ten has to move across before the answer is in standard form",
  why: "The numbers give 10 and the powers give 10⁻³, so the product is 10 × 10⁻³ = 1 × 10⁻².",
  traps: ["B: the exponents subtracted rather than added.",
          "C: the correct value, but not written in scientific notation.",
          "D: the extra power of ten moved the wrong way."] },

{ sig: "units-of-a-product", code: "SAAT-M-ALG.10", lvl: 2,
  stem: "In the relation below B is measured in kg/m³, C in m/s² and D in m. What are the units of A?",
  stemEq: "a_dim1",
  opts: [{ eq: "a_dim1o1" }, { eq: "a_dim1o2" }, { eq: "a_dim1o3" }, { eq: "a_dim1o4" }], ans: 1,
  trick: "units cancel exactly like numbers — three metres downstairs against two upstairs leaves ONE metre downstairs",
  why: "kg/m³ × m/s² × m = kg × m² ÷ (m³ × s²) = kg/(m·s²).",
  traps: ["A: the m³ in the denominator ignored.",
          "C: only one of the two metres in the numerator counted.",
          "D: every metre cancelled."] },

{ sig: "units-identify-quantity", code: "SAAT-M-ALG.10", lvl: 2,
  stem: "If v is a speed and t is a time, which of the expressions below has the units of a length?",
  opts: [{ eq: "a_dim2o1" }, { eq: "a_dim2o2" }, { eq: "a_dim2o3" }, { eq: "a_dim2o4" }], ans: 2,
  trick: "write the units out and cancel them — m/s multiplied by s is the only combination that leaves metres alone",
  why: "v × t has units (m/s) × s = m, a length.",
  traps: ["A: v ÷ t gives m/s², an acceleration.", "B: v × t² gives m·s.", "D: v ÷ t² gives m/s³."] },

{ sig: "vector-linear-combination", code: "SAAT-M-ALG.11", lvl: 2,
  stem: "Given the two vectors below, find 2A − B.",
  stemEq: "a_vec1",
  opts: [{ eq: "a_vec1o1" }, { eq: "a_vec1o2" }, { eq: "a_vec1o3" }, { eq: "a_vec1o4" }], ans: 3,
  trick: "the 2 multiplies BOTH components of A, and the subtraction then applies to both components of B — one careless component is the usual loss",
  why: "2A = ⟨10, −6⟩, and subtracting B = ⟨1, 4⟩ gives ⟨9, −10⟩.",
  traps: ["A: the y-components added instead of subtracted.",
          "B: B added throughout rather than subtracted.",
          "C: A − B computed, the factor 2 forgotten."] },

{ sig: "vector-magnitude", code: "SAAT-M-ALG.11", lvl: 1,
  stem: "What is the magnitude of the vector below?",
  stemEq: "a_vec2",
  opts: ["10", "14", "100", "2"], ans: 0,
  trick: "the components are SQUARED before they are added, so the minus sign disappears — and the square root at the end is not optional",
  why: "√((−6)² + 8²) = √(36 + 64) = √100 = 10.",
  traps: ["B: the components added.", "C: the square root not taken.", "D: the components subtracted."] },

{ sig: "odd-function-identification", code: "SAAT-M-ALG.12", lvl: 2,
  stem: "Which of the functions below is an odd function?",
  opts: [{ eq: "a_odd2" }, { eq: "a_odd3" }, { eq: "a_odd4" }, { eq: "a_odd1" }], ans: 1,
  trick: "test f(−x): odd means the whole output changes sign, so an EVEN power or a modulus can never qualify",
  why: "(−x)⁷ = −x⁷, so f(−x) = −f(x) and the function is odd.",
  traps: ["A: an even power gives an even function.",
          "C: the principal square root is not defined for negative x, so it is neither.",
          "D: |−x| = |x|, which makes the function even."] },

{ sig: "classify-even-odd-neither", code: "SAAT-M-ALG.12", lvl: 2,
  stem: "Classify the function below as even, odd, both or neither.",
  stemEq: "a_odd5",
  opts: ["Both even and odd", "Even", "Odd", "Neither"], ans: 2,
  trick: "substitute −x into EVERY term before deciding — a mixture of powers looks like \"neither\" until the substitution is finished",
  why: "f(−x) = (−x)³ − (−x) = −x³ + x = −(x³ − x) = −f(x), so f is odd.",
  traps: ["A: only the zero function is both even and odd.",
          "B: the sign applied to the first term only.",
          "D: the two different powers taken to rule out any symmetry."] },

{ sig: "composition-equality-solve", code: "SAAT-M-ALG.13", lvl: 3,
  stem: "Let f(x) = x² + 1 and g(x) = x − 3. For which value of x is f(g(x)) equal to g(f(x))?",
  opts: ["3", "0", "1", "2"], ans: 3,
  trick: "the two compositions are DIFFERENT functions — expand both in full, and the x² terms then cancel and leave a linear equation",
  why: "f(g(x)) = (x − 3)² + 1 = x² − 6x + 10 and g(f(x)) = x² − 2, so −6x + 10 = −2, giving x = 2.",
  traps: ["A: the same rule applied twice in the same order.",
          "B: the x² terms cancelled but the constants dropped.",
          "C: −6x + 10 = 2 solved instead."] },

{ sig: "composition-evaluate-order", code: "SAAT-M-ALG.13", lvl: 1,
  stem: "Let f(x) = 2x + 1 and g(x) = x². What is g(f(3))?",
  opts: ["49", "64", "19", "37"], ans: 0,
  trick: "the INNER function acts first — g(f(3)) means f first, and reversing the order is the whole trap",
  why: "f(3) = 7, and g(7) = 49.",
  traps: ["B: f(3) read as 8 and squared.",
          "C: the order reversed, f(g(3)) = f(9).",
          "D: only the 2x squared, (2 × 3)² + 1."] },

{ sig: "dot-product-perpendicular", code: "SAAT-M-ALG.14", lvl: 2,
  stem: "Find b so that the two vectors below are perpendicular.",
  stemEq: "a_dot1",
  opts: ["−3", "3", "6", "−6"], ans: 1,
  trick: "perpendicular means the dot product is ZERO, not that the vectors are equal or opposite — set it to 0 and solve",
  why: "(−2)b + (−3)(−1) + (1)(3) = −2b + 6 = 0, so b = 3.",
  traps: ["A: −2b + 6 = 0 solved as b = −3.",
          "C: the coefficient −2 ignored, leaving b − 6 = 0.",
          "D: the whole dot product given the wrong sign and then solved."] },

{ sig: "dot-product-value", code: "SAAT-M-ALG.14", lvl: 1,
  stem: "What is the dot product of the two vectors below?",
  stemEq: "a_dot2",
  opts: ["21", "−3", "3", "11"], ans: 2,
  trick: "the dot product is a NUMBER, not a vector — multiply matching components and add, keeping every sign",
  why: "(4)(3) + (−1)(5) + (2)(−2) = 12 − 5 − 4 = 3.",
  traps: ["A: all three products taken as positive.",
          "B: every sign flipped.",
          "D: the last term added instead of subtracted."] },

{ sig: "de-moivre-power", code: "SAAT-M-ALG.15", lvl: 3,
  stem: "Use De Moivre's theorem to compute the value below.",
  stemEq: "a_dm1",
  opts: [{ eq: "a_dm1o2" }, { eq: "a_dm1o3" }, { eq: "a_dm1o4" }, { eq: "a_dm1o1" }], ans: 3,
  trick: "the modulus is RAISED to the power while the angle is MULTIPLIED by it — swapping those two operations is what the options are built on",
  why: "2³ = 8 and 3 × 60° = 180°, so the value is 8(cos 180° + i sin 180°) = −8.",
  traps: ["A: the modulus multiplied by 3 instead of cubed.",
          "B: cos 180° taken as +1.",
          "C: the modulus cubed but the angle left at 60°."] },

{ sig: "de-moivre-modulus-argument", code: "SAAT-M-ALG.15", lvl: 2,
  stem: "A complex number has modulus 3 and argument 40°. What are the modulus and the argument of its cube?",
  opts: ["27 and 120°", "9 and 43°", "9 and 120°", "27 and 40°"], ans: 0,
  trick: "cubing does two different things at once — the modulus is cubed, the argument is tripled",
  why: "The modulus becomes 3³ = 27 and the argument becomes 3 × 40° = 120°.",
  traps: ["B: 3 added to the argument and the modulus squared.",
          "C: the modulus multiplied by 3 rather than cubed.",
          "D: the argument left unchanged."] },

{ sig: "log-linear-combination", code: "SAAT-M-ALG.16", lvl: 3,
  stem: "Two logarithms are given below. What is the value of log₃x + 3log₂y?",
  stemEq: "a_lgv",
  opts: ["0.6", "1", "1.2", "1.8"], ans: 1,
  trick: "the coefficient 3 belongs to the SECOND logarithm only — attaching it to both, or to neither, produces two of the four options",
  why: "0.4 + 3 × 0.2 = 0.4 + 0.6 = 1.",
  traps: ["A: the coefficient 3 dropped, 0.4 + 0.2.",
          "C: the 3 attached to the first logarithm instead.",
          "D: both logarithms multiplied by 3."] },

{ sig: "change-of-base", code: "SAAT-M-ALG.16", lvl: 2,
  stem: "Which expression below is equal to log of 5 to the base 8?",
  opts: [{ eq: "a_cob4" }, { eq: "a_cob1" }, { eq: "a_cob2" }, { eq: "a_cob3" }], ans: 2,
  trick: "the BASE goes underneath — writing it on top gives the reciprocal, which is a different number entirely",
  why: "Change of base gives log 5 ÷ log 8, in any one base throughout.",
  traps: ["A: the base left as a plain number rather than a logarithm.",
          "B: the base written on top.",
          "D: change of base confused with the quotient rule."] },

// ================================================================= GEOMETRY
{ sig: "rhombus-diagonals-to-side", code: "SAAT-M-GEO.1", lvl: 2,
  stem: "The diagonals of the rhombus below measure 16 cm and 30 cm. What is the length of one side?",
  fig: "saat_rhombus", figW: 1.95,
  opts: ["23 cm", "24 cm", "34 cm", "17 cm"], ans: 3,
  trick: "the diagonals bisect each other at right angles, so the side is the hypotenuse of a triangle whose legs are HALF of each diagonal",
  why: "The legs are 8 cm and 15 cm, so the side is √(64 + 225) = √289 = 17 cm.",
  traps: ["A: the two half-diagonals added, 8 + 15.",
          "B: half the sum of the full diagonals.",
          "C: the full diagonals used as the legs, giving √(256 + 900)."] },

{ sig: "rhombus-area-from-diagonals", code: "SAAT-M-GEO.1", lvl: 1,
  stem: "A rhombus has diagonals of length 12 cm and 20 cm. What is its area?",
  opts: ["120 cm²", "240 cm²", "32 cm²", "60 cm²"], ans: 0,
  trick: "the area is half the product of the diagonals — halving once is right, halving each of them separately is not",
  why: "½ × 12 × 20 = 120 cm².",
  traps: ["B: the halving forgotten.",
          "C: the diagonals added instead of multiplied.",
          "D: each diagonal halved first, 6 × 10."] },

{ sig: "parabola-orientation", code: "SAAT-M-GEO.2", lvl: 2,
  stem: "In which direction does the parabola below open?",
  stemEq: "a_par_a",
  opts: ["Up", "Down", "Left", "Right"], ans: 0,
  trick: "the SQUARED variable fixes the axis — x² means up or down, and only then does the sign of the other coefficient decide which",
  why: "x² = 4p(y − k) with 4p = 8 > 0, so the parabola opens upwards.",
  traps: ["B: the sign read off the −8 inside the bracket.",
          "C: the squared variable taken to be y.",
          "D: the squared variable taken to be y with a positive coefficient."] },

{ sig: "parabola-vertex-and-direction", code: "SAAT-M-GEO.2", lvl: 2,
  stem: "What is the vertex of the parabola below, and in which direction does it open?",
  stemEq: "a_par_b",
  opts: ["(5, −2), down", "(5, −2), left", "(5, −2), right", "(−5, 2), left"], ans: 1,
  trick: "the numbers inside the brackets appear with the OPPOSITE sign in the vertex, and y² makes the parabola horizontal whatever the numbers do",
  why: "(y + 2)² = −12(x − 5) has vertex (5, −2); the variable squared is y and −12 < 0, so it opens to the left.",
  traps: ["A: y² mistaken for the vertical case.",
          "C: the minus sign in −12 ignored.",
          "D: the signs inside the brackets copied straight into the vertex."] },

{ sig: "trapezoid-midsegment-find-base", code: "SAAT-M-GEO.3", lvl: 1,
  stem: "In the trapezoid below the midsegment EF measures 7 cm and the base AB measures 6 cm. What is the length of the base CD?",
  fig: "saat_trapezoid", figW: 2.05,
  opts: ["14 cm", "1 cm", "8 cm", "13 cm"], ans: 2,
  trick: "the midsegment is the AVERAGE of the two bases, so the sum of the bases is twice the midsegment — 14, not 7",
  why: "(6 + CD) ÷ 2 = 7, so 6 + CD = 14 and CD = 8 cm.",
  traps: ["A: the midsegment doubled and the given base ignored.",
          "B: the base subtracted from the midsegment.",
          "D: the midsegment and the base added."] },

{ sig: "trapezoid-midsegment-algebraic", code: "SAAT-M-GEO.3", lvl: 2,
  stem: "In a trapezoid the two bases measure 3x and x + 8, and the midsegment measures 12. What is x?",
  opts: ["6", "10", "1", "4"], ans: 3,
  trick: "double the midsegment BEFORE forming the equation — the sum of the bases is 24, and every wrong option here comes from a version of that step",
  why: "3x + (x + 8) = 24, so 4x = 16 and x = 4.",
  traps: ["A: the constant 8 dropped, 4x = 24.",
          "B: the midsegment taken as the difference of the bases.",
          "C: the midsegment used without doubling, 4x + 8 = 12."] },

{ sig: "classify-triangle-in-3d", code: "SAAT-M-GEO.4", lvl: 3,
  stem: "A triangle has vertices A(0, 3, 5), B(1, 0, 2) and C(0, −3, 5). What kind of triangle is ABC?",
  opts: ["Isosceles", "Right-angled", "Scalene", "Equilateral"], ans: 0,
  trick: "compare the SQUARES of the three lengths — no square root is needed to see which two are equal, and 19 + 19 is not 36",
  why: "AB² = 1 + 9 + 9 = 19, BC² = 1 + 9 + 9 = 19 and AC² = 0 + 36 + 0 = 36, so two sides are equal and the triangle is isosceles.",
  traps: ["B: 19 + 19 assumed to equal 36.",
          "C: the two equal squares not compared.",
          "D: two equal sides read as three."] },

{ sig: "distance-between-points-in-3d", code: "SAAT-M-GEO.4", lvl: 1,
  stem: "What is the distance between the points P(1, 2, 3) and Q(5, 5, 15)?",
  opts: ["5", "13", "19", "169"], ans: 1,
  trick: "there are THREE differences to square, not two — dropping the z-difference is the standard slip",
  why: "The differences are 4, 3 and 12, so the distance is √(16 + 9 + 144) = √169 = 13.",
  traps: ["A: the z-difference left out, √(16 + 9).",
          "C: the three differences added instead of squared.",
          "D: the square root not taken."] },

// ============================================================= TRIGONOMETRY
{ sig: "quadrant-both-negative", code: "SAAT-M-TRI.1", lvl: 1,
  stem: "In which quadrant are sin θ and cos θ both negative?",
  opts: ["Quadrant I", "Quadrant II", "Quadrant III", "Quadrant IV"], ans: 2,
  trick: "cosine follows x and sine follows y, so \"both negative\" is the quadrant where both coordinates are negative",
  why: "In the third quadrant x < 0 and y < 0, so both cos θ and sin θ are negative.",
  traps: ["A: every ratio is positive in the first quadrant.",
          "B: sine is positive there, only cosine is negative.",
          "D: cosine is positive there, only sine is negative."] },

{ sig: "quadrant-from-two-signs", code: "SAAT-M-TRI.1", lvl: 2,
  stem: "If sin θ is negative and cos θ is positive, in which quadrant does θ lie?",
  opts: ["Quadrant I", "Quadrant II", "Quadrant III", "Quadrant IV"], ans: 3,
  trick: "each condition rules out two quadrants — take the ONE quadrant they have in common rather than answering from the first condition",
  why: "sin θ < 0 leaves the third and fourth quadrants, and cos θ > 0 leaves the first and fourth, so θ is in the fourth.",
  traps: ["A: both signs read as positive.",
          "B: the two signs exchanged.",
          "C: both signs read as negative."] },

{ sig: "law-of-cosines-perimeter", code: "SAAT-M-TRI.2", lvl: 2,
  stem: "A triangle has two sides of length 15 cm each and the angle between them measures 60°. What is its perimeter?",
  opts: ["56 cm", "30 cm", "45 cm", "51 cm"], ans: 2,
  trick: "two EQUAL sides with 60° between them force an equilateral triangle — the third side is 15 cm before any cosine rule is written down",
  why: "c² = 225 + 225 − 2(225)(½) = 225, so c = 15 cm and the perimeter is 45 cm.",
  traps: ["A: the sign in the cosine rule taken as plus, giving c² = 675.",
          "B: only the two given sides added.",
          "D: cos 60° taken as 0, giving c = 15√2."] },

{ sig: "law-of-cosines-largest-angle", code: "SAAT-M-TRI.2", lvl: 3,
  stem: "A triangle has sides of 7 cm, 8 cm and 13 cm. What is the measure of its largest angle?",
  opts: ["150°", "60°", "90°", "120°"], ans: 3,
  trick: "the largest angle faces the LONGEST side, and a negative cosine is the signal that it is obtuse — dropping that minus sign gives 60°",
  why: "cos C = (49 + 64 − 169) ÷ (2 × 7 × 8) = −56 ÷ 112 = −0.5, so C = 120°.",
  traps: ["A: cos C = −0.5 matched to the wrong angle.",
          "B: the minus sign on the cosine dropped.",
          "C: 49 + 64 compared with 169 and read as a right angle."] },

{ sig: "simplify-sin-squared-over-tan-squared", code: "SAAT-M-TRI.3", lvl: 2,
  stem: "Simplify the expression below.",
  stemEq: "a_tr1",
  opts: [{ eq: "a_tr1o2" }, { eq: "a_tr1o3" }, { eq: "a_tr1o4" }, { eq: "a_tr1o1" }], ans: 0,
  trick: "rewrite the tangent as sine over cosine FIRST — dividing by a fraction then flips it, and the sines cancel completely",
  why: "sin²θ ÷ (sin²θ ÷ cos²θ) = sin²θ × (cos²θ ÷ sin²θ) = cos²θ.",
  traps: ["B: the tangent cancelled against the sine.",
          "C: the fraction left inverted.",
          "D: the reciprocal multiplied instead of divided."] },

{ sig: "simplify-with-pythagorean-identity", code: "SAAT-M-TRI.3", lvl: 2,
  stem: "Simplify the expression below.",
  stemEq: "a_tr2",
  opts: [{ eq: "a_tr2o2" }, { eq: "a_tr2o3" }, { eq: "a_tr2o4" }, { eq: "a_tr2o1" }], ans: 1,
  trick: "1 − cos²θ is sin²θ — until that is written down the expression looks as though nothing cancels",
  why: "(1 − cos²θ) ÷ (sin θ cos θ) = sin²θ ÷ (sin θ cos θ) = sin θ ÷ cos θ = tan θ.",
  traps: ["A: numerator and denominator both read as sin θ cos θ.",
          "C: only one factor of sine cancelled.",
          "D: the fraction inverted at the last step."] },

{ sig: "double-angle-identity-recognise", code: "SAAT-M-TRI.4", lvl: 3,
  stem: "Simplify the expression below.",
  stemEq: "a_tr3",
  opts: [{ eq: "a_tr3o4" }, { eq: "a_tr3o1" }, { eq: "a_tr3o2" }, { eq: "a_tr3o3" }], ans: 2,
  trick: "1 + tan²θ is sec²θ, so dividing by it MULTIPLIES by cos²θ — the expression then collapses to a double angle",
  why: "2 tan θ ÷ sec²θ = 2(sin θ ÷ cos θ)cos²θ = 2 sin θ cos θ = sin 2θ.",
  traps: ["A: 1 + tan²θ cancelled against the tangent.",
          "B: the cosine double angle used instead.",
          "D: the 2 read as doubling the angle of the tangent."] },

{ sig: "double-angle-value-from-sine", code: "SAAT-M-TRI.4", lvl: 2,
  stem: "If sin θ = 3/5 and θ is acute, what is sin 2θ?",
  opts: [{ eq: "a_tr4o4" }, { eq: "a_tr4o1" }, { eq: "a_tr4o2" }, { eq: "a_tr4o3" }], ans: 3,
  trick: "sin 2θ is not twice sin θ — the cosine has to be found first, and the 3-4-5 triangle gives it without a calculator",
  why: "cos θ = 4/5, so sin 2θ = 2 × (3/5) × (4/5) = 24/25.",
  traps: ["A: the sine simply doubled.",
          "B: cos 2θ computed instead, 1 − 2(9/25).",
          "C: the factor 2 left out."] },

{ sig: "polar-to-cartesian-negative-r", code: "SAAT-M-TRI.5", lvl: 3,
  stem: "What are the Cartesian coordinates of the polar point below?",
  stemEq: "a_pol1",
  opts: [{ eq: "a_pol1o4" }, { eq: "a_pol1o1" }, { eq: "a_pol1o2" }, { eq: "a_pol1o3" }], ans: 0,
  trick: "a NEGATIVE r sends the point to the opposite side of the origin, so BOTH coordinates change sign — this is the whole item",
  why: "x = −2cos 60° = −1 and y = −2sin 60° = −√3.",
  traps: ["B: r taken as +2.",
          "C: the negative sign applied to x only.",
          "D: the negative sign applied to y only."] },

{ sig: "cartesian-to-polar-on-axis", code: "SAAT-M-TRI.5", lvl: 2,
  stem: "A point has Cartesian coordinates (0, −4). Which pair of polar coordinates describes it?",
  opts: ["(4, 180°)", "(4, 270°)", "(−4, 270°)", "(4, 90°)"], ans: 1,
  trick: "r is a DISTANCE and so is never written negative here; the sign of y is carried by the angle instead",
  why: "The point is 4 units from the origin on the negative y-axis, which is the direction 270°.",
  traps: ["A: the point placed on the negative x-axis.",
          "C: the sign carried twice, once in r and once in the angle.",
          "D: the sign of y ignored."] },

{ sig: "triangle-area-two-sides-and-angle", code: "SAAT-M-TRI.6", lvl: 2,
  stem: "A triangle has two sides of length 18 cm and 22 cm with an included angle of 30°. What is its area?",
  opts: ["198 cm²", "396 cm²", "99 cm²", "172 cm²"], ans: 2,
  trick: "there are TWO halves in this calculation — the ½ in the formula and the ½ that is sin 30° — and each option below drops one of them",
  why: "½ × 18 × 22 × sin 30° = ½ × 18 × 22 × ½ = 99 cm².",
  traps: ["A: sin 30° taken as 1.",
          "B: the factor ½ dropped as well.",
          "D: sin 30° confused with cos 30°."] },

{ sig: "find-included-angle-from-area", code: "SAAT-M-TRI.6", lvl: 3,
  stem: "A triangle has sides of 10 cm and 12 cm with an included acute angle θ, and its area is 30 cm². What is θ?",
  opts: ["45°", "60°", "15°", "30°"], ans: 3,
  trick: "run the area formula backwards — divide by ½ and by both sides FIRST, and only then read the angle off the sine",
  why: "½ × 10 × 12 × sin θ = 30 gives sin θ = 0.5, so θ = 30°.",
  traps: ["A: sin θ = 0.5 matched to 45°.",
          "B: the complement of the correct angle given.",
          "C: the factor ½ applied twice, giving sin θ = 0.25."] },

// ================================================================= CALCULUS
{ sig: "count-zeros-by-sign-change", code: "SAAT-M-CAL.1", lvl: 3,
  stem: "A continuous function f takes the values in the table below. What is the least number of real zeros f must have on the interval [−2, 3]?",
  table: [["x", "−2", "−1", "0", "1", "2", "3"],
          ["f(x)", "−5", "−2", "1", "−3", "4", "−5"]],
  opts: ["4", "5", "2", "3"], ans: 0,
  trick: "only a change of SIGN forces a zero — −5 to −2 is a rise but not a crossing, and counting rises instead of crossings gives five",
  why: "The signs run −, −, +, −, +, −, so the sign changes between x = −1 and 0, 0 and 1, 1 and 2, and 2 and 3: four zeros.",
  traps: ["B: one zero counted for every interval in the table.",
          "C: only the changes from negative to positive counted.",
          "D: one crossing missed between the last two columns."] },

{ sig: "intermediate-value-statement", code: "SAAT-M-CAL.1", lvl: 2,
  stem: "A function f is continuous on [1, 4], with f(1) = −3 and f(4) = 5. Which statement must be true?",
  opts: ["f has exactly one zero on (1, 4).",
         "f has at least one zero on (1, 4).",
         "f has no zero on (1, 4).",
         "f is increasing on (1, 4)."], ans: 1,
  trick: "the theorem promises AT LEAST one crossing and never promises exactly one — \"exactly one\" is the option that catches most students",
  why: "f is continuous and changes sign on [1, 4], so it takes the value 0 somewhere between.",
  traps: ["A: the theorem guarantees at least one zero, never exactly one.",
          "C: the sign change ignored.",
          "D: a sign change taken to mean the function rises throughout."] },

{ sig: "average-rate-of-change", code: "SAAT-M-CAL.2", lvl: 2,
  stem: "What is the average rate of change of the function below on the interval [0, 6]?",
  stemEq: "a_arc",
  opts: ["192", "6", "32", "36"], ans: 2,
  trick: "this is the slope of a CHORD, not a derivative — divide the change in f by the change in x, which is 6 and not 1",
  why: "f(6) = 216 − 24 + 2 = 194 and f(0) = 2, so the average rate is (194 − 2) ÷ 6 = 32.",
  traps: ["A: f(6) − f(0) never divided by 6.",
          "B: the length of the interval reported as the answer.",
          "D: only the 6x² term used, 216 ÷ 6."] },

{ sig: "average-rate-equals-instantaneous", code: "SAAT-M-CAL.2", lvl: 2,
  stem: "For the function below, at which value of x does the instantaneous rate of change equal the average rate of change on [0, 4]?",
  stemEq: "a_arc2",
  opts: ["4", "8", "1", "2"], ans: 3,
  trick: "two different calculations meet here — the chord slope first, then the derivative set equal to it",
  why: "The average rate is (16 − 0) ÷ 4 = 4, and f′(x) = 2x, so 2x = 4 and x = 2.",
  traps: ["A: the average rate itself reported as x.",
          "B: f(4) − f(0) halved and taken as x.",
          "C: the average rate divided by 4 instead of by 2."] },

{ sig: "derivative-power-rule", code: "SAAT-M-CAL.3", lvl: 1,
  stem: "What is the derivative of the function below?",
  stemEq: "a_dv1",
  opts: [{ eq: "a_dv1o2" }, { eq: "a_dv1o3" }, { eq: "a_dv1o4" }, { eq: "a_dv1o1" }], ans: 0,
  trick: "the old power comes DOWN as a coefficient and the new power is one less — doing only one of those two things produces two of the options",
  why: "The derivative of x⁴ is 4x³.",
  traps: ["B: the coefficient brought down but the exponent not reduced.",
          "C: the antiderivative given instead of the derivative.",
          "D: the exponent and the coefficient exchanged."] },

{ sig: "derivative-radical-and-reciprocal", code: "SAAT-M-CAL.3", lvl: 2,
  stem: "Differentiate the function below.",
  stemEq: "a_dv2",
  opts: [{ eq: "a_dv2o4" }, { eq: "a_dv2o1" }, { eq: "a_dv2o2" }, { eq: "a_dv2o3" }], ans: 1,
  trick: "write both terms as POWERS before differentiating — √x is x to the half and 2/x is 2x to the power −1, and the negative power is where the sign comes from",
  why: "3x^(1/2) differentiates to (3/2)x^(−1/2), and 2x^(−1) differentiates to −2x^(−2).",
  traps: ["A: the coefficient 3 dropped.",
          "C: the sign produced by the power −1 lost.",
          "D: the second term differentiated as though the power were 0."] },

{ sig: "derivative-at-a-point", code: "SAAT-M-CAL.4", lvl: 1,
  stem: "For the function below, in which c is a constant, what is f′(1)?",
  stemEq: "a_dv3",
  opts: ["35", "10", "25", "30"], ans: 2,
  trick: "the derivative of a CONSTANT is zero, so c disappears before anything is substituted",
  why: "f′(x) = 30x − 5, so f′(1) = 30 − 5 = 25.",
  traps: ["A: the 5 added rather than subtracted.",
          "B: only the 15x² term differentiated and then halved.",
          "D: only the first term differentiated."] },

{ sig: "tangent-line-equation", code: "SAAT-M-CAL.4", lvl: 3,
  stem: "What is the equation of the tangent to the curve below at the point where x = 2?",
  stemEq: "a_dv4",
  opts: [{ eq: "a_dv4o3" }, { eq: "a_dv4o4" }, { eq: "a_dv4o1" }, { eq: "a_dv4o2" }], ans: 3,
  trick: "a tangent needs BOTH a slope and a point — the curve passes through (2, 0), and a line through the origin is the option that ignores it",
  why: "y(2) = 8 − 8 = 0 and y′ = 3x² − 4 gives slope 8, so y − 0 = 8(x − 2), that is y = 8x − 16.",
  traps: ["A: the point (2, 0) never substituted.",
          "B: the −4 dropped when differentiating, giving slope 12.",
          "C: the slope read off the −4x term only."] },

{ sig: "fundamental-theorem-statement", code: "SAAT-M-CAL.5", lvl: 1,
  stem: "F is an antiderivative of f. What does the definite integral below equal?",
  stemEq: "a_int1",
  opts: [{ eq: "a_int1o2" }, { eq: "a_int1o3" }, { eq: "a_int1o4" }, { eq: "a_int1o1" }], ans: 0,
  trick: "upper limit MINUS lower limit, in that order — reversing them changes the sign of the whole integral",
  why: "By the fundamental theorem the integral equals F(3) − F(0).",
  traps: ["B: the lower limit dropped.",
          "C: f used in place of its antiderivative.",
          "D: the limits used the wrong way round."] },

{ sig: "antiderivative-values-to-integral", code: "SAAT-M-CAL.5", lvl: 2,
  stem: "F is an antiderivative of f, with F(1) = 4 and F(5) = 19. What is the value of the integral of f from 1 to 5?",
  opts: ["4", "15", "19", "23"], ans: 1,
  trick: "the two values of F are SUBTRACTED, not added — and neither of them is the answer on its own",
  why: "The integral equals F(5) − F(1) = 19 − 4 = 15.",
  traps: ["A: the value at the lower limit given.",
          "C: the value at the upper limit given.",
          "D: the two values added."] },

{ sig: "evaluate-definite-integral", code: "SAAT-M-CAL.6", lvl: 2,
  stem: "Evaluate the definite integral below.",
  stemEq: "a_int2",
  opts: ["4", "10", "11", "21"], ans: 2,
  trick: "integrate FIRST and substitute afterwards — substituting into 4x + 1 itself is the mistake option A is built from",
  why: "The antiderivative is 2x² + x, and (18 + 3) − (8 + 2) = 21 − 10 = 11.",
  traps: ["A: the integrand itself evaluated at the limits, 13 − 9.",
          "B: the constant term dropped, 2(9) − 2(4).",
          "D: only the upper limit substituted."] },

{ sig: "maximum-on-closed-interval", code: "SAAT-M-CAL.7", lvl: 3,
  stem: "What is the maximum value of the function below on the interval [0, 3]?",
  stemEq: "a_max",
  opts: ["32", "0", "16", "27"], ans: 3,
  trick: "on a CLOSED interval the endpoints compete with the critical points, and here the only critical point inside is a minimum",
  why: "f′(x) = 12x − 3x² = 3x(4 − x), so the critical points are x = 0 and x = 4; x = 4 lies outside, and f(0) = 0, f(3) = 54 − 27 = 27.",
  traps: ["A: x = 4 used even though it lies outside [0, 3].",
          "B: f(0) taken because x = 0 is a critical point.",
          "C: only the middle of the interval tested, f(2)."] },

{ sig: "count-critical-points", code: "SAAT-M-CAL.7", lvl: 2,
  stem: "How many critical points does the function below have?",
  stemEq: "a_crit",
  opts: ["1", "2", "3", "0"], ans: 0,
  trick: "the derivative is a PERFECT SQUARE, so its two roots are the same point — a quadratic derivative does not always mean two critical points",
  why: "f′(x) = 3x² − 6x + 3 = 3(x − 1)², which is zero only at x = 1.",
  traps: ["B: a quadratic assumed to have two distinct roots.",
          "C: the degree of f used as the count.",
          "D: the repeated root read as no root at all."] },

{ sig: "limit-removable-discontinuity", code: "SAAT-M-CAL.8", lvl: 2,
  stem: "Evaluate the limit below.",
  stemEq: "a_lim1",
  opts: ["5", "10", "25", "0"], ans: 1,
  trick: "0/0 is not an answer — factor the numerator, cancel the common factor, and only then substitute",
  why: "(x² − 25) ÷ (x − 5) = x + 5 for x ≠ 5, and 5 + 5 = 10.",
  traps: ["A: the value x = 5 given as the limit.",
          "C: only the numerator evaluated.",
          "D: 0 ÷ 0 read as 0."] },

{ sig: "limit-by-rationalising", code: "SAAT-M-CAL.8", lvl: 3,
  stem: "Evaluate the limit below.",
  stemEq: "a_lim2",
  opts: [{ eq: "a_lim2o4" }, { eq: "a_lim2o1" }, { eq: "a_lim2o2" }, { eq: "a_lim2o3" }], ans: 2,
  trick: "multiply by the CONJUGATE of the numerator — the x then cancels and the denominator becomes √9 + 3, which is 6 and not 3",
  why: "The expression becomes 1 ÷ (√(x + 9) + 3), and at x = 0 that is 1 ÷ 6.",
  traps: ["A: the final fraction inverted.",
          "B: a numerator of 0 read as a limit of 0.",
          "D: the denominator written as 3 instead of 3 + 3."] },

{ sig: "second-derivative-test", code: "SAAT-M-CAL.9", lvl: 3,
  stem: "Using the second derivative test, where does the function below have a local maximum and where a local minimum?",
  stemEq: "a_sdt",
  opts: ["Maximum at x = 3, minimum at x = −3",
         "Maximum at x = −3, minimum at x = 3",
         "Maximum at x = −1, minimum at x = 1",
         "Maximum at x = 1, minimum at x = −1"], ans: 3,
  trick: "a NEGATIVE second derivative marks the maximum — the sign feels backwards, and reversing it swaps the two answers",
  why: "f′(x) = 3 − 3x² = 0 gives x = ±1, and f″(x) = −6x is negative at x = 1 and positive at x = −1.",
  traps: ["A: 3 − 3x² = 0 solved as x² = 9.",
          "B: both errors made together.",
          "C: the sign of f″ read the wrong way round."] },

{ sig: "point-of-inflection", code: "SAAT-M-CAL.9", lvl: 2,
  stem: "At which value of x does the graph of the function below change concavity?",
  stemEq: "a_inf",
  opts: ["2", "4", "6", "0"], ans: 0,
  trick: "concavity is governed by the SECOND derivative — solving f′(x) = 0 finds turning points instead and gives option C",
  why: "f″(x) = 6x − 12, which is zero at x = 2 and changes sign there.",
  traps: ["B: f′(x) = 3x² − 12x = 0 solved instead, a turning point.",
          "C: the coefficient 6 read off as the answer.",
          "D: f″(0) evaluated rather than f″(x) = 0 solved."] },

{ sig: "definite-integral-of-a-line", code: "SAAT-M-CAL.6", lvl: 2,
  stem: "Evaluate the definite integral below.",
  stemEq: "a_int3",
  opts: ["12", "20", "21", "24"], ans: 1,
  trick: "every term is integrated, the constant one included — dropping the −2 costs four and looks like a rounding slip",
  why: "The antiderivative is 3x² − 2x, and (27 − 6) − (3 − 2) = 21 − 1 = 20.",
  traps: ["A: the integrand itself evaluated at the limits, 16 − 4.",
          "C: only the upper limit substituted.",
          "D: the constant term dropped, 3(9) − 3(1)."] },

// ================================================ STATISTICS AND PROBABILITY
{ sig: "conditional-probability-dice", code: "SAAT-M-STA.1", lvl: 3,
  stem: "Two fair dice numbered 1 to 6 are rolled. Given that the sum of the two faces is 9, what is the probability that one of the dice shows 5?",
  opts: [{ eq: "a_pr1o1" }, { eq: "a_pr1o2" }, { eq: "a_pr1o3" }, { eq: "a_pr1o4" }], ans: 2,
  trick: "the condition SHRINKS the sample space to the four ways of making 9 — the 36 outcomes are gone, and (4, 5) and (5, 4) are two of the four, not one",
  why: "A sum of 9 comes from (3, 6), (4, 5), (5, 4) and (6, 3); two of those four contain a 5, so the probability is 2/4 = 1/2.",
  traps: ["A: 4 out of 36 computed, the condition ignored.",
          "B: (4, 5) and (5, 4) counted as one outcome.",
          "D: 2 counted out of the five sums that can contain a 5."] },

{ sig: "conditional-probability-subgroup", code: "SAAT-M-STA.1", lvl: 2,
  stem: "In a class of 30 students, 18 study biology and 12 of those are girls. A student is chosen at random from those who study biology. What is the probability that the student is a girl?",
  opts: [{ eq: "a_pr2o1" }, { eq: "a_pr2o2" }, { eq: "a_pr2o3" }, { eq: "a_pr2o4" }], ans: 3,
  trick: "the choice is made from the 18 biology students, so 18 is the denominator — 30 belongs to a question that was not asked",
  why: "12 of the 18 biology students are girls, so the probability is 12/18 = 2/3.",
  traps: ["A: 12 out of 30, the condition ignored.",
          "B: the 18 assumed to split evenly.",
          "C: 18 out of 30 given, the wrong quantity altogether."] },

{ sig: "normal-one-standard-deviation", code: "SAAT-M-STA.2", lvl: 2,
  stem: "The lifetimes of 1 000 batteries are normally distributed with a mean of 300 days and a standard deviation of 40 days. About how many of them last between 260 and 340 days?",
  opts: ["680", "950", "340", "500"], ans: 0,
  trick: "260 and 340 are exactly ONE standard deviation either side of the mean, so the 68% figure applies and not the 95% one",
  why: "About 68% of the values lie within one standard deviation, and 68% of 1 000 is 680.",
  traps: ["B: the two-standard-deviation figure of 95% used.",
          "C: only one side of the mean counted.",
          "D: half the batteries assumed."] },

{ sig: "normal-tail-percentage", code: "SAAT-M-STA.2", lvl: 3,
  stem: "Scores on a test are normally distributed with a mean of 70 and a standard deviation of 8. About what percentage of the scores lie above 86?",
  opts: ["32%", "2.5%", "5%", "16%"], ans: 1,
  trick: "86 is two standard deviations above the mean, and the 5% left outside is shared by TWO tails — only half of it lies above",
  why: "About 95% lie within two standard deviations, leaving 5% outside and 2.5% in the upper tail.",
  traps: ["A: the whole of the region outside one standard deviation used.",
          "C: both tails counted instead of the upper one.",
          "D: the one-standard-deviation upper tail used."] },

];
