// ---------------------------------------------------------------------------
// SIMULATED SAAT (TAHSILI) BANK — part B: UNIT 1, Number, Algebra & Algebraic
// Reasoning (weeks 1-3, sessions 1-9).
//
// Written against saat_skill_map.js, one item per objective of each session in
// the unit, so every item has a session it belongs to and nothing is here that
// the 45-week plan does not ask for. The `ses` field carries that session
// number; the strand code carries the domain, as in part A.
//
// Sessions 4 and 9 already had items in part A, so only their uncovered
// objectives appear below.
//
// Skills and tricks come from the department's Tahsili sources. No stem, number
// set, option list or figure is reproduced from any of them, and every answer is
// re-derived in verify_saat.py.
// ---------------------------------------------------------------------------
module.exports = [

// ============================ SESSION 1 — Real numbers & their properties ===
{ sig: "smallest-number-set", code: "SAAT-M-ALG.17", ses: 1, lvl: 1,
  stem: "To which set below does the number shown belong, and is the smallest set that contains it?",
  stemEq: "b_set1",
  opts: ["Natural numbers", "Integers", "Rational numbers", "Irrational numbers"], ans: 0,
  trick: "work the root out BEFORE classifying — the radical sign is what makes people answer irrational, and √36 is simply 6",
  why: "√36 = 6, a counting number, so the smallest set containing it is the natural numbers.",
  traps: ["B: 6 is an integer, but the integers are not the smallest set that contains it.",
          "C: also true, and also not the smallest.",
          "D: the radical sign taken as a sign of irrationality without evaluating it."] },

{ sig: "name-the-property-used", code: "SAAT-M-ALG.17", ses: 1, lvl: 1,
  stem: "Which property of real numbers justifies the step below?",
  stemEq: "b_prop",
  opts: ["Commutative", "Distributive", "Additive identity", "Associative"], ans: 1,
  trick: "look at what the 3 DID — it was multiplied into each term inside the bracket, and only one property does that",
  why: "The 3 multiplies both x and 7/6, which is multiplication distributing over subtraction.",
  traps: ["A: commutativity changes the order; the order here is unchanged.",
          "C: the additive identity adds zero, which is not what happened.",
          "D: associativity regroups a sum or a product; no bracket is opened."] },

{ sig: "multiplicative-inverse", code: "SAAT-M-ALG.17", ses: 1, lvl: 1,
  stem: "What is the multiplicative inverse of the number below?",
  stemEq: "b_mi",
  opts: [{ eq: "b_mi4" }, { eq: "b_mi1" }, { eq: "b_mi2" }, { eq: "b_mi3" }], ans: 2,
  trick: "the multiplicative inverse turns the fraction UPSIDE DOWN and keeps the sign; changing the sign is the additive inverse, a different question",
  why: "The reciprocal of −3/5 is −5/3, and (−3/5)(−5/3) = 1.",
  traps: ["A: the number itself repeated.",
          "B: the sign changed as well, which gives a product of −1.",
          "D: the additive inverse given instead."] },

{ sig: "closure-under-an-operation", code: "SAAT-M-ALG.17", ses: 1, lvl: 2,
  stem: "Which set below is NOT closed under division, ignoring division by zero?",
  opts: ["Non-zero rational numbers", "Real numbers", "Non-zero real numbers", "Integers"], ans: 3,
  trick: "closure fails as soon as ONE example leaves the set — 3 ÷ 2 is enough, and no amount of other examples repairs it",
  why: "3 ÷ 2 = 1.5, which is not an integer, so the integers are not closed under division.",
  traps: ["A: a quotient of two non-zero rationals is again a non-zero rational.",
          "B: closed once zero is excluded, which the question does.",
          "C: closed for the same reason."] },

// ================================ SESSION 2 — Rational & irrational numbers =
{ sig: "identify-the-irrational-number", code: "SAAT-M-ALG.18", ses: 2, lvl: 1,
  stem: "Which of the numbers below is irrational?",
  opts: [{ eq: "b_ir4" }, { eq: "b_ir1" }, { eq: "b_ir2" }, { eq: "b_ir3" }], ans: 0,
  trick: "a root is irrational only when the number under it is NOT a perfect square — √121 is 11 and belongs with the fractions, not with √8",
  why: "√8 = 2√2 is a non-terminating, non-repeating decimal; the other three are a fraction, a repeating decimal and the integer −11.",
  traps: ["B: a fraction of two integers is rational, however famous it is as an approximation of π.",
          "C: a repeating decimal is always rational.",
          "D: −√121 = −11, an integer."] },

{ sig: "product-of-surds-is-rational", code: "SAAT-M-ALG.18", ses: 2, lvl: 2,
  stem: "Which statement about the product below is true?",
  stemEq: "b_sur",
  opts: ["It is irrational, because both factors are irrational.",
         "It is rational, and equals 4.",
         "It is rational, and equals 16.",
         "It is irrational, and equals 4√2."], ans: 1,
  trick: "multiply the two roots into ONE root before deciding — two irrational factors can perfectly well have a rational product",
  why: "√2 × √8 = √16 = 4, a rational number.",
  traps: ["A: irrationality assumed to survive multiplication, which it need not.",
          "C: 2 × 8 = 16 taken as the answer without the square root.",
          "D: the roots left unmultiplied."] },

{ sig: "repeating-decimal-is-rational", code: "SAAT-M-ALG.18", ses: 2, lvl: 1,
  stem: "A decimal runs for ever but repeats the block 45 without end. Which statement about it is true?",
  opts: ["It is neither rational nor irrational.",
         "It is irrational, because it never terminates.",
         "It is rational, because the repeating block makes it a fraction of two integers.",
         "It is irrational, because it has infinitely many digits."], ans: 2,
  trick: "\"never ends\" is not the test — REPEATING is: every repeating decimal can be written as a fraction, and every fraction gives a terminating or repeating decimal",
  why: "A repeating decimal can always be written as a ratio of two integers, so it is rational.",
  traps: ["A: every real number is one or the other.",
          "B: non-terminating confused with non-repeating.",
          "D: the number of digits is not the test."] },

{ sig: "integers-either-side-of-a-surd", code: "SAAT-M-ALG.18", ses: 2, lvl: 1,
  stem: "Between which two consecutive integers does the number below lie?",
  stemEq: "b_bet",
  opts: ["8 and 9", "26 and 28", "6 and 7", "7 and 8"], ans: 3,
  trick: "find the perfect squares on either side, 49 and 64 — halving the number is what produces the last option",
  why: "49 < 55 < 64, so 7 < √55 < 8.",
  traps: ["A: 64 and 81 used.",
          "B: the number halved instead of square-rooted.",
          "C: 36 and 49 used, which do not straddle 55."] },

// ==================================== SESSION 3 — Exponents & radicals ======
{ sig: "simplify-product-of-powers", code: "SAAT-M-ALG.19", ses: 3, lvl: 2,
  stem: "Simplify the expression below.",
  stemEq: "b_pow",
  opts: [{ eq: "b_pow3" }, { eq: "b_pow4" }, { eq: "b_pow1" }, { eq: "b_pow2" }], ans: 0,
  trick: "multiplying powers of the same base ADDS the exponents, negatives included — −3 + 5 is 2, not 8",
  why: "2 × 7 = 14, x^(−3) × x^5 = x², and y³ × y^(−6) = y^(−3), giving 14x² ÷ y³.",
  traps: ["B: the coefficients added rather than multiplied.",
          "C: the exponents subtracted instead of added.",
          "D: the negative exponent left in the numerator."] },

{ sig: "radical-to-rational-exponent", code: "SAAT-M-ALG.19", ses: 3, lvl: 1,
  stem: "Which expression is equal to the radical below?",
  stemEq: "b_rad",
  opts: [{ eq: "b_rad4" }, { eq: "b_rad1" }, { eq: "b_rad2" }, { eq: "b_rad3" }], ans: 1,
  trick: "the INDEX goes underneath and the power on top — putting them the other way round is the whole of this question",
  why: "The cube root of x⁷ is x^(7/3).",
  traps: ["A: the index multiplied by the power.",
          "C: index and power exchanged.",
          "D: the index subtracted from the power."] },

{ sig: "even-index-needs-absolute-value", code: "SAAT-M-ALG.19", ses: 3, lvl: 3,
  stem: "Simplify the expression below, where a is any real number.",
  stemEq: "b_abs",
  opts: [{ eq: "b_abs4" }, { eq: "b_abs1" }, { eq: "b_abs2" }, { eq: "b_abs3" }], ans: 2,
  trick: "an EVEN index with an ODD result needs absolute value bars — the root is never negative, and a − 1 may be",
  why: "24 ÷ 8 = 3, which is odd, and the index 8 is even, so the value is |a − 1|³.",
  traps: ["A: the index subtracted from the power.",
          "B: the bars dropped, which allows a negative value from an even root.",
          "D: the exponents multiplied instead of divided."] },

{ sig: "quotient-of-radicals", code: "SAAT-M-ALG.19", ses: 3, lvl: 2,
  stem: "Evaluate the expression below.",
  stemEq: "b_qr",
  opts: [{ eq: "b_qr4" }, { eq: "b_qr1" }, { eq: "b_qr2" }, { eq: "b_qr3" }], ans: 3,
  trick: "bring the two roots under ONE root first — 63 ÷ 28 is 9/4, and its root is exact, so nothing has to be approximated",
  why: "√63 ÷ √28 = √(63/28) = √(9/4) = 3/2.",
  traps: ["A: the square root of 9/4 left as 9/4.",
          "B: 63 − 28 taken under the root.",
          "C: the roots simplified separately and then subtracted."] },

{ sig: "rationalise-a-two-term-denominator", code: "SAAT-M-ALG.19", ses: 3, lvl: 3,
  stem: "Rationalise the denominator of the fraction below.",
  stemEq: "b_ratl",
  opts: [{ eq: "b_ratl1" }, { eq: "b_ratl2" }, { eq: "b_ratl3" }, { eq: "b_ratl4" }], ans: 0,
  trick: "multiply top and bottom by the CONJUGATE, √3 − 1; the denominator becomes 3 − 1 = 2, which then cancels the 2 on top",
  why: "2(√3 − 1) ÷ [(√3 + 1)(√3 − 1)] = 2(√3 − 1) ÷ 2 = √3 − 1.",
  traps: ["B: the sign of the conjugate taken the same as the denominator.",
          "C: the denominator computed as 3 + 1 = 4.",
          "D: only the denominator multiplied by the conjugate."] },

// =============================== SESSION 4 — Scientific notation (part A) ===
{ sig: "compare-in-scientific-notation", code: "SAAT-M-ALG.9", ses: 4, lvl: 2,
  stem: "Which of the numbers below is the largest?",
  opts: [{ eq: "b_cmp1" }, { eq: "b_cmp2" }, { eq: "b_cmp3" }, { eq: "b_cmp4" }], ans: 1,
  trick: "compare the POWERS of ten first and the digits only afterwards — −2 beats −3 however large the leading digit is",
  why: "1.2 × 10⁻² = 0.012 and 1.05 × 10⁻² = 0.0105, both larger than either number with 10⁻³; of the two, 1.2 is the larger.",
  traps: ["A: the largest leading digit chosen without looking at the power.",
          "C: 8.5 read as larger than 1.2 with the powers ignored.",
          "D: the correct power but the smaller leading digit."] },

// =========================== SESSION 5 — Algebraic expressions & operations =
{ sig: "leading-coefficient-of-a-polynomial", code: "SAAT-M-ALG.20", ses: 5, lvl: 1,
  stem: "What is the leading coefficient of the polynomial below?",
  stemEq: "b_lead",
  opts: ["−1", "4", "−2", "−3"], ans: 2,
  trick: "the leading coefficient belongs to the HIGHEST power, not to the first term written — the terms here are out of order on purpose",
  why: "The highest power is x⁴ and its coefficient is −2.",
  traps: ["A: the coefficient of the first term written.",
          "B: the degree given instead of the coefficient.",
          "D: the coefficient of x², the largest-looking term."] },

{ sig: "missing-factor-from-an-area", code: "SAAT-M-ALG.20", ses: 5, lvl: 2,
  stem: "A rectangle has area x² + 3x − 40 and one side of length x − 5. What is the length of the other side?",
  opts: [{ eq: "b_area3" }, { eq: "b_area4" }, { eq: "b_area1" }, { eq: "b_area2" }], ans: 3,
  trick: "area ÷ side = the other side, so FACTOR the area — the two numbers must multiply to −40 and add to 3",
  why: "x² + 3x − 40 = (x − 5)(x + 8), so the other side is x + 8.",
  traps: ["A: the 5 from the given side reused as the constant.",
          "B: 40 divided by 5 and written as a coefficient.",
          "C: the sign of the known factor copied into the answer."] },

{ sig: "simplify-quotient-with-negative-powers", code: "SAAT-M-ALG.20", ses: 5, lvl: 2,
  stem: "Simplify the expression below.",
  stemEq: "b_negp",
  opts: [{ eq: "b_negp4" }, { eq: "b_negp1" }, { eq: "b_negp2" }, { eq: "b_negp3" }], ans: 0,
  trick: "dividing powers SUBTRACTS the exponents, and a negative result moves the letter to the other side of the fraction bar",
  why: "2 ÷ 6 = 1/3, a³ ÷ a⁵ = a^(−2), and b² ÷ b = b, giving b ÷ (3a²).",
  traps: ["B: the exponents added.",
          "C: the coefficients subtracted rather than divided.",
          "D: a² left in the numerator."] },

{ sig: "substitute-a-monomial-into-a-polynomial", code: "SAAT-M-ALG.20", ses: 5, lvl: 2,
  stem: "For the function below, what is f(−2x)?",
  stemEq: "b_subm",
  opts: [{ eq: "b_subm2" }, { eq: "b_subm3" }, { eq: "b_subm4" }, { eq: "b_subm1" }], ans: 1,
  trick: "the whole of −2x is squared, so that term becomes +8x², and the middle term changes sign — both, not one",
  why: "2(−2x)² − 3(−2x) − 3 = 8x² + 6x − 3.",
  traps: ["A: the sign of the middle term left unchanged.",
          "C: the constant multiplied by −2 as well.",
          "D: only the x squared, leaving −2x² in front."] },

// ==================================== SESSION 6 — Factoring polynomials =====
{ sig: "factor-difference-of-squares-in-a-product", code: "SAAT-M-ALG.21", ses: 6, lvl: 3,
  stem: "Simplify the product below.",
  stemEq: "b_dos",
  opts: [{ eq: "b_dos4" }, { eq: "b_dos1" }, { eq: "b_dos2" }, { eq: "b_dos3" }], ans: 2,
  trick: "factor a² − b² BEFORE multiplying — the factor a − b then cancels, and nothing needs expanding at all",
  why: "(a − b)(a + b) ÷ (3b) × 9b² ÷ (a − b) = 3b(a + b).",
  traps: ["A: a² − b² read as (a − b)².",
          "B: the numerators multiplied out instead of factored.",
          "D: only b² cancelled, leaving 3b in the wrong place."] },

{ sig: "factor-a-quadratic-trinomial", code: "SAAT-M-ALG.21", ses: 6, lvl: 1,
  stem: "Which expression below is a factor of x² + 4x − 5?",
  opts: [{ eq: "b_tri2" }, { eq: "b_tri3" }, { eq: "b_tri4" }, { eq: "b_tri1" }], ans: 3,
  trick: "the two numbers must MULTIPLY to −5 and ADD to 4, and only 5 and −1 do both",
  why: "x² + 4x − 5 = (x + 5)(x − 1), so x + 5 is a factor.",
  traps: ["A: signs of the correct pair exchanged.",
          "B: 4 taken from the middle term as a factor.",
          "C: the second factor with its sign reversed."] },

{ sig: "identify-a-prime-polynomial", code: "SAAT-M-ALG.21", ses: 6, lvl: 2,
  stem: "Which of the polynomials below is prime over the integers?",
  opts: [{ eq: "b_pr3" }, { eq: "b_pr4" }, { eq: "b_pr1" }, { eq: "b_pr2" }], ans: 0,
  trick: "prime means NO factoring is possible at all, and a common numerical factor counts — 2x + 4 is not prime because 2 comes out",
  why: "3x − 7 has no common factor and is not a difference of squares or a factorable trinomial.",
  traps: ["B: x factors out, giving x(x + 5).",
          "C: 2 factors out, giving 2(x + 2).",
          "D: a difference of two squares, (x − y)(x + y)."] },

{ sig: "factor-by-grouping", code: "SAAT-M-ALG.21", ses: 6, lvl: 2,
  stem: "Factor the polynomial below completely.",
  stemEq: "b_grp",
  opts: [{ eq: "b_grp3" }, { eq: "b_grp4" }, { eq: "b_grp1" }, { eq: "b_grp2" }], ans: 1,
  trick: "take the common factor out of each PAIR first; the bracket left behind must be identical, which is what tells you the grouping was right",
  why: "x²(x + 2) − 3(x + 2) = (x + 2)(x² − 3).",
  traps: ["A: the common bracket taken as x − 2.",
          "C: the sign of the second group left as +3.",
          "D: x² − 3 written as a difference of squares, which it is not over the integers."] },

// ====================================== SESSION 7 — Algebraic fractions =====
{ sig: "simplify-a-rational-expression", code: "SAAT-M-ALG.22", ses: 7, lvl: 3,
  stem: "Write the expression below in its simplest form.",
  stemEq: "b_rat",
  opts: [{ eq: "b_rat3" }, { eq: "b_rat4" }, { eq: "b_rat1" }, { eq: "b_rat2" }], ans: 2,
  trick: "factor EVERY part first, the 4x − 12 included — one x − 3 cancels and one survives, which is where the errors come from",
  why: "(x − 2)(x − 3)² ÷ [4(x − 3)(x + 3)(x − 2)] = (x − 3) ÷ [4(x + 3)].",
  traps: ["A: the 4 left in the numerator.",
          "B: x² + x − 6 factored as (x + 2)(x − 3).",
          "D: both factors of (x − 3)² cancelled."] },

{ sig: "subtract-two-rational-expressions", code: "SAAT-M-ALG.22", ses: 7, lvl: 2,
  stem: "Simplify the expression below.",
  stemEq: "b_sub",
  opts: [{ eq: "b_sub4" }, { eq: "b_sub1" }, { eq: "b_sub2" }, { eq: "b_sub3" }], ans: 3,
  trick: "the common denominator is a² − 1, and the subtraction reaches BOTH terms of the second numerator — that is where the −1 becomes +1",
  why: "[a(a + 1) − a(a − 1)] ÷ (a² − 1) = 2a ÷ (a² − 1).",
  traps: ["A: the a multiplied into both brackets and the results added.",
          "B: the minus sign not carried across the second numerator, leaving 0.",
          "C: (a − 1)(a + 1) multiplied out as a² + 1."] },

{ sig: "simplify-a-complex-fraction", code: "SAAT-M-ALG.22", ses: 7, lvl: 2,
  stem: "Simplify the complex fraction below.",
  stemEq: "b_cf",
  opts: [{ eq: "b_cf2" }, { eq: "b_cf3" }, { eq: "b_cf4" }, { eq: "b_cf1" }], ans: 0,
  trick: "a fraction over a fraction is a DIVISION — invert the lower fraction and multiply, rather than cancelling across the bar",
  why: "(x/6) ÷ [(x − 3)/5] = (x/6)(5/(x − 3)) = 5x ÷ (6x − 18).",
  traps: ["B: the two numerators and the two denominators multiplied straight across.",
          "C: the 5 lost when the second fraction was inverted.",
          "D: the first fraction inverted instead of the second."] },

{ sig: "values-that-make-an-expression-undefined", code: "SAAT-M-ALG.22", ses: 7, lvl: 2,
  stem: "For which values of x is the expression below undefined?",
  stemEq: "b_und",
  opts: [{ eq: "b_und3" }, { eq: "b_und4" }, { eq: "b_und1" }, { eq: "b_und2" }], ans: 1,
  trick: "the DENOMINATOR alone decides, and x = 3 still counts even though it cancels with the numerator — cancelling does not make the original expression defined there",
  why: "x² + 4x − 21 = (x + 7)(x − 3), which is zero at x = 3 and x = −7.",
  traps: ["A: the signs of both roots reversed.",
          "C: only the value that does not cancel given.",
          "D: the numerator set to zero instead."] },

{ sig: "lcm-of-two-monomials", code: "SAAT-M-ALG.22", ses: 7, lvl: 1,
  stem: "What is the least common multiple of the two expressions below?",
  stemEq: "b_lcm",
  opts: [{ eq: "b_lcm1" }, { eq: "b_lcm2" }, { eq: "b_lcm3" }, { eq: "b_lcm4" }], ans: 2,
  trick: "the LCM takes the HIGHEST power of every letter, not the lowest — the lowest powers give the highest common factor instead",
  why: "LCM(20, 4) = 20, the highest power of x is x³ and of y is y⁶, giving 20x³y⁶.",
  traps: ["A: the lowest power of each letter used, which is the HCF.",
          "B: the two coefficients multiplied.",
          "D: the exponents added."] },

// ========================== SESSION 8 — Linear equations & inequalities =====
{ sig: "solve-a-linear-equation-with-fractions", code: "SAAT-M-ALG.23", ses: 8, lvl: 2,
  stem: "Solve the equation below.",
  stemEq: "b_lin",
  opts: ["−17", "1", "7", "17"], ans: 3,
  trick: "cross-multiply once and the fractions are gone; multiplying only one side by its own denominator is what produces the small answers",
  why: "3(3x + 4) = 5(2x − 1) gives 9x + 12 = 10x − 5, so x = 17.",
  traps: ["A: the sign lost when 9x was taken from both sides.",
          "B: only the numerators equated.",
          "C: 12 − 5 taken as the answer."] },

{ sig: "reverse-the-sign-when-dividing-by-a-negative", code: "SAAT-M-ALG.23", ses: 8, lvl: 2,
  stem: "Solve the inequality below.",
  stemEq: "b_ineq",
  opts: [{ eq: "b_ineq2" }, { eq: "b_ineq3" }, { eq: "b_ineq4" }, { eq: "b_ineq1" }], ans: 0,
  trick: "dividing by −4 REVERSES the inequality sign — the arithmetic is easy and the sign is the whole question",
  why: "−4x > 16, and dividing by −4 gives x < −4.",
  traps: ["B: 3 added instead of subtracted, giving −4x > 22.",
          "C: the minus sign dropped from −4x.",
          "D: the sign not reversed."] },

{ sig: "write-an-inequality-as-an-interval", code: "SAAT-M-ALG.23", ses: 8, lvl: 1,
  stem: "Which interval represents the inequality below?",
  stemEq: "b_int",
  opts: [{ eq: "b_int2" }, { eq: "b_int3" }, { eq: "b_int4" }, { eq: "b_int1" }], ans: 1,
  trick: "a square bracket goes with ≤ and a round bracket with < — the two ends are decided separately, and mixing them is the point of this item",
  why: "−2 is included, so a square bracket; 5 is not, so a round bracket: [−2, 5).",
  traps: ["A: both ends open.", "C: the two brackets exchanged.", "D: both ends closed."] },

{ sig: "point-in-the-solution-region", code: "SAAT-M-ALG.23", ses: 8, lvl: 3,
  stem: "Which point below satisfies both inequalities of the system shown?",
  stemEq: "b_sys",
  opts: [{ eq: "b_sys2" }, { eq: "b_sys3" }, { eq: "b_sys4" }, { eq: "b_sys1" }], ans: 2,
  trick: "a point must satisfy BOTH lines — testing it in the first one only is what makes three of these look right",
  why: "At (10, 15): 15 ≤ 2(10) − 3 = 17 and 15 ≥ 10 + 4 = 14, so both hold.",
  traps: ["A: satisfies the first only, since 10 < 12.",
          "B: satisfies the first only, since 2 < 9.",
          "D: satisfies the second inequality only."] },

{ sig: "vertex-of-a-feasible-region", code: "SAAT-M-ALG.23", ses: 8, lvl: 3,
  stem: "In the system below, what are the coordinates of the vertex where the slanted boundary meets the line y = 9?",
  stemEq: "b_vert",
  opts: [{ eq: "b_vert2" }, { eq: "b_vert3" }, { eq: "b_vert4" }, { eq: "b_vert1" }], ans: 3,
  trick: "a vertex is where two boundaries MEET, so substitute one equation into the other rather than reading a point off the picture",
  why: "9 = −3x + 12 gives 3x = 3 and x = 1, so the vertex is (1, 9).",
  traps: ["A: −3x = −3 solved as x = 3.",
          "B: the coordinates written the wrong way round.",
          "C: the sign of x lost."] },

// ================== SESSION 9 — Absolute-value equations & inequalities =====
{ sig: "absolute-value-equal-to-a-negative", code: "SAAT-M-ALG.4", ses: 9, lvl: 2,
  stem: "Solve the equation below.",
  stemEq: "b_avn",
  opts: ["No solution", "x = 1", "x = 5", "x = 1 or x = 5"], ans: 0,
  trick: "an absolute value is never negative, so the equation is impossible before any working starts — every value offered comes from ignoring that",
  why: "|2x − 6| is greater than or equal to 0 for every x, so it can never equal −4.",
  traps: ["B: the bars dropped and 2x − 6 = −4 solved.",
          "C: the bars dropped and 2x − 6 = 4 solved.",
          "D: both branches solved with the minus sign ignored."] },

{ sig: "absolute-value-inequality-as-a-double-inequality", code: "SAAT-M-ALG.4", ses: 9, lvl: 2,
  stem: "Solve the inequality below.",
  stemEq: "b_avi",
  opts: [{ eq: "b_avi2" }, { eq: "b_avi3" }, { eq: "b_avi4" }, { eq: "b_avi1" }], ans: 1,
  trick: "a LESS-THAN absolute value becomes one double inequality, not two separate branches — \"or\" belongs to the greater-than case",
  why: "−3 < x − 4 < 3, and adding 4 throughout gives 1 < x < 7.",
  traps: ["A: the two-branch \"or\" form used, which answers |x − 4| > 3.",
          "C: 4 subtracted instead of added.",
          "D: only the positive branch solved."] },

];
