// ---------------------------------------------------------------------------
// SIMULATED SAAT (TAHSILI) BANK — part C: UNIT 2, Equations, Systems &
// Quadratics (weeks 4-6, sessions 10-18).
//
// Written against saat_skill_map.js, one item per uncovered objective. Session
// 10 already held six matrix items from part A, so only its substitution and
// elimination objective appears here.
//
// Nothing is transcribed from any source: skills and tricks only, every stem
// and number set fresh, every answer re-derived in verify_saat.py.
// ---------------------------------------------------------------------------
module.exports = [

// ======================== SESSION 10 — Systems of linear equations =========
{ sig: "solve-system-by-elimination", code: "SAAT-M-ALG.24", ses: 10, lvl: 2,
  stem: "Solve the system below by elimination. What is y?",
  stemEq: "c_elim",
  opts: ["2", "3", "6", "18"], ans: 0,
  trick: "the y terms already cancel when the equations are ADDED — and the question asks for y, not for x",
  why: "Adding gives 6x = 18, so x = 3; substituting back, 6 + 3y = 12 and y = 2.",
  traps: ["B: x reported instead of y.",
          "C: 3y = 6 read off without dividing by 3.",
          "D: 6x = 18 left undivided."] },

// ============= SESSION 11 — Systems in context & number of solutions =======
{ sig: "number-of-solutions-from-slopes", code: "SAAT-M-ALG.25", ses: 11, lvl: 2,
  stem: "How many solutions does the system below have?",
  stemEq: "c_nosol",
  opts: ["Exactly one solution", "No solution", "Infinitely many solutions", "Exactly two solutions"], ans: 1,
  trick: "match the coefficients before deciding — doubling the first equation gives the same left side but a DIFFERENT constant, so the lines are parallel",
  why: "Doubling the first equation gives 4x − 6y = 12, and the second says 4x − 6y = 18. The two cannot both hold.",
  traps: ["A: two equations assumed to mean one crossing point.",
          "C: the matching left sides taken as the whole test — the constants differ.",
          "D: a system of two straight lines never has exactly two solutions."] },

{ sig: "system-from-a-worded-situation", code: "SAAT-M-ALG.25", ses: 11, lvl: 2,
  stem: "Tickets to an exhibition in Jeddah cost 45 SAR for an adult and 20 SAR for a child. On one day 30 tickets were sold for a total of 950 SAR. How many child tickets were sold?",
  opts: ["10", "14", "16", "20"], ans: 2,
  trick: "price all thirty at the ADULT rate first — the shortfall, divided by the DIFFERENCE in price, is the number of children",
  why: "Thirty adults would be 1 350 SAR; the takings are 400 SAR short, and each child saves 25 SAR, so there were 400 ÷ 25 = 16 children.",
  traps: ["A: 400 divided by 40 rather than by the 25 SAR difference.",
          "B: the number of adults reported.",
          "D: 400 divided by the child price instead of the price difference."] },

{ sig: "point-satisfying-every-constraint", code: "SAAT-M-ALG.25", ses: 11, lvl: 3,
  stem: "Which point below satisfies every constraint of the system shown?",
  stemEq: "c_feas",
  opts: [{ eq: "c_feas3" }, { eq: "c_feas4" }, { eq: "c_feas1" }, { eq: "c_feas2" }], ans: 3,
  trick: "test the point in EVERY line, not in the first one that works — three of these satisfy some of the system",
  why: "At (4, 6): both coordinates are positive, 4 + 6 = 10 which is allowed, and 8 + 6 = 14 which is allowed.",
  traps: ["A: 6 + 5 = 11, which breaks x + y ≤ 10.",
          "B: 16 + 0 = 16, which breaks 2x + y ≤ 14.",
          "C: fails the first constraint, since a coordinate is negative."] },

{ sig: "area-of-a-triangle-by-determinant", code: "SAAT-M-ALG.25", ses: 11, lvl: 3,
  stem: "A triangle has vertices at (0, 0), (5, 0) and (2, 6). What is its area?",
  opts: ["15", "30", "36", "7.5"], ans: 0,
  trick: "the determinant gives TWICE the area — the one half is part of the formula, not an extra step to invent or to repeat",
  why: "With a base of 5 along the x-axis and a height of 6, the area is ½ × 5 × 6 = 15 square units.",
  traps: ["B: the determinant reported without halving.",
          "C: the two largest coordinates multiplied.",
          "D: halved a second time."] },

// ==================== SESSION 12 — Quadratic equations by factoring ========
{ sig: "solve-quadratic-by-factoring", code: "SAAT-M-ALG.26", ses: 12, lvl: 1,
  stem: "Solve the equation below by factoring.",
  stemEq: "c_fac",
  opts: [{ eq: "c_fac4" }, { eq: "c_fac1" }, { eq: "c_fac2" }, { eq: "c_fac3" }], ans: 1,
  trick: "the two numbers multiply to +12 and add to −7, so BOTH are negative — and the roots then come out positive",
  why: "x² − 7x + 12 = (x − 3)(x − 4), so x = 3 or x = 4.",
  traps: ["A: a pair multiplying to 12 but adding to 13.",
          "C: the signs of the factors carried into the roots.",
          "D: a pair multiplying to 12 but adding to 8."] },

{ sig: "form-a-quadratic-from-its-roots", code: "SAAT-M-ALG.26", ses: 12, lvl: 2,
  stem: "Which equation has roots 5 and −2?",
  opts: [{ eq: "c_frm4" }, { eq: "c_frm1" }, { eq: "c_frm2" }, { eq: "c_frm3" }], ans: 2,
  trick: "the coefficient of x is MINUS the sum of the roots, and the constant is their product — the sign of the middle term is where this is lost",
  why: "The sum is 3 and the product is −10, so the equation is x² − 3x − 10 = 0.",
  traps: ["A: the roots added as 5 + 2 and multiplied as 5 × 2.",
          "B: the sum used with its own sign instead of reversed.",
          "D: the product given the wrong sign."] },

{ sig: "equation-quadratic-after-clearing-a-fraction", code: "SAAT-M-ALG.26", ses: 12, lvl: 3,
  stem: "Solve the equation below.",
  stemEq: "c_clr",
  opts: [{ eq: "c_clr4" }, { eq: "c_clr1" }, { eq: "c_clr2" }, { eq: "c_clr3" }], ans: 3,
  trick: "multiply through by x FIRST — the equation is quadratic in disguise, and x = 0 is excluded from the start",
  why: "Multiplying by x gives x² + 6 = 5x, that is x² − 5x + 6 = 0, so x = 2 or x = 3.",
  traps: ["A: 5 and 6 read straight out of the equation.",
          "B: the signs of the roots reversed.",
          "C: a pair multiplying to 6 but adding to 7."] },

{ sig: "zeros-from-factored-form", code: "SAAT-M-ALG.26", ses: 12, lvl: 1,
  stem: "What are the zeros of the function below?",
  stemEq: "c_zer",
  opts: [{ eq: "c_zer4" }, { eq: "c_zer1" }, { eq: "c_zer2" }, { eq: "c_zer3" }], ans: 0,
  trick: "set each bracket to zero and SOLVE it — 2x − 6 = 0 gives 3, not 6, because the 2 has to be divided out",
  why: "2x − 6 = 0 gives x = 3, and x + 4 = 0 gives x = −4.",
  traps: ["B: both signs reversed.",
          "C: 2x − 6 = 0 read as x = 6.",
          "D: the coefficient 2 taken as a zero."] },

// ============ SESSION 13 — Completing the square & the quadratic formula ===
{ sig: "complete-the-square-to-vertex-form", code: "SAAT-M-ALG.27", ses: 13, lvl: 2,
  stem: "Write the function below in vertex form.",
  stemEq: "c_cts",
  opts: [{ eq: "c_cts4" }, { eq: "c_cts1" }, { eq: "c_cts2" }, { eq: "c_cts3" }], ans: 1,
  trick: "half of −6 is −3 and its square is 9, so 9 is ADDED inside and SUBTRACTED outside — the constant left over is 11 − 9 = 2",
  why: "x² − 6x + 11 = (x² − 6x + 9) + 2 = (x − 3)² + 2.",
  traps: ["A: the whole coefficient used instead of half of it.",
          "C: the sign inside the bracket copied from the equation.",
          "D: the 9 subtracted twice."] },

{ sig: "quadratic-formula-with-complex-pair", code: "SAAT-M-ALG.27", ses: 13, lvl: 3,
  stem: "Solve the equation below.",
  stemEq: "c_cpx",
  opts: [{ eq: "c_cpx4" }, { eq: "c_cpx1" }, { eq: "c_cpx2" }, { eq: "c_cpx3" }], ans: 2,
  trick: "the discriminant is −16, so the root of it is 4i — and the whole numerator is divided by 2a, the imaginary part included",
  why: "x = (2 ± √(4 − 20)) ÷ 2 = (2 ± 4i) ÷ 2 = 1 ± 2i.",
  traps: ["A: −b taken as 2 and left undivided.",
          "B: the sign of −b lost.",
          "D: only the real part divided by 2."] },

{ sig: "vertex-from-completed-square", code: "SAAT-M-ALG.27", ses: 13, lvl: 1,
  stem: "What is the vertex of the parabola below?",
  stemEq: "c_vtx",
  opts: [{ eq: "c_vtx4" }, { eq: "c_vtx1" }, { eq: "c_vtx2" }, { eq: "c_vtx3" }], ans: 3,
  trick: "the number inside the bracket appears in the vertex with the OPPOSITE sign; the number outside keeps its own",
  why: "y = 2(x + 4)² − 7 has h = −4 and k = −7, so the vertex is (−4, −7).",
  traps: ["A: both signs copied without change.",
          "B: the sign inside the bracket copied straight out.",
          "C: the sign outside reversed as well."] },

{ sig: "recover-c-from-a-given-vertex", code: "SAAT-M-ALG.27", ses: 13, lvl: 3,
  stem: "The function below has a minimum value of −5. What is c?",
  stemEq: "c_recc",
  opts: ["11", "21", "−5", "3"], ans: 0,
  trick: "the minimum sits at x = −b ÷ 2a, so substitute x = −4 and let the equation find c — guessing from the constant term never works",
  why: "At x = −4 the value is 16 − 32 + c = c − 16, and c − 16 = −5 gives c = 11.",
  traps: ["B: the minimum added instead of subtracted.",
          "C: the minimum value copied as c.",
          "D: b used where b² ÷ 4a was needed."] },

// =================== SESSION 14 — The discriminant & nature of roots =======
{ sig: "discriminant-nature-of-roots", code: "SAAT-M-ALG.28", ses: 14, lvl: 1,
  stem: "What is the nature of the roots of the equation below?",
  stemEq: "c_disc",
  opts: ["One repeated real root",
         "Two conjugate complex roots",
         "No roots of any kind",
         "Two different real roots"], ans: 1,
  trick: "compute the discriminant and stop — 9 − 40 is negative, and a negative discriminant is a COMPLEX pair, not an absence of roots",
  why: "b² − 4ac = 9 − 40 = −31, which is negative.",
  traps: ["A: the discriminant read as zero.",
          "C: complex roots are still roots — every quadratic has two.",
          "D: the sign of the discriminant read as positive."] },

{ sig: "rational-or-irrational-roots", code: "SAAT-M-ALG.28", ses: 14, lvl: 2,
  stem: "The equation below has two real roots. Are they rational or irrational?",
  stemEq: "c_disc2",
  opts: ["Two complex roots", "Two rational roots", "Two irrational roots", "One repeated rational root"], ans: 2,
  trick: "a positive discriminant makes the roots REAL; only a PERFECT SQUARE discriminant makes them rational, and 20 is not one",
  why: "b² − 4ac = 36 − 16 = 20, which is positive but not a perfect square.",
  traps: ["A: the sign of the discriminant mistaken.",
          "B: a positive discriminant assumed to mean rational.",
          "D: the discriminant read as zero."] },

{ sig: "parameter-for-equal-roots", code: "SAAT-M-ALG.28", ses: 14, lvl: 2,
  stem: "For which value of k does the equation below have one repeated root?",
  stemEq: "c_eqr",
  opts: [{ eq: "c_eqr1" }, { eq: "c_eqr2" }, { eq: "c_eqr3" }, { eq: "c_eqr4" }], ans: 3,
  trick: "k² = 36 has TWO solutions — a squared unknown always does, and the negative one is a real answer here",
  why: "Equal roots need k² − 36 = 0, so k = 6 or k = −6.",
  traps: ["A: the square root of 36 taken as 3.",
          "B: 9 used in place of 36.",
          "C: only the positive root given."] },

{ sig: "graph-from-the-discriminant", code: "SAAT-M-ALG.28", ses: 14, lvl: 2,
  stem: "A parabola has a discriminant equal to zero. What does its graph do?",
  opts: ["It touches the x-axis at one point",
         "It never meets the x-axis",
         "It crosses the y-axis at two points",
         "It crosses the x-axis at two points"], ans: 0,
  trick: "a discriminant of zero is a REPEATED root — one point of contact, where the curve turns on the axis rather than crossing it",
  why: "One repeated real root means the vertex sits on the x-axis.",
  traps: ["B: a negative discriminant.",
          "C: no function crosses the y-axis twice.",
          "D: a positive discriminant."] },

// ==================== SESSION 15 — Quadratic functions & their graphs =====
{ sig: "axis-of-symmetry-from-standard-form", code: "SAAT-M-ALG.29", ses: 15, lvl: 2,
  stem: "What is the axis of symmetry of the parabola below?",
  stemEq: "c_axis",
  opts: [{ eq: "c_axis2" }, { eq: "c_axis3" }, { eq: "c_axis4" }, { eq: "c_axis1" }], ans: 1,
  trick: "the axis is a VERTICAL line, so its equation starts x = — an answer beginning y = is wrong before the arithmetic is checked",
  why: "x = −b ÷ 2a = 4 ÷ 2 = 2.",
  traps: ["A: b used without dividing by 2a.",
          "C: the correct value written as a horizontal line.",
          "D: the sign of −b lost."] },

{ sig: "maximum-value-of-a-quadratic", code: "SAAT-M-ALG.29", ses: 15, lvl: 2,
  stem: "What is the maximum value of the function below?",
  stemEq: "c_max",
  opts: ["9", "3", "4", "5"], ans: 2,
  trick: "the maximum is the y-value at the vertex, not the x-value — finding x = 3 is half the work, and 3 is one of the options",
  why: "x = −6 ÷ (−2) = 3, and y = −9 + 18 − 5 = 4.",
  traps: ["A: b² ÷ 4 computed and offered as the maximum.",
          "B: the x-coordinate of the vertex given.",
          "D: the constant term given with its sign changed."] },

{ sig: "number-of-real-zeros-from-the-vertex", code: "SAAT-M-ALG.29", ses: 15, lvl: 1,
  stem: "A parabola has its vertex at (2, 5) and opens downwards. How many real zeros does it have?",
  opts: ["3", "0", "1", "2"], ans: 3,
  trick: "a vertex ABOVE the axis opening DOWNWARDS must come back down through the axis on both sides — sketch the two facts before counting",
  why: "The curve starts at y = 5 and falls without limit on both sides, so it crosses the x-axis twice.",
  traps: ["A: a quadratic can never have three real zeros.",
          "B: the direction of opening ignored.",
          "C: the vertex counted as the only point of contact."] },

{ sig: "equation-from-x-intercepts", code: "SAAT-M-ALG.29", ses: 15, lvl: 2,
  stem: "Which equation has x-intercepts at −3 and 1?",
  opts: [{ eq: "c_int1" }, { eq: "c_int2" }, { eq: "c_int3" }, { eq: "c_int4" }], ans: 0,
  trick: "an intercept of −3 comes from the factor (x + 3) — the sign in the bracket is always the opposite of the intercept",
  why: "(x + 3)(x − 1) = x² + 2x − 3.",
  traps: ["B: both signs in the brackets copied from the intercepts.",
          "C: the constant given the wrong sign.",
          "D: both intercepts taken as positive, giving (x − 3)(x − 1)."] },

// ========================= SESSION 16 — Polynomial equations ==============
{ sig: "synthetic-division-quotient", code: "SAAT-M-ALG.30", ses: 16, lvl: 2,
  stem: "What is the quotient when the polynomial below is divided by x − 2?",
  stemEq: "c_syn",
  opts: [{ eq: "c_syn1" }, { eq: "c_syn2" }, { eq: "c_syn3" }, { eq: "c_syn4" }], ans: 1,
  trick: "synthetic division uses +2, not −2 — the divisor is x − r and the number carried down is r",
  why: "The quotient is x² − 2x + 1, and (x − 2)(x² − 2x + 1) returns the original polynomial.",
  traps: ["A: −2 used in the division instead of +2.",
          "C: the sign of the constant term lost.",
          "D: the sign of the middle term lost."] },

{ sig: "remainder-theorem-value", code: "SAAT-M-ALG.30", ses: 16, lvl: 1,
  stem: "What is the remainder when the polynomial below is divided by x − 2?",
  stemEq: "c_rem",
  opts: ["−5", "8", "11", "21"], ans: 2,
  trick: "substitute, do not divide — the remainder is f(2), and long division here is four times the work for the same mark",
  why: "f(2) = 8 + 8 − 5 = 11.",
  traps: ["A: the constant term read off as the remainder.",
          "B: only the x³ term evaluated.",
          "D: the constant added instead of subtracted."] },

{ sig: "factor-theorem-decide", code: "SAAT-M-ALG.30", ses: 16, lvl: 2,
  stem: "Which expression below is a factor of the polynomial shown?",
  stemEq: "c_fct",
  opts: [{ eq: "c_fct4" }, { eq: "c_fct1" }, { eq: "c_fct2" }, { eq: "c_fct3" }], ans: 3,
  trick: "test the ROOT, not the bracket — x − 2 is a factor when f(2) = 0, and the sign flips when you substitute",
  why: "f(2) = 8 − 16 + 2 + 6 = 0, so x − 2 is a factor.",
  traps: ["A: f(6) = 84, not zero.", "B: f(4) = 10, not zero.", "C: f(−2) = −20, not zero."] },

{ sig: "parameter-from-a-stated-remainder", code: "SAAT-M-ALG.30", ses: 16, lvl: 3,
  stem: "When the polynomial below is divided by x − 2 the remainder is 1. What is k?",
  stemEq: "c_par",
  opts: ["−5", "−1", "1", "5"], ans: 0,
  trick: "set f(2) equal to the REMAINDER, not to zero — this is the factor theorem with a number on the right instead of a zero",
  why: "f(2) = 8 + 2k + 3 = 1, so 2k = −10 and k = −5.",
  traps: ["B: 2k = −2 solved from a mis-added constant.",
          "C: the sign lost at the last step.",
          "D: f(2) set equal to zero instead of to 1."] },

{ sig: "conjugate-root-pair", code: "SAAT-M-ALG.30", ses: 16, lvl: 2,
  stem: "A polynomial with real coefficients has 3 − i as a root. Which number must also be a root?",
  opts: [{ eq: "c_cnj1" }, { eq: "c_cnj2" }, { eq: "c_cnj3" }, { eq: "c_cnj4" }], ans: 1,
  trick: "only the IMAGINARY part changes sign — the real part stays exactly as it is",
  why: "Complex roots of a real polynomial come in conjugate pairs, so 3 + i is also a root.",
  traps: ["A: both parts negated.",
          "C: the real part negated as well.",
          "D: the real and imaginary parts exchanged."] },

{ sig: "real-zeros-from-a-table", code: "SAAT-M-ALG.30", ses: 16, lvl: 2,
  stem: "A polynomial takes the values in the table below. How many real zeros does it have between x = −2 and x = 2?",
  table: [["x", "−2", "−1", "0", "1", "2"],
          ["f(x)", "−7", "2", "5", "−1", "4"]],
  opts: ["1", "2", "3", "4"], ans: 2,
  trick: "count the SIGN CHANGES, not the values — 2 to 5 is a rise with no crossing, and it is the pair that tempts a fourth count",
  why: "The signs run −, +, +, −, +, so the sign changes three times.",
  traps: ["A: only the first crossing counted.",
          "B: the change between x = 1 and x = 2 missed.",
          "D: the rise from 2 to 5 counted as a crossing."] },

// ============================= SESSION 17 — Rational equations ============
{ sig: "rational-equation-with-a-rejected-root", code: "SAAT-M-ALG.31", ses: 17, lvl: 3,
  stem: "Solve the equation below.",
  stemEq: "c_rateq",
  opts: ["x = 0", "x = 3", "x = −3", "No solution"], ans: 3,
  trick: "the algebra produces x = 3 and the denominator FORBIDS x = 3 — the equation therefore has no solution at all",
  why: "Multiplying by x − 3 gives x = 3 + 2(x − 3), so x = 3; but x = 3 makes both denominators zero.",
  traps: ["A: the equation solved as though the denominators were 1.",
          "B: the algebraic answer given without testing it.",
          "C: the sign of the rejected root reversed."] },

{ sig: "solve-a-proportion", code: "SAAT-M-ALG.31", ses: 17, lvl: 1,
  stem: "Solve the proportion below.",
  stemEq: "c_prop",
  opts: ["8", "16", "2", "4"], ans: 0,
  trick: "cross-multiply once and the denominators are gone — multiplying only one side by its own denominator is what produces the small answers",
  why: "8(x + 2) = 4(3x − 4) gives 8x + 16 = 12x − 16, so 4x = 32 and x = 8.",
  traps: ["B: 16 + 16 taken as the answer without dividing.",
          "C: only the numerators equated.",
          "D: 4x = 16 solved from a dropped constant."] },

{ sig: "identify-the-type-of-variation", code: "SAAT-M-ALG.31", ses: 17, lvl: 2,
  stem: "In the table below, how do x and y vary?",
  table: [["x", "2", "4", "6"], ["y", "12", "6", "4"]],
  opts: ["Directly", "Inversely", "Jointly", "They do not vary at all"], ans: 1,
  trick: "test the PRODUCT and the QUOTIENT — here xy is 24 every time, which is inverse variation; direct variation would keep y ÷ x constant",
  why: "2 × 12 = 4 × 6 = 6 × 4 = 24, so xy is constant.",
  traps: ["A: y ÷ x is not constant — it falls from 6 to 0.67.",
          "C: joint variation needs a third variable.",
          "D: y changes as x changes, so there is a relationship."] },

{ sig: "joint-variation-find-value", code: "SAAT-M-ALG.31", ses: 17, lvl: 3,
  stem: "z varies jointly with x and y, and z = 60 when x = 3 and y = 4. What is z when x = 2 and y = 7?",
  opts: ["140", "35", "70", "105"], ans: 2,
  trick: "find the constant FIRST — joint variation multiplies both variables, so k = z ÷ (xy) and everything follows from it",
  why: "k = 60 ÷ 12 = 5, so z = 5 × 2 × 7 = 70.",
  traps: ["A: the new values multiplied by the old z and halved.",
          "B: k taken as 2.5 from dividing by x alone.",
          "D: k taken as 7.5 from dividing by y alone."] },

// ============================== SESSION 18 — Radical equations ============
{ sig: "solve-a-radical-equation", code: "SAAT-M-ALG.32", ses: 18, lvl: 2,
  stem: "Solve the equation below.",
  stemEq: "c_rad1",
  opts: ["21", "29", "5", "7"], ans: 3,
  trick: "square the WHOLE of each side — the 5 becomes 25, not 10, and that single step decides the question",
  why: "3x + 4 = 25, so 3x = 21 and x = 7.",
  traps: ["A: 3x = 21 left undivided.",
          "B: 25 + 4 computed instead of 25 − 4.",
          "C: the right-hand side copied out as the answer."] },

{ sig: "radical-on-each-side", code: "SAAT-M-ALG.32", ses: 18, lvl: 2,
  stem: "Solve the equation below.",
  stemEq: "c_rad2",
  opts: ["6", "8", "12", "4"], ans: 0,
  trick: "with a radical on each side, one squaring clears BOTH — no conjugate and no second squaring is needed",
  why: "2x − 1 = x + 5, so x = 6, and both sides then equal √11.",
  traps: ["B: 2x = x + 5 solved with the −1 dropped.",
          "C: the two constants multiplied.",
          "D: the constants added instead of subtracted."] },

{ sig: "extraneous-root", code: "SAAT-M-ALG.32", ses: 18, lvl: 3,
  stem: "Solve the equation below.",
  stemEq: "c_rad3",
  opts: ["x = 2", "x = 9", "x = 2 or x = 9", "No solution"], ans: 1,
  trick: "squaring produces two candidates and the ORIGINAL equation keeps only one — a root is not an answer until it has been tested",
  why: "Squaring gives x² − 11x + 18 = 0, so x = 2 or x = 9; at x = 2 the right side is −3 and a square root is never negative, so only x = 9 holds.",
  traps: ["A: the rejected candidate chosen.",
          "C: both candidates kept without testing.",
          "D: both rejected, as though squaring had failed."] },

{ sig: "radical-inequality-domain", code: "SAAT-M-ALG.32", ses: 18, lvl: 3,
  stem: "Solve the inequality below.",
  stemEq: "c_rad4",
  opts: [{ eq: "c_rad4o3" }, { eq: "c_rad4o4" }, { eq: "c_rad4o1" }, { eq: "c_rad4o2" }], ans: 2,
  trick: "a radical inequality has TWO conditions — the squared inequality and the radicand being non-negative — and the lower end is included",
  why: "x − 3 < 16 gives x < 19, and x − 3 ≥ 0 gives x ≥ 3, so 3 ≤ x < 19.",
  traps: ["A: only the domain given.",
          "B: the lower end excluded, though x = 3 gives 0 < 4, which is true.",
          "D: the domain condition forgotten."] },

];
