// ---------------------------------------------------------------------------
// SAAT + SAT + GAT combined worksheet — GRADE 11, WEEK 6.
// Anchor: Topic 6, Lessons 6-3/6-4 Logarithms and Logarithmic Functions.
//
// Format matches the real, already-delivered SAAT_SAT_GAT_Gr11_W5_Paper.pdf
// exactly (fetched and read from Google Drive, id 1UXPBcIPsCQpCDsox0MzMiMFbY3RkhAyc):
// 18 items, 25 minutes, three six-item sections (SAAT Tahsili-style / SAT
// context-style / GAT Qudurat-style), a single ★ flags a multi-step item,
// bare paper (no cover, no EXAM CONDITIONS box — conditions live in each
// section band's own note), same footer and header wording.
// ---------------------------------------------------------------------------
const { buildSet } = require("../../engines/exam_engine");

const cfg = {
  mathIndex: "math_g11w6/_index.json",
  examName: "SAAT, SAT and GAT worksheet",
  targets: { "SAAT-M-11": "~33%", "SAT-ADV": "~33%", "GAT-Q-ALG": "~11%",
             "GAT-Q-ARI": "~11%", "GAT-Q-GEO": "~5.5%", "GAT-Q-LOG": "~5.5%" },
  dense: true, itemGap: 40, bare: true, optScale: 1,
  weekLine: "Grade 11 · Week 6 · Semester 1, 2026–27",
  headerLine: "Grade 11 · SAAT, SAT and GAT · anchor: Algebra II Topic 6 (Logarithms and Logarithmic Functions) · 18 items · 25 minutes",
  paperTitle: "SAAT · SAT · GAT — Grade 11 Worksheet",
  paperSub: "18 questions · three exam styles · logarithms and logarithmic functions, now that the class has reached them · 25 minutes",
  keyTitle: "Grade 11 Week 6 — Answer Key and Error Analysis",
  keySub: "For Mr Malek Thiab. 25 minutes total. The pH and decibel items are where the log-of-a-ratio idea is really being tested.",
  outPaper: "SAATSATGAT_Gr11_W6_Paper.docx",
  outKey: "SAATSATGAT_Gr11_W6_Key.docx",
  budgetNote: "18 items — 6 SAAT, 6 SAT, 6 GAT. Section weights are fixed by the paper's own format; the GAT sub-strand split follows this week's mix of algebra, arithmetic, geometry and logic-style reasoning items.",
  sourceNote: "Every item was written for this worksheet, against the ETEC / Qiyas framework in the GAT and SAAT Classification Map and the College Board's published SAT domain descriptions. No leaked or circulated exam questions are used.",
  followUp: [
    ["16 or more", "Secure across all three styles. Move to full timed sections; the ceiling from here is pace."],
    ["12 to 15", "The direct SAAT items are solid. Re-mark counting only the SAT context items — reading the ratio out of a word problem is the reliable gap."],
    ["8 to 11", "Expected this early in Topic 6. Re-run Section 1 alone before adding the contexts back."],
    ["Below 8", "Fix one idea first: a logarithm is an exponent. Rewrite every item in exponential form before choosing an option."],
    ["Whole class", "Any item where more than half the class chose the same wrong option is a teaching point — the key's reasoning column says what to put on the board."],
  ],
  items: [
    // ================================================ SECTION 1 — SAAT
    { code: "SAAT-M-11.1", lvl: 2,
      sec: { title: "SECTION 1 — SAAT (Tahsili) style", note: "6 questions · no calculator · curriculum language, asked directly" },
      stem: "Evaluate.", stemEq: "g6_log1",
      opts: ["4", "5", "6", "16"], ans: 1,
      why: "log₂32 asks which power of 2 gives 32: 2⁵ = 32, so the value is 5.",
      traps: ["A: 2⁴ = 16 read off instead.", "C: the exponent overshot by one.", "D: the argument itself given as the answer."] },
    { code: "SAAT-M-11.1", lvl: 2,
      stem: "Solve for x.", stemEq: "g6_log2",
      opts: ["12", "48", "64", "81"], ans: 2,
      why: "log₄x = 3 means x = 4³ = 64.",
      traps: ["A: 4 × 3 computed instead of 4³.", "B: 4³ found but then multiplied by ¾.", "D: the base and exponent swapped — 3⁴ instead of 4³."] },
    { code: "SAAT-M-11.1", lvl: 2,
      stem: "Simplify.", stemEq: "g6_log3",
      opts: ["2", "3", "7", "8"], ans: 1,
      why: "The quotient rule gives log₂40 − log₂5 = log₂(40/5) = log₂8 = 3.",
      traps: ["A: one step of the division taken twice.", "C: the arguments subtracted (40 − 5 = 35) and misread.", "D: the simplified argument, 8, given instead of the logarithm of it."] },
    { code: "SAAT-M-11.1", lvl: 2,
      stem: "For the logarithmic function f(x) = log₂(x − 3) + 1, what is the equation of its vertical asymptote?",
      opts: ["x = −3", "x = 1", "x = 3", "x = 0"], ans: 2,
      why: "A log function is undefined where its argument is zero or negative. Here x − 3 = 0 at x = 3, which is the vertical asymptote.",
      traps: ["A: the sign of the horizontal shift reversed.", "B: the vertical shift +1 mistaken for the asymptote.", "D: the parent function's asymptote given, ignoring the shift."] },
    { code: "SAAT-M-11.1", lvl: 2,
      stem: "Which exponential equation is equivalent to log₄64 = 3 ?",
      opts: ["4³ = 64", "3⁴ = 64", "64³ = 4", "4⁶⁴ = 3"], ans: 0,
      why: "log_b(a) = c means bᶜ = a — the base stays the base and the log value becomes the exponent.",
      traps: ["B: the base and exponent swapped.", "C: the argument and base swapped.", "D: the log value written as the base's own exponent on the wrong side."] },
    { code: "SAAT-M-11.1", lvl: 2,
      stem: "Solve for x.", stemEq: "g6_log4",
      opts: ["6", "12", "14", "16"], ans: 2,
      why: "log₂(x + 2) = 4 means x + 2 = 2⁴ = 16, so x = 14.",
      traps: ["A: a rounding of a wrong rearrangement.", "B: 16 halved instead of having 2 subtracted.", "D: the −2 forgotten, giving 2⁴ itself."] },

    // ================================================ SECTION 2 — SAT
    { code: "SAT-ADV.4", lvl: 2,
      sec: { title: "SECTION 2 — SAT style", note: "6 questions · calculator allowed · context, units and longer stems" },
      stem: "A geologist models an earthquake's magnitude using M = log(I / I₀), where I₀ is a reference intensity and log is base 10. If an earthquake's intensity is 4,000 times the reference intensity, which of the following is closest to its magnitude?",
      opts: ["3.4", "3.6", "3.9", "4.0"], ans: 1,
      why: "M = log(4000) = log(4) + 3 ≈ 0.60 + 3 = 3.6.",
      traps: ["A: a rounding of a wrong intermediate value.", "C: the extra 0.3 added rather than the correct log(4).", "D: log(4000) rounded up to the nearest whole magnitude."] },
    { code: "SAT-ADV.4", lvl: 2,
      stem: "A sound's loudness in decibels is given by β = 10 log(I / I₀), where log is base 10. A vacuum cleaner produces a sound with intensity 10¹⁰ times the threshold intensity I₀. What is its loudness, in decibels?",
      opts: ["80", "90", "100", "110"], ans: 2,
      why: "log(10¹⁰) = 10, and 10 × 10 = 100 dB.",
      traps: ["A: the exponent taken as 8 instead of 10.", "B: the exponent taken as 9 instead of 10.", "D: the exponent read as 11."] },
    { code: "SAT-ADV.4", lvl: 3,
      stem: "The pH of a solution is given by pH = −log[H⁺], where [H⁺] is the hydrogen-ion concentration in moles per litre and log is base 10. A sample of seawater has pH 8.2. Which of the following is closest to its hydrogen-ion concentration, in moles per litre?",
      opts: ["6.3 × 10⁻⁹", "8.2 × 10⁻⁹", "1.6 × 10⁻⁸", "6.3 × 10⁻⁸"], ans: 0,
      why: "[H⁺] = 10⁻⁸·² = 10⁻⁹ × 10⁰·⁸ ≈ 10⁻⁹ × 6.3 = 6.3 × 10⁻⁹.",
      traps: ["B: the pH digits used directly as the coefficient.", "C: the exponent split in half instead of separated into a whole part and a decimal part.", "D: the power of ten off by a factor of 10."] },
    { code: "SAT-ADV.4", lvl: 3,
      stem: "Using the model M = log(I / I₀) from the earthquake question above, how many times more intense is a magnitude-7.0 earthquake than a magnitude-5.0 earthquake?",
      opts: ["20", "100", "200", "1,000"], ans: 1,
      why: "The magnitudes differ by 2, so the intensity ratio is 10² = 100 — a logarithm turns a DIFFERENCE in magnitude into a RATIO of intensity.",
      traps: ["A: the difference in magnitude used directly as the ratio.", "C: the ratio doubled by mistake.", "D: one magnitude too many applied."] },
    { code: "SAT-ADV.4", lvl: 3,
      stem: "Using the decibel model β = 10 log(I / I₀) from the sound question above, a rock concert measures 120 dB and normal conversation measures 60 dB. How many times more intense is the concert's sound than the conversation's?",
      opts: ["2", "60", "1,000", "1,000,000"], ans: 3,
      why: "120 dB gives I/I₀ = 10¹², and 60 dB gives I/I₀ = 10⁶, so the concert is 10¹²/10⁶ = 10⁶ = 1,000,000 times as intense.",
      traps: ["A: the decibel values simply divided.", "B: the difference in decibels given as the answer, mistaking dB for a ratio.", "C: only half the required power of ten applied."] },
    { code: "SAT-ADV.4", lvl: 3,
      stem: "A different sample of rainwater has hydrogen-ion concentration 2.5 × 10⁻⁶ moles per litre. Using the pH model from the acidity question above, which of the following is closest to its pH?",
      opts: ["5.4", "5.6", "5.8", "6.0"], ans: 1,
      why: "pH = −log(2.5 × 10⁻⁶) = −(log 2.5 − 6) = 6 − 0.4 = 5.6.",
      traps: ["A: log(2.5) rounded the wrong way.", "C: the decimal part of the log added instead of subtracted.", "D: the pH read as the whole-number exponent alone."] },

    // ================================================ SECTION 3 — GAT
    { code: "GAT-Q-ALG.4", lvl: 3,
      sec: { newPage: true, title: "SECTION 3 — GAT (Qudurat) style", note: "6 questions · no calculator · about one minute each · the trap is the point" },
      stem: "If", stemEq: "g6_log5", note: "what is the value of x² ?",
      opts: ["9", "16", "36", "64"], ans: 3,
      why: "log₂x = 3 means x = 2³ = 8, so x² = 64.",
      traps: ["A: 3² computed instead of x².", "B: the exponent itself squared.", "C: x taken as 6 by a wrong reading of the equation."] },
    { code: "GAT-Q-ARI.4", lvl: 3,
      stem: "Which quantity is greater?", stemEq: "g6_cmp", k: 1.05,
      opts: ["A is greater", "B is greater", "they are equal", "not enough information"], ans: 2,
      why: "Rewrite B with the same base: log₄(1,000,000) = log₄(10⁶) = 6·log₄(10) = 3·log₂(10) (since log₄10 = ½log₂10), which is exactly log₂(1000) = 3·log₂(10). The two quantities are equal.",
      traps: ["A: the bigger-looking number (1,000,000) assumed to win without matching bases.", "B: the same assumption in the other direction.", "D: the values wrongly treated as impossible to compare without a calculator."] },
    { code: "GAT-Q-ALG.3", lvl: 2,
      stem: "Which is equal to the expression below?", stemEq: "g6_logexpand",
      opts: [{ eq: "g6_opt_a" }, { eq: "g6_opt_b" }, { eq: "g6_opt_c" }, { eq: "g6_opt_d" }], ans: 0,
      why: "The product rule splits the multiplication, then the power rule brings the exponent down: log(x²y) = log(x²) + log(y) = 2log x + log y.",
      traps: ["B: the power rule applied to the wrong factor.", "C: the product rule confused with multiplying the logs themselves.", "D: addition replaced by multiplication."] },
    { code: "GAT-Q-GEO.2", lvl: 2,
      stem: "A ladder 17 m long leans against a wall, with its foot 8 m from the base of the wall. How high up the wall does the ladder reach, in metres?",
      opts: ["9", "12", "15", "16"], ans: 2,
      why: "17² − 8² = 289 − 64 = 225 = 15², so the ladder reaches 15 m up the wall.",
      traps: ["A: 17 − 8 taken directly.", "B: an average of the two given lengths.", "D: 17² − 8² miscalculated as 256."] },
    { code: "GAT-Q-LOG.3", lvl: 3,
      stem: "In a survey of 50 people, 30 like tea and 25 like coffee, and 12 like both. How many like NEITHER?",
      opts: ["5", "7", "10", "12"], ans: 1,
      why: "At least one: 30 + 25 − 12 = 43. Neither: 50 − 43 = 7.",
      traps: ["A: the overlap subtracted twice.", "C: the overlap ignored, giving 50 − (30 + 25) and then adjusted incorrectly.", "D: the 'both' figure copied back as the answer."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "A price increases by 20% and later decreases by 20%. What is the overall percent change from the original price?",
      opts: ["no change", "a 4% fall", "a 4% rise", "a 20% fall"], ans: 1,
      why: "1.20 × 0.80 = 0.96, a net fall of 4%. The decrease is taken from the RAISED price, which is larger than the original, so the two percentages do not cancel.",
      traps: ["A: the two percentages assumed to cancel exactly.", "C: the direction of the net change reversed.", "D: the percentages simply subtracted."] },
  ],
};

buildSet(cfg);
console.log("built", cfg.outPaper, "and", cfg.outKey);
