// ---------------------------------------------------------------------------
// SAT + GAT combined worksheet — GRADE 11, WEEK 3.
// Anchor: 5-5 Function Operations and Composition, 5-6 Inverse Functions.
// Revisit: radical equations and domains from Week 2, so the extraneous-root
// idea does not go cold one week after it was taught.
// Seed: exponential and logarithmic thinking, systems, statistics — SAT content
// the syllabus has not reached.  Four full pages, no preamble.  See spec §18.
// ---------------------------------------------------------------------------
const { buildSet } = require("./exam_engine");

const TRICKS = [
  // ---- SAT, in item order (verified against the item list)
  "composition works from the INSIDE out — g first, then f",
  "f(g(x)) and g(f(x)) are different questions; read which is asked",
  "to invert, swap x and y and then solve for y",
  "f⁻¹(k) asks which INPUT gives k — solve, do not build the whole inverse",
  "a quotient of functions loses every x that makes the denominator zero",
  "√(x²) is |x|, not x — the square root of a square keeps the sign positive",
  "a product of functions multiplies outputs, not inputs",
  "if f and g undo each other BOTH ways, they are inverses — test both orders",
  "a function has an inverse only if no output repeats",
  "reflecting in y = x turns a graph into its inverse",
  "substitute the whole inner expression, brackets and all",
  "cross-multiply to clear both fractions in one step",
  "take the joining fee off BEFORE dividing by the monthly rate",
  "a percentage change always divides by the STARTING value",
  "compound growth multiplies by (1 + r) once per period; simple interest adds",
  "the median ignores how extreme an outlier is; the mean does not",
  "lengths scale by k, areas by k squared, volumes by k cubed",
  "name the sides relative to the angle BEFORE choosing a ratio",
  "a cylinder is the circle's area times the height — square the radius, not the diameter",
  // ---- GAT, in item order
  "a percentage of a percentage multiplies, it does not add",
  "work back to the WHOLE before taking a new percentage of it",
  "successive discounts multiply what is LEFT; they never add",
  "make the bases match before comparing powers",
  "units digits run in a cycle of four — divide the exponent by 4",
  "when the differences are not constant, take the differences of the differences",
  "(a + b)² = a² + 2ab + b², so a² + b² is one subtraction away",
  "the product of the roots is c/a; no factorising needed",
  "an absolute value opens into TWO equations",
  "angles on a straight line add to 180° — collect and solve once",
  "the angle at the centre is twice the angle at the circumference",
  "shaded = whole minus the pieces removed; leave π alone",
  "similar figures scale by a RATIO, never by a difference",
  "a border takes its width off BOTH ends of every dimension",
  "a weighted mean is not the mean of the means",
  "in a two-way table the denominator is the row the question names",
  "'at least one' is 1 minus the probability of none",
  "average speed over equal distances is not the average of the speeds",
  "add the RATES, never the times",
  "convert to the same unit BEFORE comparing",
  "consecutive numbers cluster round their mean",
  "work with the remainder alone — the number itself never matters",
  "neither = total − (A + B − both); the overlap comes off once",
];

const cfg = {
  mathIndex: "math_sg/_index.json",
  figIndex: "figs_sg/_index.json",
  examName: "SAT and GAT worksheet",
  targets: { "SAT-ALG": "~17.5%", "SAT-ADV": "~17.5%", "SAT-PSD": "~7.5%",
             "SAT-GEO": "~7.5%", "GAT-Q-ARI": "~18%", "GAT-Q-ALG": "~9%",
             "GAT-Q-GEO": "~9%", "GAT-Q-DAT": "~9%", "GAT-Q-LOG": "~5%" },
  dense: true, itemGap: 40, bare: true, optScale: 1,
  weekLine: "Week 3 · Semester 1, 2026–27",
  headerLine: "Grade 11 · Week 3 · SAT (pages 1–2) and GAT Qudurat (pages 3–4) · aligned to 5-5 Operations on Functions and 5-6 Inverse Functions",
  paperTitle: "SAT and GAT Worksheet — Grade 11, Week 3",
  paperSub: "44 questions · Section 1 SAT (calculator) · Section 2 GAT (no calculator)",
  keyTitle: "Grade 11 Week 3 — Answer Key and Error Analysis",
  keySub: "For Mr Malek Thiab. 50 minutes total: 25 on each section. The composition items are where order of operations is really being tested.",
  outPaper: "SATGAT_Gr11_W3_Paper.docx",
  outKey: "SATGAT_Gr11_W3_Key.docx",
  timing: "50 minutes",
  calculator: "Section 1 yes · Section 2 no",
  marking: "One mark each, no penalty for a wrong answer",
  budgetNote: "44 items — 21 SAT and 23 GAT. Targets are the published weights HALVED, because each exam is half this paper.",
  sourceNote: "Every item was written for this worksheet. The SAT half follows the College Board's published domain weights for the digital SAT; the GAT half follows the ETEC / Qiyas framework in the GAT and SAAT Classification Map. No leaked or circulated exam questions are used.",
  followUp: [
    ["33 or more", "Secure at this level. Move to full timed sections; the ceiling is pace."],
    ["25 to 32", "Composition one way round is solid. Re-mark counting only the items that asked for the OTHER order — that is the reliable gap."],
    ["17 to 24", "Expected at this point in Topic 5. Re-run the SAT half alone before adding anything new."],
    ["Below 17", "Fix one idea first: work from the inside out. Everything in composition and inverses follows from that."],
    ["Whole class", "Any item where more than half the class chose the same wrong option is a teaching point — the trick column says what to put on the board."],
  ],
  items: [
    // ================================================ SECTION 1 — SAT
    { code: "SAT-ADV.1", lvl: 2,
      sec: { title: "SECTION 1 — SAT", note: "21 questions · calculator allowed · 25 minutes" },
      stem: "For the functions below, what is f(g(2)) ?", stemEq: "d_fg",
      opts: ["1", "3", "5", "9"], ans: 1,
      why: "Inside out: g(2) = 4 − 3 = 1, then f(1) = 2(1) + 1 = 3.",
      traps: ["A: g(2) given as the final answer.", "C: f(2) computed instead.", "D: f then g, the wrong order."] },
    { code: "SAT-ADV.2", lvl: 3, stem: "For the same functions, what is g(f(2)) ?", stemEq: "d_fg",
      opts: ["3", "13", "22", "25"], ans: 2,
      why: "f(2) = 5, then g(5) = 25 − 3 = 22. Reversing the order gives a different answer — which is the point of the item.",
      traps: ["A: f(g(2)), the previous question's answer.", "B: 16 − 3, from squaring the wrong value.", "D: the −3 forgotten."] },
    { code: "SAT-ADV.3", lvl: 2, stem: "Which is the inverse of f ?", stemEq: "d_inv",
      opts: [{ eq: "d_o_i2" }, { eq: "d_o_i1" }, { eq: "d_o_i3" }, { eq: "d_o_i4" }], ans: 1,
      why: "Swap and solve: x = (3y − 5)/2 gives 2x = 3y − 5, so y = (2x + 5)/3.",
      traps: ["A: the sign of the 5 lost in the rearrangement.", "C: the 2 and 3 swapped.", "D: the whole expression inverted rather than solved."] },
    { code: "SAT-ADV.4", lvl: 3,
      stem: "For the function below, what is f⁻¹(9) ?", stemEq: "s_inv11",
      opts: ["2", "4", "29", "36"], ans: 1,
      why: "f⁻¹(9) asks which input gives 9: 4x − 7 = 9, so x = 4. There is no need to build the whole inverse.",
      traps: ["A: 9 divided by 4 then rounded.", "C: f(9) computed instead.", "D: 4 × 9."] },
    { code: "SAT-ADV.5", lvl: 3, stem: "For the functions below, which value must be excluded from the domain?", stemEq: "d_fg",
      opts: [{ eq: "o_x0" }, { eq: "o_xsq3" }, { eq: "o_x3" }, "none"], ans: 1,
      why: "A quotient loses every x that makes the denominator zero. Here g(x) = x² − 3 is zero at x = ±√3, so those values must go.",
      traps: ["A: zero excluded by habit.", "C: the constant read as the root.", "D: the restriction missed entirely."],
      note: "Consider the quotient of f by g." },
    { code: "SAT-ADV.6", lvl: 3, stem: "For the functions below, what is f(g(x)) ?", stemEq: "d_sqrtc",
      opts: [{ eq: "o_x" }, { eq: "o_absx" }, { eq: "o_x2" }, { eq: "o_xp1" }], ans: 1,
      why: "g(x) = x² + 1, so f(g(x)) = √(x² + 1 − 1) = √(x²) = |x|. The square root of a square is the absolute value, not x.",
      traps: ["A: √(x²) simplified to x, dropping the negative half.", "C: the root ignored.", "D: the inner function returned unchanged."] },
    { code: "SAT-ADV.7", lvl: 2,
      stem: "For the functions below, what is (f · g)(4) ?", stemEq: "s_prod11",
      opts: ["14", "28", "32", "56"], ans: 3,
      why: "A product multiplies outputs: f(4) = 7 and g(4) = 8, so the product is 56.",
      traps: ["A: the outputs added.", "B: g(f(4)), a composition.", "C: f(g(4)) plus a slip."] },
    { code: "SAT-ADV.8", lvl: 3,
      stem: "Which pair of functions are inverses of each other?",
      opts: [{ eq: "o_pair1" }, { eq: "o_pair2" }, { eq: "o_pair3" }, { eq: "o_pair4" }], ans: 0,
      why: "Adding 2 and subtracting 2 undo each other in BOTH orders, which is the definition. The square and the square root only undo each other for x ≥ 0.",
      traps: ["B: doubling and squaring are unrelated.", "C: true only on part of the domain, so not a full inverse pair.", "D: multiplying and adding are different operations."] },
    { code: "SAT-ADV.9", lvl: 3,
      stem: "A function has an inverse that is also a function. Which must be true?",
      opts: ["it passes the vertical line test", "no output is repeated", "it is always increasing", "it passes through the origin"], ans: 1,
      why: "If two inputs shared an output, the inverse would have to send one input to two places and would not be a function. So no output may repeat.",
      traps: ["A: true of every function, so it distinguishes nothing.", "C: sufficient but not necessary — decreasing functions qualify too.", "D: irrelevant to invertibility."] },
    { code: "SAT-ADV.10", lvl: 2,
      stem: "The graph of a function is reflected in the line y = x. What does the result represent?",
      opts: ["the negative of the function", "the inverse of the function", "the function shifted diagonally", "the reciprocal of the function"], ans: 1,
      why: "Reflecting in y = x swaps every x with its y, which is exactly what forming an inverse does.",
      traps: ["A: reflection in the x-axis.", "C: a translation, not a reflection.", "D: the reciprocal is 1/f(x), a different thing entirely."] },
    { code: "SAT-ALG.1", lvl: 3,
      stem: "For the function below, what is f(a + 1) ?", stemEq: "s_lin11",
      opts: [{ eq: "o_5am1" }, { eq: "o_5ap3" }, { eq: "o_5ap5" }, { eq: "o_5am2" }], ans: 1,
      why: "Substitute the whole expression: 5(a + 1) − 2 = 5a + 5 − 2 = 5a + 3. The bracket must be multiplied out in full.",
      traps: ["A: only the a multiplied by 5.", "C: the −2 dropped.", "D: the +1 ignored."] },
    { code: "SAT-ALG.3", lvl: 2,
      stem: "Solve for x.", stemEq: "s_frac11",
      opts: ["−11", "11", "17", "22"], ans: 1,
      why: "Cross-multiply: 3(x + 4) = 5(x − 2), so 3x + 12 = 5x − 10 and 2x = 22, giving x = 11.",
      traps: ["A: the sign lost when collecting.", "C: 12 and 10 added rather than moved.", "D: 2x = 22 not divided."] },
    { code: "SAT-ALG.4", lvl: 3,
      stem: "A gym charges 300 SAR to join plus 120 SAR a month. After how many months does the total reach 1500 SAR?",
      opts: ["8", "10", "12", "15"], ans: 1,
      why: "1500 − 300 = 1200, and 1200 ÷ 120 = 10. Take the joining fee off before dividing.",
      traps: ["A: a rounding of a wrong remainder.", "C: 1500 divided by 120 with the fee ignored.", "D: the fee added instead."] },
    { code: "SAT-PSD.1", lvl: 3,
      stem: "A population grows from 40 000 to 46 000. By what percentage did it grow?",
      opts: ["13%", "15%", "16%", "20%"], ans: 1,
      why: "The rise is 6 000 against a starting value of 40 000, which is 15%.",
      traps: ["A: divided by 46 000.", "C: rounded from the wrong base.", "D: 8 000 assumed as the rise."] },
    { code: "SAT-PSD.2", lvl: 3,
      stem: "A sum of 5 000 SAR is invested at 6% per year, compounded annually. Which expression gives its value after 3 years?",
      opts: [{ eq: "o_ci1" }, { eq: "o_ci2" }, { eq: "o_ci3" }, { eq: "o_ci4" }], ans: 2,
      why: "Compound growth multiplies by 1.06 once for each year: 5000 × 1.06³.",
      traps: ["A: the multiplier applied once and then scaled.", "B: the rate multiplied by 3 — simple interest.", "D: the rate added as a raw number."] },
    { code: "SAT-PSD.3", lvl: 3,
      stem: "The values are 5, 6, 7, 8 and 74. Which statement is true?",
      opts: ["the mean is smaller than the median", "the mean and median are equal", "the mean is larger than the median", "the range equals the mean"], ans: 2,
      why: "The median is 7; the mean is 100/5 = 20. The single extreme value pulls the mean up but leaves the median untouched.",
      traps: ["A: the direction reversed.", "B: the outlier assumed not to matter.", "D: the range is 69, not 20."] },
    { code: "SAT-GEO.1", lvl: 3,
      stem: "Two similar cones have heights in the ratio 3 : 4. What is the ratio of their volumes?",
      opts: ["3 : 4", "9 : 16", "27 : 64", "6 : 8"], ans: 2,
      why: "Volumes scale by the cube of the length ratio: 3³ : 4³ = 27 : 64.",
      traps: ["A: the length ratio reused.", "B: the area ratio.", "D: the ratio simply doubled."] },
    { code: "SAT-GEO.2", lvl: 2,
      stem: "In a right triangle the side adjacent to an angle is 8 and the hypotenuse is 17. What is the cosine of that angle?",
      opts: [{ eq: "f_815" }, { eq: "f_817" }, { eq: "f_1517" }, { eq: "f_178" }], ans: 1,
      why: "Cosine is adjacent over hypotenuse: 8/17.",
      traps: ["A: the tangent.", "C: the sine.", "D: the ratio inverted."] },
    { code: "SAT-GEO.4", lvl: 3,
      stem: "A cylindrical tank has radius 3 m and height 5 m. What is its volume, in cubic metres, to the nearest whole number?",
      opts: ["45", "94", "141", "471"], ans: 2,
      why: "V = πr²h = π × 9 × 5 = 45π ≈ 141.",
      traps: ["A: π omitted.", "B: the radius used once instead of squared.", "D: the diameter squared instead of the radius."] },

    // ================================================ SECTION 2 — GAT
    { code: "GAT-Q-ARI.3", lvl: 3,
      sec: { newPage: true, title: "SECTION 2 — GAT (Qudurat)",
             note: "23 questions · NO calculator · 25 minutes" },
      stem: "What is 40% of 25% of 800 ?",
      opts: ["60", "80", "100", "520"], ans: 1,
      why: "25% of 800 is 200, and 40% of 200 is 80. The percentages multiply to 10%, and 10% of 800 is 80.",
      traps: ["A: 30% of 200.", "C: 12.5% of 800.", "D: the percentages added."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "60% of a number is 150. What is 25% of the same number?",
      opts: ["37.5", "50", "62.5", "75"], ans: 2,
      why: "The number is 150 ÷ 0.6 = 250, and 25% of 250 is 62.5. Return to the whole first.",
      traps: ["A: 25% of 150.", "B: a guess between the values.", "D: 30% of 250."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "A price rises by 25% and the new price is then reduced by 20%. What is the overall change?",
      opts: ["5% decrease", "no change", "5% increase", "45% increase"], ans: 1,
      why: "1.25 × 0.80 = 1.00 exactly, so the price returns to where it began. The fall is taken from the RAISED price, which is why the two cancel.",
      traps: ["A: the percentages subtracted.", "C: the direction guessed from the larger figure.", "D: the percentages added."] },
    { code: "GAT-Q-ARI.4", lvl: 3, stem: "Which quantity is greater?", stemEq: "g_cmp230", k: 1.05,
      opts: ["A is greater", "B is greater", "they are equal", "not enough information"], ans: 1,
      why: "Match the exponents: 2³⁰ = 8¹⁰ and 3²⁰ = 9¹⁰, so B is greater.",
      traps: ["A: the larger exponent assumed to win.", "C: both read as simply enormous.", "D: both are fully determined."] },
    { code: "GAT-Q-ARI.5", lvl: 3, stem: "What is the units digit of the number below?", stemEq: "a_pow",
      opts: ["1", "3", "7", "9"], ans: 1,
      why: "Powers of 3 cycle 3, 9, 7, 1. 17 leaves remainder 1 on division by 4, so the digit is 3.",
      traps: ["A: remainder taken as 0.", "C: remainder taken as 3.", "D: remainder taken as 2."] },
    { code: "GAT-Q-ARI.5", lvl: 3,
      stem: "What is the next term of the sequence 1, 4, 9, 16, 25, … ?",
      opts: ["30", "34", "36", "49"], ans: 2,
      why: "These are the square numbers, so the next is 6² = 36. The differences 3, 5, 7, 9 rise by 2 and confirm it.",
      traps: ["A: the last difference repeated.", "B: the difference taken as 9.", "D: 7² given, one term too far."] },
    { code: "GAT-Q-ALG.4", lvl: 3, stem: "If", stemEq: "a_ident",
      opts: ["19", "29", "39", "49"], ans: 1,
      why: "(a + b)² = a² + 2ab + b², so 49 = a² + b² + 20 and a² + b² = 29.",
      traps: ["A: 10 subtracted once instead of twice.", "C: 10 added rather than 20 subtracted.", "D: the identity ignored."],
      note: "what is the value of a² + b² ?" },
    { code: "GAT-Q-ALG.3", lvl: 3, stem: "What is the product of the roots?", stemEq: "g_quadr",
      opts: ["7", "10", "17", "70"], ans: 1,
      why: "The product of the roots is c/a = 10.",
      traps: ["A: the sum of the roots.", "C: the coefficients added.", "D: sum and product multiplied."] },
    { code: "GAT-Q-ALG.1", lvl: 3,
      stem: "What is the sum of the solutions?", stemEq: "s_abs11b",
      opts: ["2", "4", "5", "8"], ans: 1,
      why: "4x − 8 = 12 gives x = 5, and 4x − 8 = −12 gives x = −1. Their sum is 4.",
      traps: ["A: the negative solution's size only.", "C: only the positive branch taken.", "D: the 8 copied back."] },
    { code: "GAT-Q-GEO.1", lvl: 3,
      stem: "Three angles on a straight line are (2x)°, (x + 30)° and (3x − 30)°. What is the value of x ?",
      opts: ["20", "25", "30", "36"], ans: 2,
      why: "6x = 180, so x = 30. The constants cancel, which is worth noticing before doing any arithmetic.",
      traps: ["A: the constants mishandled.", "B: the angles assumed to total 150°.", "D: the angles assumed to total 216°."] },
    { code: "GAT-Q-GEO.4", lvl: 3,
      stem: "An angle at the centre of a circle measures 110°. What is the angle at the circumference on the same arc?",
      opts: ["35°", "55°", "70°", "220°"], ans: 1,
      why: "The angle at the circumference is half the angle at the centre: 55°.",
      traps: ["A: the angle quartered.", "C: the supplement halved.", "D: the relationship applied backwards."] },
    { code: "GAT-Q-GEO.3", lvl: 3,
      stem: "A circle of radius 5 cm is inscribed in a square. What area of the square lies outside the circle, in cm² ?",
      opts: [{ eq: "g_o_sh1" }, { eq: "g_o_sh2" }, { eq: "g_o_sh3" }, { eq: "g_o_sh4" }], ans: 0,
      why: "The square has side 10 and area 100; the circle has area 25π, leaving 100 − 25π.",
      traps: ["B: the radius used as the side.", "C: the circumference subtracted.", "D: the circle's area given instead."] },
    { code: "GAT-Q-GEO.2", lvl: 3,
      stem: "Two similar triangles have areas 32 cm² and 50 cm². The smaller has a side of 8 cm. What is the corresponding side of the larger, in cm?",
      opts: ["10", "12", "12.5", "15"], ans: 0,
      why: "Areas are in the ratio 32 : 50 = 16 : 25, so lengths are in the ratio 4 : 5. Then 8 × 5/4 = 10.",
      traps: ["B: the difference of the areas used.", "C: the area ratio applied to the length.", "D: the areas divided directly."] },
    { code: "GAT-Q-GEO.3", lvl: 3,
      stem: "A rectangular field 30 m by 18 m has a path 3 m wide around the INSIDE of its edge. What is the area of the path, in m² ?",
      opts: ["252", "264", "276", "288"], ans: 0,
      why: "The width comes off both ends of each dimension, so the inner rectangle is 24 by 12 = 288 m². The path is 540 − 288 = 252 m².",
      traps: ["B: the inner rectangle taken as 27 by 15.", "C: the perimeter multiplied by the width.", "D: the inner area given instead of the path."] },
    { code: "GAT-Q-DAT.5", lvl: 3,
      stem: "In a class, 15 students scored a mean of 76 and 25 students scored a mean of 60. What is the mean for all 40 ?",
      opts: ["64", "66", "68", "70"], ans: 1,
      why: "Totals: 1140 + 1500 = 2640, and 2640/40 = 66.",
      traps: ["A: a guess below the true value.", "C: the mean of 76 and 60.", "D: the larger group under-weighted."] },
    { code: "GAT-Q-DAT.1", lvl: 3,
      stem: "The table shows a survey of 100 people. What percentage of those who read daily also exercise?",
      table: [["", "Exercises", "Does not", "Total"], ["Reads daily", "21", "14", "35"], ["Does not read", "24", "41", "65"], ["Total", "45", "55", "100"]],
      opts: ["21%", "35%", "47%", "60%"], ans: 3,
      why: "Read the 'Reads daily' row only: 21 out of 35, which is 60%. The grand total of 100 is not the denominator, however inviting it looks.",
      traps: ["A: 21 out of 100 — the trap the round total sets.", "B: the row total given as the answer.", "C: 21 out of 45, using the column."] },
    { code: "GAT-Q-DAT.3", lvl: 3,
      stem: "Two fair coins are tossed. What is the probability of at least one tail?",
      opts: [{ eq: "f_14" }, { eq: "f_12" }, { eq: "f_34" }, "1"], ans: 2,
      why: "'At least one' is 1 minus 'none': the chance of no tails is 1/4, so the answer is 3/4.",
      traps: ["A: exactly two tails.", "B: exactly one tail.", "D: the event assumed certain."] },
    { code: "GAT-Q-LOG.1", lvl: 3,
      stem: "A train covers 90 km at 45 km/h and the next 90 km at 90 km/h. What is its average speed for the whole journey, in km/h?",
      opts: ["55", "60", "65", "67.5"], ans: 1,
      why: "Times are 2 and 1 hours for 180 km, so 180/3 = 60 km/h. More time is spent at the slower speed, so the answer falls below the mean of 67.5.",
      traps: ["A: a guess below the true value.", "C: a guess between.", "D: the mean of 45 and 90 — the trap."] },
    { code: "GAT-Q-LOG.2", lvl: 3,
      stem: "One tap fills a tank in 2 hours and another fills it in 3 hours. With both open, how long does it take, in hours?",
      opts: ["1.2", "1.5", "2.5", "5"], ans: 0,
      why: "Add the rates: 1/2 + 1/3 = 5/6 of the tank per hour, so the time is 6/5 = 1.2 hours.",
      traps: ["B: the times averaged.", "C: a guess between the two times.", "D: the times added."] },
    { code: "GAT-Q-ARI.2", lvl: 3,
      stem: "A cyclist travels 18 km in 40 minutes. What is the speed in metres per second?",
      opts: ["6.5", "7.5", "8", "27"], ans: 1,
      why: "18 000 m in 2 400 s gives 7.5 m/s. Convert both quantities before dividing.",
      traps: ["A: a rounding of a wrong conversion.", "C: minutes taken as 2 250 s.", "D: the speed in km/h given unchanged."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "The sum of five consecutive odd integers is 135. What is the smallest?",
      opts: ["23", "25", "27", "29"], ans: 0,
      why: "The five average 27, which is the middle one. Stepping back two odd numbers gives 23.",
      traps: ["B: a step of one taken instead of two.", "C: the middle one.", "D: one step above the middle."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "When n is divided by 9 the remainder is 5. What is the remainder when 4n is divided by 9 ?",
      opts: ["2", "5", "11", "20"], ans: 0,
      why: "Work with the remainder alone: 4 × 5 = 20, and 20 leaves remainder 2 on division by 9.",
      traps: ["B: the original remainder copied.", "C: 20 reduced by 9 only once and mis-stated.", "D: the unreduced value given."] },
    { code: "GAT-Q-LOG.3", lvl: 3,
      stem: "Of 60 students, 38 play tennis, 30 play squash and 8 play neither. How many play both?",
      opts: ["12", "14", "16", "18"], ans: 2,
      why: "52 play at least one, so 38 + 30 − both = 52 and both = 16.",
      traps: ["A: a guess below the value.", "B: the 'neither' figure mishandled.", "D: the difference of the two sports."] },
  ],
};

if (TRICKS.length !== cfg.items.length)
  throw new Error(`${TRICKS.length} tricks for ${cfg.items.length} items`);
cfg.items.forEach((it, i) => { it.trick = TRICKS[i]; });

buildSet(cfg);
console.log("built", cfg.outPaper, "and", cfg.outKey);
