// ---------------------------------------------------------------------------
// SAT + GAT combined worksheet — GRADE 10, WEEK 5.
// Anchor: Algebra II Topic 1, Lesson 6 — Linear Systems (elimination,
// substitution, number of solutions). SAT half (Section 1) is ~60% linear
// systems in Saudi-context word problems, ~40% spiral (quadratic/exponential
// transformations, similar triangles, percentage, unit rate — all seen in
// Weeks 1-4 and kept alive here). GAT half (Section 2) mixes a linear-system
// trap set with the standing GAT spiral (percent, ratio, units digit,
// identities, angles, area, weighted mean, probability, work rate).
//
// Every item's stem is written as plain text (matching this bank's own
// precedent — e.g. Week 4's "F(m) = 2.25m + 8" and the two-line system in
// SAT-ALG.4 are both plain TextRun text, no LaTeX image). No item here needs
// a figure or a typeset display, so mathIndex simply points at an existing,
// already-built index file to satisfy the engine's loader — none of its
// keys are referenced by any item below.
// ---------------------------------------------------------------------------
const { buildSet } = require("./exam_engine");

const TRICKS = [
  // ---- SAT (Section 1)
  "subtract the two equations when one variable's coefficient already matches — one line of work removes it",
  "isolate the flat fee first by subtracting the two equations, then substitute back for the rate",
  "eliminate the variable with the SAME coefficient first, even before touching the third piece of information",
  "no solution means the coefficient ratios match but the constant's ratio does NOT — check all three",
  "solve the system for x first, then substitute to find y — do not average or guess the intersection",
  "in (x − h)² + k, the shift is right h and up k — the parenthesis sign flips only for the horizontal part",
  "a growth factor compounds — raise it to the power of the elapsed time, never multiply by it",
  "the straight-line distance is the hypotenuse — square, add, then root, never add the two legs directly",
  "same-time shadows keep the same height-to-shadow ratio — set up the proportion with matching quantities on top",
  "apply the two percentage changes to what is LEFT at each stage — they never simply cancel or add",
  "convert one unit at a time — scale the rate to a full period first, then convert the volume unit",
  "scale both equations to match one variable's coefficient before subtracting — one scaling step, then eliminate",
  // ---- GAT (Section 2)
  "subtract the equation with the matching coefficient first — it isolates one variable in a single step",
  "infinitely many solutions needs ALL three ratios to match, not just two of the three",
  "translate BOTH sentences into equations before solving either one",
  "a discount price is what's LEFT — divide by (1 − discount), don't multiply back up by the discount rate",
  "find the value of ONE part first, then take the DIFFERENCE in parts, not the difference in the ratio numbers",
  "divide the exponent by 4 and read the remainder off the four-term cycle — remainder 1 means the FIRST term, not the base itself",
  "expand (a + b)² first, then subtract 2ab — the individual values of a and b are never needed",
  "angles on a straight line total 180° — combine like terms once, then solve",
  "shaded/remaining = the WHOLE region minus the piece removed — find both areas separately first",
  "go through the TOTALS — a weighted mean is never the mean of the means",
  "'at least one' is 1 minus the probability of NONE — find that complement first",
  "add the RATES (work per hour), not the times — then flip the combined rate to get the time",
];

const cfg = {
  mathIndex: "math_w4sat/_index.json",
  examName: "SAT and GAT worksheet",
  targets: { "SAT-ALG": "~25%", "SAT-ADV": "~8%", "SAT-GEO": "~8%", "SAT-PSD": "~8%",
             "GAT-Q-ALG": "~17%", "GAT-Q-ARI": "~13%", "GAT-Q-GEO": "~8%",
             "GAT-Q-DAT": "~8%", "GAT-Q-LOG": "~4%" },
  dense: true, itemGap: 40, bare: true, optScale: 1,
  weekLine: "Week 5 · Semester 1, 2026–27",
  headerLine: "Grade 10 · Week 5 · SAT (pages 1–2, anchored to Linear Systems) and GAT Qudurat (pages 3–4, linear systems plus the standing spiral)",
  paperTitle: "SAT and GAT Worksheet — Grade 10, Week 5",
  paperSub: "24 questions · Section 1 SAT (calculator) · Section 2 GAT (no calculator)",
  keyTitle: "Grade 10 Week 5 — Answer Key and Error Analysis",
  keySub: "For Mr Malek Thiab. 30 minutes total: 15 on each section. Each item names the trick to say aloud and the error behind every wrong option.",
  outPaper: "SATGAT_Gr10_W5_Paper.docx",
  outKey: "SATGAT_Gr10_W5_Key.docx",
  timing: "30 minutes",
  calculator: "Section 1 yes · Section 2 no",
  marking: "One mark each, no penalty for a wrong answer",
  budgetNote: "24 items — 12 SAT and 12 GAT, anchored to Algebra II Topic 1 Lesson 6 (Linear Systems): elimination, substitution, and the number-of-solutions cases, in Saudi-context word problems on the SAT half and trap-heavy quantitative reasoning on the GAT half. Earlier topics (transformations, exponential growth, similar triangles, percent, sequences-adjacent identities) are spiralled in on both halves so nothing goes cold.",
  sourceNote: "Every item was hand-authored for this worksheet, in the house style of the Week 2–4 SAT+GAT sets. The SAT half follows the domain and difficulty character of the digital SAT (Algebra and Advanced Math, medium/hard). The GAT half follows the ETEC / Qiyas framework in the GAT and SAAT Classification Map. No leaked or circulated exam questions are used. Every numeric answer was independently re-derived before release.",
  followUp: [
    ["19 or more", "Linear systems are secure on both papers at this level. Move to full timed sections."],
    ["14 to 18", "Elimination and substitution are solid; the number-of-solutions items are the next marks to chase."],
    ["9 to 13", "Expected at this point. Re-run the weaker section whole before adding anything new."],
    ["Below 9", "Work the plain elimination items alone first — everything else this week builds from that one skill."],
    ["Whole class", "Any item where more than half the class chose the same wrong option is a teaching point — the trick column says what to put on the board."],
  ],
  items: [
    // ============================== SECTION 1 — SAT (Linear Systems anchor + spiral)
    { code: "SAT-ALG.1", lvl: 2,
      sec: { title: "SECTION 1 — SAT", note: "12 questions · calculator allowed · 15 minutes" },
      stem: "At a souq in Jeddah, 4 shirts and 3 belts cost SAR 262, while 4 shirts and 5 belts cost SAR 322. What is the cost, in SAR, of one belt?",
      opts: ["25", "28", "30", "32"], ans: 2,
      why: "Subtracting the first equation from the second eliminates the shirts, since both have a coefficient of 4: (4s + 5b) − (4s + 3b) = 322 − 262, so 2b = 60 and b = 30.",
      traps: ["A: an arithmetic slip while dividing 60.", "B: a rounding slip on the subtraction 322 − 262.", "D: the shirt price found and reported instead of the belt price (4s = 172, s = 43)."] },
    { code: "SAT-ALG.2", lvl: 2,
      stem: "A taxi company in Riyadh charges a flat fee plus a fixed rate per kilometer. A 10 km trip costs SAR 38, and a 25 km trip costs SAR 83. What is the per-kilometer rate, in SAR?",
      opts: ["2", "3", "4", "5"], ans: 1,
      why: "Letting the flat fee be f and the rate be r: f + 10r = 38 and f + 25r = 83. Subtracting: 15r = 45, so r = 3.",
      traps: ["A: an arithmetic slip while dividing 45 by 15.", "C: the flat fee (8) confused with a rate value.", "D: the total change in cost (45) divided by the wrong number of kilometers."] },
    { code: "SAT-ALG.3", lvl: 3,
      stem: "A family invests a total of SAR 20,000 in two accounts, one earning 4% annual interest and the other 7%. After one year, the total interest earned is SAR 1,220. How much, in SAR, was invested at 7%?",
      opts: ["10,000", "12,000", "14,000", "16,000"], ans: 2,
      why: "Letting x be the amount at 4% and y the amount at 7%: x + y = 20,000 and 0.04x + 0.07y = 1,220. Multiplying the first equation by 0.04 and subtracting gives 0.03y = 420, so y = 14,000.",
      traps: ["A: the amount at 4% reported instead of the amount at 7%.", "B: an arithmetic slip while dividing 420 by 0.03.", "D: the two interest rates swapped before setting up the second equation."] },
    { code: "SAT-ALG.4", lvl: 3,
      stem: "For what value of k does the system of equations below have NO solution ?  4x + 6y = 18  and  kx + 9y = 20",
      opts: ["4", "6", "8", "9"], ans: 1,
      why: "No solution requires the coefficient ratios to match while the constant's ratio does not: 4/k = 6/9 = 2/3, so k = 6. Checking the constants, 18/20 = 9/10 ≠ 2/3, confirming no solution.",
      traps: ["A: a coefficient ratio set up with mismatched terms.", "C: the constant 18 mistaken for part of the ratio instead of solving 4/k = 2/3.", "D: the value 9 copied down as k instead of solved for."] },
    { code: "SAT-ALG.5", lvl: 2,
      stem: "Line ℓ₁ has equation y = 2x − 3 and line ℓ₂ has equation y = −x + 9. At the point where they intersect, what is the value of x + y ?",
      opts: ["7", "8", "9", "10"], ans: 2,
      why: "Setting the equations equal: 2x − 3 = −x + 9, so 3x = 12 and x = 4. Then y = 2(4) − 3 = 5, and x + y = 4 + 5 = 9.",
      traps: ["A: an arithmetic slip while solving 3x = 12.", "B: only x reported instead of x + y.", "D: an arithmetic slip while adding x and y."] },
    { code: "SAT-ALG.6", lvl: 3,
      stem: "A group buys 2 adult tickets and 5 child tickets to Boulevard World for SAR 360, and 3 adult tickets and 2 child tickets for SAR 320. What is the price, in SAR, of one adult ticket?",
      opts: ["60", "70", "80", "90"], ans: 2,
      why: "Letting a be the adult price and c the child price: 2a + 5c = 360 and 3a + 2c = 320. Scaling the first by 3 and the second by 2 gives 6a + 15c = 1080 and 6a + 4c = 640; subtracting, 11c = 440, so c = 40 and a = 80.",
      traps: ["A: the value of c found and mistaken for a.", "B: an arithmetic slip while solving for c.", "D: a rounding slip after scaling the equations."] },
    { code: "SAT-ADV.1", lvl: 2,
      stem: "The graph of the function h(x) = (x + 5)² − 11 is the same as the graph of y = x² after which of the following transformations ?",
      opts: ["Shifted left 5 and down 11", "Shifted right 5 and up 11", "Shifted left 5 and up 11", "Shifted right 5 and down 11"], ans: 0,
      why: "In h(x) = (x − h)² + k, the graph of y = x² shifts right by h and up by k. Here h = −5 and k = −11, so the shift is left 5 and down 11.",
      traps: ["B: both the horizontal and vertical shift signs reversed.", "C: the vertical shift's sign reversed.", "D: the horizontal shift's sign reversed."] },
    { code: "SAT-ADV.2", lvl: 2,
      stem: "The number of visitors to a Red Sea heritage site grows according to V(t) = 800(1.15)^t, where t is the number of years since the site opened. Which of the following is closest to the number of visitors after 6 years ?",
      opts: ["1,690", "1,850", "1,960", "2,100"], ans: 1,
      why: "V(6) = 800(1.15)⁶ ≈ 800 × 2.3131 ≈ 1,850.",
      traps: ["A: the exponent applied to only part of the growth factor.", "C: an arithmetic slip while computing 1.15⁶.", "D: the growth treated as linear, computing 800 × (1 + 0.15 × 6) rounded up."] },
    { code: "SAT-GEO.1", lvl: 2,
      stem: "A path from a car park to the beach at a Jeddah corniche park runs 120 meters east, then 160 meters north. What is the straight-line distance, in meters, from the car park to the beach ?",
      opts: ["180", "190", "200", "210"], ans: 2,
      why: "By the Pythagorean theorem, the distance is √(120² + 160²) = √(14,400 + 25,600) = √40,000 = 200 meters.",
      traps: ["A: the two legs added directly instead of using the Pythagorean theorem.", "B: an arithmetic slip while computing the square root.", "D: a rounding slip on √40,000."] },
    { code: "SAT-GEO.2", lvl: 2,
      stem: "A 1.8-meter-tall lamppost casts a 2.4-meter shadow. At the same time, a nearby flagpole casts a 9.6-meter shadow. Using similar triangles, what is the height, in meters, of the flagpole ?",
      opts: ["6.4", "7.0", "7.2", "7.8"], ans: 2,
      why: "The lamppost and its shadow form a triangle similar to the flagpole and its shadow, so height-to-shadow is constant: 1.8 ÷ 2.4 = 0.75. The flagpole's height is 0.75 × 9.6 = 7.2 meters.",
      traps: ["A: the ratio inverted (shadow-to-height) before multiplying.", "B: a rounding slip on the ratio 1.8 ÷ 2.4.", "D: the shadow length used directly as the multiplier instead of the height-to-shadow ratio."] },
    { code: "SAT-PSD.1", lvl: 2,
      stem: "A furniture set is priced at SAR 4,600 before 15% VAT. After VAT is added, the store offers a 10% discount on the VAT-inclusive price. What is the final price, in SAR ?",
      opts: ["4,600", "4,669", "4,761", "4,830"], ans: 2,
      why: "After VAT: 4,600 × 1.15 = 5,290. After the discount: 5,290 × 0.90 = 4,761.",
      traps: ["A: the two percentage changes assumed to cancel out and return the original price.", "B: an arithmetic slip while applying the discount.", "D: the VAT and discount rates both added instead of applied as successive multipliers."] },
    { code: "SAT-PSD.2", lvl: 3,
      stem: "A water tanker fills at a constant rate of 2,400 liters every 15 minutes. At this rate, how many cubic meters does it fill in 5 hours ? (1 cubic meter = 1,000 liters.)",
      opts: ["36", "42", "48", "54"], ans: 2,
      why: "The rate is 2,400 ÷ 15 = 160 liters per minute, or 160 × 60 = 9,600 liters per hour. In 5 hours: 9,600 × 5 = 48,000 liters = 48 cubic meters.",
      traps: ["A: the rate scaled by only part of the 5 hours.", "B: an arithmetic slip while converting minutes to hours.", "D: the unit conversion applied before scaling to 5 hours, then a rounding slip."] },

    // ================================================ SECTION 2 — GAT
    { code: "GAT-Q-ALG.1", lvl: 3,
      sec: { newPage: true, title: "SECTION 2 — GAT (Qudurat)", note: "12 questions · NO calculator · 15 minutes" },
      stem: "In the system below, what is the value of x − y ?  5x + 3y = 29  and  2x + 3y = 17",
      opts: ["1", "2", "3", "4"], ans: 0,
      why: "Subtracting the second equation from the first eliminates y, since both have a coefficient of 3: 3x = 12, so x = 4. Substituting into 2x + 3y = 17: 8 + 3y = 17, so y = 3. Then x − y = 4 − 3 = 1.",
      traps: ["B: an arithmetic slip while solving for y.", "C: the value of y reported instead of x − y.", "D: the value of x reported instead of x − y."] },
    { code: "GAT-Q-ALG.2", lvl: 3,
      stem: "For which value of m does the system 6x + 4y = 10 and 9x + my = 15 have infinitely many solutions ?",
      opts: ["4", "5", "6", "8"], ans: 2,
      why: "Infinitely many solutions requires all three ratios to match: 6/9 = 4/m = 10/15. Since 6/9 = 2/3, solving 4/m = 2/3 gives m = 6, and 10/15 = 2/3 also matches.",
      traps: ["A: a coefficient ratio set up with mismatched terms.", "B: an arithmetic slip while solving 4/m = 2/3.", "D: the constant 15 confused with the value of m."] },
    { code: "GAT-Q-ALG.3", lvl: 3,
      stem: "A father is 3 times as old as his son. In 12 years, he will be twice as old as his son. What is the son's current age ?",
      opts: ["10", "11", "12", "14"], ans: 2,
      why: "Letting the son's age be s, the father's age is 3s. In 12 years: 3s + 12 = 2(s + 12), so 3s + 12 = 2s + 24, giving s = 12.",
      traps: ["A and B: an arithmetic slip while expanding or collecting terms.", "D: the equation set up with the +12 applied to only one side."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "After a 20% discount, a jacket costs SAR 344. What was its original price, in SAR ?",
      opts: ["380", "412", "430", "448"], ans: 2,
      why: "The discounted price is 80% of the original: 344 ÷ 0.80 = 430.",
      traps: ["A: 344 with 20% of 344 added back on, instead of dividing by 0.80.", "B: an arithmetic slip while dividing.", "D: 344 divided by 0.75 instead of 0.80."] },
    { code: "GAT-Q-ARI.2", lvl: 2,
      stem: "SAR 3,600 is shared between three partners in the ratio 3 : 4 : 5. How much more, in SAR, does the largest share receive than the smallest ?",
      opts: ["400", "500", "600", "700"], ans: 2,
      why: "The twelve parts total SAR 3,600, so one part is 300. The difference between the largest and smallest shares is 5 − 3 = 2 parts, or 2 × 300 = 600.",
      traps: ["A: two-thirds of one part.", "B: the value of one and two-thirds parts.", "D: the largest share's own value divided incorrectly."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "What is the units digit of 3^41 ?",
      opts: ["1", "3", "7", "9"], ans: 1,
      why: "Powers of 3 have units digits cycling 3, 9, 7, 1 every four. Since 41 leaves remainder 1 on division by 4, the units digit is the first in the cycle: 3.",
      traps: ["A: remainder taken as 0.", "C: remainder taken as 2.", "D: remainder taken as 3."] },
    { code: "GAT-Q-ALG.4", lvl: 3,
      stem: "If a + b = 11 and ab = 24, what is the value of a² + b² ?",
      opts: ["49", "73", "97", "121"], ans: 1,
      why: "(a + b)² = a² + b² + 2ab, so 121 = a² + b² + 48, giving a² + b² = 73. The individual values of a and b are never needed.",
      traps: ["A: 2ab subtracted twice instead of once.", "C: 2ab taken as 24 instead of 48.", "D: (a + b)² given back unchanged."] },
    { code: "GAT-Q-GEO.1", lvl: 3,
      stem: "Three angles on a straight line measure (2x)°, (3x + 10)°, and (5x − 10)°. What is the value of x ?",
      opts: ["15", "16", "18", "20"], ans: 2,
      why: "Angles on a straight line total 180°: 2x + 3x + 10 + 5x − 10 = 180, so 10x = 180 and x = 18.",
      traps: ["A: an arithmetic slip while dividing 180 by 10.", "B: the constants not cancelled correctly before dividing.", "D: the angles assumed to total 200°."] },
    { code: "GAT-Q-GEO.2", lvl: 3,
      stem: "A rectangular garden measures 20 m by 14 m. A circular fountain of radius 7 m sits inside it. What area, in m², is NOT covered by the fountain ? (Take π = 22/7.)",
      opts: ["112", "126", "140", "154"], ans: 1,
      why: "The rectangle's area is 20 × 14 = 280 m². The fountain's area is 22/7 × 7² = 154 m². The area not covered is 280 − 154 = 126 m².",
      traps: ["A: an arithmetic slip on the subtraction.", "C: the radius mistaken for the diameter when finding the circle's area.", "D: only the fountain's own area given, not the difference."] },
    { code: "GAT-Q-DAT.1", lvl: 3,
      stem: "18 students scored a mean of 72, and 12 students scored a mean of 90. What is the mean for all 30 students ?",
      opts: ["78", "79.2", "80", "81"], ans: 1,
      why: "Totals first: 18 × 72 = 1,296 and 12 × 90 = 1,080, giving 2,376 total across 30 students. The mean is 2,376 ÷ 30 = 79.2. A weighted mean is not the mean of the means.",
      traps: ["A: the two means simply averaged, (72 + 90) ÷ 2, then adjusted.", "C: a rounding slip on the division.", "D: the larger group's own mean nudged up instead of computed from totals."] },
    { code: "GAT-Q-DAT.2", lvl: 3,
      stem: "A fair coin is tossed 3 times. What is the probability of getting at least one head ?",
      opts: ["1/8", "3/8", "5/8", "7/8"], ans: 3,
      why: "'At least one' is 1 minus 'none': the probability of no heads is (1/2)³ = 1/8, so the answer is 1 − 1/8 = 7/8.",
      traps: ["A: the complement itself given as the answer.", "B: a guess between the values.", "C: a guess between the values."] },
    { code: "GAT-Q-LOG.1", lvl: 3,
      stem: "Pipe A alone fills a tank in 6 hours, and pipe B alone fills the same tank in 12 hours. Working together, how many hours do they take to fill the tank ?",
      opts: ["3", "3.5", "4", "4.5"], ans: 2,
      why: "Add the rates, not the times: pipe A fills 1/6 of the tank per hour and pipe B fills 1/12 per hour, so together they fill 1/6 + 1/12 = 3/12 = 1/4 of the tank per hour. The time to fill it is the reciprocal: 4 hours.",
      traps: ["A: the two individual times simply averaged, (6 + 12) ÷ 2, then adjusted.", "B: an arithmetic slip while combining the rates.", "D: the reciprocal of the combined rate taken with a rounding slip."] },
  ],
};

if (TRICKS.length !== cfg.items.length)
  throw new Error(`${TRICKS.length} tricks for ${cfg.items.length} items`);
cfg.items.forEach((it, i) => { it.trick = TRICKS[i]; });

buildSet(cfg);
console.log("built", cfg.outPaper, "and", cfg.outKey);
