// ---------------------------------------------------------------------------
// SAT + GAT combined worksheet — GRADE 10, WEEK 3.
// Anchor: 1-2 Transformations of Functions and 1-3 Piecewise Defined Functions.
// Spiral: Week 2's key features are revisited (vertex, zeros, range) so they do
// not go cold; inequalities, exponential growth, similarity and probability are
// seeded ahead of the syllabus. Coverage comes off the term grid, not the week.
// Four full pages of questions, no preamble. See spec §18.
// ---------------------------------------------------------------------------
const { buildSet } = require("./exam_engine");

const TRICKS = [
  // ---- SAT, in item order (verified against the item list, not assumed)
  "inside the bracket moves x and does the OPPOSITE of what it looks like",
  "a minus in FRONT flips the graph in the x-axis; a minus inside flips it in the y-axis",
  "a vertical stretch scales every y, so a zero stays exactly where it was",
  "vertex form reads the vertex straight off, with the sign inside flipped",
  "an absolute value is never negative, so its smallest value is 0",
  "at a piecewise boundary, check which piece OWNS the endpoint",
  "choose the piece by testing which condition the x satisfies first",
  "clear the fraction first, then solve — and only a negative multiplier flips the sign",
  "substitute from the simpler equation rather than eliminating blind",
  "two points give the gradient; the intercept comes after, not before",
  "name the two unknowns in words before writing any algebra",
  "solve for the letter you want by undoing operations in reverse order",
  "growth of r% per period multiplies by (1 + r) each time, never adds",
  "a percentage change always divides by the STARTING value",
  "similar figures scale lengths by k and AREAS by k squared",
  "on the coordinate plane, distance is Pythagoras in disguise",
  "name the width first, write the length in terms of it, then solve once",
  "a multiplier INSIDE the bracket compresses; outside it stretches",
  "take the fixed charge off BEFORE dividing by the rate",
  // ---- GAT, in item order
  "a percentage of a percentage multiplies, it does not add",
  "work back to the WHOLE before taking a new percentage of it",
  "units digits run in a cycle of four — divide the exponent by 4",
  "when the differences are not constant, take the differences of the differences",
  "make the exponents match before comparing the bases",
  "(a − b)² = a² + b² − 2ab, so a² + b² is one step away",
  "an absolute value opens into TWO equations",
  "the product of the roots is c/a; no factorising needed",
  "angles on a straight line add to 180° — collect the terms and solve once",
  "the angle at the centre is twice the angle at the circumference",
  "shaded = whole minus the pieces removed; leave π alone",
  "a weighted mean is not the mean of the means",
  "in a two-way table the denominator is the row the question names",
  "'at least one' is 1 minus the probability of none",
  "average speed is total distance over total time, never the average of the speeds",
  "add the rates WITH their signs — a leak is a negative rate",
  "convert everything to the same unit BEFORE dividing",
  "consecutive integers cluster around their mean — name the middle one x",
  "divisible by both 3 and 4 means divisible by 12 — test the pair, not one",
  "neither = total − (A + B − both); the overlap comes off once",
  "express the change as a FRACTION of the whole, then scale up once",
  "scale the whole group rather than pricing one and rounding",
  "a border takes its width off BOTH ends of every dimension",
  "whatever you do to every number, you do to the mean — in the same order",
];

const cfg = {
  mathIndex: "math_sg/_index.json",
  figIndex: "figs_sg/_index.json",
  examName: "SAT and GAT worksheet",
  targets: { "SAT-ALG": "~17.5%", "SAT-ADV": "~17.5%", "SAT-PSD": "~7.5%",
             "SAT-GEO": "~7.5%", "GAT-Q-ARI": "~18%", "GAT-Q-ALG": "~9%",
             "GAT-Q-GEO": "~9%", "GAT-Q-DAT": "~9%", "GAT-Q-LOG": "~5%" },
  dense: true, itemGap: 40, bare: true, optScale: 1,
  weekLine: "Week 3 · Semester 1, 2026–27",
  headerLine: "Grade 10 · Week 3 · SAT (pages 1–2) and GAT Qudurat (pages 3–4) · aligned to 1-2 Transformations and 1-3 Piecewise Functions",
  paperTitle: "SAT and GAT Worksheet — Grade 10, Week 3",
  paperSub: "46 questions · Section 1 SAT (calculator) · Section 2 GAT (no calculator)",
  keyTitle: "Grade 10 Week 3 — Answer Key and Error Analysis",
  keySub: "For Mr Malek Thiab. 50 minutes total: 25 on each section. Each item names the trick to say aloud and the error behind every wrong option.",
  outPaper: "SATGAT_Gr10_W3_Paper.docx",
  outKey: "SATGAT_Gr10_W3_Key.docx",
  timing: "50 minutes",
  calculator: "Section 1 yes · Section 2 no",
  marking: "One mark each, no penalty for a wrong answer",
  budgetNote: "46 items — 21 SAT and 25 GAT. Targets are the published weights HALVED, because each exam is half this paper.",
  sourceNote: "Every item was written for this worksheet. The SAT half follows the College Board's published domain weights for the digital SAT; the GAT half follows the ETEC / Qiyas framework in the GAT and SAAT Classification Map. No leaked or circulated exam questions are used.",
  followUp: [
    ["33 or more", "Secure on both papers at this level. The ceiling now is pace — move to full timed sections."],
    ["25 to 32", "The transformations are understood one at a time. Re-mark counting only the items with TWO transformations combined; that is where the next marks are."],
    ["17 to 24", "Expected at this point. Take the weaker section whole and re-run it before adding anything new."],
    ["Below 17", "Work the SAT half alone first. Inside-the-bracket versus outside-the-bracket is the one idea to fix before anything else."],
    ["Whole class", "Any item where more than half the class chose the same wrong option is a teaching point — the trick column says what to put on the board."],
  ],
  items: [
    // ================================================ SECTION 1 — SAT
    { code: "SAT-ADV.1", lvl: 2,
      sec: { title: "SECTION 1 — SAT", note: "21 questions · calculator allowed · 25 minutes" },
      stem: "The graph of g is obtained from the graph of f. Which describes the change?", stemEq: "b_trans",
      opts: ["3 left and 2 down", "3 right and 2 up", "3 up and 2 right", "3 right and 2 down"], ans: 1,
      why: "Inside the bracket acts on x and does the opposite of its sign: x − 3 moves the graph 3 to the RIGHT. Outside the bracket acts on y and does what it says: + 2 moves it up.",
      traps: ["A: both directions reversed.", "C: the roles of inside and outside swapped.", "D: the outside term reversed as though it were inside."] },
    { code: "SAT-ADV.2", lvl: 2,
      stem: "The graph of y = f(x) is reflected in the x-axis. Which equation describes the result?",
      opts: [{ eq: "o_fnegx" }, { eq: "o_negfx" }, { eq: "o_absfx" }, { eq: "o_fxm1" }], ans: 1,
      why: "Reflecting in the x-axis negates every output, so y = −f(x). Negating the input instead reflects in the y-axis.",
      traps: ["A: reflection in the y-axis.", "C: the negative parts folded up, not reflected.", "D: a translation, not a reflection."] },
    { code: "SAT-ADV.3", lvl: 2, stem: "The graph of f has a zero at x = 4. Where is the zero of h ?", stemEq: "b_stretch",
      opts: [{ eq: "o_x43" }, { eq: "o_x4" }, { eq: "o_x12" }, "there is no zero"], ans: 1,
      why: "A vertical stretch multiplies every output by 3. Where f was 0, three times 0 is still 0 — so the zero does not move.",
      traps: ["A: the stretch applied to x.", "C: the input multiplied by 3.", "D: the stretch assumed to remove the zero."] },
    { code: "SAT-ADV.4", lvl: 2, stem: "What is the vertex of the graph?", stemEq: "b_vertex2",
      opts: [{ eq: "o_vm25" }, { eq: "o_v25" }, { eq: "o_vm2m5" }, { eq: "o_v2m5" }], ans: 0,
      why: "Vertex form gives the vertex directly. The bracket is x + 2, which is zero at x = −2, and the constant outside gives y = 5.",
      traps: ["B: the sign inside the bracket not flipped.", "C: the outside constant sign-flipped.", "D: both signs wrong."] },
    { code: "SAT-ADV.5", lvl: 2, stem: "What is the minimum value of y ?", stemEq: "b_absg",
      opts: ["−3", "0", "3", "4"], ans: 0,
      why: "An absolute value is never negative, so its smallest value is 0, reached at x = 4. Then y = 0 − 3 = −3.",
      traps: ["B: the absolute value's own minimum reported.", "C: the sign of the constant lost.", "D: x = 4 given instead of y."] },
    { code: "SAT-ADV.6", lvl: 3, stem: "For the function below, what is the value of f(2) ?", stemEq: "b_pw",
      opts: ["1", "5", "−2", "3"], ans: 0,
      why: "x = 2 satisfies x ≥ 2, so the SECOND piece owns the boundary: 2² − 3 = 1. Which piece owns the endpoint is the whole question.",
      traps: ["B: the first piece used, 2(2) + 1 = 5 — the boundary handed to the wrong piece, and the commonest error here.", "C: a sign slip inside the square.", "D: the two pieces averaged."],
      note: "Test which condition x = 2 satisfies before choosing a piece." },
    { code: "SAT-ADV.7", lvl: 3, stem: "For the same function, what is f(0) ?", stemEq: "b_pw",
      opts: ["−3", "1", "0", "5"], ans: 1,
      why: "x = 0 satisfies x < 2, so the first piece applies: 2(0) + 1 = 1.",
      traps: ["A: the second piece used, 0 − 3.", "C: the input returned unchanged.", "D: f(2) from the first piece."] },
    { code: "SAT-ALG.1", lvl: 2, stem: "Solve the inequality.", stemEq: "b_ineq2",
      opts: [{ eq: "o_xle8" }, { eq: "o_xge8" }, { eq: "o_xle7" }, { eq: "o_xge7" }], ans: 0,
      why: "Multiply both sides by 3 first: 2x − 1 ≤ 15, so 2x ≤ 16 and x ≤ 8. Nothing was multiplied by a negative, so the sign does not flip.",
      traps: ["B: the sign flipped without cause.", "C: the 1 added before the multiplication.", "D: both errors together."] },
    { code: "SAT-ALG.2", lvl: 2, stem: "In the system below, what is the value of x ?", stemEq: "b_sys2",
      opts: ["1", "2", "3", "5"], ans: 2,
      why: "From the second equation y = x − 1. Substituting: 2x + 3(x − 1) = 12, so 5x = 15 and x = 3.",
      traps: ["A: the value of y.", "B: the equations added without adjusting coefficients.", "D: 15 divided by 3."] },
    { code: "SAT-ALG.3", lvl: 2,
      stem: "A line passes through (2, 5) and (6, 17). What is its equation?",
      opts: [{ eq: "o_l1" }, { eq: "o_l2" }, { eq: "o_l3" }, { eq: "o_l4" }], ans: 0,
      why: "Gradient = (17 − 5)/(6 − 2) = 3. Then 5 = 3(2) + c gives c = −1.",
      traps: ["B: the sign of the intercept lost.", "C: the differences taken in the wrong order.", "D: the rise used as the gradient without dividing."] },
    { code: "SAT-ALG.4", lvl: 3,
      stem: "Two notebooks and three pens cost 23 SAR. Four notebooks and one pen cost 21 SAR. What does one notebook cost, in SAR?",
      opts: ["4", "5", "6", "7"], ans: 0,
      why: "2n + 3p = 23 and 4n + p = 21. From the second, p = 21 − 4n. Substituting: 2n + 63 − 12n = 23, so 10n = 40 and n = 4.",
      traps: ["B: the pen's price.", "C: the two totals averaged and divided.", "D: the equations added without eliminating."] },
    { code: "SAT-ALG.5", lvl: 3,
      stem: "The formula for the area of a trapezium is A = ½(a + b)h. Which expression gives h ?",
      opts: [{ eq: "o_h1" }, { eq: "o_h2" }, { eq: "o_h3" }, { eq: "o_h4" }], ans: 1,
      why: "Undo in reverse: multiply both sides by 2 to clear the half, then divide by (a + b). So h = 2A/(a + b).",
      traps: ["A: division treated as subtraction.", "C: the 2 moved to the wrong side.", "D: the whole expression inverted."] },
    { code: "SAT-ALG.6", lvl: 2, stem: "A sum of 200 SAR grows at 5% per year. What does the model give after t years?", stemEq: "b_exp",
      opts: ["the amount after t years", "the interest earned in year t", "the number of years to double", "the yearly increase in SAR"], ans: 0,
      why: "The 200 is the starting amount and each year multiplies it by 1.05, so y is the total amount after t years — principal included, not the interest alone.",
      traps: ["B: the total confused with the year's interest.", "C: a doubling time read out of a growth model.", "D: the multiplier read as an amount."] },
    { code: "SAT-PSD.1", lvl: 3,
      stem: "A test score rises from 60 to 75. By what percentage did it increase?",
      opts: ["15%", "20%", "25%", "80%"], ans: 2,
      why: "The rise is 15, measured against the STARTING value: 15/60 = 25%.",
      traps: ["A: the raw rise given as a percentage.", "B: divided by 75, the finishing value.", "D: 60 as a percentage of 75."] },
    { code: "SAT-GEO.1", lvl: 3,
      stem: "Two similar triangles have corresponding sides in the ratio 2 : 5. What is the ratio of their areas?",
      opts: ["2 : 5", "4 : 10", "4 : 25", "8 : 125"], ans: 2,
      why: "Lengths scale by k, areas by k². Here k = 5/2, so areas are in the ratio 4 : 25.",
      traps: ["A: the length ratio reused.", "B: the ratio doubled rather than squared.", "D: the volume ratio, k cubed."] },
    { code: "SAT-GEO.2", lvl: 2,
      stem: "What is the distance between the points (1, 2) and (7, 10) ?",
      opts: ["8", "10", "12", "14"], ans: 1,
      why: "The horizontal gap is 6 and the vertical gap is 8, so the distance is √(36 + 64) = 10 — a 3-4-5 triangle scaled by 2.",
      traps: ["A: the vertical gap alone.", "C: the two gaps subtracted from 18.", "D: the two gaps added."] },
    { code: "SAT-GEO.3", lvl: 3,
      stem: "A rectangle has area 48 cm² and its length is 3 times its width. What is its perimeter, in cm?",
      opts: ["28", "32", "36", "48"], ans: 1,
      why: "w × 3w = 48, so w² = 16 and w = 4, length 12. Perimeter = 2(4 + 12) = 32.",
      traps: ["A: width and length taken as 6 and 8.", "C: the perimeter of a 6 by 12 rectangle.", "D: the area reused as the perimeter."] },

    { code: "SAT-ADV.8", lvl: 3,
      stem: "The graph of y = f(x) is transformed to y = f(2x). Which describes the result?",
      opts: ["stretched horizontally by a factor of 2", "compressed horizontally by a factor of 2", "stretched vertically by a factor of 2", "moved 2 units left"], ans: 1,
      why: "A multiplier INSIDE the bracket acts on x and does the opposite of what it looks like: doubling x compresses the graph horizontally, halving every input distance.",
      traps: ["A: the direction reversed — the commonest error with inside multipliers.", "C: an inside change read as an outside one.", "D: a multiplier read as a translation."] },
    { code: "SAT-ALG.7", lvl: 3,
      stem: "A taxi charges a fixed 12 SAR plus 2.50 SAR per km. A passenger pays 42 SAR. How far did the taxi travel, in km?",
      opts: ["10", "12", "16.8", "21.6"], ans: 1,
      why: "42 − 12 = 30 SAR of distance charge, and 30 ÷ 2.50 = 12 km. Take the fixed fee off BEFORE dividing.",
      traps: ["A: the fixed fee taken off twice.", "C: 42 divided by 2.50 with the fee ignored.", "D: the fee added rather than subtracted."] },

    // ================================================ SECTION 2 — GAT
    { code: "GAT-Q-ARI.3", lvl: 3,
      sec: { newPage: true, title: "SECTION 2 — GAT (Qudurat)",
             note: "25 questions · NO calculator · 25 minutes" },
      stem: "What is 30% of 40% of 500 ?",
      opts: ["36", "60", "70", "350"], ans: 1,
      why: "40% of 500 is 200, and 30% of 200 is 60. The two percentages multiply: 0.30 × 0.40 = 0.12, and 12% of 500 is 60.",
      traps: ["A: 30% of 120.", "C: the percentages added and halved.", "D: 70% of 500 — the percentages added."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "35% of a number is 70. What is 20% of the same number?",
      opts: ["14", "20", "40", "50"], ans: 2,
      why: "The number is 70 ÷ 0.35 = 200, and 20% of 200 is 40. Go back to the whole before taking any new percentage.",
      traps: ["A: 20% of 70.", "B: the two percentages subtracted.", "D: 25% of 200."] },
    { code: "GAT-Q-ARI.5", lvl: 3, stem: "What is the units digit of the number below?", stemEq: "a_pow",
      opts: ["1", "3", "7", "9"], ans: 1,
      why: "Powers of 3 have units digits cycling 3, 9, 7, 1 every four. 17 leaves remainder 1 on division by 4, so the units digit is the first: 3.",
      traps: ["A: remainder taken as 0.", "C: remainder taken as 3.", "D: remainder taken as 2."] },
    { code: "GAT-Q-ARI.5", lvl: 3,
      stem: "What is the next term of the sequence 3, 8, 15, 24, 35, … ?",
      opts: ["44", "46", "48", "50"], ans: 2,
      why: "The differences are 5, 7, 9, 11 — rising by 2. The next difference is 13, so the next term is 35 + 13 = 48.",
      traps: ["A: the last difference repeated.", "B: the differences assumed to rise by 1.", "D: the difference taken as 15."] },
    { code: "GAT-Q-ARI.4", lvl: 3, stem: "Which quantity is greater?", stemEq: "g_cmp230", k: 1.05,
      opts: ["A is greater", "B is greater", "they are equal", "not enough information"], ans: 1,
      why: "Match the exponents: 2³⁰ = 8¹⁰ and 3²⁰ = 9¹⁰. Since 9 > 8, B is greater.",
      traps: ["A: the larger exponent assumed to win.", "C: both read as simply enormous.", "D: both are fully determined."] },
    { code: "GAT-Q-ALG.4", lvl: 3,
      stem: "If", stemEq: "s_idg10", note: "what is the value of a² + b² ?",
      opts: ["19", "23", "29", "49"], ans: 2,
      why: "(a − b)² = a² + b² − 2ab, so 9 = a² + b² − 20 and a² + b² = 29. The values of a and b are never needed.",
      traps: ["A: 10 subtracted once instead of added twice.", "B: 2ab taken as 6.", "D: the identity for (a + b)² used."] },
    { code: "GAT-Q-ALG.1", lvl: 3,
      stem: "What is the sum of the solutions?", stemEq: "s_absg10",
      opts: ["2", "4", "5", "6"], ans: 1,
      why: "3x − 6 = 9 gives x = 5, and 3x − 6 = −9 gives x = −1. Their sum is 4.",
      traps: ["A: the negative solution's size only.", "C: only the positive branch taken.", "D: the 6 copied back."] },
    { code: "GAT-Q-ALG.3", lvl: 3, stem: "What is the product of the roots?", stemEq: "g_quadr",
      opts: ["7", "10", "17", "70"], ans: 1,
      why: "The product of the roots is c/a = 10. Factorising to (x − 2)(x − 5) confirms it, but the formula skips the work.",
      traps: ["A: the sum of the roots.", "C: the coefficients added.", "D: the sum and product multiplied."] },
    { code: "GAT-Q-GEO.1", lvl: 3,
      stem: "Three angles on a straight line are (2x)°, (3x + 10)° and (x + 20)°. What is the value of x ?",
      opts: ["20", "25", "30", "35"], ans: 1,
      why: "Angles on a straight line total 180°: 6x + 30 = 180, so x = 25. Collect the terms and solve once rather than guessing.",
      traps: ["A: the constants dropped.", "C: the angles assumed to total 210°.", "D: the angles assumed to total 240°."] },
    { code: "GAT-Q-GEO.4", lvl: 3,
      stem: "In a circle, an angle at the centre measures 80°. What is the angle at the circumference standing on the same arc?",
      opts: ["20°", "40°", "80°", "160°"], ans: 1,
      why: "The angle at the centre is twice the angle at the circumference on the same arc, so the answer is 40°.",
      traps: ["A: the angle quartered.", "C: the two assumed equal.", "D: the relationship applied backwards."] },
    { code: "GAT-Q-GEO.3", lvl: 3,
      stem: "A circle of radius 5 cm is inscribed in a square. What area of the square lies outside the circle, in cm² ?",
      opts: [{ eq: "g_o_sh1" }, { eq: "g_o_sh2" }, { eq: "g_o_sh3" }, { eq: "g_o_sh4" }], ans: 0,
      why: "The circle touches all four sides, so the square has side 10 and area 100. The circle has area 25π, leaving 100 − 25π. Leave π alone.",
      traps: ["B: the radius used as the side.", "C: the circumference subtracted instead of the area.", "D: the circle's area given instead of the region outside."] },
    { code: "GAT-Q-DAT.5", lvl: 3,
      stem: "In a class, 10 students scored a mean of 80 and 20 students scored a mean of 65. What is the mean for all 30 ?",
      opts: ["70", "72.5", "73", "75"], ans: 0,
      why: "Totals first: 800 + 1300 = 2100, and 2100/30 = 70. A weighted mean is not the mean of the means.",
      traps: ["B: the mean of 80 and 65.", "C: rounded from the wrong average.", "D: the larger group ignored."] },
    { code: "GAT-Q-DAT.1", lvl: 3,
      stem: "The table shows the results of a survey. What percentage of those who own a car also own a bicycle?",
      table: [["", "Bicycle", "No bicycle", "Total"], ["Car", "24", "16", "40"], ["No car", "18", "22", "40"], ["Total", "42", "38", "80"]],
      opts: ["30%", "48%", "57%", "60%"], ans: 3,
      why: "Read the Car row only: 24 out of 40, which is 60%. The grand total of 80 is not the denominator.",
      traps: ["A: 24 out of 80.", "B: a misread of the Bicycle column.", "C: 24 out of 42, using the column total."] },
    { code: "GAT-Q-DAT.3", lvl: 3,
      stem: "A fair coin is tossed three times. What is the probability of at least one head?",
      opts: [{ eq: "f_38" }, { eq: "f_12" }, { eq: "f_58" }, { eq: "f_78" }], ans: 3,
      why: "'At least one' is 1 minus 'none': the chance of no heads is (1/2)³ = 1/8, so the answer is 7/8.",
      traps: ["A: exactly one head.", "B: a guess from symmetry.", "C: at least two heads."] },
    { code: "GAT-Q-LOG.1", lvl: 3,
      stem: "A driver covers 120 km at 80 km/h and the next 120 km at 60 km/h. What is the average speed for the whole journey, in km/h?",
      opts: ["66", "68.6", "70", "72"], ans: 1,
      why: "Total time is 1.5 + 2 = 3.5 hours for 240 km, so 240/3.5 ≈ 68.6. More time is spent at the slower speed, so it must fall below 70.",
      traps: ["A: a guess below the true value.", "C: the mean of 80 and 60 — the trap.", "D: a guess above the mean."] },
    { code: "GAT-Q-LOG.2", lvl: 3,
      stem: "A tank fills through one pipe in 4 hours and empties through another in 6 hours. With both open, how long does it take to fill?",
      opts: ["10 hours", "12 hours", "2.4 hours", "5 hours"], ans: 1,
      why: "Rates, with signs: 1/4 − 1/6 = 1/12 of the tank per hour, so 12 hours. Adding the times, or ignoring the sign, both fail.",
      traps: ["A: the times added.", "C: the rates added without the sign.", "D: the times averaged."] },
    { code: "GAT-Q-ARI.2", lvl: 3,
      stem: "A car travels 45 km in 30 minutes. What is its speed in metres per second?",
      opts: ["12.5", "18", "25", "90"], ans: 2,
      why: "45 km in half an hour is 90 km/h. Then 90 000 m ÷ 3600 s = 25 m/s. Convert before comparing, never after.",
      traps: ["A: 45 000 divided by 3600.", "B: a partial conversion.", "D: the speed in km/h given unchanged."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "The sum of five consecutive integers is 105. What is the largest of them?",
      opts: ["19", "21", "23", "25"], ans: 2,
      why: "Name the middle one x. The five sum to 5x = 105, so x = 21 and the largest is 23. Consecutive integers always cluster round their mean.",
      traps: ["A: the smallest.", "B: the middle one.", "D: the mean taken as the largest."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "How many integers from 1 to 100 inclusive are divisible by both 3 and 4 ?",
      opts: ["4", "8", "12", "16"], ans: 1,
      why: "Divisible by both 3 and 4 means divisible by 12. The multiples of 12 up to 100 are 12, 24, … , 96 — that is 8 of them.",
      traps: ["A: multiples of 24 counted.", "C: multiples of 8 counted.", "D: multiples of 6 counted."] },
    { code: "GAT-Q-LOG.3", lvl: 3,
      stem: "In a group of 40 students, 25 study French, 20 study German and 5 study neither. How many study both?",
      opts: ["5", "8", "10", "15"], ans: 2,
      why: "35 study at least one. Then 25 + 20 − both = 35, so both = 10. The overlap is what makes the two counts exceed the total.",
      traps: ["A: the 'neither' figure reused.", "B: a guess between the values.", "D: the difference of the two subjects."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "A tank is two-thirds full. After 24 litres are drawn off it is half full. What is the capacity of the tank, in litres?",
      opts: ["108", "132", "144", "160"], ans: 2,
      why: "The 24 litres is the difference between two-thirds and one-half, which is one-sixth of the tank. So the capacity is 24 × 6 = 144.",
      traps: ["A: one-ninth used as the fraction.", "B: a guess between the values.", "D: one-fifth used as the fraction."] },
    { code: "GAT-Q-ALG.5", lvl: 3,
      stem: "If 5 pens cost 12 SAR, how many pens can be bought with 96 SAR?",
      opts: ["24", "30", "40", "48"], ans: 2,
      why: "96 ÷ 12 = 8 lots of five pens, so 8 × 5 = 40. Scale the whole group rather than finding the price of one and rounding.",
      traps: ["A: 96 divided by 4.", "B: the two numbers combined without scaling.", "D: 96 divided by 2."] },
    { code: "GAT-Q-GEO.3", lvl: 3,
      stem: "A rectangular garden 20 m by 12 m has a path 2 m wide running all the way around the INSIDE of its edge. What is the area of the path, in m² ?",
      opts: ["60", "112", "128", "136"], ans: 1,
      why: "The width comes off BOTH ends of each dimension, so the inner rectangle is 16 by 8 = 128 m². The path is 240 − 128 = 112 m².",
      traps: ["A: the width taken off only once per dimension, giving an inner 18 by 10.", "C: the perimeter multiplied by the width — this double-counts the four corners, and here it happens to equal the inner area.", "D: a slip in the subtraction."] },
    { code: "GAT-Q-DAT.5", lvl: 3,
      stem: "The mean of six numbers is 15. Every number is then increased by 4 and the set is doubled. What is the new mean?",
      opts: ["19", "34", "38", "42"], ans: 2,
      why: "Adding 4 to every number lifts the mean to 19. Doubling every number then doubles the mean: 38. Each operation acts on the mean exactly as it acts on the numbers.",
      traps: ["A: only the addition applied.", "B: the doubling applied before the addition.", "D: 4 added after the doubling as well."] },
  ],
};

if (TRICKS.length !== cfg.items.length)
  throw new Error(`${TRICKS.length} tricks for ${cfg.items.length} items`);
cfg.items.forEach((it, i) => { it.trick = TRICKS[i]; });

buildSet(cfg);
console.log("built", cfg.outPaper, "and", cfg.outKey);
