// ---------------------------------------------------------------------------
// SAT + GAT combined worksheet — GRADE 11, WEEK 2.
// Anchor: 5-3 Graphing Radical Functions and 5-4 Solving Radical Equations.
// Revisit: 5-2 properties of exponents and radicals, met in Week 1.
// Seed: rational exponents, equivalent expressions, quadratics and circle
// geometry — all SAT Advanced Math, none of it yet reached in the syllabus.
// Four full pages of questions, no preamble. See spec §18.
// ---------------------------------------------------------------------------
const { buildSet } = require("./exam_engine");

const TRICKS = [
  // ---- SAT, in item order
  "square both sides, then CHECK — squaring can invent a solution that is not there",
  "an extraneous root is not a mistake; it is the method's own by-product",
  "a square root needs its inside non-negative — that is the whole domain",
  "a radical graph starts at the point where the inside is zero",
  "a fractional exponent is a root: the bottom is the root, the top is the power",
  "simplify each radical to the same surd before adding; unlike surds never combine",
  "multiplying powers of the same base ADDS the exponents",
  "a cube root of a negative is negative — unlike a square root",
  "isolate the radical before squaring, or the square undoes nothing",
  "take off what is already there BEFORE dividing by the rate",
  "expand both brackets before collecting anything",
  "a percentage change always divides by the STARTING value",
  "the median ignores how extreme an outlier is; the mean does not",
  "the angle in a semicircle is a right angle",
  "write a circle equation in completed-square form to read the centre",
  "name the sides relative to the angle BEFORE choosing a ratio",
  "lengths scale by k, areas by k squared, volumes by k cubed",
  "rationalise by multiplying top and bottom by the same surd",
  "undo a fractional exponent by raising to its reciprocal",
  // ---- GAT, in item order
  "a percentage of a percentage multiplies, it does not add",
  "work back to the WHOLE before taking a new percentage of it",
  "the square root of a decimal below 1 is BIGGER than the decimal",
  "make the bases match before comparing powers",
  "units digits run in a cycle of four — divide the exponent by 4",
  "square the whole expression: (x + 1/x)² gives x² + 1/x² + 2",
  "the sum of the roots is −b/a; no factorising needed",
  "an absolute value opens into TWO equations",
  "successive discounts multiply what is LEFT; they never add",
  "angles on a straight line add to 180° — collect and solve once",
  "the angle at the centre is twice the angle at the circumference",
  "shaded = whole minus the pieces removed; leave π alone",
  "similar figures scale by a RATIO, never by a difference",
  "a weighted mean is not the mean of the means",
  "in a two-way table the denominator is the row the question names",
  "'at least one' is 1 minus the probability of none",
  "average speed over equal distances is not the average of the speeds",
  "add the RATES, never the times",
  "convert to the same unit BEFORE comparing",
  "work with the remainder alone — the number itself never matters",
  "neither = total − (A + B − both); the overlap comes off once",
  "chain ratios by matching the shared term, not by taking the outer numbers",
  "consecutive numbers cluster round their mean — find the mean first",
  "a mean question is a TOTAL question; work in totals and subtract",
];

const cfg = {
  mathIndex: "math_sg/_index.json",
  figIndex: "figs_sg/_index.json",
  examName: "SAT and GAT worksheet",
  targets: { "SAT-ALG": "~17.5%", "SAT-ADV": "~17.5%", "SAT-PSD": "~7.5%",
             "SAT-GEO": "~7.5%", "GAT-Q-ARI": "~18%", "GAT-Q-ALG": "~9%",
             "GAT-Q-GEO": "~9%", "GAT-Q-DAT": "~9%", "GAT-Q-LOG": "~5%" },
  dense: true, itemGap: 40, bare: true, optScale: 1,
  weekLine: "Week 2 · Semester 1, 2026–27",
  headerLine: "Grade 11 · Week 2 · SAT (pages 1–2) and GAT Qudurat (pages 3–4) · aligned to 5-3 Graphing Radical Functions and 5-4 Solving Radical Equations",
  paperTitle: "SAT and GAT Worksheet — Grade 11, Week 2",
  paperSub: "45 questions · Section 1 SAT (calculator) · Section 2 GAT (no calculator)",
  keyTitle: "Grade 11 Week 2 — Answer Key and Error Analysis",
  keySub: "For Mr Malek Thiab. 50 minutes total: 25 on each section. The extraneous-root items are the ones to work through on the board.",
  outPaper: "SATGAT_Gr11_W2_Paper.docx",
  outKey: "SATGAT_Gr11_W2_Key.docx",
  timing: "50 minutes",
  calculator: "Section 1 yes · Section 2 no",
  marking: "One mark each, no penalty for a wrong answer",
  budgetNote: "45 items — 21 SAT and 24 GAT. Targets are the published weights HALVED, because each exam is half this paper.",
  sourceNote: "Every item was written for this worksheet. The SAT half follows the College Board's published domain weights for the digital SAT; the GAT half follows the ETEC / Qiyas framework in the GAT and SAAT Classification Map. No leaked or circulated exam questions are used.",
  followUp: [
    ["34 or more", "Secure at this level. Move to full timed sections; the ceiling is pace."],
    ["26 to 33", "The mechanics are sound. Re-mark counting only the items where a solution had to be CHECKED — that is where radical equations are won or lost."],
    ["18 to 25", "Expected at this point in Topic 5. Re-run the SAT half alone before adding anything."],
    ["Below 18", "Fix one idea first: squaring both sides can create a root that does not satisfy the original equation. Everything else follows from taking that seriously."],
    ["Whole class", "Any item where more than half the class chose the same wrong option is a teaching point — the trick column says what to put on the board."],
  ],
  items: [
    // ================================================ SECTION 1 — SAT
    { code: "SAT-ADV.1", lvl: 2,
      sec: { title: "SECTION 1 — SAT", note: "21 questions · calculator allowed · 25 minutes" },
      stem: "Solve for x.", stemEq: "c_rad1",
      opts: ["17", "23", "26", "49"], ans: 1,
      why: "Square both sides: 2x + 3 = 49, so 2x = 46 and x = 23. Checking, √49 = 7 — the solution is genuine.",
      traps: ["A: 7 squared taken as 40.", "C: 49 + 3 halved.", "D: the square of the right-hand side given as x."] },
    { code: "SAT-ADV.2", lvl: 3, stem: "How many solutions does the equation have?", stemEq: "c_rad2",
      opts: ["none", "exactly one", "exactly two", "infinitely many"], ans: 1,
      why: "Squaring gives x + 7 = x² − 10x + 25, so x² − 11x + 18 = 0 and x = 2 or x = 9. Check both in the ORIGINAL: at x = 2 the right side is −3, and a square root is never negative, so x = 2 is extraneous. Only x = 9 survives.",
      traps: ["A: both roots rejected.", "C: both roots accepted without checking — the error the item exists to catch.", "D: the equation read as an identity."] },
    { code: "SAT-ADV.3", lvl: 2, stem: "What is the domain of the function?", stemEq: "c_dom",
      opts: [{ eq: "o_xge0" }, { eq: "o_xge3" }, { eq: "o_xle3" }, "all real numbers"], ans: 1,
      why: "The inside must be non-negative: 3x − 9 ≥ 0, so x ≥ 3.",
      traps: ["A: the condition applied to x rather than to 3x − 9.", "C: the inequality reversed.", "D: the restriction ignored."] },
    { code: "SAT-ADV.4", lvl: 3, stem: "What is the starting point of the graph?", stemEq: "c_shift",
      opts: [{ eq: "o_p41" }, { eq: "o_pm41" }, { eq: "o_p4m1" }, { eq: "o_p14" }], ans: 0,
      why: "The graph begins where the inside of the root is zero, at x = 4, and the + 1 outside lifts it to y = 1. So it starts at (4, 1).",
      traps: ["B: the sign inside the root not flipped.", "C: the outside constant sign-flipped.", "D: the coordinates swapped."] },
    { code: "SAT-ADV.5", lvl: 2, stem: "Evaluate.", stemEq: "c_ratexp",
      opts: ["6", "9", "18", "54"], ans: 1,
      why: "The denominator is the root and the numerator is the power: the cube root of 27 is 3, and 3² = 9. Take the root first and the numbers stay small.",
      traps: ["A: 27 divided by 3 then halved.", "C: the power taken before the root and mis-rooted.", "D: 27 doubled."] },
    { code: "SAT-ADV.6", lvl: 2, stem: "Simplify.", stemEq: "c_simp",
      opts: [{ eq: "c_o_r3" }, { eq: "c_o_r1" }, { eq: "c_o_r2" }, { eq: "c_o_r4" }], ans: 2,
      why: "√50 = 5√2 and √18 = 3√2. Both are now the same surd, so they add: 8√2.",
      traps: ["A: only one term simplified.", "B: the coefficients subtracted.", "D: the two numbers added under one root — unlike surds do not combine that way."] },
    { code: "SAT-ADV.7", lvl: 2, stem: "Simplify.", stemEq: "c_expr",
      opts: [{ eq: "o_x" }, { eq: "o_x2" }, { eq: "o_sqx" }, { eq: "o_one" }], ans: 0,
      why: "Multiplying powers of the same base adds the exponents: ½ + 3/2 = 2, giving x². Dividing then subtracts 1, leaving x.",
      traps: ["B: the division forgotten.", "C: the exponents averaged.", "D: the exponents cancelled to zero."] },
    { code: "SAT-ADV.8", lvl: 2, stem: "Evaluate.", stemEq: "c_cube",
      opts: ["−4", "4", "−8", "not a real number"], ans: 0,
      why: "A cube root of a negative IS real and negative: (−4)³ = −64. Only even roots of negatives fail.",
      traps: ["B: the sign dropped.", "C: 64 halved.", "D: the rule for square roots applied to a cube root."] },
    { code: "SAT-ADV.9", lvl: 3,
      stem: "Which value of x satisfies the equation?", stemEq: "s_rad11",
      opts: ["−1", "4", "both −1 and 4", "neither"], ans: 0,
      why: "Isolate first: √(x + 5) = x + 3. Squaring gives x + 5 = x² + 6x + 9, so x² + 5x + 4 = 0 and x = −1 or x = −4. Checking in the original, x = −1 works and x = −4 does not, since the right side would be negative.",
      traps: ["B: a value never produced by the algebra.", "C: both roots accepted without checking.", "D: the genuine root rejected too."] },
    { code: "SAT-ALG.2", lvl: 3,
      stem: "A pool is filled at 15 litres per minute. It already holds 200 litres and its capacity is 950 litres. How many minutes until it is full?",
      opts: ["45", "50", "63", "77"], ans: 1,
      why: "750 litres remain, and 750 ÷ 15 = 50 minutes. Take off what is already there before dividing.",
      traps: ["A: a rounding of the wrong remainder.", "C: 950 divided by 15 with the 200 ignored.", "D: the two volumes added."] },
    { code: "SAT-ALG.3", lvl: 2,
      stem: "What is the value of x ?", stemEq: "s_brk11",
      opts: ["2", "11", "18", "22"], ans: 3,
      why: "3x − 12 = 2x + 10, so x = 22.",
      traps: ["A: the brackets not expanded.", "B: the constants added instead of moved.", "C: a sign error on the 12."] },
    { code: "SAT-PSD.1", lvl: 3,
      stem: "A price falls from 250 SAR to 200 SAR. By what percentage did it fall?",
      opts: ["16.7%", "20%", "25%", "50%"], ans: 1,
      why: "The fall is 50, measured against the STARTING value: 50/250 = 20%.",
      traps: ["A: divided by 300.", "C: divided by 200, the finishing value.", "D: the raw difference read as a percentage."] },
    { code: "SAT-PSD.2", lvl: 3,
      stem: "The values are 8, 9, 10, 11 and 62. Which statement is true?",
      opts: ["the mean is smaller than the median", "the mean and median are equal", "the mean is larger than the median", "the mode is the best summary"], ans: 2,
      why: "The median is 10; the mean is 100/5 = 20. One extreme value pulls the mean up and leaves the median alone.",
      traps: ["A: the direction reversed.", "B: the outlier assumed not to matter.", "D: there is no repeated value, so no mode."] },
    { code: "SAT-GEO.1", lvl: 3,
      stem: "A triangle is inscribed in a circle with one side as the diameter. What is the angle opposite that side?",
      opts: ["45°", "60°", "90°", "it cannot be determined"], ans: 2,
      why: "The angle in a semicircle is a right angle — one of the few circle facts the SAT expects outright.",
      traps: ["A: a guess from symmetry.", "B: the equilateral case assumed.", "D: the theorem not recognised."] },
    { code: "SAT-GEO.2", lvl: 3,
      stem: "What is the centre of the circle?", stemEq: "s_circ11",
      opts: [{ eq: "o_c3m2" }, { eq: "o_cm32" }, { eq: "o_c6m4" }, { eq: "o_cm64" }], ans: 0,
      why: "Complete the square: (x − 3)² + (y + 2)² = 25. The centre is (3, −2) — each sign flips from the bracket.",
      traps: ["B: both signs left unflipped.", "C: the coefficients halved but not signed.", "D: neither halved nor signed."] },
    { code: "SAT-GEO.3", lvl: 2,
      stem: "In a right triangle the side opposite an angle is 7 and the hypotenuse is 25. What is the sine of that angle?",
      opts: [{ eq: "f_724" }, { eq: "f_725" }, { eq: "f_2425" }, { eq: "f_257" }], ans: 1,
      why: "Sine is opposite over hypotenuse: 7/25. Naming the sides relative to the angle first is what prevents the wrong ratio.",
      traps: ["A: the tangent.", "C: the cosine.", "D: the ratio inverted."] },
    { code: "SAT-GEO.4", lvl: 3,
      stem: "Two similar cylinders have radii in the ratio 2 : 3. What is the ratio of their volumes?",
      opts: ["2 : 3", "4 : 9", "6 : 9", "8 : 27"], ans: 3,
      why: "Lengths scale by k, areas by k² and volumes by k³. Here 2³ : 3³ = 8 : 27.",
      traps: ["A: the length ratio reused.", "B: the area ratio.", "C: the ratio simply doubled."] },

    { code: "SAT-ADV.10", lvl: 3, stem: "Simplify.", stemEq: "c_rat",
      opts: [{ eq: "c_o_t3" }, { eq: "c_o_t1" }, { eq: "c_o_t2" }, { eq: "c_o_t4" }], ans: 1,
      why: "Multiply top and bottom by √3: 6√3 / 3 = 2√3. Rationalising removes the root from the denominator without changing the value.",
      traps: ["A: the 6 divided by 3 twice.", "C: only the numerator multiplied.", "D: the denominator left in place."] },
    { code: "SAT-ADV.11", lvl: 3, stem: "Solve for x.", stemEq: "c_x32",
      opts: ["3", "6", "9", "81"], ans: 2,
      why: "Raise both sides to the power 2/3: x = 27^(2/3) = (∛27)² = 9.",
      traps: ["A: the cube root of 27 given as the answer.", "B: 27 divided by 4.5.", "D: 27 raised to 3/2 instead."] },

    // ================================================ SECTION 2 — GAT
    { code: "GAT-Q-ARI.3", lvl: 3,
      sec: { newPage: true, title: "SECTION 2 — GAT (Qudurat)",
             note: "24 questions · NO calculator · 25 minutes" },
      stem: "What is 25% of 80% of 300 ?",
      opts: ["45", "60", "75", "105"], ans: 1,
      why: "80% of 300 is 240, and 25% of 240 is 60. The percentages multiply: 0.25 × 0.80 = 0.20, and 20% of 300 is 60.",
      traps: ["A: 15% of 300.", "C: 25% of 300.", "D: the percentages added."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "45% of a number is 90. What is 30% of the same number?",
      opts: ["45", "54", "60", "66"], ans: 2,
      why: "The number is 90 ÷ 0.45 = 200, and 30% of 200 is 60. Return to the whole before taking a new percentage.",
      traps: ["A: half of 90.", "B: 60% of 90.", "D: a guess between the values."] },
    { code: "GAT-Q-ARI.4", lvl: 2, stem: "Evaluate", stemEq: "a_root",
      opts: ["0.05", "0.5", "2.5", "5"], ans: 1,
      why: "0.5 × 0.5 = 0.25, so the root is 0.5. Rooting a number below 1 makes it LARGER.",
      traps: ["A: the digits halved and the decimal kept.", "C: the point moved the wrong way.", "D: the point dropped."] },
    { code: "GAT-Q-ARI.4", lvl: 3, stem: "Which quantity is greater?", stemEq: "g_cmp230", k: 1.05,
      opts: ["A is greater", "B is greater", "they are equal", "not enough information"], ans: 1,
      why: "Match the exponents: 2³⁰ = 8¹⁰ and 3²⁰ = 9¹⁰, so B is greater.",
      traps: ["A: the larger exponent assumed to win.", "C: both read as simply enormous.", "D: both are fully determined."] },
    { code: "GAT-Q-ARI.5", lvl: 3, stem: "What is the units digit of the number below?", stemEq: "a_pow",
      opts: ["1", "3", "7", "9"], ans: 1,
      why: "Powers of 3 cycle 3, 9, 7, 1. 17 leaves remainder 1 on division by 4, so the units digit is 3.",
      traps: ["A: remainder taken as 0.", "C: remainder taken as 3.", "D: remainder taken as 2."] },
    { code: "GAT-Q-ALG.4", lvl: 3, stem: "If", stemEq: "g_recipx",
      opts: ["21", "23", "25", "27"], ans: 1,
      why: "Squaring: x² + 2 + 1/x² = 25, so x² + 1/x² = 23. The value of x is never needed.",
      traps: ["A: 4 subtracted instead of 2.", "C: the middle term forgotten.", "D: 2 added rather than subtracted."],
      note: "what is the value of x² + 1/x² ?" },
    { code: "GAT-Q-ALG.3", lvl: 3, stem: "What is the sum of the roots?", stemEq: "g_quadr",
      opts: ["5", "7", "10", "17"], ans: 1,
      why: "The sum of the roots is −b/a = 7. Factorising to (x − 2)(x − 5) confirms it but is slower.",
      traps: ["A: one root.", "C: the product of the roots.", "D: the coefficients added."] },
    { code: "GAT-Q-ALG.1", lvl: 3,
      stem: "What is the sum of the solutions?", stemEq: "s_abs11",
      opts: ["−3", "0", "4", "11"], ans: 0,
      why: "2x + 3 = 11 gives x = 4, and 2x + 3 = −11 gives x = −7. Their sum is −3.",
      traps: ["B: the two solutions assumed to cancel.", "C: only the positive branch taken.", "D: the 11 copied back."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "A price is cut by 30%, then the reduced price is cut by a further 10%. What is the overall reduction?",
      opts: ["37%", "40%", "43%", "45%"], ans: 0,
      why: "0.70 × 0.90 = 0.63, so 63% remains and 37% has gone. Discounts multiply what is LEFT.",
      traps: ["B: the two discounts added.", "C: a guess above the added figure.", "D: the discounts added and inflated."] },
    { code: "GAT-Q-GEO.1", lvl: 3,
      stem: "Three angles on a straight line are (x)°, (2x + 15)° and (x + 25)°. What is the value of x ?",
      opts: ["25", "35", "40", "45"], ans: 1,
      why: "4x + 40 = 180, so x = 35.",
      traps: ["A: the constants dropped.", "C: the angles assumed to total 200°.", "D: the angles assumed to total 220°."] },
    { code: "GAT-Q-GEO.4", lvl: 3,
      stem: "An angle at the circumference of a circle measures 35°. What is the angle at the centre on the same arc?",
      opts: ["17.5°", "35°", "70°", "145°"], ans: 2,
      why: "The angle at the centre is twice the angle at the circumference: 70°.",
      traps: ["A: the relationship applied backwards.", "B: the two assumed equal.", "D: the supplement taken."] },
    { code: "GAT-Q-GEO.3", lvl: 3,
      stem: "A circle of radius 5 cm is inscribed in a square. What area of the square lies outside the circle, in cm² ?",
      opts: [{ eq: "g_o_sh1" }, { eq: "g_o_sh2" }, { eq: "g_o_sh3" }, { eq: "g_o_sh4" }], ans: 0,
      why: "The square has side 10 and area 100; the circle has area 25π. The region outside is 100 − 25π.",
      traps: ["B: the radius used as the side.", "C: the circumference subtracted.", "D: the circle's area given instead."] },
    { code: "GAT-Q-GEO.2", lvl: 3,
      stem: "Two similar rectangles have areas 27 cm² and 75 cm². The smaller has a side of 9 cm. What is the corresponding side of the larger, in cm?",
      opts: ["12", "15", "18", "25"], ans: 1,
      why: "Areas are in the ratio 27 : 75 = 9 : 25, so lengths are in the ratio 3 : 5. Then 9 × 5/3 = 15.",
      traps: ["A: the difference of the areas used.", "C: the areas divided directly.", "D: the area ratio applied to the length."] },
    { code: "GAT-Q-DAT.5", lvl: 3,
      stem: "In a school, 12 students scored a mean of 90 and 18 students scored a mean of 70. What is the mean for all 30 ?",
      opts: ["76", "78", "80", "82"], ans: 1,
      why: "Totals first: 1080 + 1260 = 2340, and 2340/30 = 78. A weighted mean is not the mean of the means.",
      traps: ["A: a guess below the true value.", "C: the mean of 90 and 70.", "D: the larger group under-weighted."] },
    { code: "GAT-Q-DAT.1", lvl: 3,
      stem: "The table shows a survey of 90 people. What percentage of those who exercise daily also sleep 8 hours?",
      table: [["", "Sleeps 8h", "Sleeps less", "Total"], ["Exercises", "27", "18", "45"], ["Does not", "15", "30", "45"], ["Total", "42", "48", "90"]],
      opts: ["30%", "45%", "60%", "64%"], ans: 2,
      why: "Read the Exercises row only: 27 out of 45, which is 60%. The grand total of 90 is not the denominator.",
      traps: ["A: 27 out of 90.", "B: a misread of the column.", "D: 27 out of 42, using the column total."] },
    { code: "GAT-Q-DAT.3", lvl: 3,
      stem: "A fair die is rolled twice. What is the probability of at least one six?",
      opts: [{ eq: "f_16" }, { eq: "f_13" }, { eq: "f_1136" }, { eq: "f_12" }], ans: 2,
      why: "'At least one' is 1 minus 'none': the chance of no six is (5/6)² = 25/36, so the answer is 11/36.",
      traps: ["A: one roll only considered.", "B: the two chances added.", "D: a guess from symmetry."] },
    { code: "GAT-Q-LOG.1", lvl: 3,
      stem: "A cyclist rides 30 km at 15 km/h and returns along the same road at 10 km/h. What is the average speed for the whole ride, in km/h?",
      opts: ["11.5", "12", "12.5", "13"], ans: 1,
      why: "Times are 2 and 3 hours for 60 km, so 60/5 = 12 km/h. More time is spent at the slower speed, so it falls below 12.5.",
      traps: ["A: a guess below the true value.", "C: the mean of 15 and 10 — the trap.", "D: a guess above the mean."] },
    { code: "GAT-Q-LOG.2", lvl: 3,
      stem: "One pipe fills a tank in 3 hours and another fills it in 6 hours. With both open, how long does it take?",
      opts: ["1.5 hours", "2 hours", "4.5 hours", "9 hours"], ans: 1,
      why: "Add the rates: 1/3 + 1/6 = 1/2 of the tank per hour, so 2 hours.",
      traps: ["A: the faster time halved.", "C: the times averaged.", "D: the times added."] },
    { code: "GAT-Q-ARI.2", lvl: 3,
      stem: "A runner covers 3 km in 12 minutes. What is the speed in metres per second?",
      opts: ["3.75", "4.17", "5", "6.25"], ans: 1,
      why: "3000 m in 720 s gives 3000/720 ≈ 4.17 m/s. Convert both quantities before dividing.",
      traps: ["A: minutes treated as seconds in part.", "C: the distance rounded to 3600 m.", "D: 3000 divided by 480."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "When n is divided by 5 the remainder is 4. What is the remainder when 3n + 2 is divided by 5 ?",
      opts: ["0", "2", "4", "14"], ans: 2,
      why: "Work with the remainder alone: 3(4) + 2 = 14, and 14 leaves remainder 4 on division by 5.",
      traps: ["A: 14 taken as divisible.", "B: only the +2 considered.", "D: the unreduced value given."] },
    { code: "GAT-Q-LOG.3", lvl: 3,
      stem: "Of 50 students, 30 study physics, 24 study chemistry and 6 study neither. How many study both?",
      opts: ["8", "10", "12", "14"], ans: 1,
      why: "44 study at least one, so 30 + 24 − both = 44 and both = 10.",
      traps: ["A: a guess below the value.", "C: the 'neither' figure doubled.", "D: the difference of the two subjects."] },
    { code: "GAT-Q-ARI.2", lvl: 3,
      stem: "If a : b = 3 : 4 and b : c = 2 : 5, what is a : c ?",
      opts: ["3 : 10", "3 : 5", "6 : 5", "5 : 6"], ans: 0,
      why: "Match b: a : b = 6 : 8 and b : c = 8 : 20, so a : c = 6 : 20 = 3 : 10.",
      traps: ["B: the outer numbers taken straight.", "C: the ratios multiplied term by term.", "D: the ratio inverted."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "The sum of four consecutive even integers is 92. What is the largest?",
      opts: ["22", "24", "26", "28"], ans: 2,
      why: "Four consecutive even integers average 23, so they are 20, 22, 24 and 26. The largest is 26.",
      traps: ["A: the second of the four.", "B: the third.", "D: one step beyond the set."] },
    { code: "GAT-Q-DAT.5", lvl: 3,
      stem: "The mean of eight numbers is 12. A ninth number is added and the mean becomes 13. What is the ninth number?",
      opts: ["13", "18", "21", "24"], ans: 2,
      why: "Totals: 8 × 12 = 96 and 9 × 13 = 117. The ninth number is 117 − 96 = 21. Go through the totals, never the means.",
      traps: ["A: the new mean given as the number.", "B: a guess between the values.", "D: 96 and 117 mis-subtracted."] },
  ],
};

if (TRICKS.length !== cfg.items.length)
  throw new Error(`${TRICKS.length} tricks for ${cfg.items.length} items`);
cfg.items.forEach((it, i) => { it.trick = TRICKS[i]; });

buildSet(cfg);
console.log("built", cfg.outPaper, "and", cfg.outKey);
