// ---------------------------------------------------------------------------
// SAT + GAT combined worksheet — GRADE 10, WEEK 2.
// Four pages: two of SAT, two of GAT, split by a section band on a fresh page.
//
// COVERAGE IS SPIRAL, not local. The week's lesson (1-1 Key Features of
// Functions) is the ANCHOR — vertex, zeros, range, intervals of increase — but
// it is only part of the paper. SAT and GAT do not wait for the syllabus, so
// this set also SEEDS topics not yet taught: inequalities, absolute value,
// exponential growth, and the domain of a radical (which Grade 11 meets in
// Topic 5). Nothing here is chosen locally; it comes off the term coverage grid.
//
// SAT half follows the College Board digital-SAT domain weights: Algebra ~35%,
// Advanced Math ~35%, Problem-Solving and Data Analysis ~15%, Geometry and
// Trigonometry ~15%. On 12 items that is 4 / 4 / 2 / 2.
// GAT half keeps the paper's own strand mix, as the Grade 12 sets do.
// Every item carries a named trick, printed in the ANSWER KEY only.
// ---------------------------------------------------------------------------
const { buildSet } = require("./exam_engine");

const TRICKS = [
  // ---- SAT
  "constant first differences mean linear — find the step, then step on",
  "the per-unit rate multiplies the variable; the fixed fee stands alone",
  "expand the bracket before collecting — the 3 multiplies both terms",
  "add the two equations to eliminate y in one line",
  "x = −b/2a tells you WHERE the minimum is; substitute to get the value",
  "a zero is the value that makes a bracket zero, so the sign flips",
  "range is what y does, and the vertex is the floor",
  "increasing and decreasing are read left to right along x, never up the y-axis",
  "a percentage increase multiplies by 1 + the rate, in one step",
  "name the width first, write the length in terms of it, then solve once",
  "dividing an inequality by a negative REVERSES it",
  "an absolute value opens into TWO equations — solve both, then answer",
  "vertex form hands you the vertex; the sign inside the bracket flips",
  "a square root needs its inside to be non-negative — that is the whole domain",
  "convert to a per-one rate first, then multiply once",
  "the exponent applies to the BASE only — the coefficient is never raised",
  "a rise then an equal-looking fall does not return you to the start — multiply the factors",
  // ---- GAT
  "a percentage of a percentage multiplies, it does not add",
  "units digits run in a cycle of four — divide the exponent by 4",
  "when the differences are not constant, take the differences of the differences",
  "solve for x first, then answer the question actually asked",
  "(a + b)² = a² + 2ab + b², so a² + b² is one subtraction away",
  "put the angles in one equation: they add to 180°, so solve once",
  "a mean question is a TOTAL question — recover the total before you change it",
  "more machines do not change the time — read the rate per machine",
  "neither = total - (A + B - both); the overlap is subtracted once",
  "square the whole expression: (x + 1/x)² gives x² + 1/x² + 2",
  "make the exponents match before you compare the bases",
  "chain ratios by matching the shared term, not by taking the outer numbers",
  "successive discounts multiply what is LEFT; they never add",
  "average speed over equal distances is not the average of the speeds",
  "add the RATES, never the times",
  "work with the remainder alone — the number itself never matters",
  "an inscribed circle has diameter equal to the side; leave π alone",
  "without replacement changes BOTH the top and the bottom of the second fraction",
  "the sum of the roots is −b/a — no factorising needed",
  "name the angle pair BEFORE calculating; co-interior angles add to 180°",
  "in a two-way table the denominator is the row the question names, not the grand total",
];

const cfg = {
  mathIndex: "math_sg/_index.json",
  figIndex: "figs_sg/_index.json",
  examName: "SAT and GAT worksheet",
  // Each exam is HALF this paper, so every published weight is halved here —
  // otherwise the budget table compares a 12-item section against a whole-paper
  // target and every row reads as a miss.
  targets: { "SAT-ALG": "~17.5%", "SAT-ADV": "~17.5%", "SAT-PSD": "~7.5%",
             "SAT-GEO": "~7.5%", "GAT-Q-ARI": "~18%", "GAT-Q-ALG": "~9%",
             "GAT-Q-GEO": "~9%", "GAT-Q-DAT": "~9%", "GAT-Q-LOG": "~5%" },
  dense: true, itemGap: 40, bare: true, optScale: 1,
  weekLine: "Week 2 · Semester 1, 2026–27",
  headerLine: "Grade 10 · Week 2 · SAT (pages 1–2) and GAT Qudurat (pages 3–4) · aligned to 1-1 Key Features of Functions",
  paperTitle: "SAT and GAT Worksheet — Grade 10, Week 2",
  paperSub: "40 questions · Section 1 SAT (calculator) · Section 2 GAT (no calculator)",
  keyTitle: "Grade 10 Week 2 — Answer Key and Error Analysis",
  keySub: "For Mr Malek Thiab. Each item names the trick to say aloud and the error behind every wrong option.",
  outPaper: "SATGAT_Gr10_W2_Paper.docx",
  outKey: "SATGAT_Gr10_W2_Key.docx",
  timing: "40 minutes",
  calculator: "Section 1 yes · Section 2 no",
  marking: "One mark each, no penalty for a wrong answer",
  budgetNote: "40 items — 12 SAT and 12 GAT. Targets are the published weights HALVED, because each exam is half this paper. With 12 items per section the finest step is 8.3%, so a row may sit one item either side.",
  conditions: "Work on the paper itself. Section 1 (SAT) allows a calculator, as the digital SAT does throughout its Math section. Section 2 (GAT) does NOT — no calculator, no phone, no smartwatch. Figures are drawn to scale unless the item says otherwise. If an item passes about 90 seconds, mark it and move on.",
  sourceNote: "Every item was written for this worksheet. The SAT half follows the College Board's published domain weights and skill descriptors for the digital SAT; the GAT half follows the ETEC / Qiyas framework recorded in the GAT and SAAT Classification Map. No leaked or circulated exam questions are used.",
  followUp: [
    ["20 or more", "Secure on both papers. Move to full timed sections; the ceiling now is pace, not content."],
    ["15 to 19", "The single-step work is sound. Re-mark counting only the two-step items — that is the real score, and it is where the next marks are."],
    ["10 to 14", "Expected at this point in the term. Take the weaker SECTION, not the weaker questions, and re-run it before adding anything new."],
    ["Below 10", "Work the SAT half alone first. Two exams at once is the wrong load until the key features of a function are secure."],
    ["Whole class", "Any item where more than half the class chose the same wrong option is a teaching point — the trick column tells you what to say."],
  ],
  items: [
    // ================================================ SECTION 1 — SAT
    { code: "SAT-ALG.1", lvl: 1,
      sec: { title: "SECTION 1 — SAT", note: "19 questions · calculator allowed · 25 minutes" },
      stem: "The table shows values of the linear function f.",
      table: [["x", "0", "1", "2", "3"], ["f(x)", "7", "11", "15", "19"]],
      opts: ["23", "27", "31", "35"], ans: 1,
      why: "The first differences are all 4, so f is linear with step 4 and f(x) = 4x + 7. Then f(5) = 20 + 7 = 27.",
      traps: ["A: f(4), one step short.", "C: f(6), one step too far.", "D: f(7), two steps too far."],
      note: "What is the value of f(5) ?" },
    { code: "SAT-ALG.2", lvl: 1,
      stem: "A mobile plan costs 45 SAR per month plus 0.30 SAR for each minute of calls. Which equation gives the total monthly cost C, in SAR, for m minutes?",
      opts: [{ eq: "o_c1" }, { eq: "o_c2" }, { eq: "o_c3" }, { eq: "o_c4" }], ans: 1,
      why: "The 0.30 SAR is charged per minute, so it multiplies m. The 45 SAR is charged once, so it stands alone: C = 0.30m + 45.",
      traps: ["A: the rate and the fixed fee swapped.", "C: the two amounts added into one rate.", "D: the fixed fee brought inside the bracket, charging it per minute."] },
    { code: "SAT-ALG.3", lvl: 2, stem: "Solve for x.", stemEq: "a_lin1",
      opts: ["4", "8", "11", "16"], ans: 2,
      why: "6x - 15 = 4x + 7, so 2x = 22 and x = 11.",
      traps: ["A: only the 2x multiplied by 3.", "B: 15 added to the wrong side.", "D: the 15 and 7 added rather than moved."] },
    { code: "SAT-ALG.4", lvl: 2, stem: "In the system below, what is the value of y ?", stemEq: "a_sys",
      opts: ["5", "6", "7", "9"], ans: 2,
      why: "Adding the two equations eliminates y: 3x = 15, so x = 5 and y = 12 - 5 = 7.",
      traps: ["A: the value of x reported instead of y.", "B: half of 12.", "D: the equations subtracted rather than added."] },
    { code: "SAT-ADV.1", lvl: 2, stem: "What is the minimum value of f ?", stemEq: "a_quad",
      opts: ["−4", "−3", "3", "5"], ans: 0,
      why: "The minimum sits at x = −b/2a = 6/2 = 3. Substituting, f(3) = 9 − 18 + 5 = −4. The question asks for the VALUE, not where it happens.",
      traps: ["B: the constant term sign-flipped.", "C: x = 3, where the minimum is rather than what it is — the commonest error on this item.", "D: f(0), the y-intercept."] },
    { code: "SAT-ADV.2", lvl: 1, stem: "For which values of x is f(x) = 0 ?", stemEq: "a_fact",
      opts: [{ eq: "o_z1" }, { eq: "o_z2" }, { eq: "o_z3" }, { eq: "o_z4" }], ans: 1,
      why: "A product is zero when a factor is zero: x - 2 = 0 gives x = 2, and x + 5 = 0 gives x = -5. Each sign flips.",
      traps: ["A: both signs copied straight from the brackets.", "C: signs ignored entirely.", "D: both signs flipped the same way."] },
    { code: "SAT-ADV.3", lvl: 2, stem: "The graph of y = f(x) is shown. What is the range of f ?",
      fig: "g10w2_graph", figW: 1.9,
      opts: [{ eq: "o_yge4" }, { eq: "o_yle4" }, { eq: "o_yge1" }, "all real numbers"], ans: 0,
      why: "The curve turns at its lowest point, (1, -4), and rises on both sides. So y takes every value from -4 upwards.",
      traps: ["B: the inequality reversed.", "C: the x-coordinate of the vertex used instead of the y-coordinate — range is about y.", "D: the domain given instead of the range."] },
    { code: "SAT-ADV.4", lvl: 2, // The graph is printed once, on the item above. Repeating it cost a third of
      // a page and taught nothing — the stem already sends the student back to it.
      stem: "For the same graph, on which interval is f increasing?",
      opts: [{ eq: "o_xlt1" }, { eq: "o_xgt1" }, { eq: "o_ygtm4" }, { eq: "o_m1x3" }], ans: 1,
      why: "Read left to right: the curve falls until x = 1 and rises after it. So f is increasing for x > 1.",
      traps: ["A: the decreasing interval.", "C: an interval written in y — intervals of increase are always in x.", "D: the interval between the x-intercepts, where the curve is below the axis."] },
    { code: "SAT-PSD.1", lvl: 1,
      stem: "A shop increases the price of an item from 240 SAR by 15%. What is the new price, in SAR?",
      opts: ["255", "276", "288", "360"], ans: 1,
      why: "An increase of 15% multiplies by 1.15: 240 × 1.15 = 276.",
      traps: ["A: 15 added rather than 15%.", "C: 20% taken instead of 15%.", "D: 150% of 240."] },
    { code: "SAT-GEO.1", lvl: 2,
      stem: "A rectangle has perimeter 36 cm and its length is twice its width. What is its area, in cm² ?",
      opts: ["36", "54", "72", "81"], ans: 2,
      why: "Let the width be w. Then 2(w + 2w) = 36, so 6w = 36 and w = 6, length 12. Area = 6 × 12 = 72.",
      traps: ["A: the perimeter reused as the area.", "B: width and length taken as 6 and 9.", "D: the rectangle treated as a square of side 9."] },
    { code: "SAT-ALG.5", lvl: 2, stem: "Solve the inequality.", stemEq: "a_ineq",
      opts: [{ eq: "o_xltm4" }, { eq: "o_xgtm4" }, { eq: "o_xlt4" }, { eq: "o_xgt4" }], ans: 0,
      why: "−3x > 12. Dividing by −3 reverses the inequality: x < −4.",
      traps: ["B: the sign not reversed — the single commonest error on inequalities.", "C: the negative dropped from the 4.", "D: both the sign and the negative mishandled."] },
    { code: "SAT-ALG.6", lvl: 3, stem: "What is the sum of the solutions?", stemEq: "a_abs",
      opts: ["2", "5", "7", "9"], ans: 1,
      why: "An absolute value opens into two equations: 2x − 5 = 9 gives x = 7, and 2x − 5 = −9 gives x = −2. Their sum is 5.",
      traps: ["A: only the negative branch taken.", "C: only the positive branch taken — the branch students stop at.", "D: the 9 copied straight back."] },
    { code: "SAT-ADV.5", lvl: 2, stem: "What is the minimum value of f ?", stemEq: "a_vertex",
      opts: ["−8", "−3", "3", "8"], ans: 0,
      why: "Vertex form gives the vertex directly: the squared term is smallest at x = 3, where it is 0, leaving f(3) = −8.",
      traps: ["B: the 3 sign-flipped and read as the value.", "C: x = 3, where the minimum happens rather than what it is.", "D: the sign of the constant lost."] },
    { code: "SAT-ADV.6", lvl: 3, stem: "What is the domain of f ?", stemEq: "a_domrad",
      opts: [{ eq: "o_xge0" }, { eq: "o_xge4" }, { eq: "o_xle4" }, "all real numbers"], ans: 1,
      why: "A square root needs a non-negative inside: x − 4 ≥ 0, so x ≥ 4. The domain is where the function is allowed to exist, not where it is positive.",
      traps: ["A: the condition applied to x rather than to x − 4.", "C: the inequality reversed.", "D: the restriction ignored."] },
    { code: "SAT-PSD.3", lvl: 2,
      stem: "A car uses 8 litres of fuel per 100 km. How many litres does it use on a 350 km journey from Jeddah to Taif?",
      opts: ["22.4", "28", "32", "43.75"], ans: 1,
      why: "8 litres per 100 km is 0.08 litres per km, and 0.08 × 350 = 28.",
      traps: ["A: 350 divided by 100 then multiplied by 6.4.", "C: rounded up from a wrong rate.", "D: 350 divided by 8 — the rate inverted."] },

    { code: "SAT-ADV.7", lvl: 2, stem: "What is the value of f(4) ?", stemEq: "a_expo",
      opts: ["24", "48", "81", "96"], ans: 1,
      why: "The exponent applies to the base only: 2⁴ = 16, then 3 × 16 = 48. The 3 is never raised to the power.",
      traps: ["A: 3 × 2 × 4.", "C: 3⁴, the coefficient raised instead of the base.", "D: 2⁵ × 3, one power too many."] },
    { code: "SAT-PSD.2", lvl: 3,
      stem: "A quantity increases by 25% and the new value then decreases by 20%. What is the overall change?",
      opts: ["5% decrease", "no change", "5% increase", "45% increase"], ans: 1,
      why: "1.25 × 0.80 = 1.00 exactly, so the quantity returns to where it started. The fall is 20% of the RAISED value, which is larger than 20% of the original — and here the two effects cancel exactly.",
      traps: ["A: the percentages subtracted.", "C: the direction guessed from the larger percentage.", "D: the percentages added."] },

    // ================================================ SECTION 2 — GAT
    { code: "GAT-Q-ARI.3", lvl: 2,
      sec: { newPage: true, title: "SECTION 2 — GAT (Qudurat)",
             note: "21 questions · NO calculator · 25 minutes" },
      stem: "What is 20% of 60% of 400 ?",
      opts: ["24", "48", "72", "320"], ans: 1,
      why: "60% of 400 is 240, and 20% of 240 is 48. Percentages of percentages multiply: 0.20 × 0.60 = 0.12, and 12% of 400 is 48.",
      traps: ["A: 20% of 120.", "C: the percentages added to 80% and then halved.", "D: 80% of 400 — the percentages added."] },
    { code: "GAT-Q-ARI.5", lvl: 3, stem: "What is the units digit of the number below?", stemEq: "a_pow",
      opts: ["1", "3", "7", "9"], ans: 1,
      why: "The units digits of powers of 3 cycle 3, 9, 7, 1 and repeat every four. 17 ÷ 4 leaves remainder 1, so the units digit is the first in the cycle: 3.",
      traps: ["A: remainder taken as 0.", "C: remainder taken as 3.", "D: remainder taken as 2."] },
    { code: "GAT-Q-ARI.5", lvl: 3,
      stem: "What is the next term of the sequence 2, 6, 12, 20, 30, … ?",
      opts: ["36", "40", "42", "46"], ans: 2,
      why: "The differences are 4, 6, 8, 10 — rising by 2 each time. The next difference is 12, so the next term is 30 + 12 = 42.",
      traps: ["A: the last difference repeated.", "B: the differences assumed constant at 10.", "D: the difference taken as 16."] },
    { code: "GAT-Q-ALG.1", lvl: 2, stem: "If", stemEq: "a_div4",
      opts: ["16", "64", "128", "256"], ans: 3,
      why: "x = 16, so x² = 256. The question asks for x², not x — the extra step is the whole item.",
      traps: ["A: x reported instead of x².", "B: 4³, the wrong operation on 4.", "C: 16 × 8."],
      note: "what is the value of x² ?" },
    { code: "GAT-Q-ALG.4", lvl: 3, stem: "If", stemEq: "a_ident",
      opts: ["19", "29", "39", "49"], ans: 1,
      why: "(a + b)² = a² + 2ab + b², so 49 = a² + b² + 20 and a² + b² = 29. There is no need to find a and b at all.",
      traps: ["A: 10 subtracted once instead of twice.", "C: 10 added rather than 20 subtracted.", "D: the identity ignored and 49 given straight back."],
      note: "what is the value of a² + b² ?" },
    { code: "GAT-Q-GEO.2", lvl: 2,
      stem: "The three angles of a triangle are in the ratio 2 : 3 : 4. What is the largest angle, in degrees?",
      opts: ["40", "60", "80", "100"], ans: 2,
      why: "The parts total 9, and the angles total 180°, so one part is 20°. The largest is 4 × 20 = 80°.",
      traps: ["A: the smallest angle.", "B: the middle angle.", "D: the angles assumed to total 225°."] },
    { code: "GAT-Q-DAT.5", lvl: 3,
      stem: "The mean of five numbers is 14. One of the numbers, 20, is removed. What is the mean of the remaining four?",
      opts: ["11", "12.5", "13", "14"], ans: 1,
      why: "The total was 5 × 14 = 70. Removing 20 leaves 50, and 50 ÷ 4 = 12.5. Means cannot be adjusted directly — go through the total.",
      traps: ["A: 20 subtracted from 14 and divided.", "C: the total divided by 5 rather than 4.", "D: the mean assumed unchanged."] },
    { code: "GAT-Q-LOG.2", lvl: 3,
      stem: "If 6 machines make 6 items in 6 minutes, how long do 30 machines take to make 30 items?",
      opts: ["1 minute", "5 minutes", "6 minutes", "30 minutes"], ans: 2,
      why: "One machine makes one item in 6 minutes. Thirty machines working at the same time make thirty items in the same 6 minutes — the rate per machine has not changed.",
      traps: ["A: the numbers divided.", "B: the numbers scaled by 6.", "D: the number in the question copied — the answer the item is designed to attract."] },
    { code: "GAT-Q-LOG.3", lvl: 3,
      stem: "In a class of 30 students, 18 play football and 15 play basketball. If 8 play both, how many play neither?",
      opts: ["3", "5", "7", "10"], ans: 1,
      why: "Playing at least one sport: 18 + 15 - 8 = 25. So 30 - 25 = 5 play neither. The overlap is subtracted once, because it was counted twice.",
      traps: ["A: the overlap subtracted twice.", "C: the overlap not subtracted at all.", "D: 18 and 15 assumed to have no overlap."] },
    { code: "GAT-Q-ALG.4", lvl: 3, stem: "If", stemEq: "g_recipx",
      opts: ["21", "23", "25", "27"], ans: 1,
      why: "Square both sides: (x + 1/x)² = x² + 2 + 1/x² = 25, so x² + 1/x² = 23. There is no need to find x.",
      traps: ["A: 4 subtracted instead of 2.", "C: the squaring done but the middle term forgotten.", "D: 2 added rather than subtracted."],
      note: "what is the value of x² + 1/x² ?" },
    { code: "GAT-Q-ARI.4", lvl: 3, stem: "Which quantity is greater?", stemEq: "g_cmp230", k: 1.05,
      opts: ["A is greater", "B is greater", "they are equal", "not enough information"], ans: 1,
      why: "Make the exponents match: 2³⁰ = (2³)¹⁰ = 8¹⁰ and 3²⁰ = (3²)¹⁰ = 9¹⁰. Since 9 > 8, B is greater.",
      traps: ["A: the larger exponent assumed to win.", "C: both read as simply enormous.", "D: both values are fully determined."] },
    { code: "GAT-Q-ARI.2", lvl: 3,
      stem: "If a : b = 2 : 3 and b : c = 4 : 5, what is a : c ?",
      opts: ["8 : 15", "2 : 5", "3 : 10", "5 : 6"], ans: 0,
      why: "Match b: a : b = 8 : 12 and b : c = 12 : 15. So a : c = 8 : 15.",
      traps: ["B: the outer numbers taken straight.", "C: the ratios divided.", "D: the inner numbers taken straight."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "A price is reduced by 20%, then the reduced price is cut by a further 25%. What is the overall reduction?",
      opts: ["40%", "45%", "50%", "55%"], ans: 0,
      why: "0.80 × 0.75 = 0.60, so 60% of the price remains and 40% has gone. Discounts multiply what is LEFT; they do not add.",
      traps: ["B: the two discounts added.", "C: rounded up from the added figure.", "D: the discounts added and then inflated."] },
    { code: "GAT-Q-LOG.1", lvl: 3,
      stem: "A bus travels from a town to a village at 60 km/h and returns along the same road at 40 km/h. What is its average speed for the whole journey, in km/h?",
      opts: ["45", "48", "50", "52"], ans: 1,
      why: "Average speed is total distance over total time. For equal distances it is 2(60)(40)/(60 + 40) = 48. More time is spent at the slower speed, so the answer must fall below 50.",
      traps: ["A: a guess below the true value.", "C: the mean of 60 and 40 — the trap the item is built on.", "D: a guess above the mean."] },
    { code: "GAT-Q-LOG.2", lvl: 3,
      stem: "One worker paints a wall in 6 hours and another paints the same wall in 12 hours. Working together, how many hours do they take?",
      opts: ["3", "4", "6", "9"], ans: 1,
      why: "Add the RATES, not the times: 1/6 + 1/12 = 3/12 = 1/4 of the wall each hour, so 4 hours.",
      traps: ["A: the times halved.", "C: the faster worker's time reused.", "D: the mean of 6 and 12."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "When n is divided by 7 the remainder is 3. What is the remainder when 2n + 1 is divided by 7 ?",
      opts: ["0", "1", "3", "6"], ans: 0,
      why: "Work with the remainder alone: 2(3) + 1 = 7, and 7 leaves remainder 0. The value of n never matters.",
      traps: ["B: the 1 taken as the remainder.", "C: the original remainder copied.", "D: 2 × 3 taken without the +1."] },
    { code: "GAT-Q-GEO.3", lvl: 3,
      stem: "A circle of radius 5 cm is inscribed in a square. What area of the square lies outside the circle, in cm² ?",
      opts: [{ eq: "g_o_sh1" }, { eq: "g_o_sh2" }, { eq: "g_o_sh3" }, { eq: "g_o_sh4" }], ans: 0,
      why: "The circle touches all four sides, so the square has side 10 and area 100. The circle has area 25π. The region outside is 100 − 25π. Leave π alone rather than approximating.",
      traps: ["B: the radius used as the side of the square.", "C: the circumference subtracted instead of the area.", "D: the circle's area given instead of the region outside it."] },
    { code: "GAT-Q-DAT.3", lvl: 3,
      stem: "A bag holds 3 red and 5 blue marbles. Two are drawn without replacement. What is the probability that both are red?",
      opts: [{ eq: "p_o_a" }, { eq: "p_o_b" }, { eq: "p_o_c" }, { eq: "p_o_d" }], ans: 0,
      why: "First red: 3/8. Second red: 2/7, because both the reds and the total have gone down by one. 3/8 × 2/7 = 6/56 = 3/28.",
      traps: ["B: drawn WITH replacement — the trap the words 'without replacement' are testing.", "C: the two fractions added and simplified.", "D: only the first draw considered."] },
    { code: "GAT-Q-ALG.3", lvl: 3, stem: "What is the sum of the roots?", stemEq: "g_quadr",
      opts: ["5", "7", "10", "17"], ans: 1,
      why: "The sum of the roots is −b/a = 7. Factorising to (x − 2)(x − 5) confirms it, but the formula is faster and never needs the roots themselves.",
      traps: ["A: one root given.", "C: the product of the roots.", "D: the two coefficients added."] },
    { code: "GAT-Q-GEO.1", lvl: 3,
      stem: "Two parallel lines are crossed by a transversal. One co-interior angle is (3x + 20)° and the other is (2x + 10)°. What is the value of x ?",
      opts: ["20", "30", "40", "50"], ans: 1,
      why: "Co-interior angles on parallel lines add to 180°: 5x + 30 = 180, so x = 30. Naming the pair first is what prevents the wrong rule.",
      traps: ["A: the angles set equal to each other.", "C: the angles assumed to total 200°.", "D: the angles set equal and then doubled."] },
    { code: "GAT-Q-DAT.1", lvl: 3,
      stem: "The table shows how many students in a year group study each subject. What percentage of the students who study Physics also study Chemistry?",
      table: [["", "Chemistry", "No Chemistry", "Total"], ["Physics", "18", "12", "30"], ["No Physics", "10", "20", "30"], ["Total", "28", "32", "60"]],
      opts: ["30%", "45%", "60%", "64%"], ans: 2,
      why: "Read only the Physics row: 18 of the 30 Physics students also take Chemistry, and 18/30 = 60%. The grand total of 60 is not the denominator here.",
      traps: ["A: 18 out of 60, the grand total used.", "B: a misread of the Chemistry column.", "D: 18 out of 28, the Chemistry column used as the base."] },
  ],
};

if (TRICKS.length !== cfg.items.length)
  throw new Error(`${TRICKS.length} tricks for ${cfg.items.length} items`);
cfg.items.forEach((it, i) => { it.trick = TRICKS[i]; });

buildSet(cfg);
console.log("built", cfg.outPaper, "and", cfg.outKey);
