// ---------------------------------------------------------------------------
// SAT + GAT combined worksheet — GRADE 10, WEEK 4.
// SAT half (Section 1): regenerated from "SAT Bank — Verified Item Bank
// (Medium/Hard, Coverage-Matched)" — real College Board domain/skill/
// difficulty weighting, no leaked items. GAT half (Section 2) is unchanged,
// still anchored to 1-4 Arithmetic Sequences and Series.
// ---------------------------------------------------------------------------
const { buildSet } = require("./exam_engine");

const TRICKS = [
  // ---- SAT (from the verified bank, refreshed §2.16/§2.17 items)
  "read a linear model piece by piece — the coefficient on the variable is the rate, the constant alone is the fixed part",
  "subtract two equations with a matching coefficient to eliminate one variable at once",
  "find the constant rate of change between table pairs first, then extend the pattern to a new input",
  "infinitely many solutions means EVERY ratio of coefficients and constants must match, not just two of the three",
  "a growth factor compounds — raise it to the power of the elapsed time, never multiply by it",
  "in (x − h)² + k, the sign inside the parenthesis flips for the horizontal shift, but not for the vertical one",
  "substitute the known root into the equation first, then solve the resulting one-variable equation for the constant",
  "solve the system for every x first, then find each matching y, before adding anything",
  "when a triangle is not right-angled but you know two sides and the angle between them, reach for the Law of Cosines, not Pythagoras",
  "same-time shadows keep the same height-to-shadow ratio — set up the proportion with matching quantities on top",
  "a percent increase then the same percent decrease do NOT cancel, because the second percentage is taken of a different base",
  "convert one unit at a time — scale to a full day first, then convert the volume unit",
  // ---- GAT
  "the nth term formula works the same way whether the context is money, height or count",
  "solving Sn = value for n means writing the sum formula as a quadratic in n and solving it",
  "when the first differences are not constant, take the differences of the differences",
  "work back to the WHOLE before taking a new percentage of it",
  "units digits run in a cycle of four — divide the exponent by 4",
  "(a + b)² = a² + b² + 2ab, so a² + b² is one step away",
  "angles on a straight line add to 180° — collect the terms and solve once",
  "shaded = whole minus the pieces removed; leave π alone",
  "a weighted mean is not the mean of the means",
  "'at least one' is 1 minus the probability of none",
  "average speed is total distance over total time, never the average of the speeds",
  "consecutive integers cluster around their mean — name the smallest one x and write the rest from it",
];

const cfg = {
  mathIndex: "math_w4sat/_index.json",
  figIndex: "figs_w4/_index.json",
  examName: "SAT and GAT worksheet",
  targets: { "SAT-ALG": "~20%", "SAT-ADV": "~15%", "SAT-PSD": "~7.5%",
             "SAT-GEO": "~7.5%", "GAT-Q-ARI": "~20%", "GAT-Q-ALG": "~9%",
             "GAT-Q-GEO": "~9%", "GAT-Q-DAT": "~9%", "GAT-Q-LOG": "~5%" },
  dense: true, itemGap: 40, bare: true, optScale: 1,
  weekLine: "Week 4 · Semester 1, 2026–27",
  headerLine: "Grade 10 · Week 4 · SAT (pages 1–2, from the verified SAT item bank) and GAT Qudurat (pages 3–4, aligned to 1-4 Arithmetic Sequences and Series)",
  paperTitle: "SAT and GAT Worksheet — Grade 10, Week 4",
  paperSub: "24 questions · Section 1 SAT (calculator) · Section 2 GAT (no calculator)",
  keyTitle: "Grade 10 Week 4 — Answer Key and Error Analysis",
  keySub: "For Mr Malek Thiab. 30 minutes total: 15 on each section. Each item names the trick to say aloud and the error behind every wrong option.",
  outPaper: "SATGAT_Gr10_W4_Paper.docx",
  outKey: "SATGAT_Gr10_W4_Key.docx",
  timing: "30 minutes",
  calculator: "Section 1 yes · Section 2 no",
  marking: "One mark each, no penalty for a wrong answer",
  budgetNote: "24 items — 12 SAT and 12 GAT, half of Week 3's paper since the class has three teaching days this week.",
  sourceNote: "The SAT half (Section 1) is drawn from 'SAT Bank — Verified Item Bank (Medium/Hard, Coverage-Matched)' — house-authored items calibrated against the domain, skill and difficulty distribution of 974 real College Board digital-SAT questions (Easy items excluded). The GAT half follows the ETEC / Qiyas framework in the GAT and SAAT Classification Map. No leaked or circulated exam questions are used.",
  followUp: [
    ["19 or more", "Secure on both papers at this level. Move to full timed sections."],
    ["14 to 18", "The nth-term formula is solid; the sum formula and the n-solving items are the next marks."],
    ["9 to 13", "Expected at this point. Re-run the weaker section whole before adding anything new."],
    ["Below 9", "Work the nth-term items alone first — everything else in this topic builds on that one formula."],
    ["Whole class", "Any item where more than half the class chose the same wrong option is a teaching point — the trick column says what to put on the board."],
  ],
  items: [
    // ============================== SECTION 1 — SAT (refreshed from §2.16/§2.17 of the verified bank)
    { code: "SAT-ALG.1", lvl: 2,
      sec: { title: "SECTION 1 — SAT", note: "12 questions · calculator allowed · 15 minutes" },
      stem: "A ride-hailing fare in Jeddah is modeled by the function F(m) = 2.25m + 8, where m is the number of kilometers traveled and F(m) is the fare in SAR. What does the value 8 represent in this context?",
      opts: ["The additional fare, in SAR, for each additional kilometer traveled", "The fare for a trip of exactly 1 kilometer", "A fixed cost that does not depend on distance traveled", "The maximum possible fare"], ans: 2,
      why: "In F(m) = 2.25m + 8, the constant term 8 is the y-intercept — the fare when m = 0 — representing a fixed cost such as a base charge, while 2.25 is the per-kilometer rate.",
      traps: ["A: the meaning of the slope (2.25) assigned to the constant term instead.", "B: the constant term mistaken for the total cost of a specific 1 km trip rather than the fixed base charge.", "D: no basis in the model for a maximum — the function is unbounded as m increases."] },
    { code: "SAT-ALG.2", lvl: 2,
      stem: "At a school bookstore, 3 notebooks and 2 pens cost SAR 29, while 5 notebooks and 2 pens cost SAR 43. What is the cost, in SAR, of one notebook?",
      opts: ["5", "6", "7", "8"], ans: 2,
      why: "Subtracting the first equation from the second eliminates the pens: (5n + 2p) − (3n + 2p) = 43 − 29, so 2n = 14 and n = 7.",
      traps: ["A: an arithmetic slip while dividing 14.", "B: the equations subtracted in the wrong order before dividing.", "D: the pen price mistakenly solved for and reported instead of the notebook price."] },
    { code: "SAT-ALG.3", lvl: 2,
      stem: "The table shows three values of the linear function g.\nx: 2, 5, 8\ng(x): 13, 22, 31\nWhat is the value of g(10) ?",
      opts: ["34", "35", "37", "40"], ans: 2,
      why: "The slope is (22 − 13) ÷ (5 − 2) = 3, and using (2, 13): 13 = 3(2) + b gives b = 7, so g(x) = 3x + 7. Then g(10) = 3(10) + 7 = 37.",
      traps: ["A: the pattern extended by repeated addition of the table's own step (9) instead of the actual slope of 3.", "B: an arithmetic slip while evaluating 3(10) + 7.", "D: the slope and intercept swapped before evaluating."] },
    { code: "SAT-ALG.4", lvl: 3,
      stem: "For what value of k does the system of equations below have infinitely many solutions ?\n6x + 9y = 21\nkx + 6y = 14",
      opts: ["3", "4", "6", "9"], ans: 1,
      why: "Infinitely many solutions requires all three ratios to match: 6/k = 9/6 = 21/14 = 3/2. Solving 6/k = 3/2 gives k = 4.",
      traps: ["A: a coefficient ratio set up with mismatched terms.", "C: the ratio 9/6 confused with the value of k itself.", "D: the constant 21 mistaken for the value needed instead of solving the coefficient ratio."] },
    { code: "SAT-ADV.1", lvl: 2,
      stem: "The number of subscribers to an online tutoring platform grows according to N(t) = 500(1.2)^t, where t is the number of months since launch. Which of the following is closest to the number of subscribers after 5 months ?",
      opts: ["1,000", "1,100", "1,244", "1,500"], ans: 2,
      why: "N(5) = 500(1.2)⁵ = 500 × 2.48832 ≈ 1,244.",
      traps: ["A: the growth treated as linear, computing 500 × (1 + 0.2×5).", "B: the exponent applied to only part of the growth factor.", "D: the base 500 multiplied by 1.2 and then by 5 directly instead of raising 1.2 to the 5th power."] },
    { code: "SAT-ADV.2", lvl: 2,
      stem: "The graph of the function g(x) = (x − 3)² − 7 is the same as the graph of y = x² after which of the following transformations ?",
      opts: ["Shifted left 3 and up 7", "Shifted right 3 and down 7", "Shifted right 3 and up 7", "Shifted left 3 and down 7"], ans: 1,
      why: "In g(x) = (x − h)² + k, the graph of y = x² shifts right by h and up by k. Here h = 3 and k = −7, so the shift is right 3 and down 7.",
      traps: ["A: the sign inside the parenthesis misread as producing a leftward shift.", "C: the vertical shift's sign reversed.", "D: both the horizontal and vertical shift signs reversed."] },
    { code: "SAT-ADV.3", lvl: 3,
      stem: "If x = 5 is one solution to the equation x² − kx + 20 = 0, what is the value of k ?",
      opts: ["5", "7", "9", "11"], ans: 2,
      why: "Substituting x = 5: 25 − 5k + 20 = 0, so 45 = 5k and k = 9.",
      traps: ["A: the given root x = 5 reported back as if it were the value of k.", "B: an arithmetic slip while combining the constant terms.", "D: an arithmetic slip while dividing 45 by 5."] },
    { code: "SAT-ADV.4", lvl: 3,
      stem: "What is the sum of the y-coordinates of the solutions to the system below ?\ny = x² − 4x\ny = 2x − 5",
      opts: ["−2", "0", "2", "4"], ans: 2,
      why: "Setting the expressions equal: x² − 4x = 2x − 5, so x² − 6x + 5 = 0 and (x − 1)(x − 5) = 0, giving x = 1 or x = 5. At x = 1, y = −3; at x = 5, y = 5. The sum is −3 + 5 = 2.",
      traps: ["A: only one solution's y-value reported, with a sign error.", "B: the two y-values incorrectly assumed to cancel to zero.", "D: an arithmetic slip while adding the two y-values."] },
    { code: "SAT-GEO.1", lvl: 3, fig: "g10_geo1_tri", figW: 2.0,
      stem: "A triangular plot of land has two sides measuring 80 meters and 95 meters, with an included angle of 62° between them. Which of the following is closest to the length, in meters, of the third side ?",
      opts: ["83.4", "87.9", "91.0", "95.7"], ans: 2,
      why: "By the Law of Cosines, c² = 80² + 95² − 2(80)(95)cos(62°) ≈ 15,425 − 7,136 = 8,289, so c ≈ 91.0.",
      traps: ["A: the Pythagorean theorem applied directly, ignoring that the triangle is not right-angled.", "B: the cosine term computed with the wrong angle value.", "D: the subtraction step replaced with addition, overestimating the third side."] },
    { code: "SAT-GEO.2", lvl: 2, fig: "g10_geo2_shadow", figW: 2.3,
      stem: "A pole that is 2.4 meters tall casts a shadow 3.2 meters long. At the same time, a nearby communications tower casts a shadow 52 meters long. Using similar triangles, which of the following is closest to the height, in meters, of the tower ?",
      opts: ["34.7", "36.4", "39.0", "41.6"], ans: 2,
      why: "The pole and its shadow form a triangle similar to the tower and its shadow, so height-to-shadow is constant: 2.4 ÷ 3.2 = 0.75. The tower's height is 0.75 × 52 = 39.0.",
      traps: ["A: the ratio inverted (shadow-to-height) before multiplying.", "B: a rounding slip on the ratio 2.4 ÷ 3.2.", "D: the shadow length used directly as the multiplier instead of the height-to-shadow ratio."] },
    { code: "SAT-PSD.1", lvl: 2,
      stem: "The population of a town increased by 10% in the first year and then decreased by 10% in the second year. If the population at the start of the first year was 5,000, what was the population at the end of the second year ?",
      opts: ["4,900", "4,950", "5,000", "5,050"], ans: 1,
      why: "After the first year: 5,000 × 1.10 = 5,500. After the second year: 5,500 × 0.90 = 4,950.",
      traps: ["A: an arithmetic slip while applying the second percentage.", "C: the two percent changes assumed to cancel out and return the population to its original value.", "D: the order of the increase and decrease effectively reversed by a sign error."] },
    { code: "SAT-PSD.2", lvl: 3,
      stem: "A desalination plant in the Eastern Province produces fresh water at a constant rate of 1,250,000 liters per hour. At this rate, which of the following is closest to the number of cubic meters of water the plant produces in one day? (1 cubic meter = 1,000 liters.)",
      opts: ["25,000", "28,000", "30,000", "32,500"], ans: 2,
      why: "In one day, the plant produces 1,250,000 × 24 = 30,000,000 liters, which is 30,000,000 ÷ 1,000 = 30,000 cubic meters.",
      traps: ["A: the hourly rate scaled by only part of a day instead of the full 24 hours.", "B: an arithmetic slip while multiplying by 24.", "D: the unit conversion applied before scaling to a full day, then a rounding slip."] },

    // ================================================ SECTION 2 — GAT
    { code: "GAT-Q-ARI.5", lvl: 2,
      sec: { newPage: true, title: "SECTION 2 — GAT (Qudurat)", note: "12 questions · NO calculator · 15 minutes" },
      stem: "An arithmetic sequence has the values below. What is the 15th term?", stemEq: "g10g_seq",
      opts: ["95", "98", "102", "109"], ans: 2,
      why: "a15 = a1 + 14d = 4 + 14(7) = 102.",
      traps: ["A: 13 steps used.", "B: an arithmetic slip.", "D: 15 steps used instead of 14."] },
    { code: "GAT-Q-ARI.5", lvl: 3,
      stem: "An arithmetic series has first term 4 and common difference 6. For which value of n is the sum of the first n terms equal to 310?",
      opts: ["8", "9", "10", "11"], ans: 2,
      why: "Sn = n/2 · (2(4) + (n − 1)(6)) = n(3n + 1). Testing n = 10: 10(31) = 310.",
      traps: ["A and B: the quadratic in n solved with an arithmetic slip.", "D: one step too many tried after 310 was already reached."] },
    { code: "GAT-Q-ARI.5", lvl: 3, stem: "What is the next term of the sequence below?", stemEq: "g10g_diff",
      opts: ["76", "78", "80", "82"], ans: 2,
      why: "First differences are 7, 11, 15, 19 — not constant, so this is NOT arithmetic. Their differences are constant at 4, so the next first difference is 23, and the next term is 57 + 23 = 80.",
      traps: ["A: the last difference repeated without the +4.", "B: the second-difference step applied only halfway.", "D: an extra +4 applied twice."] },
    { code: "GAT-Q-ARI.3", lvl: 3,
      stem: "45% of a number is 90. What is 20% of the same number?",
      opts: ["18", "36", "40", "45"], ans: 2,
      why: "The number is 90 ÷ 0.45 = 200, and 20% of 200 is 40. Go back to the whole before taking any new percentage.",
      traps: ["A: 20% of 90.", "B: a rounding slip.", "D: 25% of 200 taken by mistake."] },
    { code: "GAT-Q-ARI.4", lvl: 3,
      stem: "What is the units digit of 7²³ ?",
      opts: ["1", "3", "7", "9"], ans: 1,
      why: "Powers of 7 have units digits cycling 7, 9, 3, 1 every four. 23 leaves remainder 3 on division by 4, so the units digit is the third in the cycle: 3.",
      traps: ["A: remainder taken as 0.", "C: remainder taken as 1.", "D: remainder taken as 2."] },
    { code: "GAT-Q-ALG.4", lvl: 3,
      stem: "If", stemEq: "g10g_ident", note: "what is the value of a² + b² ?",
      opts: ["25", "53", "67", "81"], ans: 1,
      why: "(a + b)² = a² + b² + 2ab, so 81 = a² + b² + 28 and a² + b² = 53. The values of a and b are never needed.",
      traps: ["A: 28 subtracted twice instead of once.", "C: 2ab taken as 14.", "D: the 9² given back unchanged."] },
    { code: "GAT-Q-GEO.1", lvl: 3, fig: "g10_gat_angles", figW: 2.3,
      stem: "Three angles on a straight line are the expressions below. What is the value of x ?", stemEq: "g10g_angles",
      opts: ["15", "18", "20", "24"], ans: 2,
      why: "Angles on a straight line total 180°: 3x + 2x + 10 + 4x − 10 = 180, so 9x = 180 and x = 20.",
      traps: ["A: the constants not cancelled correctly.", "B: a rounding slip.", "D: the angles assumed to total 216°."] },
    { code: "GAT-Q-GEO.3", lvl: 3, fig: "g10_gat_circle", figW: 1.7,
      stem: "A circle of radius 6 cm is inscribed in a square. What area of the square lies outside the circle, in cm² ?",
      opts: [{ eq: "g10g_o_out1" }, { eq: "g10g_o_out2" }, { eq: "g10g_o_out3" }, { eq: "g10g_o_out4" }], ans: 0,
      why: "The circle touches all four sides, so the square has side 12 and area 144. The circle has area 36π, leaving 144 − 36π. Leave π alone.",
      traps: ["B: the radius used as the side.", "C: only the circle's own area given.", "D: an arithmetic slip on the square's area."] },
    { code: "GAT-Q-DAT.5", lvl: 3,
      stem: "In a class, 15 students scored a mean of 70 and 25 students scored a mean of 82. What is the mean for all 40 ?",
      opts: ["74.5", "76", "77.5", "79"], ans: 2,
      why: "Totals first: 1050 + 2050 = 3100, and 3100/40 = 77.5. A weighted mean is not the mean of the means.",
      traps: ["A: the mean of 70 and 82, then rounded.", "B: the arithmetic mean of the two given means.", "D: the larger group's own mean nudged up."] },
    { code: "GAT-Q-DAT.3", lvl: 3,
      stem: "A fair die is rolled twice. What is the probability of rolling at least one six?",
      opts: ["1/6", "1/3", "11/36", "25/36"], ans: 2,
      why: "'At least one' is 1 minus 'none': the chance of no sixes is (5/6)² = 25/36, so the answer is 11/36.",
      traps: ["A: a single-roll probability given for two rolls.", "B: a guess between the values.", "D: the complement itself given as the answer."] },
    { code: "GAT-Q-LOG.1", lvl: 3,
      stem: "A driver covers 100 km at 50 km/h and the next 60 km at 40 km/h. What is the average speed for the whole journey, in km/h?",
      opts: ["43", "44", "45.7", "48"], ans: 2,
      why: "Total time is 2 + 1.5 = 3.5 hours for 160 km, so 160/3.5 ≈ 45.7. Average speed is total distance over total time, never the mean of the two speeds.",
      traps: ["A and B: guesses below the true value.", "D: the mean of 50 and 40 — the trap."] },
    { code: "GAT-Q-ARI.1", lvl: 3,
      stem: "The sum of four consecutive integers is 118. What is the largest of them?",
      opts: ["28", "29", "30", "31"], ans: 3,
      why: "Naming the smallest x: x + (x+1) + (x+2) + (x+3) = 4x + 6 = 118, so x = 28 and the largest is 31.",
      traps: ["A: the smallest given instead of the largest.", "B: an off-by-one slip.", "C: the second integer given."] },
  ],
};

if (TRICKS.length !== cfg.items.length)
  throw new Error(`${TRICKS.length} tricks for ${cfg.items.length} items`);
cfg.items.forEach((it, i) => { it.trick = TRICKS[i]; });

buildSet(cfg);
console.log("built", cfg.outPaper, "and", cfg.outKey);
