H=[
r"Write $(5,-1)=a(1,1)+b(1,-1)$ and compare the two coordinates. You get two equations in $a$ and $b$; add them, then subtract them.",
r"Set $(2,3,4)=a(1,1,1)+b(0,1,2)$ and compare coordinates. The first coordinate gives $a$; then check that the second and third coordinates agree on one value of $b$.",
r"Set $(1,0,0)=a(1,1,0)+b(0,1,1)$. The first coordinate fixes $a$ and the third fixes $b$; then test the second coordinate with those values.",
r"Write $(1,2,k)=a(1,1,0)+b(1,-1,2)$. The first two coordinates form a system in $a,b$: solve it, then the third coordinate gives $k$.",
r"Set $(1+i,\,2)=a(1,i)+b(1,-i)$ with $a,b\in\mathbb{C}$. The coordinates give $a+b=1+i$ and $i(a-b)=2$. Divide the second by $i$, using $\dfrac1i=-i$.",
r"One vector is a multiple of the other, so the span is the set of all multiples of a single nonzero vector. Write a general element $t(1,2)$ and find the relation between its $x$ and $y$.",
r"A general element is $a(1,0,2)+b(0,1,-1)=(a,\,b,\,2a-b)$. Read off $x=a$ and $y=b$, then express $z$ in terms of $x$ and $y$.",
r"Use the subspace test: the set is non-empty (it contains $\mathbf 0$) and closed under addition and scalar multiplication. Add two general linear combinations and regroup the terms by $v_i$.",
r"Check whether one vector is a scalar multiple of the other, or solve $a(1,2)+b(3,6)=\mathbf 0$ and look for a solution other than $a=b=0$.",
r"Solve $a(1,2)+b(2,3)=\mathbf 0$ coordinate by coordinate. Is $a=b=0$ the only solution?",
r"Solve $a(1,0,1)+b(1,1,0)+c(0,1,1)=\mathbf 0$. Three equations in $a,b,c$: add and subtract them to isolate each unknown.",
r"Compare $v_2-v_1$ with $v_3-v_2$. Rearranging that observation gives a relation among $v_1,v_2,v_3$.",
r"Solve $a(1,1,1)+b(1,2,3)+c(1,3,k)=\mathbf 0$. Use the first equation to eliminate $a$, express $b$ in terms of $c$, and ask when $c$ can be nonzero.",
r"Compare coefficients: in $a(1+x)+b(1-x)+2c=0$ the coefficient of $1$ and of $x$ must both vanish. How many equations and how many unknowns do you have?",
r"(a) Over $\mathbb{C}$ the scalar may be complex: divide the first coordinates, then test the second. (b) Over $\mathbb{R}$, write $a(1,i)+b(1+i,\,i-1)=\mathbf 0$ with real $a,b$ and separate real and imaginary parts.",
r"Start from $a(u+v)+b(v+w)+c(u+w)=\mathbf 0$. Collect the coefficients of $u$, $v$ and $w$, then use the independence of $u,v,w$.",
r"Write $(1,2,3)=a(1,0,1)+b(2,1,0)+c(0,1,1)$ as three equations: $a+2b=1$, $b+c=2$, $a+c=3$. Substitute to eliminate one unknown at a time.",
r"Set $(a,b,c)=s(1,2,0)+t(0,1,1)$. The first coordinate gives $s$ and the third gives $t$; substitute both into the second coordinate.",
r"Solve the condition for one variable, for example $x=-y-z$, and write a general vector with $y,z$ free. Split it into a part that contains $y$ and a part that contains $z$.",
r"(a) For a general $(x,y)$, solve $a(1,1)+b(1,2)=(x,y)$ using only the first two vectors. (b) Compare the number of vectors with the dimension of $\mathbb{R}^2$, or find a relation among the three.",
r"Take an arbitrary $a+bx+cx^2$ and write it as $p\cdot1+q(1+x)+r(1+x+x^2)$. Match the $x^2$ coefficient first, then $x$, then the constant.",
r"Write a general matrix $\begin{pmatrix}p&q\\r&s\end{pmatrix}$ as $\alpha A_1+\beta A_2+\gamma A_3+\delta A_4$ and compare entries: four equations in four unknowns. For independence, set the matrix equal to $0$.",
r"Prove two inclusions. $\operatorname{span}\{v_1,\dots,v_k\}\subseteq\operatorname{span}\{v_1,\dots,v_k,w\}$ is immediate; for the reverse, write $w=\sum c_iv_i$ and substitute it into a general combination.",
r"Suppose $a_1v_1+\dots+a_{k+1}v_{k+1}=\mathbf 0$. Ask what happens if $a_{k+1}\neq0$ (where would $v_{k+1}$ lie?), then use the independence of $v_1,\dots,v_k$.",
]
assert len(H)==24
