from mathgen import render
INK, WHITE = "222E2D", "FFFFFF"
B = r"\underline{\qquad}"
E = {
 "a_title_w": (r"f(x)=3^{x}\ \longleftrightarrow\ f^{-1}(x)=\log_3 x", WHITE),
 "a_v1": (r"f^{-1}\!\left(f(x)\right)=x", INK),
 "a_v2": (r"f(x)=\log_b x,\quad b>0,\ b\neq1", INK),
 "a_p1": (r"\log_3 9=2", INK),
 "a_p2": (r"f(x)=3^{x}", INK),
 "a_p3": (r"(a,b)\ \leftrightarrow\ (b,a)", INK),
 "a_co_w": (r"(2,9)\ \text{on}\ 3^{x}\ \longrightarrow\ (9,2)\ \text{on}\ \log_3 x", WHITE),
 "a_d1": (r"\log_3 81 = " + B, INK),
 "a_d2": (r"\log_2\dfrac18 = " + B, INK),
 "a_d3": (r"f(x)=3^{x}.\quad f(3)=" + B, INK),
 "a_d4": (r"f(x)=3^{x}.\quad f(" + B + r")=9", INK),
 "a_d5": (r"3^{x}=0", INK),
 "a_arc1": (r"\dfrac{\log_3 3-\log_3 1}{3-1}=\dfrac{1-0}{2}=\dfrac12", INK),
 "a_arc2": (r"\dfrac{\log_3 9-\log_3 3}{9-3}=\dfrac{2-1}{6}=\dfrac16", INK),
 "a_arc3": (r"\dfrac{\log_3 27-\log_3 9}{27-9}=\dfrac{3-2}{18}=\dfrac1{18}", INK),
 "a_swap": (r"y=3^{x}\ \xrightarrow{\ \text{swap}\ }\ x=3^{y}\ \Longleftrightarrow\ y=\log_3 x", INK),
 "a_tabs": (r"\begin{array}{c|cccc}x&-1&0&1&2\\\hline f(x)&\tfrac13&1&3&9\end{array}\ \longrightarrow\ \begin{array}{c|cccc}x&\tfrac13&1&3&9\\\hline f^{-1}(x)&-1&0&1&2\end{array}", INK),
 "a_swap1": (r"y=3^{x}\ \xrightarrow{\ \text{swap}\ }\ x=3^{y}", INK),
 "a_swap2": (r"x=3^{y}\ \Longleftrightarrow\ y=\log_3 x", INK),
 "a_inv1": (r"\log_3 3^{x}=x\quad\text{and}\quad 3^{\log_3 x}=x\ \ (x>0)", INK),
 "a_tab": (r"f(2)=9\ \Longrightarrow\ f^{-1}(9)=2", INK),
 "a_qc": (r"f(x)=3^{x}\ \Rightarrow\ f^{-1}(x)=" + B, INK),
 "a_g1": (r"f(x)=2^{x}\ \Rightarrow\ f^{-1}(x)=" + B, INK),
 "a_g2": (r"f^{-1}(25)=" + B + r",\quad f^{-1}(125)=" + B, INK),
 "a_ws1": (r"f(x)=4^{x}\ \Rightarrow\ f^{-1}(x)=" + B, INK),
 "a_ws3": (r"P=10\cdot 3^{t/5}", INK),
 "a_model_w": (r"t=5\log_3\!\left(\dfrac{P}{10}\right)", WHITE),
 "a_gate_w": (r"f(x)=5^{x}", WHITE),
 "a_sh": (r"g(x)=\log_3(x-2)+1", INK),
}
render(E, "w6l4", "math_w6l4")
