// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part F: the 24 skills left over from part E.
//
// Same rule as part E. The source taught a METHOD; the method is a mathematical
// fact and not protected writing, and every item here is written fresh around
// one. Nothing is translated, transcribed or reproduced.
//
// WHY THE GEOMETRY WEIGHTING. Seventeen of the twenty-four items below are
// geometry, which takes the bank's geometry share to 28% — well ABOVE the ETEC
// blueprint's ~18%. That is deliberate and it is not a blueprint error: this is
// a bank, not a paper. A mock is built by sampling to the blueprint, so every
// strand needs a surplus to sample from, and geometry had the thinnest surplus
// in exactly the places Grade 12 loses marks in the computerised sitting —
// solids, coordinate geometry and circle theorems, none of which the department
// practice sets covered. Data is still the strand with no surplus, at 10%.
// ---------------------------------------------------------------------------
const CMP = ["A is greater", "B is greater", "they are equal",
             "not enough information"];

module.exports = [

// ================================================================ GEOMETRY
{ sig: "angle-bisector-ratio", code: "GAT-Q-GEO.2", lvl: 3,
  stem: "In the triangle shown, AD bisects the angle at A. Find the length of DC, in centimetres.",
  fig: "sim_bisector", figW: 2.35,
  opts: ["9", "10", "12", "15"], ans: 1,
  trick: "the bisector cuts the opposite side in the ratio of the two sides BESIDE the angle, not in half",
  why: "BD⁄DC = AB⁄AC, so 6⁄DC = 9⁄15. Then DC = 6 × 15 ÷ 9 = 10 cm.",
  traps: ["A: matched BD to the wrong side, using 6 × 9 ÷ 15 and rounding.",
          "C: assumed the bisector also bisects BC, doubling 6.",
          "D: copied AC straight down as the answer."] },

{ sig: "cyclic-quadrilateral", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "The four vertices of the quadrilateral shown lie on the circle. Find the size of the angle marked y.",
  fig: "sim_cyclic", figW: 2.25,
  opts: ["68°", "78°", "102°", "112°"], ans: 2,
  trick: "on a circle, OPPOSITE angles of the quadrilateral add to 180° — the two angles side by side tell you nothing",
  why: "y is opposite the 78° angle, so y = 180° − 78° = 102°.",
  traps: ["A: subtracted from 146° instead of 180°.",
          "B: copied the opposite angle, treating them as equal.",
          "D: subtracted the adjacent 68° from 180° instead."] },

{ sig: "arc-length", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "A circular fountain rim at King Abdullah Park has radius 21 m. A path runs along the rim through a central angle of 120°. How long is the path? (Take π = 22⁄7.)",
  opts: ["22 m", "44 m", "66 m", "88 m"], ans: 1,
  trick: "an arc is a FRACTION of the circumference — the fraction is the angle over 360, and the circumference uses 2πr, not πr",
  why: "The full circumference is 2 × 22⁄7 × 21 = 132 m. The path is 120⁄360 = one third of it, so 44 m.",
  traps: ["A: took a third of πr instead of 2πr.",
          "C: took half the circumference instead of a third.",
          "D: took two thirds, reading 120° as the part left over."] },

{ sig: "distance-midpoint-coordinate", code: "GAT-Q-GEO.6", lvl: 2,
  stem: "A surveyor marks two points on a plan at (−3, 4) and (9, −1). How far apart are they?",
  opts: ["12", "13", "15", "17"], ans: 1,
  trick: "square the two GAPS, add, then take the root — the gap is a subtraction, so a negative coordinate widens it",
  why: "The horizontal gap is 9 − (−3) = 12 and the vertical gap is 4 − (−1) = 5. Then √(144 + 25) = √169 = 13.",
  traps: ["A: used the horizontal gap alone.",
          "C: added the two gaps, 12 + 5, and then subtracted 2.",
          "D: added the two gaps."] },

{ sig: "circle-equation", code: "GAT-Q-GEO.6", lvl: 2,
  stem: "The equation below describes a circle. What is its radius?",
  stemEq: "s_circle_eq",
  opts: ["3", "7", "24.5", "49"], ans: 1,
  trick: "the number on the right is r SQUARED — and the centre reads with the signs flipped",
  why: "Comparing with (x − h)² + (y − k)² = r² gives r² = 49, so r = 7. (The centre is (4, −3).)",
  traps: ["A: took the root of the 9 inside the bracket.",
          "C: halved 49, confusing radius with diameter.",
          "D: read 49 as the radius itself — the trap this item exists for."] },

{ sig: "parallel-angle-pairs", code: "GAT-Q-GEO.1", lvl: 2,
  stem: "In the figure the two horizontal lines are parallel. Find the value of x.",
  fig: "sim_parallel_pair", figW: 2.55,
  opts: ["15", "20", "25", "30"], ans: 1,
  trick: "co-interior angles on the SAME side of the transversal add to 180°; only alternate and corresponding angles are equal",
  why: "The two marked angles are co-interior, so (3x + 10) + (5x + 10) = 180, giving 8x = 160 and x = 20.",
  traps: ["A: set the two expressions equal, treating them as alternate angles.",
          "C: added to 200 instead of 180.",
          "D: solved 6x = 180, dropping both constants."] },

{ sig: "equal-area-same-base", code: "GAT-Q-GEO.2", lvl: 3,
  stem: "In the figure the two triangles stand on the same base PQ, and the dashed line through R and S is parallel to PQ. Which is greater?   A: the area of triangle PQR   B: the area of triangle PQS",
  fig: "sim_same_base", figW: 2.70,
  opts: CMP, ans: 2,
  trick: "area depends on the base and the PERPENDICULAR height only — a triangle that leans is not larger, and between parallels every apex has the same height",
  why: "Both triangles have base PQ and the same height, because R and S sit on a line parallel to PQ. The areas are equal.",
  traps: ["A: judged by the longer sloping sides of PQR.",
          "B: judged by S sitting further along.",
          "D: the parallel line fixes the height, so this is decidable."] },

{ sig: "square-area-equals-perimeter", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "A square is drawn so that the number giving its area is equal to the number giving its perimeter. What is the length of one side?",
  opts: ["2", "4", "8", "16"], ans: 1,
  trick: "write both as expressions in the side and solve — do not hunt for the answer by trying values",
  why: "s² = 4s, so s² − 4s = 0 and s(s − 4) = 0. A side cannot be 0, so s = 4. (Area 16, perimeter 16.)",
  traps: ["A: solved s = 4 ÷ 2.",
          "C: doubled the correct side.",
          "D: gave the area rather than the side."] },

{ sig: "circle-in-square", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "A circular tile is set inside a square panel as shown below, touching all four sides. The panel has side 14 cm. Find the shaded area, in square centimetres. (Take π = 22⁄7.)",
  fig: "sim_circle_square", figW: 1.95,
  opts: ["28", "42", "56", "154"], ans: 1,
  trick: "the circle's DIAMETER equals the side of the square, so the radius is half of it — halve before you square",
  why: "The radius is 7 cm. Square 14² = 196; circle 22⁄7 × 49 = 154. Shaded = 196 − 154 = 42 cm².",
  traps: ["A: used a radius of 14 and then patched the negative answer.",
          "C: doubled the correct difference.",
          "D: gave the area of the circle rather than what is left."] },

{ sig: "tangent-circles-shaded", code: "GAT-Q-GEO.4", lvl: 3,
  stem: "Two equal circles are fitted inside the rectangle shown so that each touches three sides and the two touch each other. Find the shaded area, in square centimetres. (Take π = 3.14.)",
  fig: "sim_two_circles", figW: 2.85,
  opts: ["15.48", "27.48", "43.48", "56.52"], ans: 0,
  trick: "the height of the rectangle fixes the radius, and the length is then FOUR radii — subtract two circles, not one",
  why: "The height 6 cm is one diameter, so r = 3 and the length 12 = 4r checks out. Shaded = 12 × 6 − 2 × 3.14 × 3² = 72 − 56.52 = 15.48 cm².",
  traps: ["B: subtracted only one circle.",
          "C: used a radius of 1.5, halving twice.",
          "D: gave the area of the two circles instead of what is left."] },

{ sig: "equal-perimeter-area-order", code: "GAT-Q-GEO.4", lvl: 3,
  stem: "A square and a circle are each made from 24 cm of wire, with none left over. Which is greater?   A: the area enclosed by the square   B: the area enclosed by the circle",
  opts: CMP, ans: 1,
  trick: "for a fixed perimeter the CIRCLE always encloses the most — the more corners a shape loses, the more it holds",
  why: "The square has side 6 and area 36 cm². The circle has 2πr = 24, so r ≈ 3.82 and area ≈ 45.8 cm². B is greater.",
  traps: ["A: assumed the straight-sided shape holds more.",
          "C: assumed equal perimeter forces equal area — the trap this item exists for.",
          "D: both perimeters are given, so both areas are fixed."] },

{ sig: "similar-sides-ratio", code: "GAT-Q-GEO.2", lvl: 3,
  stem: "Two similar triangular sails have corresponding sides in the ratio 3 : 5. The smaller sail has area 45 m². What is the area of the larger one, in square metres?",
  opts: ["75", "108", "125", "135"], ans: 2,
  trick: "areas scale by the SQUARE of the side ratio — 3 : 5 on the sides is 9 : 25 on the areas",
  why: "45 ÷ 9 = 5, and 5 × 25 = 125 m².",
  traps: ["A: scaled by 5⁄3 once instead of squaring.",
          "B: used the ratio 9 : 25 upside down and rounded.",
          "D: tripled the smaller area."] },

{ sig: "triangle-area-find-base", code: "GAT-Q-GEO.4", lvl: 1,
  stem: "A triangular flowerbed has area 84 m² and a perpendicular height of 12 m. How long is its base, in metres?",
  opts: ["7", "12", "14", "28"], ans: 2,
  trick: "working backwards means DOUBLING the area first — the half in the formula moves to the other side",
  why: "84 = ½ × b × 12, so 168 = 12b and b = 14 m.",
  traps: ["A: divided 84 by 12 and then halved.",
          "B: read the height back as the base.",
          "D: doubled the correct base, halving nothing."] },

{ sig: "count-rectangles-in-grid", code: "GAT-Q-GEO.4", lvl: 3,
  stem: "How many rectangles of any size can be traced along the lines of the grid shown?",
  fig: "sim_grid_rects", figW: 2.15,
  opts: ["6", "12", "18", "24"], ans: 2,
  trick: "a rectangle is fixed by choosing TWO of the vertical lines and TWO of the horizontal ones — count lines, not squares",
  why: "There are 4 vertical lines and 3 horizontal ones. Choosing 2 of each gives 6 × 3 = 18 rectangles.",
  traps: ["A: counted only the six unit squares.",
          "B: counted the unit squares and the six 1 × 2 rectangles.",
          "D: counted every pair of lines including repeats."] },

{ sig: "cuboid-volume-surface", code: "GAT-Q-GEO.5", lvl: 2,
  stem: "A storage box measures 8 cm by 5 cm by 3 cm. Which is greater?   A: its volume in cubic centimetres   B: its total surface area in square centimetres",
  opts: CMP, ans: 1,
  trick: "surface area needs all THREE pairs of faces — 2(lw + lh + wh), not four sides like a room",
  why: "Volume = 8 × 5 × 3 = 120. Surface = 2(40 + 24 + 15) = 158. So B is greater.",
  traps: ["A: counted only four faces, giving 118.",
          "C: no pair of these figures is equal.",
          "D: all three dimensions are given, so both are fixed."] },

{ sig: "cylinder-volume", code: "GAT-Q-GEO.5", lvl: 2,
  stem: "A cylindrical water tank has radius 7 m and height 10 m. What is its volume, in cubic metres? (Take π = 22⁄7.)",
  opts: ["220", "440", "1540", "3080"], ans: 2,
  trick: "the base is a CIRCLE, so square the radius before multiplying by the height — πr²h, never 2πrh",
  why: "V = 22⁄7 × 7² × 10 = 22 × 7 × 10 = 1540 m³.",
  traps: ["A: used the circumference 2πr and forgot the height.",
          "B: used the curved surface area 2πrh instead of the volume.",
          "D: doubled the volume, using 2πr²h."] },

{ sig: "volume-unit-conversion", code: "GAT-Q-GEO.5", lvl: 2,
  stem: "A rooftop tank measures 2 m by 1.5 m by 0.8 m. How many litres does it hold when full?",
  opts: ["24", "240", "2400", "24 000"], ans: 2,
  trick: "one cubic metre is a THOUSAND litres — the metre-to-centimetre factor of 100 is cubed, not used once",
  why: "The volume is 2 × 1.5 × 0.8 = 2.4 m³, and 2.4 × 1000 = 2400 litres.",
  traps: ["A: gave the volume in cubic metres times ten.",
          "B: multiplied by 100 instead of 1000.",
          "D: multiplied by 10 000."] },

// =================================================================== LOGIC
{ sig: "handshakes-vs-gifts", code: "GAT-Q-LOG.3", lvl: 3,
  stem: "Ten teachers meet at a staff breakfast. Which is greater?   A: the number of handshakes if each pair shakes hands once   B: the number of gifts if each teacher gives a gift to every other teacher",
  opts: CMP, ans: 1,
  trick: "a handshake is SHARED by the pair but a gift has a giver and a receiver — one is n(n−1)/2, the other is n(n−1)",
  why: "Handshakes: 10 × 9 ÷ 2 = 45. Gifts: 10 × 9 = 90, because A giving to B is not the same as B giving to A. B is greater.",
  traps: ["A: counted the gifts as pairs too.",
          "C: treated the two situations as the same counting problem — the trap this item exists for.",
          "D: the number of teachers fixes both counts."] },

{ sig: "wheel-revolutions", code: "GAT-Q-LOG.1", lvl: 3,
  stem: "A bicycle wheel has diameter 70 cm. How many complete turns does it make over 4.4 km? (Take π = 22⁄7.)",
  opts: ["1000", "2000", "4000", "20 000"], ans: 1,
  trick: "one turn covers one CIRCUMFERENCE — and the units must meet, so put the distance into centimetres first",
  why: "Circumference = 22⁄7 × 70 = 220 cm. The distance is 4.4 km = 440 000 cm. Then 440 000 ÷ 220 = 2000 turns.",
  traps: ["A: used the diameter as the distance per turn and rounded.",
          "C: used the radius 35 cm in place of the circumference.",
          "D: divided by 22 instead of 220."] },

{ sig: "cost-price-from-markup", code: "GAT-Q-LOG.4", lvl: 3,
  stem: "A shop in Jeddah sells a jacket for 621 SAR, making a profit of 15% on what it paid. What did the shop pay, in SAR?",
  opts: ["527.85", "540", "571.50", "606"], ans: 1,
  trick: "the percentage is taken on the COST, which is the unknown — so divide by 1.15; taking 15% off the selling price is the trap",
  why: "Cost × 1.15 = 621, so cost = 621 ÷ 1.15 = 540 SAR. (Check: 15% of 540 = 81, and 540 + 81 = 621.)",
  traps: ["A: took 15% off 621 — the trap this item exists for.",
          "C: subtracted 15% of 540 rather than working back to it.",
          "D: subtracted a flat 15 SAR."] },

{ sig: "ratio-parts-share", code: "GAT-Q-LOG.2", lvl: 2,
  stem: "A prize of 3600 SAR is divided between three students in the ratio 2 : 3 : 7. How much more does the largest share get than the smallest, in SAR?",
  opts: ["900", "1200", "1500", "2100"], ans: 2,
  trick: "find the value of ONE part first — the total is 12 parts here, not 3",
  why: "There are 2 + 3 + 7 = 12 parts, so one part is 3600 ÷ 12 = 300 SAR. The difference is 7 − 2 = 5 parts, or 1500 SAR.",
  traps: ["A: used the difference 3 parts between the two smaller shares.",
          "B: divided the total by 3 and took a quarter.",
          "D: gave the largest share instead of the difference."] },

{ sig: "combined-work-time", code: "GAT-Q-LOG.1", lvl: 3,
  stem: "One painter can finish a wall in 12 hours and a second can finish the same wall in 6 hours. Working together, how many hours do they take?",
  opts: ["3", "4", "6", "9"], ans: 1,
  trick: "add the RATES, not the times — and the answer must be shorter than the faster worker alone, which rules the average out",
  why: "In one hour they paint 1⁄12 + 1⁄6 = 3⁄12 = 1⁄4 of the wall, so the whole wall takes 4 hours.",
  traps: ["A: halved the faster time.",
          "C: gave the faster painter's own time.",
          "D: averaged 12 and 6 — the trap this item exists for."] },

{ sig: "day-of-week-cycle", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "Today is Tuesday. What day of the week will it be 100 days from now?",
  opts: ["Wednesday", "Thursday", "Friday", "Saturday"], ans: 1,
  trick: "only the REMAINDER after dividing by 7 moves the day — the whole weeks in between change nothing",
  why: "100 ÷ 7 = 14 remainder 2, so the day moves forward 2 from Tuesday, to Thursday.",
  traps: ["A: moved forward 1, using a remainder of 1.",
          "C: moved forward 3.",
          "D: counted 100 ÷ 7 as 14 remainder 4."] },

// ==================================================================== DATA
{ sig: "permutation-vs-combination", code: "GAT-Q-DAT.4", lvl: 3,
  stem: "Eight students are available. Which is greater?   A: the number of ways to pick 3 of them for a committee   B: the number of ways to pick 3 of them for first, second and third place in a race",
  opts: CMP, ans: 1,
  trick: "ask whether ORDER changes the outcome — on a committee it does not, on a podium it does, and ordering multiplies by 3! = 6",
  why: "Committee: 8 × 7 × 6 ÷ 6 = 56. Podium: 8 × 7 × 6 = 336. B is greater, by a factor of 6.",
  traps: ["A: divided the podium count by 6 as well.",
          "C: treated the two as the same selection — the trap this item exists for.",
          "D: eight students and three places fix both counts."] },

];
