// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part I: skills mined from the expanded English worksheet.
//
// That sheet carried 167 questions, each already carrying the skill it tests and
// the trick it turns on. Roughly two thirds of those skills the bank already
// had; the 51 below are the ones it did not.
//
// The weighting is deliberate. The bank was 34% level-3 and the weekly builder
// was running out of level-1 and level-2 arithmetic and algebra by Week 11 —
// which is why 30 of these 51 are level 1 or 2, and why most of them sit in ARI
// and ALG. A bank that can only offer hard questions makes every later worksheet
// harder than the one before it, which tells you nothing about the student.
//
// The diagrams the source lost in its PDF text layer are REBUILT from scratch
// here (i_circles_grid, i_lshape, i_two_curves) — drawn to the house figure
// spec, measured by figlabel, and checked against the answer they must support.
//
// Nothing is transcribed: skills are facts, wording and numbers are new, and
// every answer is re-derived in verify_sim.py before release.
// ---------------------------------------------------------------------------
module.exports = [

// ============================================================== ARITHMETIC
{ sig: "multiply-near-round", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Find the value of the product below.", stemEq: "i_998",
  opts: ["24 500", "24 950", "24 975", "25 000"], ans: 1,
  trick: "push the awkward number up to the round one and take the difference back off — 998 × 25 is 1000 × 25 minus 2 × 25, which is one line of mental work instead of a long multiplication",
  why: "998 × 25 = 25 000 − 50 = 24 950.",
  traps: ["A: 500 subtracted instead of 50.",
          "C: 1000 × 25 minus 25, only one of the two lots removed.",
          "D: the rounding never undone."] },

{ sig: "multiply-by-1001", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Find the value of the product below.", stemEq: "i_1001",
  opts: ["372 037", "372 372", "373 372", "375 372"], ans: 1,
  trick: "1001 = 1000 + 1, so multiplying a three-digit number by 1001 just writes that number twice — recognise it and the question costs three seconds",
  why: "372 × 1001 = 372 000 + 372 = 372 372.",
  traps: ["A: the 372 added into the wrong place value.",
          "C: 1000 carried in as 1001 twice.",
          "D: a carry invented in the thousands column."] },

{ sig: "count-hundreds-in-number", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "How many complete hundreds are there in 75 632?",
  opts: ["6", "75", "756", "7563"], ans: 2,
  trick: "the question asks how many hundreds are IN the number, not which digit sits in the hundreds column — divide by 100 and drop the remainder",
  why: "75 632 ÷ 100 = 756 with 32 left over, so there are 756 complete hundreds.",
  traps: ["A: the hundreds DIGIT read off instead.",
          "B: the number of thousands given.",
          "D: divided by 10 instead of 100."] },

{ sig: "divisible-by-digit-sum", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "Which of the following numbers is divisible by the sum of its own digits?",
  opts: ["121", "132", "142", "155"], ans: 1,
  trick: "add the digits FIRST, then divide once — testing each option by long division is four divisions where one addition would have chosen for you",
  why: "1 + 3 + 2 = 6 and 132 ÷ 6 = 22 exactly. The others give 121 ÷ 4, 142 ÷ 7 and 155 ÷ 11, none of which is a whole number.",
  traps: ["A: 121 assumed to work because it is 11².",
          "C: 142 ÷ 7 rounded to 20.",
          "D: 155 ÷ 11 rounded to 14."] },

{ sig: "divisibility-by-9-find-digit", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "The four-digit number below is divisible by 9. Find the digit q.",
  stemEq: "i_num9",
  opts: ["3", "4", "5", "8"], ans: 2,
  trick: "for 9 the DIGIT SUM must be a multiple of 9 — write 8 + 2q and hunt for the multiple, rather than testing four whole numbers",
  why: "The digit sum is 2 + q + q + 6 = 8 + 2q. Only q = 5 makes it a multiple of 9 (18), and 2556 ÷ 9 = 284.",
  traps: ["A: the rule for 3 used instead of the rule for 9.",
          "B: q counted once rather than twice.",
          "D: the digit sum taken as 8 + q."] },

{ sig: "fraction-percent-to-decimal", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Write the quantity below as a decimal.", stemEq: "i_frac34",
  opts: ["0.0075", "0.075", "0.75", "7.5"], ans: 0,
  trick: "there are TWO steps hiding here — turn the fraction into 0.75 and then divide by 100 for the percent sign. Stopping after one of them is the whole point of the question",
  why: "¾% = 0.75% = 0.75 ÷ 100 = 0.0075.",
  traps: ["B: divided by 10 instead of 100.",
          "C: the percent sign simply ignored.",
          "D: the percent sign dropped and the fraction inverted."] },

{ sig: "decimal-multiply-then-add", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Use the values below.", stemEq: "i_dec_abc",
  opts: ["0.0052", "0.052", "0.082", "0.52"], ans: 1,
  trick: "count decimal places in the PRODUCT before you add — 0.06 × 0.5 has three places, and it is the count, not the digits, that goes wrong",
  why: "0.06 × 0.5 = 0.03, and 0.03 + 0.022 = 0.052.",
  traps: ["A: one decimal place too many carried through.",
          "C: the three numbers added without multiplying.",
          "D: one decimal place too few in the product."] },

{ sig: "sum-symmetric-pairing", code: "GAT-Q-ARI.5", lvl: 1,
  stem: "Find the value of the sum below.", stemEq: "i_symsum",
  opts: ["21", "36", "42", "48"], ans: 2,
  trick: "the list runs up and straight back down, so it is twice the sum of 1 to 6 — see the mirror and you never add twelve numbers",
  why: "1 + 2 + … + 6 = 21, and the sum is that twice: 42.",
  traps: ["A: only one half of the list added.",
          "B: the two 6s counted once.",
          "D: 1 to 6 added twice and 6 added a third time."] },

{ sig: "percent-discount-with-cap", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "A shop offers 15% off, but the discount on any one purchase is capped at 150 SAR. A customer buys goods worth 1 200 SAR. How much does he pay, in riyals?",
  opts: ["1 020", "1 050", "1 150", "1 185"], ans: 1,
  trick: "work out the percentage, then CHECK it against the cap — a capped offer is not a percentage offer once the bill is large enough",
  why: "15% of 1 200 is 180 SAR, which is above the 150 SAR cap, so only 150 is taken off: 1 200 − 150 = 1 050 SAR.",
  traps: ["A: the cap ignored and the full 180 taken off.",
          "C: the cap read as 50 SAR.",
          "D: 15 riyals taken off instead of 15%."] },

{ sig: "compare-near-one-fractions", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Which quantity is greater?", stemEq: "i_cmp_near",
  opts: ["A is greater", "B is greater", "they are equal", "not enough information"], ans: 0,
  trick: "write each one as 1 plus a bit: the bit is 1/99 against 1/999, and the bigger bottom makes the SMALLER bit. Bigger numbers do not mean a bigger fraction",
  why: "100/99 = 1 + 1/99 and 1000/999 = 1 + 1/999. Since 1/99 > 1/999, A is greater.",
  traps: ["B: the larger numerator and denominator read as the larger value.",
          "C: both dismissed as 'about 1'.",
          "D: both are exact numbers, so a comparison is always possible."] },

{ sig: "divide-by-zero-undefined", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Let x be any number other than zero. Which statement about the two expressions below is correct?",
  stemEq: "i_zerodiv",
  opts: ["Both equal zero", "A equals zero and B is undefined",
         "A is undefined and B equals zero", "Both are undefined"], ans: 1,
  trick: "zero on TOP is fine and gives zero; zero on the BOTTOM is not a number at all — the order of the two decides everything",
  why: "0 ÷ x = 0 for every non-zero x, while x ÷ 0 has no value: no number multiplied by 0 gives x.",
  traps: ["A: division by zero treated as giving zero.",
          "C: the two expressions read the wrong way round.",
          "D: any appearance of 0 assumed to make an expression undefined."] },

{ sig: "quotient-of-two-primes", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "A prime number is divided by a different prime number. Which of the following describes the result?",
  opts: ["Always a whole number", "Always a prime number",
         "Always a fraction that cannot be simplified", "Always greater than 1"], ans: 2,
  trick: "two DIFFERENT primes share no factor except 1, so the fraction is already in lowest terms and can never cancel to a whole number",
  why: "Different primes have no common factor, so the quotient is a fraction in lowest terms — 3 ÷ 7 or 7 ÷ 3, never a whole number.",
  traps: ["A: 'prime ÷ prime' confused with 'prime × prime'.",
          "B: a prime numerator assumed to make a prime result.",
          "D: only the case where the larger prime is on top considered."] },

{ sig: "count-digits-in-range", code: "GAT-Q-ARI.3", lvl: 3,
  stem: "A student writes out every whole number from 1 to 200. How many digits does he write altogether?",
  opts: ["200", "483", "492", "600"], ans: 2,
  trick: "split the run by how many digits the numbers have — 1 to 9, then 10 to 99, then 100 to 200 — and count each block separately",
  why: "9 numbers of one digit (9), 90 of two digits (180) and 101 of three digits (303) give 9 + 180 + 303 = 492 digits.",
  traps: ["A: the numbers counted instead of the digits.",
          "B: 100 numbers counted in the last block instead of 101.",
          "D: every number treated as three digits."] },

{ sig: "count-common-multiples", code: "GAT-Q-ARI.2", lvl: 2,
  stem: "How many whole numbers less than 100 are multiples of both 6 and 8?",
  opts: ["3", "4", "6", "12"], ans: 1,
  trick: "a number in both lists is a multiple of the LCM, not of 6 × 8 — take the LCM first and then count",
  why: "The LCM of 6 and 8 is 24, and the multiples of 24 below 100 are 24, 48, 72 and 96: four numbers.",
  traps: ["A: 96 missed at the top of the range.",
          "C: 6 × 8 = 48 used but counted as if the step were 16.",
          "D: the multiples of 8 alone counted."] },

{ sig: "second-difference-sequence", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "Find the missing term in the pattern below.", stemEq: "i_seq2nd",
  opts: ["40", "42", "44", "46"], ans: 1,
  trick: "the gaps are not equal, so look at the gaps BETWEEN the gaps — here they shrink by 2 each time, so work backwards from the end where the numbers are known",
  why: "The known gaps are −6 then −4, shrinking by 2, so the gap before them is −8 and the one before that −10. From 34 back: 34 + 8 = 42, and 52 − 10 = 42 confirms it.",
  traps: ["A: a constant gap of −6 assumed.",
          "C: the gap taken as −10 in the wrong place.",
          "D: the average of 52 and 34 given."] },

{ sig: "reverse-square-sequence", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "Find the seventh term of the pattern below.", stemEq: "i_seqsq",
  opts: ["49", "64", "81", "100"], ans: 1,
  trick: "these are squares, but they start at 2² — so the nth term is (n + 1)², and counting from 1² is exactly the slip the item is set for",
  why: "The terms are 2², 3², 4², 5², … so the seventh is 8² = 64.",
  traps: ["A: 7² given, counting the squares from 1².",
          "C: 9², one term too far.",
          "D: 10², the tenth square rather than the seventh term."] },

// ================================================================= ALGEBRA
{ sig: "n-to-the-n-sequence", code: "GAT-Q-ARI.5", lvl: 3,
  stem: "Find the missing term in the sequence below.", stemEq: "i_seq_nn",
  opts: ["64", "125", "256", "625"], ans: 2,
  trick: "when the terms grow far too fast for a common difference or ratio, test the position against itself — 1¹, 2², 3³ — because nⁿ is the pattern the paper hides here",
  why: "The terms are 1¹ = 1, 2² = 4, 3³ = 27, 4⁴ = 256 and 5⁵ = 3125, so the missing term is 256.",
  traps: ["A: 4³ used, the exponent left at 3.",
          "B: 5³ used.",
          "D: 5⁴ used, base and exponent swapped."] },

{ sig: "zero-product-inference", code: "GAT-Q-ALG.3", lvl: 2,
  stem: "Use the two statements below to decide which variable must be zero.",
  stemEq: "i_zeroprod",
  opts: ["ℓ", "m", "n", "k"], ans: 3,
  trick: "a product is zero only if one factor is zero — and the second statement tells you the other three multiply to 1, so none of THEM can be it",
  why: "ℓmn = 1 means none of ℓ, m, n is zero. Since kℓmn = 0, the zero factor must be k.",
  traps: ["A: ℓ chosen, ignoring that ℓmn = 1 keeps every one of those three away from zero.",
          "B: m chosen for the same reason.",
          "C: n chosen, the last factor read as the one that must vanish."] },

{ sig: "recurrence-sign-flip", code: "GAT-Q-ALG.5", lvl: 3,
  stem: "A sequence is defined by the rule below. Find its tenth term.",
  stemEq: "i_recur",
  opts: ["−11", "−8", "3", "11"], ans: 3,
  trick: "write out four terms before you reach for a formula — a rule that flips the sign repeats every two steps, so only 'odd or even' matters",
  why: "a₁ = −8, a₂ = 8 + 3 = 11, a₃ = −11 + 3 = −8, a₄ = 11. The sequence alternates, so every even term is 11 and a₁₀ = 11.",
  traps: ["A: the sign flipped once too often.",
          "B: the odd-position value given.",
          "C: only the +3 applied and the sign flip dropped."] },

{ sig: "product-and-difference-of-squares", code: "GAT-Q-ALG.3", lvl: 3,
  stem: "Two positive numbers satisfy the statements below. Find the larger number.",
  stemEq: "i_prodsq",
  opts: ["3", "6", "9", "18"], ans: 1,
  trick: "small whole-number factor pairs are faster than algebra here — list the pairs multiplying to 18 and test the difference of squares on each",
  why: "The factor pairs of 18 are 1 and 18, 2 and 9, 3 and 6. Only 6 and 3 give 6² − 3² = 36 − 9 = 27, so the larger number is 6.",
  traps: ["A: the smaller number given.",
          "C: 9 taken from the pair 2 and 9 without checking the difference.",
          "D: the product itself given."] },

{ sig: "fraction-transform-system", code: "GAT-Q-ALG.2", lvl: 3,
  stem: "Two conditions on a fraction are given below. Find the fraction.",
  stemEq: "i_fracsys",
  opts: [{ eq: "i_o_f1" }, { eq: "i_o_f2" }, { eq: "i_o_f3" }, { eq: "i_o_f4" }], ans: 1,
  trick: "clear each fraction into a straight line first — a system dressed as fractions is an ordinary pair of linear equations once the bottoms are gone",
  why: "p + 2 = q + 1 gives p = q − 1, and p − 1 = 2(q − 3) then gives q − 2 = 2q − 6, so q = 4 and p = 3. The fraction is ¾.",
  traps: ["A: p and q read the wrong way round.",
          "C: the second condition solved as p − 1 = 2q − 3.",
          "D: q found correctly but p taken as q − 2."] },

{ sig: "translate-verbal-to-equation", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "The product of two numbers is seven less than five times their sum. Which equation says this?",
  opts: [{ eq: "i_o_v3" }, { eq: "i_o_v1" }, { eq: "i_o_v4" }, { eq: "i_o_v2" }], ans: 1,
  trick: "'seven less than' means the seven is SUBTRACTED from what follows, not the other way round — and 'their sum' needs brackets before it is multiplied",
  why: "Five times their sum is 5(x + y); seven less than that is 5(x + y) − 7, and that equals the product xy.",
  traps: ["A: the brackets dropped, so only x is multiplied by 5.",
          "C: 'sum' read as 'difference'.",
          "D: 'seven less than' reversed into 7 minus the expression."] },

{ sig: "chain-substitution-sum", code: "GAT-Q-ALG.2", lvl: 2,
  stem: "Use the three statements below to find the value of A + D.",
  stemEq: "i_chain",
  opts: ["6", "8", "9", "11"], ans: 2,
  trick: "you are not asked for A or for D, so do not solve for them — add the equations so that B and C cancel and the pair you want survives",
  why: "Adding all three gives (A − B) + (B − C) + (C + D) = A + D = 5 + 3 + 1 = 9.",
  traps: ["A: only the first two constants added.",
          "B: A − C = 8 given instead of A + D.",
          "D: the last equation used as C − D = 1."] },

{ sig: "fraction-of-number-given", code: "GAT-Q-ALG.5", lvl: 1,
  stem: "Find the number N from the statement below.", stemEq: "i_third_of",
  opts: ["1", "2", "5", "6"], ans: 1,
  trick: "to undo 'one third of', multiply by 3 — do it to the value on the right, not to the fraction on the left",
  why: "N = 3 × ⅔ = 2.",
  traps: ["A: ⅓ and ⅔ cancelled to 1.",
          "C: 10/15 left unsimplified and read as 5.",
          "D: the denominators multiplied, 3 × 2."] },

{ sig: "consecutive-product-equals-sum", code: "GAT-Q-ALG.3", lvl: 3,
  stem: "The product of three consecutive integers equals five times their sum. Find the smallest of the three.",
  stemEq: "i_prodsum3",
  opts: ["2", "3", "4", "5"], ans: 1,
  trick: "call the MIDDLE one n — the sum is then 3n and the outer two are n − 1 and n + 1, so the whole equation collapses to n² − 1 = 15",
  why: "(n − 1)n(n + 1) = 5(3n) gives n(n² − 1) = 15n, so n² = 16 and n = 4. The integers are 3, 4, 5 and the smallest is 3.",
  traps: ["A: the answer read off from the sum 15 ÷ 5.",
          "C: the middle integer given.",
          "D: the largest integer given."] },

{ sig: "consecutive-from-product", code: "GAT-Q-ALG.3", lvl: 2,
  stem: "Three consecutive whole numbers, one of which is 11, have a product of 990. Find their sum.",
  opts: ["27", "30", "33", "36"], ans: 1,
  trick: "the three numbers are close to the cube root of the product — ∛990 is just under 10, so try 9, 10, 11 before doing any algebra",
  why: "9 × 10 × 11 = 990, so the sum is 9 + 10 + 11 = 30.",
  traps: ["A: 8, 9, 10 tried without checking the product.",
          "C: 10, 11, 12 used, so 11 is not the largest.",
          "D: 11, 12, 13 used."] },

{ sig: "quadratic-lost-root", code: "GAT-Q-ALG.3", lvl: 2,
  stem: "Solve the equation below for n.", stemEq: "i_quadtrap",
  opts: ["n = 4 only", "n = 0 only", "n = 0 and n = 4", "no solution"], ans: 2,
  trick: "never divide both sides by n — n could be zero, and dividing throws that root away. Bring everything to one side and factor instead",
  why: "10n + n² = 14n gives n² − 4n = 0, so n(n − 4) = 0 and n is 0 or 4.",
  traps: ["A: both sides divided by n, losing n = 0 — the trap this item exists for.",
          "B: the factor n − 4 dropped.",
          "D: the 10n on each side read as cancelling the whole equation."] },

{ sig: "three-pair-sums-system", code: "GAT-Q-ALG.2", lvl: 2,
  stem: "Three partners hold shares worth, in millions of riyals: Ahmed and Khalid together 12, Khalid and Mohammed together 15, Ahmed and Mohammed together 19. How many millions does Khalid hold?",
  opts: ["3", "4", "8", "11"], ans: 1,
  trick: "add all three pair totals: every partner is counted exactly twice, so half that sum is the whole group — then subtract the pair that leaves out the one you want",
  why: "The three totals add to 46, which counts each partner twice, so all three together hold 23. Khalid is 23 − 19 = 4 million riyals.",
  traps: ["A: 46 halved and then divided by 3.",
          "C: the pair 12 subtracted instead of 19.",
          "D: 23 − 12 given, which is Mohammed's share."] },

// ================================================================ GEOMETRY
{ sig: "surface-area-rectangular-prism", code: "GAT-Q-GEO.5", lvl: 2,
  stem: "A rectangular box has edges 5 cm, 2 cm and 2 cm. Find its total surface area, in square centimetres.",
  opts: ["20", "40", "48", "52"], ans: 2,
  trick: "there are three DIFFERENT faces and each appears twice — find the three areas, add, then double, in that order",
  why: "The three distinct faces are 5 × 2 = 10, 5 × 2 = 10 and 2 × 2 = 4. Their total is 24, and doubling gives 48 cm².",
  traps: ["A: the volume given, 5 × 2 × 2.",
          "B: the three faces added and doubled but the square face left out.",
          "D: the square face counted four times."] },

{ sig: "rectangle-axes-of-symmetry", code: "GAT-Q-GEO.4", lvl: 1,
  stem: "How many axes of symmetry does a rectangle that is not a square have?",
  opts: ["1", "2", "4", "Infinitely many"], ans: 1,
  trick: "fold it — the two lines through the midpoints of opposite sides work, but the diagonals do NOT, which is exactly where a square is different",
  why: "Only the two lines joining the midpoints of opposite sides map a rectangle onto itself: two axes.",
  traps: ["A: only the longer axis counted.",
          "C: the diagonals wrongly included, giving a square's four axes.",
          "D: a circle's property applied."] },

{ sig: "circles-packed-in-rectangle", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "The rectangle below measures 6 cm by 4 cm and holds six equal circles arranged three by two, each touching its neighbours and the sides. Find the diameter of one circle, in centimetres.",
  fig: "i_circles_grid", figW: 2.15,
  opts: ["1", "1.5", "2", "3"], ans: 2,
  trick: "read the diameter off EITHER side — three circles fill the 6 and two fill the 4, and both give the same answer, which is your check",
  why: "Three diameters span 6 cm, so the diameter is 2 cm; two diameters span 4 cm, which agrees.",
  traps: ["A: the radius halved a second time.",
          "B: 6 divided by 4.",
          "D: the radius given as 3 from 6 ÷ 2, one circle per side assumed."] },

{ sig: "lshape-area-from-outer-sides", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "All the sides of the shape below meet at right angles, and the lengths shown are in centimetres. Find its area, in square centimetres.",
  fig: "i_lshape", figW: 1.95,
  opts: ["14", "15", "16", "20"], ans: 2,
  trick: "complete it to the full 5 by 4 rectangle and take the missing corner off — the two unlabelled edges are then differences you never have to name",
  why: "The enclosing rectangle is 5 × 4 = 20 cm² and the missing corner is 2 × 2 = 4 cm², so the area is 16 cm².",
  traps: ["A: the corner taken as 3 × 2.",
          "B: the four labels added as a perimeter of sorts.",
          "D: the corner never removed."] },

{ sig: "wire-reshape-perimeter", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "A wire bent into a square of side 9 cm is straightened and bent again into an equilateral triangle. Find the length of each side of the triangle, in centimetres.",
  opts: ["9", "12", "18", "27"], ans: 1,
  trick: "the wire's LENGTH does not change — the perimeter is the bridge between the two shapes, and the area has nothing to do with it",
  why: "The square's perimeter is 4 × 9 = 36 cm, so each side of the triangle is 36 ÷ 3 = 12 cm.",
  traps: ["A: the side copied straight across.",
          "C: the perimeter halved instead of divided by 3.",
          "D: the perimeter divided by 4 again after being found."] },

{ sig: "cube-face-perimeter-equals-area", code: "GAT-Q-GEO.5", lvl: 3,
  stem: "In a cube, the perimeter of one face is numerically equal to the area of that face. Find the volume of the cube, in cubic units.",
  opts: ["16", "27", "64", "96"], ans: 2,
  trick: "set the two expressions equal as NUMBERS — 4s = s² gives the edge, and only then go to the volume",
  why: "4s = s² gives s = 4, so the volume is 4³ = 64.",
  traps: ["A: the face area given instead of the volume.",
          "B: the edge taken as 3.",
          "D: the total surface area given, 6 × 16."] },

{ sig: "diagonals-sum-vs-perimeter", code: "GAT-Q-GEO.4", lvl: 3,
  stem: "For any square, compare the sum of the two diagonals with the perimeter.",
  opts: ["The sum of the diagonals is greater", "The perimeter is greater",
         "They are equal", "It depends on the side length"], ans: 1,
  trick: "write both in terms of the side: 2s√2 against 4s. The s cancels, so one answer covers EVERY square and 'it depends' is never right",
  why: "Each diagonal is s√2, so the two together are 2s√2 ≈ 2.83s, while the perimeter is 4s. The perimeter is greater.",
  traps: ["A: √2 taken as about 2, giving 4s and then rounded upward.",
          "C: the two assumed to balance.",
          "D: the side treated as if it did not cancel."] },

{ sig: "triangles-from-both-diagonals", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "Both diagonals of the rectangle below are drawn. How many triangles appear in the figure altogether?",
  fig: "l_rect_diagonals", figW: 1.9,
  opts: ["4", "6", "8", "10"], ans: 2,
  trick: "count the small ones first, then the ones made of two smalls — the large triangles cut by a single diagonal are the ones everybody forgets",
  why: "The diagonals cut the rectangle into 4 small triangles, and each diagonal also splits the rectangle into 2 large ones: 4 + 4 = 8.",
  traps: ["A: only the four small triangles counted.",
          "B: two of the large triangles missed.",
          "D: two triangles counted twice."] },

{ sig: "isoperimetric-circle-vs-square", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "A wire of fixed length is bent once into a circle and once into a square. Which shape encloses the larger area?",
  opts: ["The square", "The circle", "They enclose equal areas", "It depends on the length of the wire"], ans: 1,
  trick: "for a fixed perimeter the circle always wins — the more corners a shape loses, the more area it holds, and the length of the wire never changes that",
  why: "With perimeter P the square encloses P²/16 ≈ 0.0625P² and the circle P²/4π ≈ 0.0796P². The circle is larger, whatever P is.",
  traps: ["A: the square's right angles read as making it the fuller shape.",
          "C: equal perimeter assumed to mean equal area.",
          "D: P² is a common factor, so the comparison does not depend on P."] },

{ sig: "count-small-cubes-in-cube", code: "GAT-Q-GEO.5", lvl: 2,
  stem: "How many cubes of edge 0.5 cm are needed to fill a cube of edge 1.5 cm completely?",
  opts: ["3", "9", "27", "81"], ans: 2,
  trick: "scale the EDGE first, then cube it — three along each edge means 3³, not 3",
  why: "1.5 ÷ 0.5 = 3 small cubes along each edge, so 3³ = 27 are needed.",
  traps: ["A: only one edge counted.",
          "B: the face count 3² given.",
          "D: the ratio taken as 3 and then raised to the fourth power."] },

{ sig: "complementary-angles-solve", code: "GAT-Q-GEO.1", lvl: 1,
  stem: "Two complementary angles measure 6s degrees and (4s − 20) degrees. Find s.",
  opts: ["9", "11", "17", "20"], ans: 1,
  trick: "complementary means 90°, supplementary means 180° — the whole item turns on which of the two words is on the page",
  why: "6s + 4s − 20 = 90 gives 10s = 110, so s = 11.",
  traps: ["A: 180° used instead of 90° and then mis-simplified.",
          "C: 180° used, giving 10s = 200.",
          "D: the −20 added rather than subtracted."] },

// ===================================================================== DATA
{ sig: "median-with-unknown-value", code: "GAT-Q-DAT.5", lvl: 3,
  stem: "The median of the five numbers 12, 11, 5, 2 and s is 6. Find s.",
  opts: ["4", "6", "7", "9"], ans: 1,
  trick: "order the four known values first and ask where s would have to sit for the MIDDLE one to be 6 — the answer only works if s itself is the middle value",
  why: "Ordered, the known values are 2, 5, 11, 12. For the middle of five to be 6, s must be that middle value, so s = 6 and the list is 2, 5, 6, 11, 12.",
  traps: ["A: s = 4 gives the list 2, 4, 5, 11, 12 with median 5.",
          "C: the mean confused with the median.",
          "D: s = 9 gives median 9."] },

{ sig: "median-from-mean-and-mode", code: "GAT-Q-DAT.5", lvl: 3,
  stem: "Five natural numbers have smallest value 2, mode 7 and mean 6. Find the median.",
  opts: ["5", "6", "7", "8"], ans: 2,
  trick: "the mean gives the TOTAL, and the mode tells you 7 appears at least twice — place those two 7s in the ordered list and the middle position is already fixed",
  why: "The five numbers total 5 × 6 = 30 and include at least two 7s. With 2 as the smallest and the remaining values summing to 16 without creating a second mode, the two 7s always occupy the third and fourth places, so the median is 7. (For example 2, 5, 7, 7, 9 or 2, 3, 7, 7, 11.)",
  traps: ["A: the mean of the smaller values given.",
          "B: the mean given as the median.",
          "D: the mode assumed to sit above the median."] },

{ sig: "weighted-percent-two-groups", code: "GAT-Q-DAT.5", lvl: 3,
  stem: "One company has 200 employees, 30% of them non-Saudi. A second has 300 employees, 20% of them non-Saudi. What percentage of the two companies' employees together are non-Saudi?",
  opts: ["22%", "24%", "25%", "26%"], ans: 1,
  trick: "percentages of different-sized groups cannot be averaged — go back to COUNTS, add them, and only then divide by the combined total",
  why: "30% of 200 is 60 and 20% of 300 is 60, so 120 of 500 employees are non-Saudi: 120 ÷ 500 = 24%.",
  traps: ["A: the two percentages weighted the wrong way round.",
          "C: 30% and 20% simply averaged — the trap this item exists for.",
          "D: 120 divided by 460."] },

{ sig: "counts-from-probability-fraction", code: "GAT-Q-DAT.3", lvl: 2,
  stem: "A bag holds 40 balls, each red, yellow or green. The probability of drawing a red ball is 2/5. How many balls are yellow or green?",
  opts: ["16", "20", "24", "28"], ans: 2,
  trick: "turn the probability into a COUNT before anything else, then subtract from the total — the two other colours never need separating",
  why: "Red balls number ⅖ × 40 = 16, so the other two colours account for 40 − 16 = 24 balls.",
  traps: ["A: the number of red balls given.",
          "B: 40 halved.",
          "D: ⅖ read as 30% of 40."] },

{ sig: "score-needed-for-target-percent", code: "GAT-Q-DAT.5", lvl: 3,
  stem: "A test has 80 questions. A student answered 30 of the first 40 correctly. How many of the remaining 40 must he answer correctly for his overall score to be 80%?",
  opts: ["32", "34", "36", "40"], ans: 1,
  trick: "work in MARKS, not in percentages — find the total needed for 80% of the whole paper and take off what is already banked",
  why: "80% of 80 questions is 64 correct answers. He has 30, so he needs 64 − 30 = 34 of the remaining 40.",
  traps: ["A: 80% of the remaining 40 taken.",
          "C: the first 40 assumed to be worth 75% and the shortfall miscounted.",
          "D: all the remaining questions assumed necessary."] },

{ sig: "count-graph-intersections", code: "GAT-Q-DAT.1", lvl: 1,
  stem: "The graph below shows the weights of two students recorded over twelve months. On how many occasions during that year did the two weigh the same?",
  fig: "i_two_curves", figW: 2.6,
  opts: ["2", "3", "4", "5"], ans: 2,
  trick: "count where the two lines CROSS, not where either one peaks — a question about 'the same' is always about intersections",
  why: "The two curves cross four times, at roughly months 1, 4, 8 and 11.",
  traps: ["A: only the crossings in the first half counted.",
          "B: one crossing missed where the curves meet steeply.",
          "D: a point where the curves come close but do not meet counted as a crossing."] },

// ================================================================ WORD LOGIC
{ sig: "profit-percent-from-quantity-pricing", code: "GAT-Q-LOG.4", lvl: 3,
  stem: "A trader sold 16 toys for the price at which he had bought 20 toys. What was his percentage profit?",
  opts: ["20%", "25%", "80%", "125%"], ans: 1,
  trick: "profit percent is always measured against the COST — he received the cost of 20 for goods costing 16, so the gain is 4 on 16, not 4 on 20",
  why: "Taking the cost of one toy as 1, he paid 16 and received 20, so the profit is 4 on a cost of 16: 4 ÷ 16 = 25%.",
  traps: ["A: the gain of 4 divided by the selling total 20.",
          "C: 16 divided by 20.",
          "D: the ratio 20 ÷ 16 given as the profit."] },

{ sig: "minutes-to-clock-time", code: "GAT-Q-LOG.1", lvl: 2,
  stem: "It is 8:00 a.m. What will the clock read after 5 400 minutes have passed?",
  opts: ["8 p.m.", "2 a.m.", "2 p.m.", "6 a.m."], ans: 1,
  trick: "convert to hours, then throw away whole DAYS — only the remainder after dividing by 24 moves the clock",
  why: "5 400 ÷ 60 = 90 hours, and 90 = 3 × 24 + 18, so the clock advances 18 hours from 8:00 a.m. to 2:00 a.m.",
  traps: ["A: 12 hours added instead of 18.",
          "C: the a.m./p.m. half-day lost.",
          "D: 90 hours reduced modulo 12 rather than 24."] },

{ sig: "inheritance-double-shares", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "An amount of 84 000 SAR is divided among two sons and three daughters so that each son receives twice what each daughter receives. How many riyals does one daughter receive?",
  opts: ["8 000", "12 000", "14 000", "24 000"], ans: 1,
  trick: "count the PARTS before the money — each son is 2 parts and each daughter 1, so the amount is split into 2(2) + 3(1) = 7 parts, not into 5 shares",
  why: "There are 4 + 3 = 7 equal parts, so one part is 84 000 ÷ 7 = 12 000 SAR, which is one daughter's share.",
  traps: ["A: divided among 5 children and then halved.",
          "C: divided by 6 parts, the sons counted once each.",
          "D: one son's share given."] },

{ sig: "ceiling-billing-per-hour", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "A car park charges 5 SAR for each hour or part of an hour. A car is parked from 9:20 a.m. until 1:05 p.m. What is the charge, in riyals?",
  opts: ["15", "19", "20", "25"], ans: 2,
  trick: "'or part of an hour' means round UP, never to the nearest — three hours and forty-five minutes is charged as four",
  why: "The stay is 3 hours 45 minutes, which is charged as 4 hours: 4 × 5 = 20 SAR.",
  traps: ["A: rounded down to 3 hours.",
          "B: charged by the minute at a pro-rata rate.",
          "D: rounded up to 5 hours."] },

{ sig: "meeting-with-staggered-start", code: "GAT-Q-LOG.1", lvl: 3,
  stem: "Two cities are 340 km apart. A car leaves the first at 8:00 a.m. travelling at 60 km/h. A second car leaves the other city at 9:00 a.m. travelling towards it at 80 km/h. At what time do they meet?",
  opts: ["10:00 a.m.", "10:30 a.m.", "11:00 a.m.", "11:30 a.m."], ans: 2,
  trick: "deal with the head start FIRST — take off the distance the early car has already covered, and only then add the two speeds into a closing speed",
  why: "By 9:00 a.m. the first car has covered 60 km, leaving 280 km. The cars close at 60 + 80 = 140 km/h, so they meet 280 ÷ 140 = 2 hours later, at 11:00 a.m.",
  traps: ["A: the head start ignored, giving 340 ÷ 140.",
          "B: the closing speed taken as 80 − 60.",
          "D: an extra hour added for the head start twice."] },

{ sig: "doubling-pages-cumulative", code: "GAT-Q-LOG.2", lvl: 3,
  stem: "A book has 155 pages. A student reads 5 pages on Saturday and doubles the number of pages he reads each day after that. On which day does he finish the book?",
  opts: ["Tuesday", "Wednesday", "Thursday", "Friday"], ans: 1,
  trick: "add a RUNNING total, not the daily figure — a doubling total always passes the target one day earlier than the daily numbers suggest",
  why: "The daily pages are 5, 10, 20, 40, 80 and the running totals 5, 15, 35, 75, 155. The fifth day, counting Saturday as the first, is Wednesday.",
  traps: ["A: the totals stopped at 75 on the fourth day.",
          "C: Saturday counted as day zero.",
          "D: the daily figures added as if reading began on Sunday."] },

];
