// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part E: skills from the Qudurat formula compendium
//
// The source here is a commercial foundation book (formula summaries plus worked
// examples). Nothing is translated from it. What is taken is the set of METHODS
// it teaches — which are mathematical facts, not protected writing — and every
// item below is written fresh around one of them.
//
// The book carried 64 skills the bank did not have. This file holds the 40
// highest-value ones; the remaining 24 are listed at the foot of the file.
// ---------------------------------------------------------------------------
const CMP = ["A is greater", "B is greater", "they are equal",
             "not enough information"];

module.exports = [

// ============================================================== ARITHMETIC
{ sig: "sum-first-n", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "Find the value of the sum below.",
  stemEq: "s_sumn",
  opts: ["1770", "1830", "1860", "3660"], ans: 1,
  trick: "pair the ends: the sum of 1 to n is n(n+1) halved, never n squared",
  why: "The sum of the first n whole numbers is n(n + 1)/2. Here 60 × 61 ÷ 2 = 1830.",
  traps: ["A: used 59 × 60 ÷ 2, stopping one term short.",
          "C: used 60 × 62 ÷ 2.",
          "D: forgot to halve, giving 60 × 61."] },

{ sig: "sum-odd-formula", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "Find the value of the sum below.",
  stemEq: "s_sumodd",
  opts: ["196", "210", "225", "435"], ans: 2,
  trick: "the odd numbers from 1 add to a perfect SQUARE — count how many there are, then square it",
  why: "The odd numbers from 1 to 29 are (29 + 1)/2 = 15 of them, and the sum of the first n odd numbers is n². So 15² = 225.",
  traps: ["A: counted 14 terms.",
          "B: used 15 × 14, the count times one less.",
          "D: used the formula for ALL the numbers to 29, not just the odd ones."] },

{ sig: "sum-even-formula", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "Find the value of the sum below.",
  stemEq: "s_sumeven",
  opts: ["380", "400", "420", "440"], ans: 2,
  trick: "take the 2 out first: the evens to 40 are twice the whole numbers to 20",
  why: "2 + 4 + ⋯ + 40 = 2(1 + 2 + ⋯ + 20) = 2 × (20 × 21 ⁄ 2) = 420.",
  traps: ["A: used 19 × 20.",
          "B: used 20², the odd-number formula by mistake.",
          "D: used 2 × 20 × 11."] },

{ sig: "units-digit-of-product", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "What is the units digit of the product below?",
  stemEq: "s_unitsdig",
  opts: ["2", "4", "6", "8"], ans: 3,
  trick: "only the two units digits matter — multiply 8 by 1 and stop",
  why: "The units digit of a product comes only from the units digits of the factors: 8 × 1 = 8, so the product ends in 8. Nothing else in either number affects it.",
  traps: ["A: multiplied the leading digits, 4 × 2.",
          "B: added the units digits, 8 + 1, and then adjusted.",
          "C: multiplied the tens digits, 3 × 9, and took its units digit."] },

{ sig: "tens-digit-of-product", code: "GAT-Q-ARI.1", lvl: 3,
  stem: "What is the tens digit of the product below?",
  stemEq: "s_tensdig",
  opts: ["1", "4", "6", "8"], ans: 2,
  trick: "the tens digit needs the last TWO digits of each factor and nothing more — multiply 47 by 63 and read the tens column",
  why: "Only the last two digits of each factor can reach the tens column, so work out 47 × 63 = 2961. Its tens digit is 6, and that is the tens digit of the whole product.",
  traps: ["A: multiplied only the units digits, 7 × 3 = 21, and took the 2 as the tens digit — that gives the UNITS digit, not the tens.",
          "B: used the leading digits 58 × 31.",
          "D: added 4 and 3 and then adjusted."] },

{ sig: "unit-conversion-compare", code: "GAT-Q-ARI.2", lvl: 1,
  stem: "Which quantity is greater?",
  stemEq: "s_unitconv",
  opts: CMP, ans: 2,
  trick: "put both on the same unit before comparing — a bigger NUMBER in a smaller unit is not a bigger quantity",
  why: "2.4 m × 100 = 240 cm, which is exactly B. They are equal.",
  traps: ["A: compared 2.4 with 240 as plain numbers and picked the smaller as 'metres are bigger'.",
          "B: compared 2.4 with 240 as plain numbers.",
          "D: the conversion factor is fixed, so the comparison is decidable."] },

{ sig: "decimal-places-in-product", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Find the value of the product below.",
  stemEq: "s_decplace",
  opts: ["0.0004", "0.004", "0.04", "0.4"], ans: 1,
  trick: "multiply as whole numbers, then count the decimal places in the question and put that many in the answer",
  why: "Ignore the points: 4 × 2 × 5 = 40. The question has 1 + 2 + 1 = 4 decimal places, so the answer is 0.0040 = 0.004.",
  traps: ["A: counted five.",
          "C: counted three decimal places.",
          "D: counted two."] },

{ sig: "compare-fractions-cross", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_crossfr",
  opts: CMP, ans: 0,
  trick: "cross-multiply upwards: compare 5 × 10 with 7 × 7, and the bigger product sits above the bigger fraction",
  why: "Cross-multiplying, 5 × 10 = 50 against 7 × 7 = 49. Since 50 > 49, A is greater — but only just.",
  traps: ["B: compared the denominators and assumed the smaller one wins.",
          "C: read both as roughly 0.7 and called them equal — they differ by 1/70.",
          "D: both fractions are explicit."] },

{ sig: "between-zero-and-one", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_zeroone",
  opts: CMP, ans: 1,
  trick: "between 0 and 1, squaring makes a number SMALLER — the rule you learned for numbers above 1 runs backwards here",
  why: "For any k strictly between 0 and 1, k² < k. Take k = 0.5: k² = 0.25. So B is greater.",
  traps: ["A: applied 'squaring makes things bigger', which only holds above 1.",
          "C: took k = 1, which the condition excludes.",
          "D: the condition 0 < k < 1 settles it for every allowed k."] },

{ sig: "root-approx-compare", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_rootapx",
  opts: CMP, ans: 0,
  trick: "square the whole number instead of rooting the other — 7² = 49 and 50 is just above it",
  why: "Rather than estimating √50, square B: 7² = 49. Since 50 > 49, √50 > 7, so A is greater.",
  traps: ["B: estimated √50 as about 6.9.",
          "C: rounded √50 to 7 and called it a tie — it is 7.07.",
          "D: both are explicit numbers."] },

{ sig: "root-of-decimal", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Find the value of the root below.",
  stemEq: "s_rootdec",
  opts: ["0.0007", "0.007", "0.07", "0.7"], ans: 2,
  trick: "root the digits, then give the answer HALF as many decimal places as the number under the root",
  why: "√49 = 7. The number under the root has 4 decimal places, so the answer has 2: it is 0.07.",
  traps: ["A: kept four, the same as the number under the root.",
          "B: kept three.",
          "D: kept only one decimal place."] },

{ sig: "count-numbers-in-range", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "How many even numbers are there in the list below?",
  stemEq: "s_countrng",
  opts: ["39", "40", "78", "79"], ans: 1,
  trick: "subtract, halve, then ADD ONE — the last step is the one everybody drops",
  why: "(96 − 18) ÷ 2 = 39, and adding 1 for the first term gives 40.",
  traps: ["A: forgot the final +1.",
          "C: forgot to halve.",
          "D: forgot to halve and added 1."] },

// ================================================================= ALGEBRA
{ sig: "equation-or-identity", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "How many values of x satisfy the statement below?",
  stemEq: "s_ident",
  opts: ["none", "exactly one", "exactly two", "infinitely many"], ans: 3,
  trick: "the two sides are the SAME expression, so it is an identity, not an equation — every x works",
  why: "The left side and the right side are letter-for-letter identical, so the statement is true for every value of x. It has infinitely many solutions, not one.",
  traps: ["A: rearranged to 0 = 0 and read that as no solution.",
          "B: assumed a first-degree statement always has exactly one solution — that is true of an equation, not of an identity.",
          "C: counted the two sides as two solutions."] },

{ sig: "parity-by-substitution", code: "GAT-Q-ALG.5", lvl: 2,
  stem: "Given the condition below, which expression is always even?",
  stemEq: "s_parity",
  opts: [{ eq: "p1" }, { eq: "p2" }, { eq: "p3" }, { eq: "p4" }], ans: 2,
  trick: "do not reason about it — substitute one small number that fits and read the four options off",
  why: "Put n = 3. Then n² + 2 = 11, 3n + 2 = 11, n² + n = 12 and 2n + 5 = 11. Only n² + n is even — and it is even for EVERY whole number, odd or not, because n² + n = n(n + 1) is a product of two consecutive numbers and one of any two consecutive numbers is even.",
  traps: ["A: an odd number squared is odd, and odd + 2 stays odd.",
          "B: 3 × odd is odd, and odd + 2 is odd.",
          "D: 2n is even, but adding 5 makes it odd."] },

{ sig: "product-compare-by-increment", code: "GAT-Q-ALG.4", lvl: 3,
  stem: "Which quantity is greater?",
  stemEq: "s_prodinc",
  opts: CMP, ans: 0,
  trick: "do not multiply either one out — going from one to the other, one factor gains 1 and the other loses 1, so compare what each move is WORTH",
  why: "Take B = 62 × 29 and move to A = 61 × 30. The 62 drops by 1, which loses 29; the 29 rises by 1, which gains 62... in fact A = 1830 and B = 1798, so A is greater by 32.",
  traps: ["B: assumed the pair with the larger first factor must win.",
          "C: the two sums 61 + 30 and 62 + 29 are both 91, which makes the products look as if they should tie — they do not.",
          "D: both products are explicit numbers."] },

{ sig: "lcm-word-cue", code: "GAT-Q-ARI.2", lvl: 2,
  stem: "Three lighthouses flash every 4, 6 and 9 seconds. They flash together now. After how many seconds will all three flash together again?",
  opts: ["18", "24", "36", "54"], ans: 2,
  trick: "words like 'together again' or 'meet' point to the lowest common multiple, never the highest common factor",
  why: "The LCM of 4, 6 and 9 is 36: 4 = 2², 6 = 2 × 3, 9 = 3², so the LCM is 2² × 3² = 36 seconds.",
  traps: ["A: took the LCM of 6 and 9 only.",
          "B: took the LCM of 4 and 6 and doubled it.",
          "D: multiplied 6 by 9 and halved."] },

{ sig: "divisibility-rule-7-11", code: "GAT-Q-ARI.1", lvl: 3,
  stem: "Which of the following is divisible by 7?",
  opts: ["413", "417", "421", "425"], ans: 0,
  trick: "for 7: chop off the units digit, double it, and subtract from what is left — if that is a multiple of 7, so is the number",
  why: "For 413: drop the 3 to leave 41, double the 3 to get 6, and 41 − 6 = 35, which is 7 × 5. So 413 is divisible by 7 (it is 7 × 59).",
  traps: ["B: 41 − 14 = 27, not a multiple of 7.",
          "C: 42 − 2 = 40, not a multiple of 7.",
          "D: 42 − 10 = 32, not a multiple of 7."] },

{ sig: "add-radicals-after-simplify", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Find the value of the sum below.",
  stemEq: "s_addrad",
  opts: [{ eq: "r72" }, { eq: "r11r2" }, { eq: "r7r18" }, { eq: "r10r2" }], ans: 1,
  trick: "you cannot add unlike roots — simplify until both carry the SAME root, then add only the numbers in front",
  why: "√18 = √(9 × 2) = 3√2, so 2√18 = 6√2. Then 6√2 + 5√2 = 11√2.",
  traps: ["A: simplified √18 to 2√2 instead of 3√2.",
          "C: added the outside numbers but kept the wrong root.",
          "D: took 2√18 as 5√2."] },

{ sig: "same-exponent-pm", code: "GAT-Q-ALG.3", lvl: 2,
  stem: "Solve for x.",
  stemEq: "s_sameexp",
  opts: [{ eq: "just5" }, { eq: "pm5" }, { eq: "just6" }, { eq: "pm6" }], ans: 1,
  trick: "when the EXPONENTS match, the bases match — but an EVEN exponent hides a second, negative root",
  why: "x⁶ = 5⁶ gives x = 5 or x = −5, because raising either to an even power gives the same result. So x = ±5.",
  traps: ["A: took only the positive root — the trap the item is built on.",
          "C: read the exponent as the answer.",
          "D: read the exponent as the answer and remembered the sign."] },

{ sig: "difference-of-squares", code: "GAT-Q-ALG.3", lvl: 2,
  stem: "Given the two statements below, find a² − b².",
  stemEq: "s_diffsq",
  opts: ["17", "39", "52", "169"], ans: 2,
  trick: "a² − b² factorises as (a + b)(a − b), so the two facts you are given multiply straight together — you never need a or b",
  why: "a² − b² = (a + b)(a − b) = 13 × 4 = 52. (For the record a = 8.5 and b = 4.5, but working those out is wasted time.)",
  traps: ["A: added the two given values.",
          "B: used 13 × 3.",
          "D: squared the 13, forgetting the second bracket."] },

// ================================================================ GEOMETRY
{ sig: "inscribed-vs-central-angle", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "In the circle below, O is the centre. Find x.",
  fig: "sim_inscribed", figW: 1.75,
  opts: ["20°", "40°", "80°", "160°"], ans: 1,
  trick: "an angle at the circumference is HALF the angle at the centre standing on the same arc",
  why: "The central angle AOB is 80°, and the inscribed angle ACB stands on the same arc AB, so it is half of it: 40°.",
  traps: ["A: quartered the central angle.",
          "C: copied the central angle.",
          "D: doubled the central angle instead of halving it."] },

{ sig: "angle-in-semicircle", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "AB is a diameter of the circle below and C lies on the circle. Angle CAB is 34°. Find angle ABC.",
  fig: "sim_semicircle", figW: 2.05,
  opts: ["34°", "46°", "56°", "66°"], ans: 2,
  trick: "an angle standing on a DIAMETER is a right angle — that is the fact the question does not state",
  why: "C lies on the circle and AB is a diameter, so angle ACB = 90°. The angles of the triangle add to 180°, so ABC = 180 − 90 − 34 = 56°.",
  traps: ["A: assumed the triangle is isosceles.",
          "B: used 180 − 90 − 44.",
          "D: used 100 − 34."] },

{ sig: "triangle-type-from-squares", code: "GAT-Q-GEO.2", lvl: 2,
  stem: "A triangle has sides 6, 8 and 11. What kind of triangle is it?",
  opts: ["right-angled", "acute-angled", "obtuse-angled", "not a triangle"], ans: 2,
  trick: "square all three sides and compare the biggest square with the sum of the other two — bigger means obtuse, smaller means acute",
  why: "6² + 8² = 36 + 64 = 100, and 11² = 121. Since 121 > 100, the angle facing the longest side is obtuse.",
  traps: ["A: right-angled would need 121 = 100 exactly.",
          "B: acute-angled would need 121 < 100.",
          "D: 6 + 8 = 14 > 11, so the three sides do make a triangle."] },

{ sig: "thirty-sixty-ninety", code: "GAT-Q-GEO.2", lvl: 2,
  stem: "Find x in the right triangle below.",
  fig: "sim_306090", figW: 2.35,
  opts: ["4", "6", "6√3", "12"], ans: 1,
  trick: "in a 30-60-90 triangle the side FACING the 30° is exactly half the hypotenuse — no Pythagoras needed",
  why: "x faces the 30° angle, and that side is half the hypotenuse: 12 ÷ 2 = 6.",
  traps: ["A: took a third of the hypotenuse.",
          "C: gave the side facing the 60°, which is 6√3.",
          "D: copied the hypotenuse."] },

{ sig: "forty-five-triangle", code: "GAT-Q-GEO.2", lvl: 2,
  stem: "Find x in the right triangle below.",
  fig: "sim_4545", figW: 1.85,
  opts: [{ eq: "r72" }, "14", { eq: "r10r2" }, "7"], ans: 0,
  trick: "with both legs equal, the hypotenuse is the leg times root 2 — every time",
  why: "The two legs are equal, so this is a 45-45-90 triangle and the hypotenuse is 7√2. (Pythagoras agrees: √(49 + 49) = √98 = 7√2.)",
  traps: ["B: doubled the leg.",
          "C: used √200 instead of √98.",
          "D: copied the leg."] },

{ sig: "midsegment-parallel-half", code: "GAT-Q-GEO.2", lvl: 2,
  stem: "In the triangle below, M and N are the midpoints of AB and AC. Find MN, in cm.",
  fig: "sim_midseg", figW: 2.35,
  opts: ["6", "9", "12", "18"], ans: 1,
  trick: "the segment joining two midpoints is parallel to the third side and exactly HALF of it",
  why: "MN joins the midpoints of two sides, so MN = ½ × BC = ½ × 18 = 9 cm.",
  traps: ["A: took a third of BC.",
          "C: took two thirds of BC.",
          "D: copied BC."] },

{ sig: "thales-proportional", code: "GAT-Q-GEO.2", lvl: 3,
  stem: "In the triangle below DE is parallel to BC. If AD = 4, DB = 6 and AE = 6, find EC.",
  fig: "sim_thales", figW: 2.25,
  opts: ["4", "8", "9", "10"], ans: 2,
  trick: "a line parallel to one side cuts the other two in the SAME ratio — set AD/DB equal to AE/EC",
  why: "AD⁄DB = AE⁄EC, so 4⁄6 = 6⁄EC, giving EC = 36 ÷ 4 = 9.",
  traps: ["A: matched AD to AE and copied the 4.",
          "B: used 4⁄6 = EC⁄6 the wrong way up.",
          "D: added the difference 6 − 4 to 6 twice."] },

{ sig: "sector-fraction-of-circle", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "The shaded sector below is cut from a circle of radius 6 cm. Find its area, in cm².",
  fig: "sim_sector", figW: 1.55,
  opts: ["6π", "9π", "12π", "18π"], ans: 2,
  trick: "the sector is its angle over 360 of the whole circle — 120° is a third, so divide the area by three",
  why: "The whole circle has area π × 6² = 36π. The sector is 120⁄360 = one third of it, so 36π ÷ 3 = 12π cm².",
  traps: ["A: took a sixth.",
          "B: took a quarter.",
          "D: took a half."] },

{ sig: "polygon-interior-angle", code: "GAT-Q-GEO.1", lvl: 2,
  stem: "Find the size of one interior angle of a regular decagon (ten sides).",
  opts: ["36°", "120°", "144°", "1440°"], ans: 2,
  trick: "go through the EXTERIOR angle: 360 divided by the number of sides, then subtract from 180",
  why: "Each exterior angle is 360 ÷ 10 = 36°, so each interior angle is 180 − 36 = 144°.",
  traps: ["A: gave the exterior angle instead of the interior one.",
          "B: used a hexagon's interior angle.",
          "D: gave the SUM of all ten interior angles, (10 − 2) × 180."] },

{ sig: "regular-hexagon-facts", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "The regular hexagon below has side 6 cm. Find the length d of the long diagonal, in cm.",
  fig: "sim_hexagon_reg", figW: 1.85,
  opts: ["6√3", "9", "12", "6√2"], ans: 2,
  trick: "a regular hexagon is six equilateral triangles round its centre, so the long diagonal is exactly twice the side",
  why: "The long diagonal passes through the centre and equals two sides laid end to end: 2 × 6 = 12 cm.",
  traps: ["A: gave the SHORT diagonal, which is √3 times the side.",
          "B: took one and a half sides.",
          "D: used √2 instead of the factor 2."] },

{ sig: "trapezium-area", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "Find the area of the trapezium below, in cm².",
  fig: "sim_trapezium", figW: 2.35,
  opts: ["60", "72", "90", "135"], ans: 1,
  trick: "average the two parallel sides first, then multiply by the height — never add all four sides",
  why: "The parallel sides average (9 + 15)/2 = 12, and 12 × 6 = 72 cm².",
  traps: ["A: used the shorter parallel side alone times the height.",
          "C: used the longer parallel side alone times the height.",
          "D: added the parallel sides without halving, then times the height."] },

{ sig: "midpoint-square-half", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "The shaded square below is drawn by joining the midpoints of the sides of the larger square, which has side 8 cm. Find the shaded area, in cm².",
  fig: "sim_mid_square", figW: 1.75,
  opts: ["16", "32", "48", "64"], ans: 1,
  trick: "joining the midpoints of a SQUARE gives half the area — the four corner triangles make up the other half",
  why: "The four corner triangles are congruent and together fill exactly half the big square, so the inner square is the other half: 64 ÷ 2 = 32 cm².",
  traps: ["A: took a quarter — that is the rule for a TRIANGLE's medial triangle, not a square's.",
          "C: took three quarters.",
          "D: copied the whole square."] },

// ==================================================================== DATA
{ sig: "mean-after-adjustment", code: "GAT-Q-DAT.5", lvl: 2,
  stem: "The mean mark of 12 students is 74. The teacher finds an error and adds 36 marks to one student's total. What is the new mean?",
  opts: ["74", "77", "80", "110"], ans: 1,
  trick: "a change to the TOTAL is shared out over everyone — divide the change by the count and add it to the old mean",
  why: "The total rises by 36, and that is spread over 12 students: 36 ÷ 12 = 3. So the new mean is 74 + 3 = 77.",
  traps: ["A: assumed one student's change cannot move the mean.",
          "C: added 6 instead of 3.",
          "D: added the whole 36 to the mean."] },

{ sig: "count-from-mean-shift", code: "GAT-Q-DAT.5", lvl: 3,
  stem: "A group of children has mean weight 40 kg. One more child, weighing 58 kg, joins and the mean becomes 42 kg. How many children were there before?",
  opts: ["6", "8", "10", "12"], ans: 1,
  trick: "write the total both ways — before, and after — and set them equal; the count is the only unknown left",
  why: "Let there be n before. Then 40n + 58 = 42(n + 1), so 40n + 58 = 42n + 42, giving 2n = 16 and n = 8.",
  traps: ["A: solved 40n + 58 = 42n + 58.",
          "C: divided 58 − 40 by 2 and added one.",
          "D: solved 40n = 42n − 58 without the extra child on the right."] },

{ sig: "mean-of-evenly-spaced", code: "GAT-Q-DAT.5", lvl: 1,
  stem: "Find the mean of the numbers 13, 18, 23, 28, 33, 38 and 43.",
  opts: ["26", "28", "30", "33"], ans: 1,
  trick: "when the numbers go up in equal steps the mean is just the middle one — no adding required",
  why: "The numbers rise in steps of 5, so the mean is the average of the first and last, (13 + 43)/2 = 28, which is also the middle number.",
  traps: ["A: averaged the first two terms.",
          "C: averaged the last two terms.",
          "D: gave the mode-looking middle-ish value 33 without checking."] },

{ sig: "median-mode-range", code: "GAT-Q-DAT.2", lvl: 2,
  stem: "For the data 7, 4, 9, 4, 12, 6, 4, which is greater?   A: the median   B: the range",
  opts: CMP, ans: 1,
  trick: "ORDER the data before reading the median — and the range is the largest minus the smallest, not a count",
  why: "In order: 4, 4, 4, 6, 7, 9, 12. The median is the fourth value, 6. The range is 12 − 4 = 8. So B is greater.",
  traps: ["A: took the median from the unordered list, giving 9.",
          "C: read the range as the number of values.",
          "D: all seven values are given."] },

// =================================================================== LOGIC
{ sig: "league-matches", code: "GAT-Q-LOG.3", lvl: 3,
  stem: "Twelve teams play in a league and every pair meets twice. How many matches are played altogether?",
  opts: ["66", "110", "132", "144"], ans: 2,
  trick: "count the PAIRS first — n(n−1)/2 — and only then multiply by how many times each pair meets",
  why: "The number of pairs is 12 × 11 ÷ 2 = 66, and each pair meets twice, so 66 × 2 = 132 matches.",
  traps: ["A: gave the number of pairs and forgot the second meeting.",
          "B: used 11 × 10 for the pairs.",
          "D: used 12 × 12."] },

{ sig: "cuts-and-posts", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "A machine cuts a rope into pieces, taking 8 seconds per cut. How long does it take to cut one rope into 7 pieces?",
  opts: ["42 s", "48 s", "56 s", "64 s"], ans: 1,
  trick: "cutting into n pieces takes n − 1 cuts — the last two pieces are made by a single cut",
  why: "Seven pieces need 7 − 1 = 6 cuts, and 6 × 8 = 48 seconds.",
  traps: ["A: used 5 cuts.",
          "C: used one cut per piece, 7 × 8.",
          "D: used 8 cuts."] },

{ sig: "harmonic-average-speed", code: "GAT-Q-LOG.1", lvl: 3,
  stem: "A driver goes from Jeddah to Makkah at 60 km/h and returns along the same road at 40 km/h. What is the average speed for the whole journey, in km/h?",
  opts: ["45", "48", "50", "52"], ans: 1,
  trick: "the average of the two speeds is WRONG — the slow leg takes longer, so it weighs more; use twice their product over their sum",
  why: "For equal distances the average speed is 2v₁v₂⁄(v₁ + v₂) = 2 × 60 × 40 ÷ 100 = 48 km/h. Not 50.",
  traps: ["A: took a rough three quarters of 60.",
          "C: averaged the two speeds — the trap this item exists for.",
          "D: averaged and then adjusted upward."] },

{ sig: "compound-percent-change", code: "GAT-Q-LOG.4", lvl: 3,
  stem: "A price rises by 20% and then falls by 20%. What is the overall change?",
  opts: ["no change", "a 4% fall", "a 4% rise", "a 20% fall"], ans: 1,
  trick: "the rise and the fall are taken on DIFFERENT amounts, so they do not cancel — the net is a + b + ab/100",
  why: "Net change = +20 − 20 + (20 × −20)/100 = −4%, a 4% fall. (Check: 100 → 120 → 96.)",
  traps: ["A: cancelled the two 20s, which is the trap.",
          "C: got the size right but the direction wrong — a rise then a fall always ends lower.",
          "D: subtracted the second 20% from the original price."] },

];

// ---------------------------------------------------------------------------
// STILL TO MINE from the same book (24 skills), in rough priority order:
//   GEO  angle-bisector-ratio · cyclic-quadrilateral · arc-length ·
//        distance-midpoint-coordinate · circle-equation · parallel-angle-pairs ·
//        equal-area-same-base · square-area-equals-perimeter · circle-in-square ·
//        tangent-circles-shaded · equal-perimeter-area-order · similar-sides-ratio ·
//        triangle-area-find-base · count-rectangles-in-grid · cuboid-volume-surface ·
//        cylinder-volume · volume-unit-conversion
//   LOG  handshakes-vs-gifts · wheel-revolutions · cost-price-from-markup ·
//        ratio-parts-share · combined-work-time · day-of-week-cycle
//   DAT  permutation-vs-combination
// ---------------------------------------------------------------------------
