// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part A: arithmetic and algebra (50 items)
//
// Every item here is ORIGINAL writing. It keeps the sub-skill and the trick of
// an item in the department's practice sets and changes everything else: the
// numbers, the names, the context, and the distractor values. Contexts are
// grounded in Saudi settings and SAR (Pillar 3).
//
// `sig` is the skill-and-trick signature. The bank refuses to build if two
// items share one — that is what "no repeated questions" is enforced by.
// ---------------------------------------------------------------------------
const CMP = ["A is greater", "B is greater", "they are equal",
             "not enough information"];

module.exports = [

// ============================================================== ARITHMETIC
{ sig: "pct-scale-same-base", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Two engineers at the same firm earn the same salary. Faisal saves 18% of his and Nawaf saves 12% of his. Faisal saves 1440 SAR a month. How much does Nawaf save, in SAR?",
  opts: ["720", "840", "960", "1080"], ans: 2,
  trick: "one per cent of the shared salary is the bridge — never work out the salary itself",
  why: "1% of the salary is 1440 ÷ 18 = 80 SAR, so 12% is 80 × 12 = 960 SAR. (The salary is 8000, but you never have to write it down.)",
  traps: ["A: halved 1440 on the grounds that 12 is roughly half of 18.",
          "B: scaled by 12/18 but rounded 80 down to 70.",
          "D: scaled by 18/12 instead of 12/18."] },

{ sig: "ratio-powers-of-ten", code: "GAT-Q-ARI.2", lvl: 1,
  stem: "A survey counted the visitors to two heritage sites in one season, shown below. Find the ratio of the first to the second.",
  stemEq: "s_ratio_pow",
  opts: ["1 : 4", "4 : 1", "1 : 6", "6 : 1"], ans: 1,
  trick: "the power of ten is the same on both sides, so it cancels and never enters the arithmetic",
  why: "6 × 10⁵ : 1.5 × 10⁵ = 6 : 1.5 = 4 : 1.",
  traps: ["A: wrote the ratio the wrong way round.",
          "C: divided 6 by 1.5 as though 1.5 were 1.",
          "D: used the difference 4.5 × 10⁵ instead of the quotient."] },

{ sig: "pct-of-unknown-compare", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_pct_unk",
  opts: CMP, ans: 1,
  trick: "180% means multiply by 1.8, so K is SMALLER than 3600, not larger",
  why: "1.8K = 3600 gives K = 2000, which is less than 2200, so B is greater.",
  traps: ["A: read the statement as 'K is 180% more than 3600' and got 6480.",
          "C: guessed that a comparison item must balance.",
          "D: K is fully determined by the statement."] },

{ sig: "pct-simple-compare", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Which quantity is greater?   A: 380   B: 40% of 900",
  opts: CMP, ans: 0,
  trick: "work the percentage out in full — 40% of 900 is close enough to 380 that estimating will not settle it",
  why: "40% of 900 is 360, and 380 > 360, so A is greater.",
  traps: ["B: read 40% of 900 as 400 by taking 'a bit under a half' too generously.",
          "C: rounded 360 up to 380 and called it a tie.",
          "D: both quantities are fully given, so 'not enough information' cannot apply."] },

{ sig: "pct-complement", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "On Tuesday 21 students were present in a class and 30% of the class was absent. How many students are in the class altogether?",
  opts: ["25", "30", "63", "70"], ans: 1,
  trick: "the 21 who came are the 70% who were NOT absent, so divide by 0.7, not by 0.3",
  why: "If 30% were absent then 70% attended, and that 70% is 21 students. So the class is 21 ÷ 0.70 = 30.",
  traps: ["A: divided 21 by 0.84 after a slip.",
          "C: took 21 as 30% and divided by 0.3 — the word ABSENT was missed.",
          "D: divided 21 by 0.3."] },

{ sig: "unit-rate-scale", code: "GAT-Q-ARI.2", lvl: 1,
  stem: "A supplier delivers 8 water coolers for 640 SAR. What does it cost to deliver 14 coolers, at the same rate?",
  opts: ["960", "1020", "1120", "1280"], ans: 2,
  trick: "unit price first, then multiply — one division and one multiplication, never a guessed jump",
  why: "One cooler costs 640 ÷ 8 = 80 SAR, so 14 cost 80 × 14 = 1120 SAR.",
  traps: ["A: scaled by 12/8 instead of 14/8.",
          "B: added 380 for the six extra at a guessed rate.",
          "D: doubled 640."] },

{ sig: "tare-then-scale", code: "GAT-Q-ARI.2", lvl: 3,
  stem: "An empty storage tank weighs 420 kg. Filled to one fifth of its capacity it weighs 620 kg. What does it weigh when it is three fifths full?",
  opts: ["1020 kg", "1120 kg", "1240 kg", "1860 kg"], ans: 0,
  trick: "subtract the empty weight before scaling the water, never after",
  why: "One fifth of the water weighs 620 − 420 = 200 kg, so three fifths weigh 600 kg. The tank still weighs 420 kg, giving 420 + 600 = 1020 kg.",
  traps: ["B: added 700 instead of 600 by scaling from 620 ÷ 3.",
          "C: used 620 + 620 for the extra two fifths.",
          "D: tripled the whole 620 kg — the empty weight must come off first."] },

{ sig: "surd-identity-compare", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_surd_cmp",
  opts: CMP, ans: 2,
  trick: "simplify B fully — a comparison can be a disguised identity",
  why: "B is 12√20 ÷ (4√4) = 12 × 2√5 ÷ 8 = 24√5 ÷ 8 = 3√5, which is exactly A. They are equal.",
  traps: ["A: stopped at 12 ÷ 4 = 3 and never simplified √20 or √4.",
          "B: took √20 as 2√10.",
          "D: both are explicit numbers, so 'not enough information' cannot apply."] },

{ sig: "two-divisibility-conditions", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "A number is a multiple of 8. Six less than it is a multiple of 7. Which of the following is the number?",
  opts: ["40", "48", "56", "64"], ans: 1,
  trick: "test the options against BOTH conditions; one condition alone leaves all four standing",
  why: "All four are multiples of 8. Subtracting 6: 34, 42, 50, 58. Only 42 is a multiple of 7, so the number is 48.",
  traps: ["A: 40 − 6 = 34, not a multiple of 7.",
          "C: 56 is itself a multiple of 7, which is not the condition asked for.",
          "D: 64 − 6 = 58."] },

{ sig: "negative-exponent", code: "GAT-Q-ARI.4", lvl: 3,
  stem: "Solve for t.",
  stemEq: "s_neg_exp",
  opts: ["2", "4", "8", "16"], ans: 0,
  trick: "dividing by a negative exponent ADDS, so the two sevenths make a whole t",
  why: "2/7 + 5/7 = 1, so the bracket is t. Then t × t³ = t⁴ = 16, giving t = 2.",
  traps: ["B: subtracted the exponents and solved t³ = 16 badly.",
          "C: solved t² = 16.",
          "D: read t⁴ = 16 as t = 16."] },

{ sig: "remainder-subtract", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "Take away as little as possible from 1000 so that what is left divides exactly by 43. How much is taken away?",
  opts: ["9", "11", "13", "17"], ans: 1,
  trick: "the remainder on division IS the number to subtract",
  why: "43 × 23 = 989, and 1000 − 989 = 11, so the remainder is 11 and 11 must come off.",
  traps: ["A: used 991 as the nearest multiple, which is not one.",
          "C: divided by 41 rather than 43.",
          "D: took 983 as the target by subtracting a whole extra 6."] },

{ sig: "estimate-round", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_estimate",
  opts: CMP, ans: 0,
  trick: "round 63.98 to 64 and 1.001 to 1 — the estimate settles it without any long division",
  why: "0.25 × 64 = 16, and 16 ÷ 1 = 16. The true value is 15.98, which is still greater than 15, so A is greater.",
  traps: ["B: divided by 1.001 as though it were 1.1, giving about 14.5.",
          "C: rounded 15.98 to 16 and then to 15.",
          "D: every number is given, so the comparison is decidable."] },

{ sig: "hcf-tiling", code: "GAT-Q-ARI.2", lvl: 2,
  stem: "A courtyard 36 m by 60 m is to be paved exactly with identical square slabs. What is the largest possible side of one slab, in metres?",
  opts: ["6", "9", "12", "18"], ans: 2,
  trick: "'largest square that tiles it exactly' is the HCF of the two sides",
  why: "The side must divide both 36 and 60, so the largest is HCF(36, 60) = 12 m.",
  traps: ["A: gave a common factor, but not the largest.",
          "B: 9 divides 36 but not 60.",
          "D: 18 divides 36 but not 60."] },

{ sig: "power-of-two-divisor", code: "GAT-Q-ARI.1", lvl: 1,
  stem: "The number below is divisible by n. Which of these can n be?",
  stemEq: "s_pow2",
  opts: ["15", "18", "24", "27"], ans: 3,
  trick: "a power of 3 has only threes in it, so any divisor must also be a pure power of 3",
  why: "3¹² has only the prime factor 3, so any divisor is a power of 3. Of the options only 27 = 3³ qualifies; 15, 18 and 24 each carry a 2 or a 5.",
  traps: ["A: 15 = 3 × 5 — the factor 5 is not present.",
          "B: 18 = 2 × 9 — the factor 2 is not present.",
          "C: 24 = 8 × 3 — the factor 8 is not present."] },

{ sig: "identify-prime", code: "GAT-Q-ARI.1", lvl: 1,
  stem: "Only one of the four numbers below is prime. Which one?",
  opts: ["51", "57", "67", "91"], ans: 2,
  trick: "check 3 and 7 before deciding — 51, 57 and 91 all look prime and none of them is",
  why: "67 is not divisible by 2, 3, 5 or 7, and 8² = 64 < 67 < 81, so testing to 7 is enough. 51 = 3 × 17, 57 = 3 × 19, 91 = 7 × 13.",
  traps: ["A: 51 is odd, but 5 + 1 = 6 is a multiple of 3.",
          "B: 57 is odd, but 5 + 7 = 12 is a multiple of 3.",
          "D: 91 looks prime and is 7 × 13 — the classic trap."] },

{ sig: "multiplier-sequence", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "Complete the sequence: 3, 3, 6, 18, …",
  opts: ["36", "54", "72", "90"], ans: 2,
  trick: "the multipliers run 1, 2, 3, 4 — the differences do not form the pattern",
  why: "3 × 1 = 3, 3 × 2 = 6, 6 × 3 = 18, 18 × 4 = 72.",
  traps: ["A: doubled 18.",
          "B: multiplied by 3 again instead of moving on to 4.",
          "D: extended the differences (0, 3, 12) rather than the multipliers."] },

{ sig: "long-division-last-digit", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Find the quotient.",
  stemEq: "s_longdiv",
  opts: ["173 201", "173 203", "173 204", "173 207"], ans: 1,
  trick: "check the last digit: 372 ends in 2, so only a quotient ending in 3 can give a dividend ending in 6",
  why: "372 × 173 203 = 64 431 516. The units digit settles it without any long division: 2 × 3 = 6, and no other option ends in a digit that gives 6.",
  traps: ["A: 2 × 1 ends in 2, not 6.",
          "C: 2 × 4 ends in 8.",
          "D: 2 × 7 ends in 4."] },

{ sig: "banknote-fractions", code: "GAT-Q-ARI.3", lvl: 3,
  stem: "Rakan has 48 banknotes. One sixth of them are 10 SAR notes and one quarter are 50 SAR notes. The rest are 100 SAR notes. How much does Rakan have altogether, in SAR?",
  opts: ["3480", "3620", "3700", "3880"], ans: 0,
  trick: "the 'rest' is what is left after BOTH fractions, not after one of them",
  why: "One sixth of 48 is 8 ten-riyal notes (80 SAR); one quarter is 12 fifty-riyal notes (600 SAR); the rest is 48 − 8 − 12 = 28 hundred-riyal notes (2800 SAR). The total is 80 + 600 + 2800 = 3480 SAR.",
  traps: ["B: used 29 hundred-riyal notes.",
          "C: took the 'rest' as 48 − 12 = 36, forgetting the ten-riyal notes.",
          "D: used 32 hundred-riyal notes."] },

{ sig: "percent-of-total", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "A school of 480 students sent 35% of them on a field trip to Diriyah. How many students went?",
  opts: ["144", "168", "192", "216"], ans: 1,
  trick: "10% first, then scale — 35% is three tens and a half-ten",
  why: "10% of 480 is 48, so 30% is 144 and 5% is 24; 144 + 24 = 168.",
  traps: ["A: gave 30% and stopped.",
          "C: gave 40%.",
          "D: gave 45%."] },

{ sig: "difference-sequence", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "What is the next number in the sequence 8, 11, 17, 26, …?",
  opts: ["35", "38", "40", "44"], ans: 1,
  trick: "the differences run 3, 6, 9, so the next difference is 12",
  why: "The differences are 3, 6, 9 — going up in threes — so the next difference is 12 and the term is 26 + 12 = 38.",
  traps: ["A: kept the difference at 9.",
          "C: used a difference of 14.",
          "D: doubled the last difference to 18."] },

{ sig: "percent-then-divide", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Find the number that, when multiplied by 8, equals 20% of 360.",
  opts: ["7", "9", "12", "18"], ans: 1,
  trick: "take the percentage first: 20% of 360 is 72, and only then divide",
  why: "20% of 360 is 72, and 72 ÷ 8 = 9.",
  traps: ["A: used 20% of 280.",
          "C: found 72 correctly but divided by 6.",
          "D: divided 360 by 20 and stopped."] },

{ sig: "surd-complex-fraction", code: "GAT-Q-ARI.4", lvl: 3,
  stem: "Evaluate the expression below.",
  stemEq: "s_surd_frac",
  opts: ["18", "36", "54", "72"], ans: 2,
  trick: "dividing by a fraction flips it — the root of five cancels top and bottom before any arithmetic",
  why: "The numerator is √5 × 6√3 = 6√15. Dividing by √5 ⁄ (3√3) means multiplying by 3√3 ⁄ √5, so the √5 cancels: 6√3 × 3√3 = 18 × 3 = 54.",
  traps: ["A: added the surds in the bracket as 2√3 + 4√3 = 6 and lost the root.",
          "B: multiplied by √5 ⁄ (3√3) instead of dividing by it.",
          "D: squared the 3 as well as the √3."] },

{ sig: "percent-cross-compare", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_pct_cross",
  opts: CMP, ans: 2,
  trick: "0.8% is eight tenths of one per cent, not eight per cent — convert both to plain numbers first",
  why: "15% of 480 is 72. 0.8% of 9000 is 9000 × 0.008 = 72. They are equal.",
  traps: ["A: read 0.8% as 8%, giving 720 — which would make B the larger anyway.",
          "B: read 15% of 480 as 60.",
          "D: both are explicit numbers."] },

{ sig: "negative-fraction-compare", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_negfrac",
  opts: CMP, ans: 0,
  trick: "both differences are negative, so the one NEARER to zero is the greater",
  why: "A is 2/5 − 9/10 = 4/10 − 9/10 = −5/10 = −1/2. B is 1/10 − 9/10 = −8/10 = −4/5. Since −1/2 is nearer to zero, A is greater.",
  traps: ["B: compared 1/2 with 4/5 and picked the bigger number, ignoring the minus signs.",
          "C: subtracted 9/10 from both and assumed that cancels the difference.",
          "D: every number is given."] },

{ sig: "groups-plus-remainder", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "A box of pens was shared among 14 students so that each received 18 pens, and 7 pens were left over. How many pens were in the box?",
  opts: ["245", "252", "259", "266"], ans: 2,
  trick: "multiply first, then ADD the leftover — the remainder is not part of the shares",
  why: "14 × 18 = 252, and 252 + 7 = 259.",
  traps: ["A: subtracted the leftover instead of adding it.",
          "B: forgot the leftover altogether.",
          "D: added 14 rather than 7."] },

{ sig: "ratio-scale-up", code: "GAT-Q-ARI.2", lvl: 1,
  stem: "A school assigns 3 supervisors for every 25 pupils on a trip. If 400 pupils go, how many supervisors are needed?",
  opts: ["36", "42", "48", "52"], ans: 2,
  trick: "count the GROUPS first, then multiply — do not scale the two numbers separately",
  why: "400 ÷ 25 = 16 groups, and 16 × 3 = 48 supervisors.",
  traps: ["A: used 12 groups.",
          "B: divided 400 by 28 (the group total) instead of by 25.",
          "D: rounded 16 groups up to 17 and then some."] },

{ sig: "nested-percent", code: "GAT-Q-ARI.3", lvl: 3,
  stem: "Find the value of the expression below.",
  stemEq: "s_nested",
  opts: ["0.04", "0.4", "4", "40"], ans: 0,
  trick: "'of' means multiply, and a per cent sign is a division by 100 that is easy to drop",
  why: "0.02 of 4000 is 80. Then 0.05% of 80 is 0.0005 × 80 = 0.04.",
  traps: ["B: dropped one factor of 10 by reading 0.05% as 0.5%.",
          "C: read 0.05% as 5%.",
          "D: treated both 0.05% and 0.02 as whole per cents."] },

{ sig: "decimal-fraction-sum", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Find the value of the sum below.",
  stemEq: "s_decsum",
  opts: ["6.1125", "60.615", "61.125", "61.215"], ans: 2,
  trick: "convert each fraction by its OWN denominator — the three place values are all different",
  why: "75/1000 = 0.075, 45/100 = 0.45 and 606/10 = 60.6. The sum is 0.075 + 0.45 + 60.6 = 61.125.",
  traps: ["A: divided the whole answer by ten by lining the decimal points up wrongly.",
          "B: read 45/100 as 0.045 and 75/1000 as 0.75.",
          "D: transposed two digits after adding correctly."] },

{ sig: "factor-out-common", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Calculate the value of the expression below.",
  stemEq: "s_factor",
  opts: ["−35", "−25", "25", "35"], ans: 0,
  trick: "take the common factor out of the numerator first — no long multiplication is needed",
  why: "The numerator is 35(−18 + 11) = 35 × (−7) = −245, and −245 ÷ 7 = −35.",
  traps: ["B: used 35(−18 + 11) ÷ 7 with the 35 mistaken for 25.",
          "C: dropped the minus sign.",
          "D: dropped the minus sign after the correct magnitude."] },

{ sig: "sign-of-product-range", code: "GAT-Q-ARI.1", lvl: 3,
  stem: "Zero is excluded from both lists. Which is greater?   A: the product of the integers from −3 to 5   B: the product of the integers from −5 to 3",
  opts: CMP, ans: 2,
  trick: "split each product into its negative part and its positive part — the two lists turn out to be mirror images",
  why: "A is (−3)(−2)(−1) × (1×2×3×4×5) = (−6) × 120 = −720. B is (−5)(−4)(−3)(−2)(−1) × (1×2×3) = (−120) × 6 = −720. The two are equal.",
  traps: ["A: counted three negatives in A and five in B and concluded the signs differ — both products are in fact negative.",
          "B: noticed that B reaches −5 and assumed the larger negative wins.",
          "D: both lists are fully specified, so both products are determined."] },

{ sig: "odd-vs-even-sum", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "The whole numbers from 1 to 25 are written out. Which is greater?   A: the sum of the odd numbers among them   B: the sum of the even numbers among them",
  opts: CMP, ans: 0,
  trick: "there is one more odd number than even, and the odd list starts lower but reaches higher",
  why: "The odd numbers 1, 3, …, 25 are 13 terms summing to 13² = 169. The even numbers 2, 4, …, 24 are 12 terms summing to 12 × 13 = 156. A is greater.",
  traps: ["B: assumed the evens win because each even is bigger than the odd before it.",
          "C: assumed the two halves must balance.",
          "D: both sums are fully determined."] },

// ================================================================= ALGEBRA
{ sig: "case-split-compare", code: "GAT-Q-ALG.4", lvl: 3,
  stem: "Which quantity is greater?",
  stemEq: "s_casesplit",
  opts: CMP, ans: 3,
  trick: "two conditions can force a case split — when the cases disagree, (D) is the answer",
  why: "Substituting k = ab into ak = b gives a²b = b, so b(a² − 1) = 0. Either b = 0, or a = 1, or a = −1. Take a = 1: then k = b and b − a = b − 1, so A is greater. Take b = 0: then k = 0 and b − a = −a, whose sign depends on a. Different legitimate cases give different answers.",
  traps: ["A: found the a = 1 case and stopped there.",
          "B: found a case where b − a is large and stopped there.",
          "C: cancelled b from a²b = b without noting that b may be zero."] },

{ sig: "sqrt-two-roots", code: "GAT-Q-ALG.3", lvl: 2,
  stem: "Adding 3 to a number and then squaring the result gives 121. What is the number?",
  stemEq: "s_sqrt2roots",
  opts: ["8", "11", "14", "17"], ans: 0,
  trick: "a square root has two signs, but only one of them is on the option list",
  why: "k + 3 = ±11, so k = 8 or k = −14. Only 8 appears among the options.",
  traps: ["B: took the square root of 121 and stopped, forgetting the +3.",
          "C: added 3 to 11 instead of subtracting.",
          "D: added 3 twice to 11."] },

{ sig: "clear-denominator-pair", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "Find a possible pair of values of a and b.",
  stemEq: "s_denpair",
  opts: ["30 , 40", "35 , 55", "40 , 45", "50 , 60"], ans: 1,
  trick: "clear the common denominator first: the equation is simply a + b = 90",
  why: "Multiplying through by 5 gives a + b = 90. Of the four pairs only 35 + 55 = 90.",
  traps: ["A: 30 + 40 = 70 — solved a/5 + b/5 = 14.",
          "C: 40 + 45 = 85 — five short.",
          "D: 50 + 60 = 110 — overshot by treating 18 as 22."] },

{ sig: "net-movement-backwards", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "A library lent out 14 of its copies of a title, then received 5 new copies, which left 43 copies on the shelf. How many copies were on the shelf to begin with?",
  opts: ["34", "43", "52", "62"], ans: 2,
  trick: "'lent out' and 'received' move in opposite directions — work backwards and net them",
  why: "If it started with n, then n − 14 + 5 = 43, so n − 9 = 43 and n = 52.",
  traps: ["A: mis-signed both movements, giving 43 − 5 − 4.",
          "B: netted the two movements to zero.",
          "D: added both movements instead of netting them (43 + 14 + 5)."] },

{ sig: "evaluate-negative", code: "GAT-Q-ALG.5", lvl: 1,
  stem: "Evaluate the expression below.",
  stemEq: "s_eval",
  opts: ["−42", "−34", "−26", "−18"], ans: 0,
  trick: "a negative cubed stays negative; the squared term is positive BEFORE the minus sign hits it",
  why: "3(−2)³ = 3 × (−8) = −24. −2(−2)² = −2 × 4 = −8. 5(−2) = −10. Total −24 − 8 − 10 = −42.",
  traps: ["B: took (−2)² as −4, giving −24 + 8 − 10 = −26 and then mis-added.",
          "C: took (−2)² as −4.",
          "D: dropped the −2w² term."] },

{ sig: "sum-invariant-system", code: "GAT-Q-ALG.2", lvl: 3,
  stem: "Given the two equations below, find x + y + z.",
  stemEq: "s_sysinv",
  opts: ["24", "26", "28", "32"], ans: 2,
  trick: "you are asked for the SUM, not for the letters — the y terms cancel and the sum is a constant",
  why: "From the first, x = 10 − y/4. From the second, z = 18 − 3y/4. Adding: x + y + z = 10 − y/4 + y + 18 − 3y/4 = 28, because −1/4 + 1 − 3/4 = 0. The sum is 28 whatever y is.",
  traps: ["A: solved for one letter only and stopped.",
          "B: assumed y = 0 and then dropped a term.",
          "D: added 40 and 24 and halved."] },

{ sig: "words-to-linear", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "A number plus four times itself, increased by 9, is seven times the original number. Find the number.",
  opts: ["3", "4.5", "6", "9"], ans: 1,
  trick: "'plus four times itself' is 5n, not 4n",
  why: "n + 4n + 9 = 7n gives 5n + 9 = 7n, so 2n = 9 and n = 4.5.",
  traps: ["A: solved 4n + 9 = 7n, dropping the original n.",
          "C: solved 5n + 9 = 6.5n after mis-reading 'seven times'.",
          "D: gave the 9 that appears in the question."] },

{ sig: "proportion-solve", code: "GAT-Q-ALG.1", lvl: 1,
  stem: "Find v.",
  stemEq: "s_prop",
  opts: ["0.1", "1", "10", "100"], ans: 2,
  trick: "the nines on the two denominators cancel, leaving 7 = 0.7v",
  why: "The denominators are both 9, so 7 = 0.7v and v = 10.",
  traps: ["A: inverted, giving 0.7 ÷ 7.",
          "B: divided 7 by 7 and forgot the decimal.",
          "D: multiplied by 10 twice."] },

{ sig: "system-eliminate-compare", code: "GAT-Q-ALG.2", lvl: 3,
  stem: "One grocery bill lists 4 kg of dates with 6 kg of rice at 300 SAR. A second lists 8 kg of dates with 4 kg of coffee at 600 SAR. Which is greater?   A: one kilogram of rice   B: one kilogram of coffee",
  opts: CMP, ans: 1,
  trick: "halve the second equation so both carry the same number of date units, then the rest subtracts away",
  why: "Halving the second gives 4 dates + 2 coffee = 300. The first says 4 dates + 6 rice = 300. So 2 coffee = 6 rice, that is 1 coffee = 3 rice, and coffee is the greater.",
  traps: ["A: compared the coefficients 6 and 4 rather than the prices.",
          "C: saw 300 and 600 as a clean doubling and assumed a tie.",
          "D: the date terms cancel exactly, so the comparison IS decidable."] },

{ sig: "solve-then-compare", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "Which quantity is greater, given the two statements below?",
  stemEq: "s_solvecmp",
  opts: CMP, ans: 1,
  trick: "solve for p and q first; 4p and 3q are then plain numbers",
  why: "5^p = 125 gives p = 3, so 4p = 12. 9q = 54 gives q = 6, so 3q = 18. B is greater.",
  traps: ["A: read 5^p = 125 as p = 5 and got 4p = 20.",
          "C: solved 9q = 54 as q = 4, which would make both sides 12.",
          "D: both letters are fully determined."] },

{ sig: "inequality-bound-compare", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "Which quantity is greater, given the inequality below?",
  stemEq: "s_ineq",
  opts: CMP, ans: 0,
  trick: "solve the inequality first: h is above minus three quarters, and minus five sixths is below that",
  why: "3 + 4h > 0 gives h > −3/4. Since −3/4 = −0.75 and −5/6 ≈ −0.833, every allowed h is greater than −5/6. A is greater.",
  traps: ["B: solved the inequality the wrong way round to h < −3/4.",
          "C: compared −3/4 with −5/6 and read them as equal.",
          "D: the inequality bounds h above −5/6 for every allowed value."] },

{ sig: "no-sign-compare", code: "GAT-Q-ALG.5", lvl: 2,
  stem: "Which quantity is greater, given the equation below?",
  stemEq: "s_nosign",
  opts: CMP, ans: 3,
  trick: "no sign is given for either letter, and both may be zero, so no comparison can be made",
  why: "7u = 3v fixes the ratio but not the sign. If v = 7 then u = 3 and B is greater; if v = −7 then u = −3 and A is greater; if v = 0 then both are zero. Not enough information.",
  traps: ["A: assumed both letters are positive because 7 > 3.",
          "B: read the equation as u = 3v/7 and compared the coefficients.",
          "C: took the equals sign to mean the letters are equal."] },

{ sig: "reciprocal-sign-trap", code: "GAT-Q-ALG.5", lvl: 3,
  stem: "Which quantity is greater?",
  stemEq: "s_recip",
  opts: CMP, ans: 3,
  trick: "taking reciprocals only reverses an inequality when both sides carry the SAME sign, and no sign is given here",
  why: "If g and n are both positive then g < n gives 1/g > 1/n, so A. But take g = −1 and n = 1: then g < n still holds, while 1/g = −1 and 1/n = 1, so B. Not enough information.",
  traps: ["A: applied 'reciprocals reverse the inequality' without checking the signs — this is the trap the item is built on.",
          "B: found the mixed-sign case and stopped there.",
          "C: assumed the reciprocals must balance."] },

{ sig: "substitute-compare-negatives", code: "GAT-Q-ALG.5", lvl: 2,
  stem: "Which quantity is greater, given the two statements below?",
  stemEq: "s_substcmp",
  opts: CMP, ans: 0,
  trick: "u + v = 0 makes v the opposite of u, so u − v is just 2u — and then compare two negatives",
  why: "u + v = 0 gives v = 1/5, so u − v = −1/5 − 1/5 = −2/5. And 7u = −7/5. Since −2/5 > −7/5, A is greater.",
  traps: ["B: compared magnitudes and picked 7/5 as the bigger, ignoring the signs.",
          "C: took u − v as 0 by confusing it with u + v.",
          "D: both quantities are fully determined by u."] },

{ sig: "two-digit-digit-conditions", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "A two-digit number has one digit greater than the other by 4, and its two digits add to 12. What is the number?",
  opts: ["39", "57", "66", "84"], ans: 3,
  trick: "the two conditions fix the digits before you look at the options; then only the ORDER is left to check",
  why: "Digits differing by 4 and summing to 12 are 8 and 4. Of the options only 84 uses that pair.",
  traps: ["A: 3 + 9 = 12 but the digits differ by 6.",
          "B: 5 + 7 = 12 but the digits differ by 2.",
          "C: 6 + 6 = 12 but the digits do not differ at all."] },

{ sig: "diophantine-two-prices", code: "GAT-Q-ALG.1", lvl: 3,
  stem: "A canteen prices sandwiches at 8 SAR and juices at 5 SAR. Nasser takes at least one of each and hands over exactly 52 SAR. How many juices does he take?",
  opts: ["2 juices", "4 juices", "6 juices", "8 juices"], ans: 1,
  trick: "test the juice count, not the sandwich count — only one value leaves a multiple of 8",
  why: "8s + 5j = 52. Trying j = 4 gives 20, leaving 32, which is exactly 4 sandwiches. No other value of j under 10 leaves a multiple of 8.",
  traps: ["A: 2 juices leaves 42, not a multiple of 8.",
          "C: 6 juices leaves 22.",
          "D: 8 juices leaves 12."] },

{ sig: "identify-false-statement", code: "GAT-Q-ALG.4", lvl: 2,
  stem: "Given the two statements below, which of the following is INCORRECT?",
  stemEq: "s_false",
  opts: [{ eq: "q1a" }, { eq: "q1b" }, { eq: "q1c" }, { eq: "q1d" }], ans: 3,
  trick: "substitute r = 2p once and read all four options off it — three of them collapse to true statements immediately",
  why: "Since p = q, r = p + q = 2p. Then (A) p = r⁄2 is true; (B) adding the same r to two equal quantities is true; (C) tripling p + q = r is true; (D) r − q = 2p − p = p, not 3p, so (D) is the incorrect one.",
  traps: ["A: r = 2p makes p = r⁄2 exactly.",
          "B: adding the same amount to two equal quantities always holds.",
          "C: this is the original equation multiplied through by 3."] },

{ sig: "undo-two-operations", code: "GAT-Q-ALG.1", lvl: 1,
  stem: "A number is multiplied by 24 and then 83 is subtracted. The result is 1069. What is the number?",
  stemEq: "s_undo",
  opts: ["41", "44", "48", "52"], ans: 2,
  trick: "work backwards: undo the subtraction first, then the multiplication",
  why: "1069 + 83 = 1152, and 1152 ÷ 24 = 48.",
  traps: ["A: divided 1069 by 24 and rounded up.",
          "B: subtracted 83 instead of adding it, then divided.",
          "D: divided by 22."] },

{ sig: "identity-sum-product", code: "GAT-Q-ALG.3", lvl: 2,
  stem: "Given the two statements below, find c² + d².",
  stemEq: "s_identity",
  opts: ["39", "53", "67", "81"], ans: 1,
  trick: "square the sum and subtract twice the product — you never need c and d themselves",
  why: "(c + d)² = c² + 2cd + d², so c² + d² = 9² − 2 × 14 = 81 − 28 = 53.",
  traps: ["A: subtracted 14 twice more than needed.",
          "C: subtracted only one lot of 14.",
          "D: gave (c + d)² and forgot to subtract 2cd."] },

];
