// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part J: the level-1/2 top-up.
//
// This part answers a measured shortage rather than a new source. After part I
// the bank held 284 items but only TWO unused arithmetic items and five word
// logic, so the weekly builder could not assemble another worksheet: the strand
// mix, not the item count, was the wall. Arithmetic is 36% of the real paper and
// is always the first strand to empty.
//
// So every item here is level 1 or 2, and the strands are ARI, ALG, DAT and LOG
// only — geometry needed nothing, with 33 items still unissued.
//
// These are the skills the GAT quantitative blueprint tests at its easy end, the
// ones a student must not lose marks on and which the harder items are built
// from. They are written from the published blueprint and ordinary school
// mathematics, not mined from any paper — there is nothing to attribute and
// nothing to restrict. Every answer is re-derived in verify_sim.py.
// ---------------------------------------------------------------------------
module.exports = [

// ============================================================== ARITHMETIC
{ sig: "round-then-add-estimate", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Estimate the value of 3 968 + 2 013 + 1 022 by rounding each number to the nearest thousand.",
  opts: ["6 000", "7 000", "8 000", "9 000"], ans: 1,
  trick: "round FIRST and add second — the question asks for an estimate, so adding exactly and then rounding is slower and is not what is being marked",
  why: "The three numbers round to 4 000, 2 000 and 1 000, and 4 000 + 2 000 + 1 000 = 7 000.",
  traps: ["A: 3 968 rounded down to 3 000.",
          "C: 2 013 rounded up to 3 000.",
          "D: every number rounded up."] },

{ sig: "fraction-of-quantity", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Find three eighths of 640.",
  opts: ["80", "180", "240", "320"], ans: 2,
  trick: "divide by the bottom, then multiply by the top — dividing by 8 first keeps the numbers small enough to do in your head",
  why: "640 ÷ 8 = 80, and 80 × 3 = 240.",
  traps: ["A: one eighth given.",
          "B: 640 ÷ 8 read as 60 and then tripled.",
          "D: a half given."] },

{ sig: "percent-to-fraction-simplify", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Write 35% as a fraction in its lowest terms.",
  opts: [{ eq: "j_pf1" }, { eq: "j_pf2" }, { eq: "j_pf3" }, { eq: "j_pf4" }], ans: 1,
  trick: "a percent is already a fraction over 100 — write it that way, then cancel. The words 'lowest terms' are the whole second half of the question",
  why: "35% = 35/100, and dividing both parts by 5 gives 7/20.",
  traps: ["A: the top divided by 5 but the bottom by 4.",
          "C: 35% read as 60% of nothing in particular — a common eyeball guess.",
          "D: correct in value but not in lowest terms."] },

{ sig: "fraction-to-decimal", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Write the fraction below as a decimal.", stemEq: "j_58",
  opts: ["0.58", "0.625", "0.8", "1.6"], ans: 1,
  trick: "divide the top by the bottom, in that order — the eighths are worth memorising, since 1/8 = 0.125 makes every one of them instant",
  why: "5 ÷ 8 = 0.625.",
  traps: ["A: the digits 5 and 8 simply written after a point.",
          "C: 4/5 given instead.",
          "D: 8 ÷ 5 taken, the division reversed."] },

{ sig: "ratio-to-percent", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Two quantities are in the ratio 3 : 5. What percentage of the total is the first quantity?",
  opts: ["30%", "37.5%", "60%", "62.5%"], ans: 1,
  trick: "a ratio compares the two parts to EACH OTHER; a percentage compares one part to the whole. Add the parts first to get the whole",
  why: "The total is 3 + 5 = 8 parts, so the first is 3/8 = 0.375 = 37.5%.",
  traps: ["A: 3 out of 10 assumed.",
          "C: 3/5 given, the ratio used as if it were the whole.",
          "D: the second quantity's share given."] },

{ sig: "square-root-large-perfect", code: "GAT-Q-ARI.4", lvl: 1,
  stem: "Find the value below.", stemEq: "j_sqrt576",
  opts: ["22", "24", "26", "28"], ans: 1,
  trick: "a square ending in 6 has a root ending in 4 or 6, and 576 sits between 20² and 30² — that pins it down before any multiplication",
  why: "24² = 576.",
  traps: ["A: 22² = 484.",
          "C: 26² = 676.",
          "D: 28² = 784."] },

{ sig: "cube-root-integer", code: "GAT-Q-ARI.4", lvl: 1,
  stem: "Find the value below.", stemEq: "j_cbrt",
  opts: ["4", "6", "8", "12"], ans: 1,
  trick: "cube the options rather than trying to take a cube root — three multiplications settle it faster than any method",
  why: "6³ = 216.",
  traps: ["A: 4³ = 64.",
          "C: 8³ = 512.",
          "D: 216 ÷ 18 given."] },

{ sig: "odd-power-negative-base", code: "GAT-Q-ARI.4", lvl: 1,
  stem: "Find the value below.", stemEq: "j_pow",
  opts: ["−32", "−10", "10", "32"], ans: 0,
  trick: "an ODD power keeps the minus sign; an even power removes it. Decide the sign first, then the size",
  why: "(−2)⁵ = −32, because the power is odd.",
  traps: ["B: the base multiplied by the exponent.",
          "C: multiplied and the sign lost too.",
          "D: the sign dropped, as if the power were even."] },

{ sig: "scientific-notation-small", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Write 0.000 42 in scientific notation.",
  opts: [{ eq: "j_sn2" }, { eq: "j_sn1" }, { eq: "j_sn4" }, { eq: "j_sn3" }], ans: 1,
  trick: "a number SMALLER than 1 always takes a negative power of ten — count the places the point moves right, and that count is the power",
  why: "Moving the point four places right gives 4.2, so 0.000 42 = 4.2 × 10⁻⁴.",
  traps: ["A: the sign of the exponent lost.",
          "C: only three places counted.",
          "D: the first number not written between 1 and 10."] },

{ sig: "exponent-laws-combine", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Find the value below.", stemEq: "j_expo",
  opts: ["4", "8", "16", "64"], ans: 1,
  trick: "add the powers on top, subtract the power underneath — never work out 2⁷ and 2⁵ as numbers first",
  why: "2⁷ × 2⁵ = 2¹², and 2¹² ÷ 2⁹ = 2³ = 8.",
  traps: ["A: the exponent left at 2.",
          "C: the powers multiplied on top instead of added.",
          "D: the 9 subtracted from 7 only."] },

{ sig: "percent-change-two-values", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "A price rises from 40 SAR to 50 SAR. By what percentage has it increased?",
  opts: ["10%", "20%", "25%", "80%"], ans: 2,
  trick: "divide the CHANGE by the ORIGINAL, never by the new value — the original is the base of every percentage change",
  why: "The rise is 10 SAR on an original 40, and 10 ÷ 40 = 25%.",
  traps: ["A: the change itself given as a percentage.",
          "B: divided by the new price, 10 ÷ 50.",
          "D: 40 ÷ 50 given."] },

{ sig: "reverse-percent-original", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "After a discount of 20%, a jacket costs 240 SAR. What was its price before the discount, in riyals?",
  opts: ["260", "288", "300", "320"], ans: 2,
  trick: "the 240 is 80% of the original, not 100% — divide by 0.8. Adding 20% back on to 240 is the mistake this item is set for",
  why: "240 is 80% of the original price, so the original is 240 ÷ 0.8 = 300 SAR.",
  traps: ["A: 20 riyals added.",
          "B: 20% added to 240 instead — the trap this item exists for.",
          "D: 240 ÷ 0.75 taken."] },

{ sig: "add-unlike-fractions", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Find the value below.", stemEq: "j_add",
  opts: [{ eq: "j_a1" }, { eq: "j_a3" }, { eq: "j_a2" }, { eq: "j_a4" }], ans: 2,
  trick: "fractions add only over a common bottom — the tops are added, the bottoms are not",
  why: "2/3 + 3/4 = 8/12 + 9/12 = 17/12.",
  traps: ["A: tops added and bottoms added.",
          "B: the bottoms multiplied but the tops left alone.",
          "D: the tops subtracted rather than added."] },

{ sig: "count-factors", code: "GAT-Q-ARI.1", lvl: 2,
  stem: "How many different whole numbers divide 36 exactly?",
  opts: ["6", "8", "9", "12"], ans: 2,
  trick: "list the factors in PAIRS from the outside in — 1 and 36, 2 and 18, 3 and 12, 4 and 9, 6 and 6 — and stop when the pair meets",
  why: "The factors are 1, 2, 3, 4, 6, 9, 12, 18 and 36: nine of them. The square number 36 has an odd count because 6 pairs with itself.",
  traps: ["A: only the factors below 10 counted.",
          "B: the repeated 6 counted twice, giving an even count.",
          "D: the multiples of 3 counted instead."] },

{ sig: "hcf-three-numbers", code: "GAT-Q-ARI.2", lvl: 2,
  stem: "Find the highest common factor of 24, 36 and 60.",
  opts: ["4", "6", "12", "18"], ans: 2,
  trick: "test the factors of the SMALLEST number downwards — the answer can never be larger than it, so start at 24 and come down",
  why: "12 divides 24, 36 and 60, and nothing larger does.",
  traps: ["A: a common factor, but not the highest.",
          "B: another common factor that is not the highest.",
          "D: 18 divides 36 but not 24."] },

{ sig: "lcm-two-numbers", code: "GAT-Q-ARI.2", lvl: 1,
  stem: "Find the lowest common multiple of 12 and 18.",
  opts: ["6", "36", "54", "216"], ans: 1,
  trick: "count up in the LARGER number and stop at the first one the smaller one divides — 18, 36, and you are done",
  why: "36 is the first number that both 12 and 18 divide.",
  traps: ["A: the highest common factor given.",
          "C: a multiple of 18 that 12 does not divide.",
          "D: the two numbers multiplied."] },

{ sig: "round-decimal-places", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Round 3.4567 to two decimal places.",
  opts: ["3.45", "3.457", "3.46", "3.5"], ans: 2,
  trick: "look at the NEXT digit only — the 6 rounds the 5 up, and the digits after it change nothing",
  why: "The third decimal digit is 6, so the second digit rounds up: 3.46.",
  traps: ["A: the digits simply cut off.",
          "B: rounded to three places.",
          "D: rounded to one place."] },

{ sig: "absolute-value-sum", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Find the value below.", stemEq: "j_abs",
  opts: ["1", "4", "13", "16"], ans: 2,
  trick: "work out what is inside each pair of bars FIRST, then drop the sign — the bars make the result positive, they do not make what is inside positive as you go",
  why: "|−7| = 7 and |3 − 9| = |−6| = 6, so the sum is 13.",
  traps: ["A: the two values subtracted.",
          "B: 3 − 9 read as 9 − 3 and then the bars ignored.",
          "D: 3 and 9 added inside the bars."] },

{ sig: "order-of-operations", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Find the value below.", stemEq: "j_ooo",
  opts: ["12", "18", "20", "24"], ans: 1,
  trick: "brackets, then division and multiplication LEFT TO RIGHT, then addition — 6 ÷ 2 × 2 is 6, not 1.5",
  why: "The bracket gives 2, then 6 ÷ 2 = 3 and 3 × 2 = 6, so the total is 12 + 6 = 18.",
  traps: ["A: the whole second part evaluated as 0.",
          "C: the multiplication done before the division.",
          "D: 12 + 6 = 18 then doubled by the bracket again."] },

{ sig: "percent-eighth-mental", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Find 12.5% of 640.",
  opts: ["64", "80", "128", "160"], ans: 1,
  trick: "12.5% is one eighth — the awkward percentages (12.5%, 25%, 33⅓%, 75%) are all easy fractions, and converting first removes the decimal entirely",
  why: "12.5% = 1/8, and 640 ÷ 8 = 80.",
  traps: ["A: 10% given.",
          "C: 640 ÷ 5 given.",
          "D: 25% given."] },

{ sig: "divisibility-by-4-rule", code: "GAT-Q-ARI.1", lvl: 1,
  stem: "Which of the following numbers is divisible by 4?",
  opts: ["1 234", "3 218", "5 316", "7 122"], ans: 2,
  trick: "only the LAST TWO digits decide divisibility by 4 — everything in front of them is already a multiple of 100, which 4 divides",
  why: "16 is divisible by 4, so 5 316 is. The others end in 34, 18 and 22, none of which 4 divides.",
  traps: ["A: the number read as even and therefore assumed divisible by 4.",
          "B: the same assumption.",
          "D: the digit sum tested instead, which is the rule for 3."] },

{ sig: "arithmetic-sequence-nth-term", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "A sequence begins 5, 9, 13, 17, … Find its twentieth term.",
  opts: ["77", "81", "85", "89"], ans: 1,
  trick: "the first term is not one step along — take NINETEEN steps from 5, not twenty. That single step is the most common lost mark in the strand",
  why: "The step is 4, so the twentieth term is 5 + 19 × 4 = 81.",
  traps: ["A: nineteen counted but the first term dropped.",
          "C: twenty steps taken from 5 — the trap this item exists for.",
          "D: twenty-one terms counted."] },

{ sig: "geometric-sequence-nth-term", code: "GAT-Q-ARI.5", lvl: 2,
  stem: "A sequence begins 3, 6, 12, 24, … Find its seventh term.",
  opts: ["96", "144", "192", "384"], ans: 2,
  trick: "count the DOUBLINGS, not the terms — six doublings from the first term, so 3 × 2⁶",
  why: "3 × 2⁶ = 3 × 64 = 192.",
  traps: ["A: the sixth term given.",
          "B: 24 multiplied by 6 as if the sequence added.",
          "D: seven doublings taken."] },

// ================================================================= ALGEBRA
{ sig: "substitute-two-variables", code: "GAT-Q-ALG.5", lvl: 1,
  stem: "Find the value of the expression below.", stemEq: "j_sub2",
  opts: ["10", "12", "14", "16"], ans: 2,
  trick: "subtracting a negative adds — write the substitution out with its brackets, 3(4) − 2(−1), before simplifying anything",
  why: "3(4) − 2(−1) = 12 + 2 = 14.",
  traps: ["A: −2 × −1 taken as −2.",
          "B: the second term dropped.",
          "D: b treated as +1 and then added twice."] },

{ sig: "solve-two-step-equation", code: "GAT-Q-ALG.1", lvl: 1,
  stem: "Solve the equation below for x.", stemEq: "j_2step",
  opts: ["3", "5", "6", "8"], ans: 2,
  trick: "undo the equation in reverse order — the −7 goes first because it was applied last",
  why: "5x = 30, so x = 6.",
  traps: ["A: 23 divided by 5 and then rounded.",
          "B: the 7 subtracted instead of added.",
          "D: 23 − 7 taken, then divided by 2."] },

{ sig: "solve-equation-with-brackets", code: "GAT-Q-ALG.1", lvl: 1,
  stem: "Solve the equation below for x.", stemEq: "j_brack",
  opts: ["6", "8", "10", "14"], ans: 2,
  trick: "divide both sides by the 3 before you touch the bracket — one step instead of an expansion",
  why: "x − 4 = 6, so x = 10.",
  traps: ["A: 18 ÷ 3 given as the answer.",
          "B: the bracket expanded as 3x − 4 = 18.",
          "D: the 4 added to 18 before dividing."] },

{ sig: "combine-like-terms", code: "GAT-Q-ALG.4", lvl: 1,
  stem: "Simplify the expression below.", stemEq: "j_clt",
  opts: [{ eq: "j_c2" }, { eq: "j_c1" }, { eq: "j_c3" }, { eq: "j_c4" }], ans: 1,
  trick: "only terms with the SAME letter combine — the x terms and the y terms are two separate sums that never meet",
  why: "5x − 2x = 3x and 3y + 7y = 10y, so the expression is 3x + 10y.",
  traps: ["A: the 2x added rather than subtracted.",
          "C: 3y + 7y taken as 4y.",
          "D: unlike terms merged into one."] },

{ sig: "solve-linear-inequality", code: "GAT-Q-ALG.1", lvl: 2,
  stem: "Solve the inequality below.", stemEq: "j_ineq",
  opts: [{ eq: "j_i2" }, { eq: "j_i1" }, { eq: "j_i4" }, { eq: "j_i3" }], ans: 1,
  trick: "an inequality is solved exactly like an equation — the sign only turns over when you multiply or divide by a NEGATIVE, and there is no negative here",
  why: "4x < 16, so x < 4.",
  traps: ["A: the sign turned over for no reason.",
          "C: the division by 4 forgotten.",
          "D: 11 − 5 taken instead of 11 + 5."] },

{ sig: "expand-two-brackets", code: "GAT-Q-ALG.4", lvl: 2,
  stem: "Expand and simplify the expression below.", stemEq: "j_exp",
  opts: [{ eq: "j_e2" }, { eq: "j_e1" }, { eq: "j_e4" }, { eq: "j_e3" }], ans: 1,
  trick: "the two middle terms carry the signs — +3x and −5x give −2x, and the last term is negative because a plus times a minus is a minus",
  why: "(x + 3)(x − 5) = x² − 5x + 3x − 15 = x² − 2x − 15.",
  traps: ["A: the middle terms added as +2x.",
          "C: only the first and last terms multiplied.",
          "D: the final sign taken as positive."] },

{ sig: "factor-common-monomial", code: "GAT-Q-ALG.3", lvl: 1,
  stem: "Factorise the expression below completely.", stemEq: "j_fac",
  opts: [{ eq: "j_g2" }, { eq: "j_g3" }, { eq: "j_g1" }, { eq: "j_g4" }], ans: 2,
  trick: "'completely' means take out the largest number AND the letter — 3 alone or x alone leaves something still to come out",
  why: "The highest common factor of 6x² and 9x is 3x, and 6x² + 9x = 3x(2x + 3).",
  traps: ["A: only the 3 taken out, so an x remains inside.",
          "B: only the x taken out, so a 3 remains inside.",
          "D: 9x ÷ 3x worked out as 9."] },

{ sig: "evaluate-function-negative", code: "GAT-Q-ALG.5", lvl: 2,
  stem: "Use the rule below to find the value asked for.", stemEq: "j_fn",
  opts: ["−5", "5", "11", "13"], ans: 1,
  trick: "the square is applied to the whole of −2, so it comes out positive — the minus sign disappears before the −3 is applied",
  why: "f(−2) = 2(−2)² − 3 = 2(4) − 3 = 5.",
  traps: ["A: (−2)² taken as −4.",
          "C: the −3 added instead of subtracted.",
          "D: 2 × (−2) squared as a whole, giving 16 − 3."] },

{ sig: "slope-from-two-points", code: "GAT-Q-GEO.6", lvl: 2,
  stem: "A straight line passes through the points (1, 2) and (4, 11). Find its slope.",
  opts: ["2", "3", "4", "9"], ans: 1,
  trick: "the rise goes on TOP and the run underneath, and both differences must be taken in the same order — swap one and the sign flips",
  why: "The slope is (11 − 2) ÷ (4 − 1) = 9 ÷ 3 = 3.",
  traps: ["A: the run and rise divided the wrong way and rounded.",
          "C: 11 ÷ 4 rounded.",
          "D: only the rise given."] },

// ===================================================================== DATA
{ sig: "mean-of-list", code: "GAT-Q-DAT.5", lvl: 1,
  stem: "Find the mean of 4, 7, 9, 10 and 15.",
  opts: ["8", "9", "9.5", "10"], ans: 1,
  trick: "add first, divide by HOW MANY, not by the largest value — five numbers means dividing by 5",
  why: "The total is 45, and 45 ÷ 5 = 9.",
  traps: ["A: the total taken as 40.",
          "C: the middle two averaged instead.",
          "D: the total divided by 4."] },

{ sig: "range-of-list", code: "GAT-Q-DAT.2", lvl: 1,
  stem: "Find the range of the values 12, 5, 18, 7 and 20.",
  opts: ["12", "13", "15", "18"], ans: 2,
  trick: "the range is one subtraction — largest minus smallest — and it is a measure of SPREAD, so it never sits in the middle of the data",
  why: "20 − 5 = 15.",
  traps: ["A: the middle value given.",
          "B: 18 − 5 taken, the largest value misread.",
          "D: the largest value given."] },

{ sig: "median-odd-count", code: "GAT-Q-DAT.5", lvl: 1,
  stem: "Find the median of 14, 3, 9, 21 and 6.",
  opts: ["6", "9", "10.6", "14"], ans: 1,
  trick: "ORDER the values before anything else — the median is the middle of the sorted list, never the middle of the list as printed",
  why: "In order the values are 3, 6, 9, 14, 21, so the median is 9.",
  traps: ["A: the second value in the sorted list given.",
          "C: the mean given.",
          "D: the middle of the unsorted list taken."] },

{ sig: "probability-single-die", code: "GAT-Q-DAT.3", lvl: 1,
  stem: "A fair six-sided die is rolled once. What is the probability of getting a number greater than 4?",
  opts: [{ eq: "j_p16" }, { eq: "j_p13" }, { eq: "j_p12" }, { eq: "j_p23" }], ans: 1,
  trick: "'greater than 4' does not include 4 — list the outcomes that qualify rather than subtracting in your head",
  why: "Only 5 and 6 are greater than 4, so the probability is 2/6 = 1/3.",
  traps: ["A: only one outcome counted.",
          "C: 4, 5 and 6 counted, so 4 wrongly included.",
          "D: the complement given."] },

{ sig: "probability-two-coins", code: "GAT-Q-DAT.3", lvl: 2,
  stem: "Two fair coins are tossed together. What is the probability that exactly one of them shows heads?",
  opts: [{ eq: "j_p14" }, { eq: "j_p13" }, { eq: "j_p12" }, { eq: "j_p34" }], ans: 2,
  trick: "write the four outcomes out — HH, HT, TH, TT — because head-then-tail and tail-then-head are two different outcomes, not one",
  why: "Two of the four equally likely outcomes, HT and TH, show exactly one head, so the probability is 2/4 = 1/2.",
  traps: ["A: HT and TH counted as a single outcome.",
          "B: three outcomes assumed instead of four.",
          "D: 'at least one head' answered instead."] },

{ sig: "probability-two-dice-sum", code: "GAT-Q-DAT.3", lvl: 2,
  stem: "Two fair six-sided dice are rolled. What is the probability that the total is 7?",
  opts: [{ eq: "j_p112" }, { eq: "j_p16" }, { eq: "j_p17" }, { eq: "j_p736" }], ans: 1,
  trick: "the sample space is 36, not 12 — and 7 is the total with the most ways of happening, six of them, which is worth remembering outright",
  why: "The pairs giving 7 are (1,6), (2,5), (3,4), (4,3), (5,2) and (6,1): six of 36 outcomes, so 6/36 = 1/6.",
  traps: ["A: only three pairs counted, the reversals missed.",
          "C: the total 7 written straight into the fraction.",
          "D: seven outcomes counted."] },

{ sig: "arrangements-with-repeats", code: "GAT-Q-DAT.4", lvl: 2,
  stem: "How many different arrangements can be made of all the letters of the word SALAM?",
  opts: ["20", "60", "120", "240"], ans: 1,
  trick: "the two A's are identical, so every arrangement has been counted twice — divide the 5! by 2",
  why: "5! = 120 arrangements if the letters were all different; the repeated A halves that, giving 60.",
  traps: ["A: 5 × 4 taken.",
          "C: the repeat not divided out — the trap this item exists for.",
          "D: the count doubled instead of halved."] },

// ================================================================ WORD LOGIC
{ sig: "time-from-distance-speed", code: "GAT-Q-LOG.1", lvl: 1,
  stem: "A car covers 90 km at a steady 60 km/h. How long does the journey take?",
  opts: ["1 hour 15 minutes", "1 hour 30 minutes", "1 hour 50 minutes", "2 hours"], ans: 1,
  trick: "0.5 of an hour is 30 minutes, not 50 — convert the decimal part by multiplying by 60, never by reading it as minutes",
  why: "90 ÷ 60 = 1.5 hours, which is 1 hour 30 minutes.",
  traps: ["A: 0.25 of an hour taken.",
          "C: the decimal 1.5 read as 1 hour 50 minutes — the trap this item exists for.",
          "D: rounded up to a whole number of hours."] },

{ sig: "discount-then-vat", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "An item priced at 400 SAR is sold with a 25% discount, and 15% VAT is then added to the discounted price. What does the customer pay, in riyals?",
  opts: ["300", "340", "345", "360"], ans: 2,
  trick: "apply the two changes IN ORDER — the VAT is charged on what you actually pay, not on the original price, so it is 15% of 300",
  why: "The discount gives 400 × 0.75 = 300 SAR, and adding 15% gives 300 × 1.15 = 345 SAR.",
  traps: ["A: the VAT left off.",
          "B: 15% of 400 subtracted from 400 instead.",
          "D: the two percentages combined as a single 10% reduction."] },

{ sig: "best-buy-unit-price", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "Rice is sold in a 3 kg bag for 21 SAR and a 5 kg bag for 32 SAR. How much is saved per kilogram by buying the larger bag?",
  opts: ["0.10 SAR", "0.60 SAR", "1.00 SAR", "1.40 SAR"], ans: 1,
  trick: "bring both to the SAME unit — price per kilogram — before comparing. Comparing the bag prices, or the bag sizes, compares nothing",
  why: "The small bag costs 21 ÷ 3 = 7 SAR/kg and the large 32 ÷ 5 = 6.40 SAR/kg, a saving of 0.60 SAR per kilogram.",
  traps: ["A: the difference of the totals divided by the difference of the weights.",
          "C: 7 − 6 taken, the decimal dropped.",
          "D: the totals subtracted and divided by 8."] },

{ sig: "recipe-scale-ratio", code: "GAT-Q-LOG.3", lvl: 1,
  stem: "A recipe for 4 people needs 300 g of rice. How many grams are needed for 10 people?",
  opts: ["600", "700", "750", "900"], ans: 2,
  trick: "find the amount for ONE first — dividing by 4 and multiplying by 10 is safer than trying to scale by 2½ in one move",
  why: "300 ÷ 4 = 75 g per person, and 75 × 10 = 750 g.",
  traps: ["A: doubled for 8 people and left there.",
          "B: 300 + 400 taken.",
          "D: scaled by 3 for 12 people."] },

{ sig: "profit-percent-simple", code: "GAT-Q-LOG.4", lvl: 1,
  stem: "A shopkeeper buys an item for 80 SAR and sells it for 100 SAR. What is his percentage profit?",
  opts: ["20%", "25%", "80%", "125%"], ans: 1,
  trick: "profit percent is measured against the COST price, not the selling price — the 20 riyals of profit sit on a base of 80",
  why: "The profit is 20 SAR on a cost of 80, and 20 ÷ 80 = 25%.",
  traps: ["A: 20 ÷ 100 taken, the selling price used as the base.",
          "C: the cost given as a percentage of the sale.",
          "D: the sale given as a percentage of the cost."] },

{ sig: "annual-after-deduction", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "A monthly salary of 7 000 SAR is subject to a 15% deduction. What is the annual salary after the deduction, in riyals?",
  opts: ["71 400", "72 000", "79 800", "84 000"], ans: 0,
  trick: "two operations, and the ORDER does not matter — but the word 'annual' does, and stopping at the monthly figure is the mark",
  why: "After the deduction the monthly pay is 7 000 × 0.85 = 5 950 SAR, and 5 950 × 12 = 71 400 SAR a year.",
  traps: ["B: rounded to a convenient figure.",
          "C: the deduction read as 5% instead of 15%.",
          "D: the annual salary before the deduction."] },

{ sig: "minimum-buses-ceiling", code: "GAT-Q-LOG.3", lvl: 1,
  stem: "A school is taking 146 students on a trip. Each bus carries 40 students. What is the least number of buses needed?",
  opts: ["3", "4", "5", "6"], ans: 1,
  trick: "always round UP when the question asks for the least number needed — the six students left over still have to travel",
  why: "146 ÷ 40 = 3.65, so 4 buses are needed; three would leave 26 students behind.",
  traps: ["A: rounded down.",
          "C: 146 ÷ 30 taken.",
          "D: one bus added for the teachers, which the question does not mention."] },

{ sig: "simple-interest-one-year", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "A sum of 12 000 SAR earns simple interest at 5% per year. What is the total after two years, in riyals?",
  opts: ["12 600", "13 200", "13 230", "13 800"], ans: 1,
  trick: "SIMPLE interest is charged on the original sum every year — the second year's interest is on 12 000 again, not on the new total",
  why: "The interest is 600 SAR a year, so after two years the total is 12 000 + 1 200 = 13 200 SAR.",
  traps: ["A: only one year of interest added.",
          "C: compound interest worked out instead.",
          "D: three years of interest added."] },

];
