// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part B: geometry, data and logic (50 items)
// Original writing throughout; see sim_items_a.js for the rules this file follows.
// ---------------------------------------------------------------------------
const CMP = ["A is greater", "B is greater", "they are equal",
             "not enough information"];

module.exports = [

// ================================================================ GEOMETRY
{ sig: "medial-triangle-fraction", code: "GAT-Q-GEO.2", lvl: 3,
  stem: "The midpoints of the sides of the equilateral triangle below are joined, and the median from the apex is drawn. Find the area of the shaded triangle.",
  fig: "sim_medial", figW: 1.75,
  opts: [{ eq: "o4r3" }, { eq: "o8r3" }, { eq: "o16r3" }, { eq: "o32r3" }], ans: 1,
  trick: "join the midpoints, then halve again — the shaded piece is an eighth of the whole, and the area of an equilateral triangle is (root 3 over 4) times the side squared",
  why: "The whole triangle has area (√3⁄4) × 16² = 64√3. Joining the midpoints cuts it into four congruent triangles, and the shaded piece is half of one of them — an eighth of the whole. So 64√3 ÷ 8 = 8√3.",
  traps: ["A: took a sixteenth by halving one step too many.",
          "C: gave one of the four medial triangles, 64√3 ÷ 4, without the final halving.",
          "D: gave half the whole triangle."] },

{ sig: "similar-third-angle", code: "GAT-Q-GEO.2", lvl: 2,
  stem: "The two triangles below are similar and drawn in the same orientation. Find the value of x.",
  fig: "sim_similar", figW: 2.82,
  opts: ["75", "85", "95", "105"], ans: 1,
  trick: "similar triangles share all three angles, so the third one is 180 minus the other two",
  why: "Similar triangles have the same three angles: 35°, 60° and the apex. The apex is 180 − 35 − 60 = 85°, and x marks that apex.",
  traps: ["A: subtracted 35 from 110.",
          "C: used 180 − 60 − 25.",
          "D: added the two given angles and subtracted from 200."] },

{ sig: "halve-twice-ratio", code: "GAT-Q-GEO.2", lvl: 3,
  stem: "In triangle KLM, P is the midpoint of KL and Q is the midpoint of KP. Find the ratio of KQ to KL.",
  opts: [{ eq: "f14" }, { eq: "f12" }, { eq: "f13" }, { eq: "f35" }], ans: 0,
  trick: "halving twice quarters the length — and read carefully WHICH two points the ratio is between",
  why: "KP is half of KL, and KQ is half of KP, so KQ is a quarter of KL. (Both points lie on the same side, KL, which is what makes the ratio well defined.)",
  traps: ["B: halved once and stopped at the first midpoint.",
          "C: no midpoint route gives a third.",
          "D: took the remaining part, QL ⁄ KL = 3/4, instead of the part asked for."] },

{ sig: "perimeter-to-area-parts", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "Six identical small rectangles make up the rectangle drawn below, whose perimeter measures 34 cm. What is the area of one small rectangle, in cm²?",
  fig: "sim_rect_parts", figW: 2.20,
  opts: ["8", "10", "12", "15"], ans: 1,
  trick: "the perimeter gives the missing side; the height is already on the diagram",
  why: "The height is 5 cm, so 2(L + 5) = 34 gives L = 12 cm. The whole area is 12 × 5 = 60 cm², and one of six equal parts is 60 ÷ 6 = 10 cm².",
  traps: ["A: used L = 12 but divided the area by 7.5 after a slip.",
          "C: took L = 14 by forgetting that the perimeter counts each side twice.",
          "D: divided 60 by 4."] },

{ sig: "area-equal-then-perimeter", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "A triangle has the three sides listed below. A rectangle 6 cm wide covers exactly the same area as that triangle. What is the rectangle's perimeter, in cm?",
  stemEq: "s_areaeq",
  opts: ["30", "36", "42", "54"], ans: 0,
  trick: "9-12-15 is a right triangle, so its area is half the product of the two SHORT sides — the 15 never enters",
  why: "9² + 12² = 81 + 144 = 225 = 15², so the triangle is right-angled and its area is ½ × 9 × 12 = 54 cm². The rectangle has area 54 and width 6, so its length is 9 and its perimeter is 2(9 + 6) = 30 cm.",
  traps: ["B: used the triangle's own perimeter of 36.",
          "C: added the length and width of the rectangle to the triangle's short sides.",
          "D: gave the area rather than the perimeter."] },

{ sig: "circle-tangent-triangles", code: "GAT-Q-GEO.3", lvl: 3,
  stem: "In the diagram below, O is the centre of the circle. Each shaded piece is bounded by three lines: the horizontal diameter, a second line through O drawn at 135° to it, and the tangent to the circle at the point where the diameter meets it. Find the total shaded area, in cm².",
  stemEq: "s_radius",
  fig: "sim_circle_tangent", figW: 1.75,
  opts: ["20", "25", "50", "100"], ans: 1,
  trick: "the two pieces are right triangles with both legs equal to the radius, so together they come to exactly r squared",
  why: "The line leaves O at 45° to the diameter, so each shaded piece is a right triangle with legs r and r. Each has area ½ × 25 = 12.5, and the two together give 25 cm².",
  traps: ["A: used ½ × r × r once and then rounded.",
          "C: forgot to halve, giving r² × 2.",
          "D: used the square on the diameter."] },

{ sig: "arc-central-angle-compare", code: "GAT-Q-GEO.3", lvl: 3,
  stem: "In the circle below, two straight lines pass through the centre O. Which is greater?   A: arc PQR   B: arc PST",
  fig: "sim_circle_arcs", figW: 1.60,
  opts: CMP, ans: 1,
  trick: "both lines pass through the centre, so each arc is measured by its own central angle",
  why: "Both lines are diameters, so each arc is measured by its central angle. The angle between them is 74°, so arc PQR = 74° and arc PST = 180 − 74 = 106°. B is the longer arc.",
  traps: ["A: read the 74° as belonging to the arc through S.",
          "C: assumed two diameters always cut the circle into equal arcs.",
          "D: the central angle is given, so both arcs are determined."] },

{ sig: "segment-ratio-midpoint", code: "GAT-Q-GEO.4", lvl: 3,
  stem: "In the figure, r and s are the midpoints of pv and qw. Also tv = uw = ¼ of rt = ¼ of su. Find the ratio of (rt + tv + su) to (2 pr + rt).",
  fig: "sim_segments", figW: 2.30,
  opts: [{ eq: "f47" }, { eq: "f914" }, { eq: "f57" }, { eq: "f12" }], ans: 1,
  trick: "r is a midpoint, so pr equals rv, and rv is rt plus tv — that is what fixes the ratio",
  why: "Let tv = uw = k, so rt = su = 4k. Then rv = rt + tv = 5k, and since r is the midpoint of pv, pr = rv = 5k. The ratio is (4k + k + 4k) ⁄ (10k + 4k) = 9k ⁄ 14k = 9/14.",
  traps: ["A: used pr = 4k, forgetting the tv piece.",
          "C: put 10k on top by counting rt twice.",
          "D: cancelled the k and simplified 9/14 to a half by eye."] },

{ sig: "clock-angle", code: "GAT-Q-GEO.1", lvl: 2,
  stem: "The clock face below shows one minute of the minute hand's turn, marked x. Find x.",
  fig: "sim_clock", figW: 1.93,
  opts: ["3°", "5°", "6°", "12°"], ans: 2,
  trick: "one minute is a sixtieth of the whole turn, so 360 divided by 60",
  why: "The minute hand goes right round in 60 minutes, so one minute is 360 ÷ 60 = 6°.",
  traps: ["A: divided 180 by 60.",
          "B: divided 300 by 60, using only five of the six ten-minute blocks.",
          "D: gave the angle for two minutes, or divided 720 by 60."] },

{ sig: "rhombus-diagonals", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "Each square of the grid below is one unit across. What is the area of the rhombus, in square units?",
  fig: "sim_rhombus", figW: 1.95,
  opts: ["40", "48", "56", "96"], ans: 1,
  trick: "a rhombus is HALF the product of its diagonals, never base times height off the grid",
  why: "The horizontal diagonal spans 12 units and the vertical one spans 8, so the area is ½ × 12 × 8 = 48.",
  traps: ["A: counted only the whole squares inside and ignored the half squares.",
          "C: used a diagonal of 14 by counting grid lines instead of the gaps between them.",
          "D: multiplied the diagonals without halving."] },

{ sig: "pythagoras-consecutive-legs", code: "GAT-Q-GEO.2", lvl: 3,
  stem: "A right triangle has hypotenuse 26 cm, and its legs are y and y + 14. Find its area, in cm².",
  stemEq: "s_pyth",
  opts: ["60", "84", "120", "156"], ans: 2,
  trick: "the legs differ by 14 and the hypotenuse is 26, which is the 10-24-26 triangle; the area uses the LEGS, never the hypotenuse",
  why: "y² + (y + 14)² = 676 gives 2y² + 28y − 480 = 0, so y² + 14y − 240 = 0 and y = 10. The legs are 10 and 24, and the area is ½ × 10 × 24 = 120 cm².",
  traps: ["A: used ½ × 10 × 12.",
          "B: used ½ × 26 × 6.5, treating the hypotenuse as a base.",
          "D: multiplied the two legs without halving, then adjusted."] },

{ sig: "trapezoid-slant", code: "GAT-Q-GEO.2", lvl: 2,
  stem: "Find the value of x in the figure below.",
  fig: "sim_trapezoid", figW: 2.10,
  opts: ["15", "16", "17", "19"], ans: 2,
  trick: "the slant closes a right triangle whose horizontal leg is the DIFFERENCE of the two parallel sides",
  why: "The horizontal leg is 19 − 11 = 8 and the vertical leg is 15, so x = √(64 + 225) = √289 = 17. This is the 8-15-17 triangle.",
  traps: ["A: took x as the height of 15.",
          "B: rounded √289 badly, or used √(15² + 5²).",
          "D: took x as the base of 19."] },

{ sig: "triangle-inequality", code: "GAT-Q-GEO.2", lvl: 2,
  stem: "A triangle has two sides of 7 cm and 11 cm. Which of the following CANNOT be the length of the third side, in cm?",
  opts: ["5", "9", "13", "18"], ans: 3,
  trick: "the third side must be strictly between the difference and the sum of the other two",
  why: "The third side must satisfy 11 − 7 < s < 11 + 7, that is 4 < s < 18. 18 fails, because a side equal to the sum makes the three points collinear rather than a triangle.",
  traps: ["A: 5 is above 4, so it is allowed.",
          "B: 9 sits comfortably inside the range.",
          "C: 13 is below 18, so it is allowed."] },

{ sig: "polygon-exterior-angles", code: "GAT-Q-GEO.1", lvl: 2,
  stem: "A regular octagon rests on a straight line as shown. Find x + y.",
  fig: "sim_polygon_ext", figW: 2.10,
  opts: ["90", "120", "135", "270"], ans: 0,
  trick: "each exterior angle of a regular polygon is 360 divided by the number of sides — the interior angle is a detour",
  why: "A regular octagon has interior angle 135°, so each exterior angle is 180 − 135 = 45°. Then x + y = 45 + 45 = 90°.",
  traps: ["B: used a hexagon's exterior angle of 60 twice.",
          "C: gave one interior angle instead of two exterior ones.",
          "D: added the two interior angles and subtracted from 540."] },

{ sig: "parallel-isosceles-angle", code: "GAT-Q-GEO.1", lvl: 3,
  stem: "In the figure, the two marked sides are equal and the two arrowed lines are parallel. Find x.",
  fig: "sim_parallel_iso", figW: 2.20,
  opts: ["40", "50", "70", "110"], ans: 2,
  trick: "get the base angle from the isosceles triangle first, then carry it across with corresponding angles",
  why: "The triangle is isosceles with apex 40°, so each base angle is (180 − 40) ÷ 2 = 70°. The ray is parallel to the left-hand side, so x corresponds to that 70° base angle. x = 70°.",
  traps: ["A: copied the apex angle.",
          "B: used (180 − 80) ÷ 2.",
          "D: gave the angle on the other side of the line, 180 − 70."] },

{ sig: "angles-round-a-point", code: "GAT-Q-GEO.1", lvl: 1,
  stem: "Find the value of x in the figure below.",
  fig: "sim_angles_point", figW: 1.70,
  opts: ["100°", "110°", "130°", "140°"], ans: 2,
  trick: "angles round a point add to 360, and the square is a right angle you have to remember to count",
  why: "The three angles at the point fill a whole turn: 140 + 90 + x = 360, so x = 130°.",
  traps: ["A: used 180 − 80.",
          "B: subtracted from 340 rather than 360.",
          "D: copied the given 140°."] },

{ sig: "circle-area-scale-compare", code: "GAT-Q-GEO.3", lvl: 3,
  stem: "A small circle has radius 5 cm and a large circle has radius 9 cm. Which is greater?   A: three times the area of the small circle   B: the area of the large circle",
  opts: CMP, ans: 1,
  trick: "area scales with the SQUARE of the radius — compare 3 × 25 with 81, not 3 × 5 with 9",
  why: "The small area is 25π and three times it is 75π. The large area is 81π. Since 75π < 81π, B is greater.",
  traps: ["A: compared 3 × 5 = 15 with 9 and stopped — that is the radius, not the area.",
          "C: took 3 × 25 as 81 by rounding.",
          "D: both radii are given, so both areas are determined; π cancels."] },

{ sig: "parallelogram-strip-ratio", code: "GAT-Q-GEO.4", lvl: 3,
  stem: "The rectangle below is cut by the marked widths along the top. Find the ratio of the shaded region to the whole rectangle.",
  fig: "sim_strip", figW: 2.60,
  opts: ["1 : 4", "1 : 5", "2 : 5", "1 : 3"], ans: 1,
  trick: "a slanted strip is a parallelogram — its area is its top width times the height, exactly as if it stood upright",
  why: "The shaded strip is a parallelogram of width 2 and full height, and the rectangle is 5 + 2 + 3 = 10 wide with the same height. So the ratio is 2 : 10 = 1 : 5.",
  traps: ["A: used the 5 and the 2 and read 2 : 8.",
          "C: compared the strip with only the part of the rectangle to its left.",
          "D: assumed the lean makes the strip bigger than an upright one of the same width."] },

// ==================================================================== DATA
{ sig: "probability-count-over-total", code: "GAT-Q-DAT.3", lvl: 1,
  stem: "Tickets are numbered from 1 to 30. One is drawn at random. Find the probability that its number is a multiple of 5.",
  opts: [{ eq: "f15" }, { eq: "f16" }, { eq: "f13" }, "6"], ans: 0,
  trick: "probability is the favourable COUNT over the TOTAL, never the count on its own",
  why: "The multiples of 5 up to 30 are 5, 10, 15, 20, 25 and 30 — six of them — so the probability is 6/30 = 1/5.",
  traps: ["B: counted only five multiples, forgetting that 30 is itself one.",
          "C: counted the multiples of 3 instead, giving 10/30.",
          "D: gave the COUNT of favourable tickets rather than a probability."] },

{ sig: "two-way-table", code: "GAT-Q-DAT.1", lvl: 3,
  stem: "A crate holds 40 oranges: 24 large and 16 small. In total 27 oranges are ripe, and 11 of the small ones are ripe. How many large oranges are unripe?",
  opts: ["6", "8", "10", "13"], ans: 1,
  trick: "'large or small' and 'ripe or unripe' are two different cuts of the same 40 — build the table before answering",
  why: "Ripe oranges number 27, of which 11 are small, so 16 are large and ripe. There are 24 large oranges altogether, so 24 − 16 = 8 large ones are unripe.",
  traps: ["A: subtracted 11 from 16 and stopped.",
          "C: used 27 − 16 and then a wrong large total.",
          "D: gave the number of unripe oranges of both sizes (40 − 27)."] },

{ sig: "venn-and", code: "GAT-Q-DAT.1", lvl: 2,
  stem: "In the Venn diagram below, which is greater?   A: the number of dots in P   B: the number of dots in Q and R",
  fig: "sim_venn", figW: 2.70,
  opts: CMP, ans: 0,
  trick: "'in Q and R' means in BOTH — the overlap, not the total of the two",
  why: "P holds 6 dots. 'In Q and R' means the overlap of Q and R, which holds 1. So A is greater. (The same skill without a picture reads: 10 employees in one section, 8 in the other, 15 people in total, so 10 + 8 − 15 = 3 are in both.)",
  traps: ["B: read 'Q and R' as the total of Q and R (5 + 3 = 8) and forgot that the shared dot is counted twice.",
          "C: counted Q alone against a miscount of P.",
          "D: every dot is visible, so nothing is missing."] },

{ sig: "venn-or", code: "GAT-Q-DAT.1", lvl: 2,
  stem: "In the Venn diagram below, which is greater?   A: the number of dots in P   B: the number of dots in Q or R",
  fig: "sim_venn", figW: 2.70,
  opts: CMP, ans: 1,
  trick: "'Q or R' is the union — count each dot once, even where the circles cross",
  why: "P holds 6 dots. 'In Q or R' means in either, which is 5 + 3 − 1 = 7 dots. So B is greater. This is the same picture as the previous item; only the word between Q and R changes.",
  traps: ["A: repeated the answer to the previous item without re-reading the word 'or'.",
          "C: counted the union as 6 by double-counting the shared dot.",
          "D: every dot is visible."] },

{ sig: "bar-plus-given-ratio", code: "GAT-Q-DAT.1", lvl: 3,
  stem: "The chart shows overseas visitors to AlUla, in thousands. If 300 thousand domestic visitors came in 1447, find the domestic share of all visitors that year.",
  fig: "sim_visitors", figW: 2.68,
  opts: ["15 %", "20 %", "25 %", "30 %"], ans: 1,
  trick: "the bar gives OVERSEAS visitors only; the total is that bar plus the domestic figure",
  why: "The 1447 bar reads 1200 thousand from overseas. The total is 1200 + 300 = 1500 thousand, and 300 ⁄ 1500 = 1/5 = 20%.",
  traps: ["A: divided 300 by 2000 by misreading the bar.",
          "C: used the 1446 bar of 1000 instead of the 1447 bar.",
          "D: took the ratio of domestic to OVERSEAS (300 : 1200 = 25%) — and then mis-rounded."] },

{ sig: "two-bar-ratio", code: "GAT-Q-DAT.1", lvl: 1,
  stem: "The bar chart below shows the sales of two branches. What is the ratio of the first branch to the second?",
  fig: "sim_two_bars", figW: 2.27,
  opts: ["1 : 4", "2 : 1", "3 : 1", "4 : 1"], ans: 3,
  trick: "read both bars off the axis, then divide; do not eyeball the ratio",
  why: "The first branch reads 800 and the second 200, so the ratio is 800 : 200 = 4 : 1.",
  traps: ["A: wrote the ratio the wrong way round.",
          "B: read the second bar as 400.",
          "C: compared the two heights by eye rather than off the axis."] },

{ sig: "grouped-bar-minimise", code: "GAT-Q-DAT.1", lvl: 2,
  stem: "The chart shows vehicles at four gates. To avoid delays caused by buses and lorries, which gate is the best?",
  fig: "sim_grouped_min", figW: 3.09,
  opts: ["Gate 1", "Gate 2", "Gate 3", "Gate 4"], ans: 2,
  trick: "'buses and lorries' means add those two bars only — the car bar is a decoy and must be ignored",
  why: "Buses + lorries: Gate 1 is 40 + 50 = 90, Gate 2 is 55 + 40 = 95, Gate 3 is 30 + 35 = 65, Gate 4 is 45 + 60 = 105. Gate 3 is the lowest, so it is the best.",
  traps: ["A: added all three bars, which puts Gate 1 at 180 and hides Gate 3's advantage.",
          "B: read 'best' as the busiest gate.",
          "D: Gate 4 is the WORST on the two rows that matter."] },

{ sig: "bar-mean-match", code: "GAT-Q-DAT.5", lvl: 2,
  stem: "In the chart below, the average of Physics and Arabic equals which subject?",
  fig: "sim_subjects", figW: 2.91,
  opts: ["English", "Geography", "Art", "Physics"], ans: 1,
  trick: "the mean of two bars is the height halfway between them — find that height on the axis, then read across",
  why: "Physics is 90 and Arabic is 30, so their average is 60 — the height of the Geography bar.",
  traps: ["A: English is 75, the average of Physics and Geography.",
          "C: Art is 45, the average of Arabic and Geography.",
          "D: Physics is one of the two bars being averaged, so it cannot be the answer."] },

{ sig: "negative-bars-window", code: "GAT-Q-DAT.1", lvl: 3,
  stem: "Four investment funds are plotted below across four years. Over 2022, 2023 and 2024 only one of them stayed clear of loss in every single year. Which one?",
  fig: "sim_invest", figW: 3.4,
  opts: ["Fund A", "Fund B", "Fund C", "Fund D"], ans: 0,
  trick: "read the window before reading the bars — 'the last three years' is 2022 to 2024, so a dip in 2021 does not count",
  why: "The last three years are 2022, 2023 and 2024. Fund B dips in 2022, Fund C in 2023 and Fund D in 2024. Fund A is positive throughout that window; its only loss is in 2021, which is outside it.",
  traps: ["B: Fund B's loss falls inside the window.",
          "C: Fund C has the tallest bar of all, which is not the same as never losing.",
          "D: Fund D's loss is in the very last year — inside the window."] },

{ sig: "scatter-group-mean", code: "GAT-Q-DAT.5", lvl: 2,
  stem: "The scatter graph below shows the readings taken in each quarter. Find the mean of the three readings plotted for the third quarter.",
  fig: "sim_scatter", figW: 3.03,
  opts: ["45", "50", "55", "60"], ans: 1,
  trick: "'third quarter' is the third GROUP of points, not the third point in each group",
  why: "The third group reads 45, 55 and 50, and (45 + 55 + 50) ÷ 3 = 50.",
  traps: ["A: gave the lowest point in the group rather than the average.",
          "C: gave the highest point in the group.",
          "D: averaged the fourth group by mistake."] },

{ sig: "line-percent-increase", code: "GAT-Q-DAT.1", lvl: 2,
  stem: "The line graph below shows the monthly figures. Find the percentage increase from Rajab to Shaaban.",
  fig: "sim_line_months", figW: 3.18,
  opts: ["120 %", "140 %", "175 %", "240 %"], ans: 1,
  trick: "percentage increase divides by the STARTING value, not by the finishing one",
  why: "Rajab is 5 and Shaaban is 12. The increase is 7, and 7 ÷ 5 = 1.4, so 140%.",
  traps: ["A: divided the increase by 6 after misreading Rajab.",
          "C: divided the increase by the average of the two values.",
          "D: divided 12 by 5 and read 2.4 as 240% — that is the RATIO, not the increase."] },

{ sig: "grouped-bar-double", code: "GAT-Q-DAT.1", lvl: 3,
  stem: "The chart below shows the cups sold each day. On which day is the number of tea and juice cups together double the number of coffee cups?",
  fig: "sim_grouped_double", figW: 3.09,
  opts: ["Thursday", "Friday", "Saturday", "Sunday"], ans: 0,
  trick: "add the two named bars first, then compare with DOUBLE the third — do not compare the bars one at a time",
  why: "Thursday: 45 + 35 = 80, and 2 × 40 = 80. ✓  Friday: 30 + 45 = 75 against 100. Saturday: 50 + 30 = 80 against 120. Sunday: 40 + 50 = 90 against 60.",
  traps: ["B: Friday has the tallest coffee bar of the first three, which reads as 'the most' rather than 'double'.",
          "C: Saturday's tea and juice also total 80, but its coffee bar is 60, not 40.",
          "D: Sunday is the only other day where tea and juice beat coffee — but 90 is not 60 doubled."] },

// =================================================================== LOGIC
{ sig: "rate-then-scale", code: "GAT-Q-LOG.2", lvl: 1,
  stem: "A press prints 150 pages in 6 minutes. How many minutes does it take to print 1000 pages?",
  opts: ["30", "40", "45", "50"], ans: 1,
  trick: "find the rate per minute first, then divide — the two given numbers never both go on the same side",
  why: "The rate is 150 ÷ 6 = 25 pages per minute, so 1000 ÷ 25 = 40 minutes.",
  traps: ["A: used a rate of 33 pages per minute.",
          "C: scaled 6 minutes by 1000/150 and rounded badly.",
          "D: used a rate of 20 pages per minute."] },

{ sig: "fraction-remainder-whole", code: "GAT-Q-LOG.2", lvl: 3,
  stem: "Three teams lay a pipeline. The first lays a third of it and the second lays half of it. The third team lays the remaining 24 m. How many metres does the second team lay?",
  opts: ["48", "60", "72", "96"], ans: 2,
  trick: "the leftover fraction is what fixes the whole — add the two given fractions and subtract from 1 first",
  why: "The first two lay 1/3 + 1/2 = 5/6, so the third team's 24 m is the remaining sixth. The whole pipeline is 144 m, and the second team lays half of it, 72 m.",
  traps: ["A: took a third of 144.",
          "B: found the total 144 and then took 24 × 2.5.",
          "D: took two thirds of 144."] },

{ sig: "age-chain-multiplier", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "Hessa's age is 4 times Reem's age, and Munira's age is 6 times Hessa's age. Which is greater?   A: Reem's age   B: Munira's age",
  opts: CMP, ans: 1,
  trick: "chain the multipliers: 4 then 6 is 24, not 10",
  why: "Munira is 6 × 4 = 24 times Reem's age, so for any positive age Munira is older. B is greater.",
  traps: ["A: reversed the chain and made Reem the multiple.",
          "C: assumed the two ends of the chain balance.",
          "D: the multipliers fix the comparison without knowing any actual age."] },

{ sig: "equal-split-denominations", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "A cashier has 45 banknotes, an equal number of 10 SAR, 20 SAR and 100 SAR. Which is greater?   A: 2000 SAR   B: the total value of the notes",
  opts: CMP, ans: 0,
  trick: "an equal split of 45 into three kinds is 15 of each — the count per KIND is what you multiply by, not 45",
  why: "Equal numbers means 15 notes of each, so the total is 15 × (10 + 20 + 100) = 15 × 130 = 1950 SAR. That is less than 2000, so A is greater.",
  traps: ["B: multiplied 45 by 130 instead of 15 by 130.",
          "C: rounded 1950 up to 2000.",
          "D: 'an equal number' fixes the split completely, so the total IS determined."] },

{ sig: "speed-unit-convert", code: "GAT-Q-LOG.1", lvl: 1,
  stem: "A coach travels from Jeddah to Taif in 150 minutes. The distance is 200 km. Find its average speed.",
  opts: ["60 km/h", "70 km/h", "80 km/h", "90 km/h"], ans: 2,
  trick: "convert the minutes to hours BEFORE dividing, never after",
  why: "150 minutes is 2.5 hours, so the speed is 200 ÷ 2.5 = 80 km/h.",
  traps: ["A: used 200 ÷ 3.33.",
          "B: divided 200 by 2.86 after a conversion slip.",
          "D: used 3 hours' worth of distance over 2.5 hours."] },

{ sig: "bearing-reverse", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "Hamad is south-east of Turki, and Bader is east of Hamad. Where is Turki in relation to Bader?",
  opts: ["North-west", "North-east", "South-west", "South-east"], ans: 0,
  trick: "reverse each bearing one step at a time; south-east reversed is north-west",
  why: "Reverse the first bearing: Turki is north-west of Hamad. Bader is east of Hamad, so Turki is further west and further north of Bader — north-west.",
  traps: ["B: reversed only the south part and kept the east.",
          "C: gave Bader's position relative to Turki instead of Turki's relative to Bader.",
          "D: did not reverse the bearing at all."] },

{ sig: "adjacency-puzzle", code: "GAT-Q-LOG.3", lvl: 3,
  stem: "In a four-digit number, the digit 2 is next to the digit 9 and not next to the digit 4. The digit 9 is not next to the digit 4. The number is odd. Which number is it?",
  opts: ["1294", "1429", "4129", "4291"], ans: 2,
  trick: "the adjacency conditions eliminate the options before the odd-or-even rule is even needed",
  why: "In 4129 the pair 2-9 is adjacent, 2 sits next to 1 and 9 only, 9 sits next to 2 only, and the number ends in 9 so it is odd. In 4291 the 4 touches the 2; in 1429 the 4 touches the 2; in 1294 the 9 touches the 4.",
  traps: ["A: 2 and 9 are adjacent, but 9 sits next to 4, and the number is even.",
          "B: same — 2 and 9 are adjacent, but 4 sits next to 2.",
          "D: checked only that 2 and 9 are adjacent."] },

{ sig: "period-align-subtract", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "A household spends 1200 SAR a month on internet, electricity and water together. It spends 10 800 SAR a year on internet and electricity combined. How much does it spend per month on water?",
  opts: ["200", "300", "400", "500"], ans: 1,
  trick: "put both figures on the SAME period before subtracting — a year is twelve months",
  why: "10 800 a year is 10 800 ÷ 12 = 900 a month on internet and electricity, so water is 1200 − 900 = 300 SAR a month.",
  traps: ["A: divided the 900 between two items and subtracted only one share.",
          "C: used 10 800 ÷ 13.5.",
          "D: divided 10 800 by 10 and subtracted from 1200 wrongly."] },

{ sig: "time-backwards", code: "GAT-Q-LOG.1", lvl: 2,
  stem: "A workshop lasted 3 hours and 50 minutes and finished at 00:20. When did it start?",
  opts: ["19:30", "20:00", "20:30", "21:10"], ans: 2,
  trick: "work backwards from the finish time, and remember the clock passes midnight",
  why: "Going back 3 hours from 00:20 gives 21:20, and back another 50 minutes gives 20:30.",
  traps: ["A: took off 4 hours 50 minutes.",
          "B: took off 4 hours 20 minutes.",
          "D: took off 3 hours 10 minutes."] },

{ sig: "bogo-compare", code: "GAT-Q-LOG.4", lvl: 3,
  stem: "One shop sells dates at 12 SAR a kilogram, and for every 3 kg bought it gives 1 kg free. A second shop sells dates at 10 SAR a kilogram with no offer. A customer wants 8 kg. How much less does the cheaper shop cost, in SAR?",
  opts: ["4", "8", "12", "16"], ans: 1,
  trick: "buy 3 get 1 free means you pay for 3 of every 4 kilograms — count the paid kilograms, not the free ones",
  why: "With 'buy 3 get 1 free', 8 kg comes as two blocks of 4, and the customer pays for 3 kg in each block — 6 kg in total, at 12 SAR each, which is 72 SAR. The second shop charges 8 × 10 = 80 SAR. The first shop is cheaper by 8 SAR.",
  traps: ["A: paid for 7 kg at the first shop by giving away only one kilogram in total.",
          "C: paid for 8 kg at the first shop and compared 96 with 80 incorrectly.",
          "D: compared 96 with 80."] },

{ sig: "time-unit-compare", code: "GAT-Q-LOG.1", lvl: 2,
  stem: "Riding at a steady pace, a cyclist needs 95 seconds for every lap. Which is greater?   A: the riding time for 13 laps   B: 20 minutes",
  opts: CMP, ans: 0,
  trick: "put both on the same unit before comparing — 1235 seconds against 1200 is only 35 seconds apart, so it has to be worked out, not estimated",
  why: "13 × 95 = 1235 seconds. 20 minutes is 20 × 60 = 1200 seconds. Since 1235 > 1200, A is greater.",
  traps: ["B: rounded 95 down to 90 and got 1170.",
          "C: rounded 1235 to 1200 and called it a tie — this is the trap the item is built on.",
          "D: the speed is constant and both figures are exact."] },

{ sig: "zakat-reverse-percent", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "The zakat due on a sum of money is 250 SAR. What is the original sum, in SAR?",
  opts: ["6250", "8000", "10000", "12500"], ans: 2,
  trick: "zakat is 2.5%, so the sum is the zakat divided by 0.025 — which is the same as multiplying by 40",
  why: "250 ÷ 0.025 = 250 × 40 = 10 000 SAR.",
  traps: ["A: used a rate of 4%.",
          "B: multiplied by 32.",
          "D: multiplied by 50, using a rate of 2%."] },

{ sig: "rank-front-back", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "Sultan is standing in a queue. He is 9th from the front and 15th from the back. How many people are in the queue?",
  opts: ["22", "23", "24", "25"], ans: 1,
  trick: "add the two positions and subtract one — Sultan is counted in both",
  why: "9 + 15 = 24, but Sultan himself has been counted twice, so the queue holds 24 − 1 = 23 people.",
  traps: ["A: subtracted two instead of one.",
          "C: added the two positions and forgot to subtract at all.",
          "D: added one instead of subtracting."] },

{ sig: "two-tier-tariff", code: "GAT-Q-LOG.4", lvl: 3,
  stem: "A parcel service charges 6 SAR for the first 2 kg and 75 halala for each extra kilogram. A customer paid 15 SAR. What was the parcel's weight, in kg?",
  opts: ["12", "14", "16", "18"], ans: 1,
  trick: "peel the fixed charge off first, and convert halala to riyals before dividing",
  why: "15 − 6 = 9 SAR is for the extra weight. At 0.75 SAR per kilogram that is 9 ÷ 0.75 = 12 extra kilograms, so the parcel weighs 2 + 12 = 14 kg.",
  traps: ["A: gave the extra weight and forgot the first 2 kg.",
          "C: divided the full 15 SAR by 0.75 and then trimmed.",
          "D: used 0.6 SAR per kilogram."] },

{ sig: "ages-sum-shift", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "A mother and her four children have ages summing to 94 years today. What will the five ages sum to in 6 years' time?",
  opts: ["100", "112", "118", "124"], ans: 3,
  trick: "every one of the five people gains the same 6 years, so the sum rises by 5 x 6, not by 6",
  why: "Five people each gain 6 years, so the sum rises by 5 × 6 = 30. The new sum is 94 + 30 = 124.",
  traps: ["A: added 6 once.",
          "B: added 6 three times.",
          "C: added 6 four times, counting only the children."] },

{ sig: "ages-offsets-sum", code: "GAT-Q-LOG.3", lvl: 3,
  stem: "Noura has two brothers, Ziyad and Faris. Ziyad is 4 years younger than Noura and Faris is 8 years older than Noura. If the two brothers' ages add to 46, how old is Noura?",
  opts: ["19", "21", "23", "25"], ans: 1,
  trick: "the two offsets do not cancel — write both brothers in terms of Noura and collect them",
  why: "(N − 4) + (N + 8) = 46 gives 2N + 4 = 46, so 2N = 42 and N = 21.",
  traps: ["A: solved 2N + 8 = 46.",
          "C: halved 46 and treated the offsets as cancelling.",
          "D: solved 2N − 4 = 46."] },

{ sig: "cycle-position", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "A bakery makes trays in a repeating order: date, cheese, pistachio, then almond, and starts again. What is tray number 63?",
  opts: ["date", "cheese", "pistachio", "almond"], ans: 2,
  trick: "divide by the length of the cycle and read the REMAINDER — a remainder of zero means the last item, not the first",
  why: "The cycle has length 4, and 63 ÷ 4 = 15 remainder 3. A remainder of 3 is the third item in the cycle, pistachio.",
  traps: ["A: took a remainder of 3 as meaning three whole cycles and started again.",
          "B: used a cycle of length 5.",
          "D: took the remainder 3 to mean 'three from the end'."] },

{ sig: "closing-speed", code: "GAT-Q-LOG.1", lvl: 3,
  stem: "Two friends set off towards each other at the same moment, one walking at 5 km/h and the other cycling at 19 km/h. They meet after 45 minutes. How far apart were they to begin with, in km?",
  opts: ["12", "15", "18", "24"], ans: 2,
  trick: "when two things move towards each other, ADD the speeds and treat it as one journey",
  why: "The gap closes at 5 + 19 = 24 km/h. In 45 minutes, which is 0.75 hours, that is 24 × 0.75 = 18 km.",
  traps: ["A: used the difference of the speeds instead of the sum.",
          "B: used 24 km/h for 37.5 minutes.",
          "D: forgot to convert 45 minutes and used a full hour."] },

{ sig: "ordering-chain-compare", code: "GAT-Q-LOG.3", lvl: 2,
  stem: "Bandar is taller than Yousef. Adel is taller than Salem but shorter than Yousef. Which is greater?   A: Bandar's height   B: Salem's height",
  opts: CMP, ans: 0,
  trick: "write the chain out in one line before answering — every link points the same way here",
  why: "The chain is Bandar > Yousef > Adel > Salem, so Bandar is taller than Salem. A is greater.",
  traps: ["B: reversed the second sentence and put Adel above Yousef.",
          "C: assumed two people not directly compared cannot be ordered.",
          "D: the chain connects Bandar to Salem through Yousef and Adel, so it IS decidable."] },

{ sig: "pass-fail-fraction", code: "GAT-Q-LOG.4", lvl: 2,
  stem: "In an examination 120 students passed, and the number who failed was one quarter of the number who passed. How many students sat the examination?",
  opts: ["144", "150", "160", "180"], ans: 1,
  trick: "the fraction is of the PASSERS, not of the whole entry — work out the failures, then add",
  why: "The failures number 120 ÷ 4 = 30, so the entry was 120 + 30 = 150.",
  traps: ["A: took a fifth of 120 and added.",
          "C: treated 120 as three quarters of the entry.",
          "D: treated 120 as two thirds of the entry."] },

];
