// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part C: the 23 skills that only part 6 covered
//
// Part 6 of the department sets is heavy on tables and pie charts, which is
// exactly where the bank was thinnest. Same rules as parts A and B: original
// writing, Saudi contexts, and a `sig` that must not collide with any other.
// ---------------------------------------------------------------------------
const CMP = ["A is greater", "B is greater", "they are equal",
             "not enough information"];

module.exports = [

// ==================================================================== DATA
{ sig: "table-missing-cell", code: "GAT-Q-DAT.1", lvl: 2,
  stem: "The table below is complete except for one figure. How many trainers are there in Jeddah?",
  fig: "sim_table_cells", figW: 3.30,
  opts: ["59", "62", "65", "71"], ans: 2,
  trick: "use the ROW that the gap sits in, not the column — the row total is the one that closes",
  why: "The trainers row must add to 186, and 42 + 55 + 24 = 121, so the missing figure is 186 − 121 = 65. (The Jeddah column checks out too: 65 + 31 + 97 = 193.)",
  traps: ["A: closed the column with 193 − 31 − 97 and then slipped by six.",
          "B: added the row wrongly as 124.",
          "D: took the Abha column total instead of the missing cell."] },

{ sig: "table-multi-row-condition", code: "GAT-Q-DAT.1", lvl: 3,
  stem: "In the table below, which categories at least TREBLED between 1443 and 1447?",
  fig: "sim_table_years", figW: 2.60,
  opts: ["Food and Housing", "Housing and Transport", "Transport only",
         "Housing, Transport and Health"], ans: 1,
  trick: "test every row against the multiplier, and ignore the middle column — it is there to slow you down",
  why: "Housing goes 40 → 120, exactly three times. Transport goes 25 → 75, exactly three times. Food goes 60 → 150, only two and a half times. Health goes 30 → 66, only 2.2 times. So Housing and Transport.",
  traps: ["A: Food rises the most in absolute terms (90) but not by the largest factor.",
          "C: Transport qualifies, but so does Housing.",
          "D: Health falls short at 2.2 times."] },

{ sig: "pie-sector-from-values", code: "GAT-Q-DAT.1", lvl: 3,
  stem: "A farm's harvest over six years totalled 1080 tons. The second and fifth years together produced 210 tons. Using the chart, find the angle of the fifth year's sector.",
  fig: "sim_pie_years", figW: 2.45,
  opts: ["20°", "25°", "30°", "35°"], ans: 2,
  trick: "convert tons to degrees ONCE — the whole 1080 tons is 360°, so every 3 tons is one degree",
  why: "1080 tons fill 360°, so 3 tons make 1°. The second and fifth years are 210 tons = 70°. The second year is marked 40°, so the fifth is 70 − 40 = 30°.",
  traps: ["A: gave 210 ÷ 3 ÷ 3 by dividing twice.",
          "B: subtracted 40 from 65 after mis-converting.",
          "D: used 105° for the pair by taking 2 tons to the degree."] },

{ sig: "pie-angle-to-count", code: "GAT-Q-DAT.1", lvl: 2,
  stem: "The chart shows how 480 trainees finished a course. How many passed?",
  fig: "sim_pie_exam", figW: 2.10,
  opts: ["160", "200", "240", "280"], ans: 2,
  trick: "the passed sector is a straight line through the centre, so it is exactly half — no measuring needed",
  why: "The 'Passed' sector is bounded by a diameter, so it is 180° of 360°, that is half. Half of 480 is 240.",
  traps: ["A: took a third.",
          "B: used 150° instead of 180°.",
          "D: added the absent sector to the passed one."] },

// ================================================================ GEOMETRY
{ sig: "pie-missing-sector-angle", code: "GAT-Q-GEO.1", lvl: 2,
  stem: "In the pie chart below, find the angle of the sector for the trainees who failed.",
  fig: "sim_pie_exam", figW: 2.10,
  opts: ["105°", "120°", "135°", "150°"], ans: 2,
  trick: "the three sectors fill a whole turn, so subtract from 360 — and remember the passed sector is 180, not something to measure",
  why: "Passed is 180° and absent is 45°, so failed is 360 − 180 − 45 = 135°.",
  traps: ["A: subtracted 45 from 150.",
          "B: forgot the 45° absent sector and took 360 − 180 − 60.",
          "D: subtracted only the 45° and halved what was left."] },

{ sig: "equal-sectors-shaded-angle", code: "GAT-Q-GEO.1", lvl: 2,
  stem: "The circle below is divided into equal parts. Find the total angle of the shaded parts.",
  fig: "sim_pie_equal", figW: 1.75,
  opts: ["108°", "126°", "144°", "160°"], ans: 2,
  trick: "count the parts in the WHOLE circle first, then the shaded ones — 360 divided by the count gives one part",
  why: "There are 10 equal parts, so each is 360 ÷ 10 = 36°. Four are shaded, giving 4 × 36 = 144°.",
  traps: ["A: counted three shaded parts.",
          "B: divided 360 by 10 and multiplied by 3.5.",
          "D: divided 360 by 9 and multiplied by 4."] },

{ sig: "circles-along-diameter-ratio", code: "GAT-Q-GEO.3", lvl: 3,
  stem: "Eight equal circles are drawn in a row along the diameter of a large circle, as shown. Find the ratio of the area of one small circle to the area of the large circle.",
  fig: "sim_circles_row", figW: 2.05,
  opts: ["1 : 8", "1 : 16", "1 : 64", "1 : 80"], ans: 2,
  trick: "the eight small DIAMETERS make up the large diameter, so the radii are in the ratio 1 : 8 — and areas square that",
  why: "Eight small diameters span 80 cm, so each small circle has diameter 10 and radius 5. The large radius is 40. The areas are in the ratio 5² : 40² = 25 : 1600 = 1 : 64.",
  traps: ["A: gave the ratio of the radii, not the areas.",
          "B: squared 4 instead of 8.",
          "D: used the diameter 80 against the small radius 5 without squaring."] },

{ sig: "area-ratio-to-length-ratio", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "The areas of two circles are in the ratio shown. Find the ratio of their radii.",
  stemEq: "s_arearatio",
  opts: ["1 : 14", "1 : 49", "1 : 98", "1 : 196"], ans: 0,
  trick: "area scales with the SQUARE of the radius, so go backwards by taking the square root",
  why: "If the areas are 1 : 196 then the radii are √1 : √196 = 1 : 14.",
  traps: ["B: halved 196 twice.",
          "C: halved 196 once.",
          "D: repeated the area ratio without taking the root."] },

{ sig: "exterior-angle-theorem", code: "GAT-Q-GEO.1", lvl: 2,
  stem: "In the figure, which is greater?   A: m(P) + m(Q)   B: 135°",
  fig: "sim_ext_angle", figW: 2.60,
  opts: CMP, ans: 1,
  trick: "an exterior angle equals the two remote interior angles ADDED — the 55° is a decoy you never need",
  why: "The exterior angle at R is 130°, and an exterior angle equals the sum of the two opposite interior angles, so m(P) + m(Q) = 130°. That is less than 135°, so B is greater. (The 55° is not needed at all.)",
  traps: ["A: worked out m(Q) = 75 and then added 75 + 65 or similar.",
          "C: read 130 as 135.",
          "D: the exterior angle fixes the sum exactly."] },

// ============================================================== ARITHMETIC
{ sig: "percent-of-count-from-figure", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "The shaded squares in the figure are 20% of all the squares in it. How many squares are there altogether?",
  fig: "sim_squares_block", figW: 2.35,
  opts: ["48", "54", "60", "72"], ans: 2,
  trick: "count the shaded squares first, then divide by the percentage — do not try to count the empty ones",
  why: "The shaded block is 3 rows of 4, so 12 squares. If 12 is 20%, the total is 12 ÷ 0.20 = 60.",
  traps: ["A: divided 12 by 0.25.",
          "B: multiplied 12 by 4.5.",
          "D: divided 12 by 1/6 instead of 1/5."] },

{ sig: "equivalence-chain-weights", code: "GAT-Q-ARI.2", lvl: 3,
  stem: "Five dates weigh the same as two figs, and five dates also weigh the same as four apricots. What weight of dates matches 24 figs together with 40 apricots?",
  opts: ["90 dates", "100 dates", "110 dates", "120 dates"], ans: 2,
  trick: "convert each fruit to dates SEPARATELY and add at the end — the two rates are different",
  why: "Two figs are 5 dates, so 24 figs are 12 × 5 = 60 dates. Four apricots are 5 dates, so 40 apricots are 10 × 5 = 50 dates. Together, 60 + 50 = 110 dates.",
  traps: ["A: used the fig rate for both fruits.",
          "B: used the apricot rate for both fruits.",
          "D: added 24 and 40 first and then applied one rate."] },

{ sig: "power-tower-signs-compare", code: "GAT-Q-ARI.4", lvl: 3,
  stem: "Which quantity is greater?",
  stemEq: "s_powtower",
  opts: CMP, ans: 2,
  trick: "put everything on ONE base first — 25 is 5², so both brackets are powers of 5 and the exponents simply add",
  why: "(5²)^(−2) = 5^(−4). And (25^(−1))^(−3) = 25³ = (5²)³ = 5⁶. Multiplying: 5^(−4) × 5⁶ = 5² = 25. That is exactly B, so they are equal.",
  traps: ["A: multiplied the two negative exponents to get a positive and overshot.",
          "B: read 25³ as 5³.",
          "D: both sides are explicit numbers."] },

{ sig: "same-base-fractional-exponents", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Find the value of the expression below.",
  stemEq: "s_samebase",
  opts: [{ eq: "f12" }, { eq: "f14" }, { eq: "f18" }, "1"], ans: 2,
  trick: "a cube root IS the power one third, so the two exponents add to a whole one",
  why: "The cube root of 1/8 is (1/8)^(1/3). Multiplying by (1/8)^(2/3) adds the exponents: 1/3 + 2/3 = 1, so the answer is 1/8.",
  traps: ["A: took the cube root of 1/8 as 1/2 and stopped.",
          "B: multiplied the exponents instead of adding them.",
          "D: subtracted the exponents to get zero."] },

{ sig: "swapped-fraction-compare", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Which quantity is greater?",
  stemEq: "s_swapfrac",
  opts: CMP, ans: 0,
  trick: "the two look like mirror images but they are not — a third of twelve is nothing like a twelfth of three",
  why: "One third of 12 is 4. One twelfth of 3 is 0.25. So A is greater, by a long way.",
  traps: ["B: read the second as twelve thirds.",
          "C: assumed swapping the numbers must give the same answer — this is the trap the item is built on.",
          "D: both are explicit numbers."] },

{ sig: "inverse-proportion", code: "GAT-Q-ARI.2", lvl: 2,
  stem: "A generator's fuel lasts 9 hours when the load is full. How many hours will the same fuel last at 60% of that load?",
  opts: ["12", "15", "18", "21"], ans: 1,
  trick: "less load means MORE hours — divide by the fraction, never multiply by it",
  why: "The fuel is fixed, so hours and load are inversely proportional: 9 ÷ 0.60 = 15 hours.",
  traps: ["A: multiplied 9 by 4/3.",
          "C: doubled 9.",
          "D: multiplied 9 by 60/25."] },

{ sig: "divide-by-decimal", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "A storage room holds 54 m³. How many boxes of 0.045 m³ each fit inside it?",
  opts: ["900", "1080", "1200", "1350"], ans: 2,
  trick: "clear the decimal first — 54 ÷ 0.045 is the same as 54000 ÷ 45",
  why: "54 ÷ 0.045 = 54 000 ÷ 45 = 1200.",
  traps: ["A: divided by 0.06.",
          "B: divided by 0.05.",
          "D: divided by 0.04."] },

{ sig: "percent-less-than-sum", code: "GAT-Q-ARI.3", lvl: 3,
  stem: "Sara paid 15% less than Huda for the same course. Between them they paid 5550 SAR. How much did Huda pay, in SAR?",
  opts: ["2550", "2775", "3000", "3200"], ans: 2,
  trick: "the 15% is off HUDA's price, so the total is 1.85 of it — halving 5550 is the trap",
  why: "Sara paid 0.85 of Huda's price, so together they paid 1.85 × Huda = 5550, giving Huda = 3000 SAR.",
  traps: ["A: took 15% off half the total.",
          "B: halved 5550 — which would only be right if they paid the same.",
          "D: divided by 1.75."] },

// ================================================================= ALGEBRA
{ sig: "reciprocal-pair-pattern", code: "GAT-Q-ALG.1", lvl: 3,
  stem: "Find the value of x.",
  stemEq: "s_recippair",
  opts: ["9", "11", "13", "15"], ans: 2,
  trick: "both sides have the shape 'a number plus its reciprocal partner' — match the shapes instead of clearing denominators",
  why: "The left side is 7/(x−2) + (x−2)/7 and the right is 7/11 + 11/7. They match when x − 2 = 11, so x = 13.",
  traps: ["A: solved x − 2 = 7.",
          "B: gave the value of x − 2 instead of x.",
          "D: added 2 to 13 a second time."] },

{ sig: "complex-fraction-simplify", code: "GAT-Q-ALG.4", lvl: 3,
  stem: "Simplify the expression below.",
  stemEq: "s_cfrac",
  opts: [{ eq: "cf1" }, { eq: "cf2" }, { eq: "cf3" }, { eq: "cf4" }], ans: 1,
  trick: "give the top and the bottom the same denominator n, then the n cancels and a difference of two squares appears",
  why: "The top is (n + 2)/n and the bottom is (n² − 4)/n. Dividing cancels the n, leaving (n + 2)/(n² − 4) = (n + 2)/((n − 2)(n + 2)) = 1/(n − 2).",
  traps: ["A: cancelled the wrong bracket of the difference of two squares.",
          "C: cancelled the n from the top and the bottom before combining.",
          "D: kept an n on the top that had already cancelled."] },

{ sig: "absolute-value-two-roots-compare", code: "GAT-Q-ALG.5", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_absval",
  opts: CMP, ans: 3,
  trick: "a modulus opens two ways — the positive root and the negative one give different answers, so (D) is right",
  why: "4|m| = 28 gives |m| = 7, so m = 7 or m = −7. If m = 7 the two are equal; if m = −7 then B is greater. Different legitimate values give different answers, so there is not enough information.",
  traps: ["A: no value of m makes m greater than 7.",
          "B: found the m = −7 case and stopped there.",
          "C: took only the positive root."] },

{ sig: "minimum-of-square", code: "GAT-Q-ALG.5", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_minsq",
  opts: CMP, ans: 1,
  trick: "a square is never negative, and it reaches ZERO — the least value is 0, not 1 and not the 4",
  why: "(w − 4)² is smallest when w = 4, and then it is 0. Since 0 < 1, B is greater.",
  traps: ["A: took the least value as 16 by putting w = 0.",
          "C: took the least value as 1.",
          "D: the minimum of a square is fully determined."] },

{ sig: "sign-of-powers-negative", code: "GAT-Q-ALG.5", lvl: 2,
  stem: "Given the condition below, which of the following is the largest?",
  stemEq: "s_signpow",
  opts: [{ eq: "sp1" }, { eq: "sp2" }, { eq: "sp3" }, { eq: "sp4" }], ans: 2,
  trick: "check the SIGNS before the sizes — only the even power is positive, and any positive beats every negative",
  why: "With k negative, 6k is negative, k³ is negative and 1/k is negative. Only k⁴ is positive, so it is the largest.",
  traps: ["A: compared magnitudes and picked the one with the biggest number in front.",
          "B: assumed the highest power wins without checking that 3 is odd.",
          "D: thought a reciprocal of a negative turns positive."] },

{ sig: "substitute-into-quadratic", code: "GAT-Q-ALG.3", lvl: 3,
  stem: "Given the two statements below, find y.",
  stemEq: "s_subquad",
  opts: ["0", "1", "2", "3"], ans: 1,
  trick: "substitute to get ONE letter, then factorise — and check which root is on the option list",
  why: "y = x/3 gives x = 3y. Putting that in: 3y² + 3y = 6, so y² + y − 2 = 0 and (y + 2)(y − 1) = 0. So y = 1 or y = −2, and only 1 is offered.",
  traps: ["A: set y = 0 without checking the equation.",
          "C: solved 3y² = 6 and rounded.",
          "D: solved 3y² + x = 6 with x = 3 instead of x = 3y."] },

];
