// ---------------------------------------------------------------------------
// SIMULATED GAT BANK — part D: the 19 skills that only part 5 covered
//
// Part 5 is the sharpest set of the six on "spot the shortcut" arithmetic:
// matching exponents before comparing, cancelling before multiplying, and the
// classic clock-hands drift. Same rules as parts A to C.
// ---------------------------------------------------------------------------
const CMP = ["A is greater", "B is greater", "they are equal",
             "not enough information"];

module.exports = [

// ================================================================ GEOMETRY
{ sig: "count-all-squares-in-grid", code: "GAT-Q-GEO.4", lvl: 3,
  stem: "How many squares of any size can be found in the grid below?",
  fig: "sim_count_squares", figW: 1.55,
  opts: ["16", "20", "25", "30"], ans: 3,
  trick: "count the BIGGER squares too — the sixteen small ones are only the start",
  why: "There are 16 squares of side 1, 9 of side 2, 4 of side 3 and 1 of side 4. Altogether 16 + 9 + 4 + 1 = 30.",
  traps: ["A: counted only the smallest squares.",
          "B: counted the small ones and the whole grid.",
          "C: missed the four 3 × 3 squares."] },

{ sig: "rectangle-in-circle-radius", code: "GAT-Q-GEO.3", lvl: 2,
  stem: "A rectangle 6 cm by 8 cm is inscribed in a circle. Find the radius of the circle, in cm.",
  opts: ["5", "7", "10", "14"], ans: 0,
  trick: "the rectangle's DIAGONAL is the circle's diameter — and 6-8-10 makes it a whole number",
  why: "The diagonal is √(6² + 8²) = 10, and that diagonal is a diameter, so the radius is 5 cm.",
  traps: ["B: took half the perimeter of one corner, or averaged 6 and 8.",
          "C: gave the diameter instead of the radius.",
          "D: added the two sides."] },

{ sig: "shaded-fraction-of-square", code: "GAT-Q-GEO.4", lvl: 2,
  stem: "The square below has side 8 cm and is divided into four equal quarters. Find the shaded area, in cm².",
  fig: "sim_shaded_square", figW: 1.65,
  opts: ["16", "20", "24", "32"], ans: 2,
  trick: "work each quarter out on its own — one is whole and one is halved by its diagonal",
  why: "Each quarter is 4 × 4 = 16 cm². The top-right quarter is shaded whole, giving 16, and the top-left is cut in half by its diagonal, giving 8. Altogether 16 + 8 = 24 cm².",
  traps: ["A: counted only the whole quarter.",
          "B: took the half-quarter as 4 instead of 8.",
          "D: shaded both top quarters in full."] },

{ sig: "percent-greater-area-from-diameter", code: "GAT-Q-GEO.3", lvl: 3,
  stem: "The diameters of two circles are 240 cm and 200 cm. By what percentage is the larger circle's area greater than the smaller one's?",
  opts: ["20 %", "36 %", "44 %", "72 %"], ans: 2,
  trick: "square the ratio of the diameters first, THEN take the percentage increase — the 20% is on the lengths, not the areas",
  why: "The diameters are in the ratio 240 : 200 = 6 : 5, so the areas are 36 : 25. The larger exceeds the smaller by (36 − 25)/25 = 11/25 = 44%.",
  traps: ["A: gave the percentage increase in the DIAMETERS, not the areas.",
          "B: gave 36/100 straight from the squared ratio.",
          "D: doubled the 36% figure."] },

{ sig: "clock-hands-angle", code: "GAT-Q-GEO.1", lvl: 3,
  stem: "The clock below shows 08:24. Find the angle between the two hands.",
  fig: "sim_clock_hands", figW: 1.92,
  opts: ["96°", "102°", "108°", "114°"], ans: 2,
  trick: "the hour hand DRIFTS — by 24 minutes past it has moved a further 12°, and forgetting that is the whole trap",
  why: "The minute hand is at 24 × 6 = 144°. The hour hand is at 8 × 30 + 24 × 0.5 = 240 + 12 = 252°. The angle between them is 252 − 144 = 108°.",
  traps: ["A: put the hour hand exactly on the 8, giving 240 − 144.",
          "B: used a drift of half the correct amount.",
          "D: used a drift of 1° per minute."] },

// ============================================================== ARITHMETIC
{ sig: "percent-increase-price", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "A flight to Riyadh cost 5300 SAR and the fare then rose by 40%. What is the new fare, in SAR?",
  opts: ["6400", "7420", "7650", "8640"], ans: 1,
  trick: "a 40% rise means multiplying by 1.4 — the increase has to be ADDED to the old price, not given on its own",
  why: "40% of 5300 is 2120, so the new fare is 5300 + 2120 = 7420 SAR. (Equivalently 5300 × 1.4.)",
  traps: ["A: added only 1100 after taking a rough fifth.",
          "C: added 44% instead of 40%.",
          "D: multiplied by 1.63 after compounding the rise twice."] },

{ sig: "self-over-fraction-pattern", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Find the value of the sum below.",
  stemEq: "s_selfover",
  opts: ["8", "10", "12", "21"], ans: 2,
  trick: "each term is a number divided by that same number over something — the number cancels and only the denominator's bottom is left",
  why: "1 ÷ (1/3) = 3. And 2 ÷ (2/6) = 6. And 7 ÷ (7/3) = 3. The sum is 3 + 6 + 3 = 12. In every term the top number cancels, so only the 3, the 6 and the 3 survive.",
  traps: ["A: took the middle term as 2.",
          "B: worked out the first and third terms but read the middle as 4.",
          "D: added the three denominators' tops instead (1 + 2 + 7 doubled)."] },

{ sig: "add-fractions-vs-fraction-of-sum", code: "GAT-Q-ARI.3", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_addfrac",
  opts: CMP, ans: 0,
  trick: "adding two fractions is NOT the same as putting the sum of the bottoms underneath one — this item exists only to test that",
  why: "A is 1/2 + 1/3 = 3/6 + 2/6 = 5/6 ≈ 0.83. B is 1/5 = 0.2. A is greater, by a wide margin.",
  traps: ["B: read A as 1/5 as well, treating the two as the same thing.",
          "C: assumed the two expressions are just different ways of writing one number — this is the trap.",
          "D: both are explicit numbers."] },

{ sig: "cancel-before-multiplying", code: "GAT-Q-ARI.3", lvl: 1,
  stem: "Find the value of the expression below.",
  stemEq: "s_cancelm",
  opts: ["5", "6", "9", "10"], ans: 1,
  trick: "cancel BEFORE you multiply — 35 is 5 × 7, and both of those come straight out of 14 and 15",
  why: "35 = 5 × 7, and 14 = 2 × 7 and 15 = 3 × 5. Cancelling leaves 2 × 3 = 6. (The long way, 14 × 15 = 210 and 210 ÷ 35 = 6, gives the same thing with more work.)",
  traps: ["A: cancelled the 7 but not the 5.",
          "C: cancelled the 5 but not the 7.",
          "D: divided 350 by 35."] },

{ sig: "powers-common-exponent-compare", code: "GAT-Q-ARI.4", lvl: 3,
  stem: "Which quantity is greater?",
  stemEq: "s_powcmp",
  opts: CMP, ans: 0,
  trick: "make the EXPONENTS match, not the bases — 75 and 100 share the factor 25",
  why: "3⁷⁵ = (3³)²⁵ = 27²⁵ and 2¹⁰⁰ = (2⁴)²⁵ = 16²⁵. With the same exponent, the bigger base wins, and 27 > 16, so A is greater.",
  traps: ["B: compared the exponents 75 and 100 and picked the larger.",
          "C: assumed the two must balance because 3 × 25 = 75 and 4 × 25 = 100.",
          "D: both are explicit numbers, however large."] },

{ sig: "nested-radical-compare", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Which quantity is greater?",
  stemEq: "s_radcmp",
  opts: CMP, ans: 0,
  trick: "both are square roots, so compare what is INSIDE them — no need to work either root out",
  why: "Both sides are square roots, so compare the insides: 3 against 1 + √2 ≈ 2.414. Since 3 > 2.414, A is greater.",
  traps: ["B: read 1 + √2 as 1 + 2 = 3 and then as larger.",
          "C: took 1 + √2 as exactly 3.",
          "D: both are explicit numbers."] },

{ sig: "reciprocal-rationalise", code: "GAT-Q-ARI.4", lvl: 2,
  stem: "Find x.",
  stemEq: "s_recipx",
  opts: [{ eq: "o3r2" }, { eq: "o2r2" }, { eq: "o6r2" }, "12"], ans: 0,
  trick: "x to the power minus one is 1 over x, so x is the fraction TURNED OVER — then clear the root from the bottom",
  why: "x⁻¹ = √2⁄6 means x = 6⁄√2. Multiplying top and bottom by √2 gives 6√2⁄2 = 3√2.",
  traps: ["B: rationalised but then halved twice.",
          "C: forgot to divide by the 2 that appears after rationalising.",
          "D: read √2 as 2 and gave 6 ÷ 0.5."] },

{ sig: "ratio-difference-to-sum", code: "GAT-Q-ARI.2", lvl: 2,
  stem: "Two numbers are in the ratio 4 : 3 and differ by 150. Find their sum.",
  opts: ["350", "900", "1050", "1200"], ans: 2,
  trick: "the DIFFERENCE is one part, because 4 − 3 = 1 — so one part is 150 and the sum is seven of them",
  why: "The parts differ by 4 − 3 = 1, so one part is 150. The sum is 4 + 3 = 7 parts, that is 7 × 150 = 1050.",
  traps: ["A: added the ratio numbers to the difference.",
          "B: used six parts.",
          "D: used eight parts."] },

{ sig: "currency-convert-then-floor", code: "GAT-Q-ARI.3", lvl: 3,
  stem: "A traveller changes 7777 SAR into dinars at 10 SAR to the dinar. The bank has only 20-dinar notes. How many notes does the traveller receive?",
  opts: ["30", "35", "38", "40"], ans: 2,
  trick: "convert first, then divide — and round DOWN, because a part note does not exist",
  why: "7777 ÷ 10 = 777.7 dinars. Dividing by 20 gives 38.885, and only whole notes can be handed over, so 38 notes.",
  traps: ["A: divided 7777 by 260 or similar.",
          "B: rounded 38.885 down to 35 by working in fives.",
          "D: rounded 38.885 UP — the bank cannot give more than it owes."] },

// ================================================================= ALGEBRA
{ sig: "split-fraction-substitute", code: "GAT-Q-ALG.4", lvl: 2,
  stem: "Find the value of the expression below.",
  stemEq: "s_splitfr",
  opts: ["4", "6", "8", "12"], ans: 2,
  trick: "split the fraction into two before substituting — x/y is already given, so nothing has to be solved",
  why: "(x + 3y)/y = x/y + 3y/y = x/y + 3 = 5 + 3 = 8.",
  traps: ["A: cancelled the y and then the x wrongly to leave 3 + 1.",
          "B: added 1 instead of 3.",
          "D: multiplied 5 by 3 minus 3."] },

{ sig: "rect-to-square-adjust", code: "GAT-Q-ALG.1", lvl: 3,
  stem: "A rectangle has perimeter 48 cm. Taking 2 cm off its width and adding 2 cm to its length turns it into a square. Find the area of that square, in cm².",
  opts: ["44", "64", "144", "169"], ans: 2,
  trick: "the perimeter gives the sum of the sides and the adjustment gives their difference — two facts, two unknowns",
  why: "Width + length = 24. The square condition gives width − 2 = length + 2, so width = length + 4. Then length = 10 and width = 14. The square's side is 14 − 2 = 12, and its area is 144 cm².",
  traps: ["A: added the two adjusted sides instead of squaring one.",
          "B: took the side as 8.",
          "D: took the side as 13 by splitting 24 unevenly."] },

{ sig: "catch-up-linear", code: "GAT-Q-ALG.1", lvl: 3,
  stem: "Ali has 240 SAR and saves 5 SAR a day. Ahmed has 100 SAR and saves 12 SAR a day. After how many days will they have the same amount?",
  opts: ["8", "10", "20", "21"], ans: 2,
  trick: "the GAP closes at the difference of the two daily rates — 140 apart, closing 7 a day",
  why: "240 + 5d = 100 + 12d gives 140 = 7d, so d = 20 days. (The gap of 140 SAR closes at 12 − 5 = 7 SAR a day.)",
  traps: ["A: divided 140 by 17.",
          "B: divided 140 by 14.",
          "D: divided 240 − 100 by 12 − 5 and then added one."] },

// =================================================================== LOGIC
{ sig: "work-rate-people-days", code: "GAT-Q-LOG.2", lvl: 3,
  stem: "Three students complete 1500 assignments in 4 days. How many days will 4 students need to complete 4000 assignments, working at the same rate?",
  opts: ["8", "9", "10", "12"], ans: 0,
  trick: "get the rate for ONE student for ONE day first — then the people and the days both scale from it",
  why: "One student does 1500 ÷ (3 × 4) = 125 assignments a day. Four students do 500 a day, so 4000 ÷ 500 = 8 days.",
  traps: ["B: used a rate of 111 a day.",
          "C: scaled the assignments but forgot the extra student.",
          "D: scaled by 4000/1500 alone."] },

{ sig: "similar-shadows-proportion", code: "GAT-Q-LOG.1", lvl: 2,
  stem: "At the same moment, a boy 150 cm tall casts a shadow 300 cm long and a minaret casts a shadow 1200 cm long. How tall is the minaret, in cm?",
  opts: ["400", "600", "800", "2400"], ans: 1,
  trick: "the shadow is four times as long, so the height is four times as tall — scale the ratio, do not add",
  why: "The minaret's shadow is 1200 ÷ 300 = 4 times the boy's, so the minaret is 4 × 150 = 600 cm tall.",
  traps: ["A: scaled by 1200/450.",
          "C: scaled by 1200/225.",
          "D: multiplied 150 by 16, squaring the scale factor."] },

];
